"""PB1_V4_OPENING_DRIVE_LOCATION_REACCEL_SPEC_V1.

Semantic specification only. Do not implement V4. No event_n. No PnL.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.pb1_v3_1_face_validity_fix import PARENT_V2_SHA, PARENT_V3_SHA
from research.pb1_v3_2_face_failure_rca import CASE_REBUILD as PARENT_RCA_VERDICT
from research.pb1_v3_2_face_failure_rca import NEXT_V4 as PARENT_RCA_NEXT
from research.pb1_v3_2_face_failure_rca import PARENT_V32_SHA, SEMANTIC_RCA_N
from research.pb1_v3_2_opening_drive_and_reacceleration_semantics import PARENT_V31_SHA
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "PB1_V4_OPENING_DRIVE_LOCATION_REACCEL_SPEC"
ANALYSIS_ID = "PB1_V4_OPENING_DRIVE_LOCATION_REACCEL_SPEC_V1"
PARENT_RCA_PROGRAM = "PB1_V3_2_FACE_FAILURE_RCA"
assert PARENT_RCA_VERDICT == "PB1_SEMANTIC_REBUILD_V4"
assert PARENT_RCA_NEXT == "PB1_V4_OPENING_DRIVE_LOCATION_REACCEL_SPEC_V1"
assert PARENT_V32_SHA == "56edb2c2576805e46193528824fb61faebb5ae7c85be0201f0331e90f9a67f43"
assert SEMANTIC_RCA_N == 88
assert PARENT_V31_SHA == "24089d94b2610eb8eaf19160d503b6477347f970a27650b6a04282884f436c65"
assert PARENT_V3_SHA == "4348b941f9eb0a827db743041752c49f91be8cd9f92a1920c4ffd7c6c0dc8f89"
assert PARENT_V2_SHA == "3ebe0220fd9cb1e5749e39833fa1bab0146759cce5dc9daaacf0e3b3d3daf3fd"

PRIMARY_SETUP_TIMEFRAME = "5m"
ONE_M_ROLE = "execution_confirmation"
DAILY_ROLE = "location_context"
OR_ROLE = "session_reference"
V4_IS_1M_STRATEGY = False
ONE_M_CAN_CREATE_ELIGIBILITY = False
OR_ALONE_AUTOMATICALLY_VALID = False
NUMERIC_1M_THRESHOLDS_FROZEN = False
TRADINGVALUE_IS_1M_TRIGGER_GATE = False
DAILY_BIAS_IS_GATE = False
V4_MACHINE_IMPLEMENTED = False
EVENT_N_CALCULATED = False

VALID_OPENING_STATES = ("TRUE_OPENING_DRIVE", "FAILED_OPEN_THEN_REAL_DRIVE")
INVALID_OPENING_STATES = ("TWO_SIDED_OPEN", "FLAT_OR_CRAWL", "LATE_RANGE_RESOLUTION", "MICRO_OR_LEAK")
EXEMPLAR_FAILED_OPEN = ("3382", "20241004", "bear")
PARENT_CLEAR_N = 19

CASE_READY = "PB1_V4_SEMANTIC_SPEC_READY_V1"
CASE_BIND = "PB1_V4_SPEC_BIND_FAILED_V1"
NEXT_MACHINE = "PB1_V4_MACHINE_IMPLEMENTATION_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

OLD_CONFIRMATION_OPENED = False
FROZEN_VALIDATION_OPENED = False
KABU50_APPLIED = False
PNL_OPTIMIZATION = False
THRESHOLD_OPTIMIZED = False
V32_RULE_CHANGED = False
V4_IMPLEMENTED = False
FEATURE_MINING = FEATURE_MINING_CLOSED
LIVE_DATE = LIVE_TRADING_DATE
_ = PARENT_RCA_VERDICT, PARENT_RCA_NEXT
