"""Blind-validation contract. Hashed before any Old Confirmation bars are loaded."""
from __future__ import annotations

import hashlib
import json
from typing import Any

from research.pb1_v4_clarified_machine_correction_v4_freeze_and_prospective_prep import FROZEN_IDENTITY
from research.pb1_v4_frozen_old_confirmation_blind_validation import (
    CASE_FAIL,
    CASE_PASS,
    EVAL_FIRST,
    EVAL_LAST,
    EXPECTED_MACHINE_SHA256,
    EXPECTED_SOURCE_INVENTORY_SHA256,
    FV_FIRST,
    FV_LAST,
    LOOKBACK_TAIL_N,
    NEXT_FV,
    NEXT_RCA,
    POOL_N,
    PROSPECTIVE_FROM,
)
from research.pb1_v4_prospective_semantic_validation_preflight.logging import CANDIDATE_DAY_FIELDS, CAUSAL_FIELDS

ALLOWED_THESIS_LOST_REASONS = (
    "FAILED_BREAK_REACCEPTED",
    "STALE_RANGE_RESOLUTION",
    "DISPLACEMENT_UNWOUND",
    "REPEATED_FAILED_PROGRESS",
    "REPEATED_OR_RECROSS",
    "TWO_SIDED_BALANCE_REESTABLISHED",
    "RANGE_ACCEPTED",
    "OPENING_RESOLVED_WITHOUT_DRIVE",
)
REQUIRED_ZERO = (
    "ACTIVE_without_SEED",
    "LOCATION_without_ACTIVE",
    "THESIS_READY_without_LOCATION",
    "THESIS_LIVE_without_ACTIVE_LIVE",
    "EXECUTION_READY_without_THESIS_LIVE",
    "THESIS_REVIVED_AFTER_LOSS",
    "E0_WHILE_THESIS_NOT_LIVE",
    "E1_WHILE_THESIS_NOT_LIVE",
    "HIDDEN_1M_MISMATCH",
    "SAME_BAR_ENTRY",
    "1M_CREATED_SEED",
    "1M_CREATED_DIRECTION",
    "1M_CREATED_LOCATION",
    "1M_CREATED_THESIS",
    "1M_REVIVED_THESIS",
)
EVALUATED_STATES = (
    "WHY_THIS_STOCK",
    "SEED",
    "ACTIVE_REACHED",
    "ACTIVE_LIVE",
    "LOCATION_IDENTIFIED",
    "THESIS_REACHED",
    "THESIS_LIVE",
    "THESIS_LOST",
    "E0",
    "E1",
    "EXECUTION_READY",
)
ADJUDICATION_QUESTIONS = (
    "Did a real opening directional auction exist?",
    "Was ACTIVE still genuinely alive?",
    "Was LOCATION identifiable before interaction?",
    "Did 1m only time an existing 5m thesis?",
    "Was THESIS_LOST caused by an observable auction-end event?",
    "Was any transition backdated?",
)


def blind_precommit(
    *,
    machine_sha: str,
    source_inventory_sha: str,
    confirmation_n: int,
    lookback_n: int,
    lookback_first: str | None,
    lookback_last: str | None,
    confirmation_first: str | None,
    confirmation_last: str | None,
    symbol_n: int,
) -> dict[str, Any]:
    body = {
        "purpose": "SEMANTIC_CAUSAL_GENERALIZATION",
        "not_purpose": "profitability_optimization",
        "evidence_stream": "OLD_CONFIRMATION_BLIND_HISTORICAL_VALIDATION",
        "independent_of_prospective": True,
        "machine_identity": FROZEN_IDENTITY,
        "machine_sha": machine_sha,
        "EXPECTED_V4_MACHINE_SHA256": EXPECTED_MACHINE_SHA256,
        "source_inventory_sha": source_inventory_sha,
        "EXPECTED_SOURCE_INVENTORY_SHA256": EXPECTED_SOURCE_INVENTORY_SHA256,
        "date_range": {
            "old_confirmation_first": EVAL_FIRST,
            "old_confirmation_last": EVAL_LAST,
            "confirmation_n_from_frozen_split": int(confirmation_n),
            "confirmation_first_from_split": confirmation_first,
            "confirmation_last_from_split": confirmation_last,
            "opened_this_task": ["OLD_CONFIRMATION"],
            "sealed_this_task": ["FROZEN_VALIDATION", "PROSPECTIVE"],
        },
        "symbol_universe": {
            "pool": "frozen_research_pool",
            "n": int(symbol_n) if int(symbol_n) else int(POOL_N),
            "expected_n": int(POOL_N),
            "no_kabu50": True,
            "no_yfinance": True,
            "no_inferred_bid_ask": True,
        },
        "lookback": {
            "role": "FEATURE_HISTORY_ONLY",
            "source": "Discovery already development-exposed",
            "not_a_holdout": True,
            "not_adjudicated": True,
            "LOOKBACK_TAIL_N": int(LOOKBACK_TAIL_N),
            "lookback_n": int(lookback_n),
            "lookback_first": lookback_first,
            "lookback_last": lookback_last,
            "reason": "ATR20 SMA75 same-clock opening-5m noise baselines require prior completed sessions",
        },
        "sealed_periods": {
            "frozen_validation": {"first": FV_FIRST, "last": FV_LAST, "opened": False},
            "prospective": {"from": PROSPECTIVE_FROM, "opened": False},
        },
        "data_completeness_gate": {
            "native_1m_required": True,
            "native_5m_required": True,
            "am_window": "09:00-11:19 inclusive, BAR_START",
            "required_1m_n": 140,
            "atr20_from_prior_completed_sessions": True,
            "partial_AM_is_ineligible_not_semantic_fail": True,
            "no_inferred_bid_ask": True,
            "no_new_paid_data": True,
            "flatten_1520_is_session_ops_not_thesis_death": True,
        },
        "candidate_definition": {
            "unit": "symbol-date",
            "must_be_old_confirmation_calendar": True,
            "must_pass_completeness_gate": True,
            "must_be_frozen_pool_symbol": True,
            "WHY_THIS_STOCK_required_for_candidate_day": True,
            "lookback_dates_are_not_candidates": True,
            "frozen_validation_dates_are_not_candidates": True,
            "prospective_dates_are_not_candidates": True,
        },
        "evaluated_states": list(EVALUATED_STATES),
        "state_logging_schema": {
            "candidate_day": list(CANDIDATE_DAY_FIELDS),
            "causal_timestamps": list(CAUSAL_FIELDS),
        },
        "causal_timestamp_contract": {
            "fields": list(CAUSAL_FIELDS),
            "BAR_START": True,
            "entry_allowed_at_strictly_after_event_completed_at": True,
            "forbidden": [
                "backdating",
                "future_confirmation",
                "same_bar_entry",
                "future_hold_creating_past_location",
            ],
        },
        "hidden_1m_contract": {
            "HIDDEN_1M_THESIS_PARITY_required": True,
            "evaluate_5m_only_and_1m_visible_in_parallel": True,
            "1m_must_not_create_or_change": ["SEED", "ACTIVE", "direction", "LOCATION", "THESIS", "THESIS_LOST"],
            "1m_may_create": ["E1 timing only"],
        },
        "same_bar_prohibition": {
            "SAME_BAR_ENTRY_required_zero": True,
            "entry_on_completed_event_bar_forbidden": True,
        },
        "semantic_adjudication_rubric": {
            "when": "only after frozen V4 run completes on the full Old Confirmation set",
            "human_label_accuracy_is_not_primary_gate": True,
            "questions": list(ADJUDICATION_QUESTIONS),
            "allowed_thesis_lost_reasons_after_THESIS_REACHED": list(ALLOWED_THESIS_LOST_REASONS),
            "primary_gates": [
                "causal_contract",
                "state_invariants",
                "hidden_1m",
                "no_future_leakage",
                "no_systematic_semantic_breakdown",
            ],
        },
        "pass_fail_rules": {
            "PASS_VERDICT": CASE_PASS,
            "FAIL_VERDICT": CASE_FAIL,
            "PASS_NEXT": NEXT_FV,
            "FAIL_NEXT": NEXT_RCA,
            "PASS_requires": [
                "all REQUIRED_ZERO counts are 0",
                "HIDDEN_1M_THESIS_PARITY is true",
                "no Frozen Validation date loaded",
                "no prospective date loaded",
                "no same-bar entry",
                "no backdating",
                "funnel is not degenerate on complete Confirmation sessions",
                "THESIS_LOST after THESIS_REACHED uses an observable auction-end reason",
            ],
            "REQUIRED_ZERO": list(REQUIRED_ZERO),
            "degeneracy": {
                "WHY_THIS_STOCK_eq_0_on_any_complete_confirmation_session_set": "FAIL",
                "WHY_ge_21_and_SEED_eq_0": "FAIL",
                "SEED_ge_10_and_ACTIVE_REACHED_eq_0": "FAIL",
                "THESIS_LOST_without_allowed_reason_share_gt_0.50_when_lost_n_ge_10": "FAIL",
            },
            "economic_metrics_not_used": [
                "PnL",
                "PF",
                "win_rate",
                "MFE",
                "MAE",
                "future_return",
                "best_exit",
                "fixed_hold",
            ],
            "discovery_88_is_not_a_scoring_target": True,
            "do_not_retune_after_seeing_results": True,
        },
        "bug_version_invalidation_rule": {
            "mid_run_threshold_change": "forbidden",
            "single_case_exception": "forbidden",
            "symbol_specific_rescue": "forbidden",
            "semantic_definition_change": "forbidden",
            "V4_1_creation_this_task": "forbidden",
            "if_change_required": {
                "close_this_blind_batch": True,
                "verdict": CASE_FAIL,
                "new_version_required": True,
                "Old_Confirmation_becomes_DEVELOPMENT_EXPOSED_AFTER_REVIEW": True,
                "Frozen_Validation_remains_sealed": True,
                "cannot_reuse_Old_Confirmation_as_unseen_for_a_new_version": True,
            },
            "any_V4_source_or_threshold_or_state_definition_change_invalidates_frozen_identity": True,
        },
        "run_policy": {
            "frozen_v4_exactly_as_is": True,
            "once_only": True,
            "no_mid_run_learning": True,
        },
        "PNL_USED": False,
        "MFE_MAE_USED": False,
        "FUTURE_OUTCOME_USED": False,
        "FROZEN_VALIDATION_OPENED": False,
        "PROSPECTIVE_DATA_OPENED": False,
        "V4_CHANGED": False,
        "SPEC_CHANGED": False,
        "THRESHOLD_RETUNED": False,
    }
    raw = json.dumps(body, sort_keys=True, ensure_ascii=False, default=str).encode("utf-8")
    body["PRECOMMIT_SHA256"] = hashlib.sha256(raw).hexdigest()
    return body
