"""PB1_OPENING_RANGE_CONTINUATION_FACE_VALID_V1.

Ordinary Japanese-equity daytrade playbook, FACE VALIDITY ONLY:

IN-PLAY STOCK → OPENING IMPULSE → OR15 → BREAK / RETEST / HOLD → 1M TRIGGER.

Continuation only. False-break reversal is a different thesis and is not this machine.
No matching. No PnL. No Confirmation. No Frozen Validation.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE
from research.support_resistance_face_valid_first_interaction_rebuild_v1 import CONFIRM_ATR, ZONE_HALF_ATR

PROGRAM_ID = "PB1_OPENING_RANGE_CONTINUATION_FACE_VALID_V1"
ANALYSIS_ID = "PB1_OPENING_RANGE_CONTINUATION_FACE_VALID_V1"
PARENT_ANALYSIS_ID = "REAL_DAYTRADE_WORKFLOW_SEMANTICS_AUDIT_V1"
PARENT_VERDICT = "REAL_DAYTRADE_WORKFLOW_SEMANTICS_MISALIGNED_V1"
PARENT_NEXT = "FACE_VALID_CANDIDATE_PLAYBOOKS_THEN_TEST_V1"

EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_DETECTOR_SHA256 = "6e3060b71f8a4787b09d6b3c0f3ba9fa84c87712bf0f11b0165bfbfd1e0bf47e"
EXPECTED_STATE_MACHINE_SHA256 = "3c065f3757083fa6da792f9450e07504e902ea93d48391467a6bb7dca6e6a5b8"

FROZEN_CONFIRM_ATR = 0.75
FROZEN_ZONE_HALF_ATR = 0.15
assert CONFIRM_ATR == FROZEN_CONFIRM_ATR
assert ZONE_HALF_ATR == FROZEN_ZONE_HALF_ATR

LUNCH_POLICY = "AM_ONLY_NO_LUNCH_ENTRY"
SESSION_FLAT = "15:20"
OR_START = "09:00"
OR_END = "09:14"
OR_KNOWN_FROM = "09:15"
LAST_BREAK = "10:00"
LAST_TRIGGER = "11:20"
NEAR_DAILY_MA_ATR = 0.15
TV_CLOCK_LOOKBACK_DAYS = 20
TV_CLOCK_MIN_OBS = 10
WINDOW_TV_LOOKBACK_DAYS = 20
WINDOW_TV_MIN_OBS = 10

# Predeclared descriptive in-play tags. Not searched. Not outcome-tuned.
# A name is tagged in-play if ANY of these round half-spaces hold.
IN_PLAY_ABS_GAP_ATR = 0.30
IN_PLAY_TV_WINDOW_PCTL = 0.50
IN_PLAY_XS_RANK_MAX = 0.50

SAMPLE_SEED = "PB1_OPENING_RANGE_CONTINUATION_FACE_VALID_V1:sample"
SAMPLE_N = 24
SAMPLE_PER_BLOCK = 6

TRAIN_BLOCK = "D1"
EVAL_BLOCKS = ("D2", "D3", "D4")

CASE_READY = "PB1_OPENING_RANGE_FACE_VALID_READY_V1"
CASE_REBUILD = "PB1_OPENING_RANGE_SEMANTICS_NEEDS_REBUILD_V1"
CASE_NOT_REP = "PB1_OPENING_RANGE_NOT_REPRESENTABLE_V1"

NEXT_PATH_TEST = "PB1_OPENING_RANGE_CAUSAL_PATH_TEST_V1"
NEXT_FIX = "FIX_PB1_OPENING_RANGE_REPRESENTATION_V1"
NEXT_STOP = "STOP_PB1_OPENING_RANGE_V1"

FALSE_BREAK_MERGED = False
OLD_CONFIRMATION_OPENED = False
FROZEN_VALIDATION_OPENED = False
KABU50_APPLIED = False
PNL_OPTIMIZATION = False
THRESHOLD_PNL_TUNED = False
MATCHING_RUN = False
ECONOMIC_TEST_RUN = False
FEATURE_MINING = FEATURE_MINING_CLOSED
LIVE_DATE = LIVE_TRADING_DATE
