"""Blinded human classification. Future path is not used. Filled after chart review."""
from __future__ import annotations

from collections import Counter
from typing import Any


def _lab(
    face: str,
    structure: str,
    *,
    cont: bool,
    play: bool,
    brk: bool,
    ret: bool,
    hold: bool,
    trig: bool,
    inv: bool,
    reward: bool,
    note: str,
) -> dict[str, Any]:
    return {
        "face": face,
        "structure": structure,
        "machine_detected_or_continuation": cont,
        "genuinely_in_play": play,
        "real_break": brk,
        "real_retest": ret,
        "real_hold": hold,
        "trigger_recognizable": trig,
        "invalidation_sensible": inv,
        "reward_space_plausible": reward,
        "note": note,
    }


# sample_id -> labels. Do not backfill from PnL.
HUMAN_LABELS: dict[int, dict[str, Any]] = {
    1: _lab(
        "QUESTIONABLE",
        "RANGE_NOISE",
        cont=False,
        play=True,
        brk=True,
        ret=False,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="V-recovery through OR_HIGH after dumping to OR_LOW; leave is 2–3 tiny bars, not an opening-impulse continuation.",
    ),
    2: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Opening drive from OR_LOW through OR_HIGH, extension, later first retest of OR_HIGH, reclaim trigger.",
    ),
    3: _lab(
        "QUESTIONABLE",
        "RANGE_NOISE",
        cont=False,
        play=True,
        brk=False,
        ret=False,
        hold=True,
        trig=False,
        inv=False,
        reward=False,
        note="All-morning chop under OR_HIGH; late micro close-beyond is not an opening continuation. Already into PDH.",
    ),
    4: _lab(
        "QUESTIONABLE",
        "RANGE_NOISE",
        cont=False,
        play=True,
        brk=True,
        ret=False,
        hold=True,
        trig=False,
        inv=True,
        reward=True,
        note="Opening spike to OR_HIGH then dump; OR_LOW break is failed-open continuation of OR resolution, not a clean opening impulse.",
    ),
    5: _lab(
        "NOT_INTENDED_SETUP",
        "RANGE_NOISE",
        cont=False,
        play=False,
        brk=True,
        ret=False,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Open at OR_HIGH then fail; TV clock pctl 0. Not genuinely in play. Next-bar-scale leave/retest.",
    ),
    6: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=False,
        note="Gap-down opening impulse, later OR_LOW break, leave, retest as resistance. Reward space already extended.",
    ),
    7: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Recognizable bull OR_HIGH break, 15-minute leave, first retest, reclaim. Daily SMA is bear context only.",
    ),
    8: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Drive through OR_HIGH, extension, return, reclaim of retest micro-high.",
    ),
    9: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Opening impulse up, inside-OR pullback, then OR_HIGH break/retest/reclaim.",
    ),
    10: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Violent opening dump, later OR_LOW break, leave, retest of OR_LOW as resistance.",
    ),
    11: _lab(
        "QUESTIONABLE",
        "ALREADY_EXTENDED",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=False,
        note="True opening dump and OR_LOW break, but first retest arrives after ~40 minutes already extended; no target ahead.",
    ),
    12: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Gap-down dump, pause, OR_LOW break, leave, failed-push trigger at the boundary.",
    ),
    13: _lab(
        "QUESTIONABLE",
        "ALREADY_EXTENDED",
        cont=False,
        play=True,
        brk=False,
        ret=False,
        hold=True,
        trig=False,
        inv=False,
        reward=False,
        note="Creep along OR_HIGH; micro break/retest. Not a distinct opening-range continuation.",
    ),
    14: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Strong opening impulse, OR_HIGH break, short but real leave, retest, reclaim. TV pctl 1.0.",
    ),
    15: _lab(
        "QUESTIONABLE",
        "ALREADY_EXTENDED",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=False,
        note="Real morning OR_HIGH break, but first causal retest is ~10:22 after the move has already been used. R:R 0.63.",
    ),
    16: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Opening drift down, OR_LOW break, leave below, retest, failed-push trigger.",
    ),
    17: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Gap-down waterfall into OR_LOW; one away bar then retest. Tight, but it is the opening-impulse continuation.",
    ),
    18: _lab(
        "QUESTIONABLE",
        "RANGE_NOISE",
        cont=False,
        play=True,
        brk=True,
        ret=False,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Open up to OR_HIGH then reverse; OR_LOW break is failed-open, not continuation of an opening down-impulse.",
    ),
    19: _lab(
        "QUESTIONABLE",
        "OTHER",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Valid 09:19 OR_HIGH break, but first retest is 11:01 — no longer an opening continuation timing.",
    ),
    20: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=False,
        note="Opening drive, OR_HIGH break, extension, 09:41 retest, reclaim. Pattern is intended; target space already used.",
    ),
    21: _lab(
        "CLEAR_INTENDED_SETUP",
        "BREAKOUT_CONTINUATION",
        cont=True,
        play=True,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=True,
        note="Opening impulse up into OR_HIGH, short leave, retest, failed-push. Tight but recognizable.",
    ),
    22: _lab(
        "QUESTIONABLE",
        "RANGE_NOISE",
        cont=False,
        play=False,
        brk=True,
        ret=True,
        hold=True,
        trig=True,
        inv=True,
        reward=False,
        note="Quiet grind to OR_LOW. xs-rank tag only; tape is not an opening impulse.",
    ),
    23: _lab(
        "QUESTIONABLE",
        "RANGE_NOISE",
        cont=False,
        play=True,
        brk=True,
        ret=False,
        hold=True,
        trig=False,
        inv=True,
        reward=True,
        note="25 minutes of range after an opening spike, then OR_LOW break. Failed-open breakdown, not continuation.",
    ),
    24: _lab(
        "QUESTIONABLE",
        "RANGE_NOISE",
        cont=False,
        play=True,
        brk=True,
        ret=False,
        hold=True,
        trig=True,
        inv=True,
        reward=False,
        note="Open spike then grind to OR_LOW; 1-bar leave. Failed-open, R:R 0.67.",
    ),
}


def apply_labels(sample: list[dict[str, Any]]) -> dict[str, Any]:
    labeled: list[dict[str, Any]] = []
    for ev in sample:
        sid = int(ev.get("sample_id") or 0)
        lab = dict(HUMAN_LABELS.get(sid) or {})
        row = {
            "sample_id": sid,
            "symbol": ev.get("symbol"),
            "date": ev.get("date"),
            "block": ev.get("block"),
            "direction": ev.get("direction"),
            "in_play_tag": ev.get("in_play"),
            "trigger_primary": ev.get("trigger_primary") or (list(ev.get("trigger_labels") or [])[:1] or [None])[0],
            "chart": f"sample_{sid:02d}_{ev.get('symbol')}_{ev.get('date')}_{ev.get('direction')}.png",
            "face": lab.get("face"),
            "structure": lab.get("structure"),
            "machine_detected_or_continuation": lab.get("machine_detected_or_continuation"),
            "genuinely_in_play": lab.get("genuinely_in_play"),
            "real_break": lab.get("real_break"),
            "real_retest": lab.get("real_retest"),
            "real_hold": lab.get("real_hold"),
            "trigger_recognizable": lab.get("trigger_recognizable"),
            "invalidation_sensible": lab.get("invalidation_sensible"),
            "reward_space_plausible": lab.get("reward_space_plausible"),
            "note": lab.get("note"),
            "reviewed": bool(lab),
        }
        labeled.append(row)
    faces = Counter(r["face"] for r in labeled if r["reviewed"])
    structs = Counter(r["structure"] for r in labeled if r["reviewed"])
    fails = Counter()
    for r in labeled:
        if not r["reviewed"]:
            continue
        if r.get("face") != "CLEAR_INTENDED_SETUP":
            fails[str(r.get("structure") or r.get("face") or "OTHER")] += 1
    n = sum(1 for r in labeled if r["reviewed"])
    clear = int(faces.get("CLEAR_INTENDED_SETUP") or 0)
    q = int(faces.get("QUESTIONABLE") or 0)
    ni = int(faces.get("NOT_INTENDED_SETUP") or 0)
    most = fails.most_common(1)[0][0] if fails else None
    return {
        "reviewed_n": n,
        "sample_n": len(labeled),
        "CLEAR_INTENDED_SETUP": clear,
        "QUESTIONABLE": q,
        "NOT_INTENDED_SETUP": ni,
        "clear_share": float(clear / n) if n else None,
        "structure_counts": dict(structs),
        "most_common_semantic_failure": most,
        "rows": labeled,
        "future_hidden": True,
        "outcome_used": False,
    }
