"""POST_OPEN_CAUSAL_UPSIDE_MECHANISM_DISCOVERY_V1. Neutral anchors. No strategy."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "POST_OPEN_CAUSAL_UPSIDE_MECHANISM_DISCOVERY_V1"
PARENT_ID = "PRIOR_CLOSE_RECAPTURE_SUSTAINED_MECHANISM_V1"
REQUIRED_PARENT_VERDICT = "PRIOR_CLOSE_RECAPTURE_NO_STABLE_SUCCESS_MECHANISM_V1"
REQUIRED_PARENT_NEXT = "NEXT_NON_OPENING_POST_OPEN_ARCHITECTURE_V6"
PREVIOUS_CLOSE_FAMILY = "INFORMATION_EXHAUSTED"
KIND = "MECHANISM_DISCOVERY_ONLY"
CANDIDATE_STRATEGY_N = 0
V5_RESCUE = False
SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
BOARD_FRESHNESS_SEC = 5.0
PRIMARY_HORIZON_SEC = 600.0
SECONDARY_HORIZONS_SEC = (300.0, 900.0)
ANCHOR_HMS = tuple((9, m) for m in range(10, 60, 10)) + tuple((10, m) for m in range(0, 60, 10)) + ((11, 0), (11, 10))
TREE_MAX_DEPTH = 3
TREE_MAX_LEAF_NODES = 8
TREE_MIN_LEAF_N = 100
MAX_TREE_FEATURES = 6
MIN_BLOCK_AGREE = 4
LEAF_MIN_DAY_N = 8
LEAF_MIN_SYMBOL_N = 30
LEAF_MIN_N = 100

CASE_FOUND = "POST_OPEN_STABLE_CAUSAL_UPSIDE_MECHANISM_FOUND_V1"
CASE_NONE = "POST_OPEN_NO_STABLE_CAUSAL_UPSIDE_MECHANISM_IN_CURRENT_CAPTURE_V1"
NEXT_FOUND = "POST_OPEN_CAUSAL_UPSIDE_STRATEGY_PRECOMMIT_V1"
NEXT_NONE = "EXISTING_CAPTURE_POST_OPEN_INFORMATION_CONTENT_LIMIT_V1"

MBO_WORK = False
FUTURES_WORK = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

# 30 features. E3 TOTAL_QUOTE and F2 CALC-MID dropped as redundant (E1+E2, F1+spread).
FEATURE_IDS = (
    "PRICE_RETURN_60S_BPS",
    "PRICE_RETURN_180S_BPS",
    "TRADE_RANGE_60S_BPS",
    "TRADE_RANGE_180S_BPS",
    "DIST_FROM_PREVIOUS_CLOSE_BPS",
    "TRADING_VOLUME_DELTA_60S",
    "TRADING_VOLUME_DELTA_180S",
    "TRADING_VALUE_DELTA_60S",
    "TRADING_VALUE_DELTA_180S",
    "OBSERVED_TRADE_N_60S",
    "OBSERVED_TRADE_N_180S",
    "SPREAD_BPS",
    "BID1_QTY",
    "ASK1_QTY",
    "L1_QTY_IMBALANCE",
    "BUY_DEPTH_10_SUM",
    "SELL_DEPTH_10_SUM",
    "DEPTH_IMBALANCE_10",
    "BUY_DEPTH_NEAR_SHARE",
    "SELL_DEPTH_NEAR_SHARE",
    "BID_UPDATE_N_60S",
    "ASK_UPDATE_N_60S",
    "CALCPRICE_MINUS_CURRENT_BPS",
    "UNDER_BUY_QTY",
    "OVER_SELL_QTY",
    "UNDER_MINUS_OVER",
    "UNIVERSE_POSITIVE_60S_RATE",
    "UNIVERSE_ABOVE_PREVCLOSE_RATE",
    "UNIVERSE_POSITIVE_180S_RATE",
    "MINUTES_FROM_0900",
)

assert ANALYSIS_ID == "POST_OPEN_CAUSAL_UPSIDE_MECHANISM_DISCOVERY_V1"
assert REQUIRED_PARENT_VERDICT == "PRIOR_CLOSE_RECAPTURE_NO_STABLE_SUCCESS_MECHANISM_V1"
assert REQUIRED_PARENT_NEXT == "NEXT_NON_OPENING_POST_OPEN_ARCHITECTURE_V6"
assert int(CANDIDATE_STRATEGY_N) == 0
assert len(ANCHOR_HMS) == 13
assert ANCHOR_HMS[0] == (9, 10)
assert ANCHOR_HMS[-1] == (11, 10)
assert len(FEATURE_IDS) == 30
assert TRUE_OOS is False
assert V5_RESCUE is False
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
