"""Phase 2 precommit correction V1.1. Calendar/fold/shuffle only. No discovery outcomes."""
from __future__ import annotations

from research.causal_driver_pb1.phase2_precommit import (
    BOOTSTRAP_METHOD,
    BOOTSTRAP_N,
    BOOTSTRAP_SEED,
    CLOCK_FIRST,
    CLOCK_LAST,
    DAY_ELIGIBILITY_EXPECTED_N,
    DAY_ELIGIBILITY_MIN_COVERAGE,
    DAY_ELIGIBILITY_WINDOW,
    DAY_SHUFFLE_N,
    DAY_SHUFFLE_SEED,
    EXPECTED_PHASE1_INVENTORY_SHA256,
    EXPECTED_PHASE1_SOURCE_FINGERPRINT,
    EXPECTED_UNIVERSE_MANIFEST_SHA256,
    EXPECTED_UNIVERSE_N,
    EXPECTED_UNIVERSE_SYMBOLS_ORDER_SHA256,
    FDR_METHOD,
    FDR_Q,
    FX_LOOKBACKS_MIN,
    HORIZON_LAST_T,
    MKT105_MIN_VALID_SYMBOLS,
    PARENT_PHASE1_VERDICT,
    RESPONSE_HORIZONS_MIN,
    SECTOR_CLOCK_COVERAGE_MIN,
    SECTOR_MIN_CONSTITUENTS,
    STOCK_ENDPOINT,
    STOCK_PRICE_FIELD,
    STOCK_PROVIDER,
    STOCK_SOURCE_ID,
    STOCK_TIMESTAMP_SEMANTICS,
)

PRECOMMIT_ID = "PHASE2_USDJPY_STANDALONE_CAUSAL_LEAD_PRECOMMIT_V1_1"
ANALYSIS_ID = "PHASE2_USDJPY_STANDALONE_CAUSAL_LEAD_PRECOMMIT_V1_1"
PROGRAM_ID = "CAUSAL_DRIVER_PB1_FOUNDATION"

CASE_READY = "PHASE2_USDJPY_STANDALONE_CAUSAL_LEAD_PRECOMMIT_READY_V1_1"
CASE_BLOCKED = "PHASE2_USDJPY_STANDALONE_CAUSAL_LEAD_PRECOMMIT_BLOCKED_V1_1"
NEXT_RUN = "RUN_PHASE2_USDJPY_STANDALONE_CAUSAL_LEAD_DISCOVERY_V1"
NEXT_RESOLVE = "RESOLVE_TSE_TRADING_CALENDAR_IDENTITY_V1"

SUPERSEDES_PRECOMMIT_ID = "PHASE2_USDJPY_STANDALONE_CAUSAL_LEAD_PRECOMMIT_V1"
SUPERSEDES_PRECOMMIT_SHA256 = "8602f954afca5edfcc95d2b255bad60c14cdb2f7821c982b7f0c49ef7c132683"
SUPERSEDED_FOLD_BOUNDARY_SHA256 = "27fb4e169a445fc6363bc7cf052d715adc830ed6ae4f53c3be73d701da7b700b"

TSE_AM_WINDOW = ("09:00", "11:30")
TSE_AM_MIN_SYMBOLS = 90
DAY_SHUFFLE_METHOD = "SATTOLO_CYCLE_DERANGEMENT_STRATIFIED"

_ = (
    BOOTSTRAP_METHOD,
    BOOTSTRAP_N,
    BOOTSTRAP_SEED,
    CLOCK_FIRST,
    CLOCK_LAST,
    DAY_ELIGIBILITY_EXPECTED_N,
    DAY_ELIGIBILITY_MIN_COVERAGE,
    DAY_ELIGIBILITY_WINDOW,
    DAY_SHUFFLE_N,
    DAY_SHUFFLE_SEED,
    EXPECTED_PHASE1_INVENTORY_SHA256,
    EXPECTED_PHASE1_SOURCE_FINGERPRINT,
    EXPECTED_UNIVERSE_MANIFEST_SHA256,
    EXPECTED_UNIVERSE_N,
    EXPECTED_UNIVERSE_SYMBOLS_ORDER_SHA256,
    FDR_METHOD,
    FDR_Q,
    FX_LOOKBACKS_MIN,
    HORIZON_LAST_T,
    MKT105_MIN_VALID_SYMBOLS,
    PARENT_PHASE1_VERDICT,
    RESPONSE_HORIZONS_MIN,
    SECTOR_CLOCK_COVERAGE_MIN,
    SECTOR_MIN_CONSTITUENTS,
    STOCK_ENDPOINT,
    STOCK_PRICE_FIELD,
    STOCK_PROVIDER,
    STOCK_SOURCE_ID,
    STOCK_TIMESTAMP_SEMANTICS,
)
