"""P4-3: mid-hold recovery-state continuation-value / actionability audit.

Research only. Local counterfactual EXIT value. No new Gate / no best checkpoint /
no percentage cutoff search / no portfolio state-machine replay / no Runtime change.
P4-1 MID_HOLD_NO_PROGRESS_V1 remains CLOSED.
Label: REUSED_HISTORY_PRECOMMITTED_ACTIONABILITY_DIAGNOSTIC.
"""

from research.canonical_fixed_pnl_source_p3_3 import (
    FULL14,
    P1_PF,
    P1_PNL,
    P1_TRADES,
    PREDECLARED_TOP3,
    REST11,
)
from research.fixed_winner_cluster_extension_p3_4 import EXIT600_REASON, EXTEND_REASON

ANALYSIS_ID = "P4_3_MID_HOLD_CONTINUATION_VALUE"
DOCUMENT_ID = "P4_3_RECOVERY_STATE_ACTIONABILITY_AUDIT"
TASK_LABEL = "REUSED_HISTORY_PRECOMMITTED_ACTIONABILITY_DIAGNOSTIC"

STATE_RECOVERING = "RECOVERING_STATE"
STATE_NON_RECOVERING = "NON_RECOVERING_STATE"

# 120 is state-only (cohort + delta baseline). Not an EXIT checkpoint.
STATE_CHECKPOINTS_SEC = (120, 180, 240, 300, 360, 420, 480, 540)
PRIMARY_CHECKPOINTS = (180, 240, 300, 360)
SECONDARY_CHECKPOINTS = (420, 480, 540)
EXIT_CHECKPOINTS_SEC = PRIMARY_CHECKPOINTS + SECONDARY_CHECKPOINTS

P4_2_ADVERSE_N = 47
P4_2_ADVERSE_WIN = 14
P4_2_ADVERSE_LOSS = 33
P4_2_ADVERSE_DRAW = 0

P4_1_WINNER_IDS = (
    "20260722|PM|14:20|4062|19",
    "20260722|PM|14:20|285A|20",
    "20260729|PM|13:40|285A|14",
)
FALSE_RECOVERY_KNOWN_ID = "20260729|AM|09:15|9984|6"

# Canonical ledger rounding band. Not a searched cutoff.
FLAT_YEN = 0.51

CLASS_NEG = "NON_RECOVERY_HAS_NEGATIVE_CONTINUATION_VALUE"
CLASS_NOT_HARM = "NON_RECOVERY_CONTINUATION_NOT_HARMFUL"
CLASS_MIXED = "NON_RECOVERY_CONTINUATION_MIXED"
CLASS_NOT_ACTIONABLE = "RECOVERY_SIGNAL_NOT_ECONOMICALLY_ACTIONABLE"
CLASS_DATA = "MATERIAL_DATA_ISSUE"

VERDICT_OK = "P4_3_CONTINUATION_VALUE_AUDIT_COMPLETE"
VERDICT_ISSUE = "P4_3_MATERIAL_INTEGRITY_ISSUE"
VERDICT_BLOCKED = "P4_3_BLOCKED"

MAX_WORKERS = 2
CACHE_VERSION = 1

FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
P1_TRADES = P1_TRADES
P1_PNL = P1_PNL
P1_PF = P1_PF
EXIT600_REASON = EXIT600_REASON
EXTEND_REASON = EXTEND_REASON
