"""NQ_ES_SECTOR_SYMBOL_CAUSAL_RESPONSE_V1. US equity futures family. Discovery only. No purchase. No playbooks."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "EXPAND_CAUSAL_DRIVER_CATALOG_V1"
ANALYSIS_ID = "NQ_ES_SECTOR_SYMBOL_CAUSAL_RESPONSE_V1"
PARENT_ANALYSIS_ID = "USDJPY_SECTOR_SYMBOL_CAUSAL_RESPONSE_V1"
PARENT_VERDICT = "USDJPY_SECTOR_SPECIFIC_DRIVER_FOUND_V1"
KIND = "NQ_ES_SECTOR_STOCK_CAUSAL_RESPONSE"
SEMANTICS = "BAR_START"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_HM1_ANCHOR_SHA256 = "2b26609cce4f14f50c25a77727e2c77fc037261ea74965fa7e195a0c8cfb9e23"
HM1_ID = "HM1_CONTROLLED_PULLBACK_RECLAIM"
DRIVER_FAMILY = "US_EQUITY_FUTURES_CONTEXT"
FWD_HORIZONS = (1, 2, 3, 5, 10)
PRIMARY_LEAD_HORIZONS = (1, 2, 3)
MIN_CLOCK_N = 2000
MIN_STOCK_N = 400
MIN_DAY_N = 40
MIN_SECTOR_N_AT_CLOCK = 3
RHO_LEAD = 0.04
RHO_WEAK = 0.03
BETA_PER_10BPS = 0.5
BLOCK_MIN = 3
DISCOVERY_FROM = "20240916"
DISCOVERY_TO = "20251126"
ASOF_MAX_LAG_MS = 120_000

STATUS_ACCESSIBLE = "FREE_SOURCE_ACCESSIBLE"
STATUS_PROXY = "PROXY_NOT_CME_FUTURES"
STATUS_BLOCKED = "SOURCE_BLOCKED"
STATUS_PAID_BLOCKED = "TRUE_FUTURES_UNAVAILABLE_NO_PURCHASE"

CASE_NQ_TECH = "NQ_TECH_RESPONSE_GROUP_FOUND_V1"
CASE_ES_BROAD = "US_BROAD_RISK_RESPONSE_GROUP_FOUND_V1"
CASE_NO_LEAD = "NQ_ES_NO_CAUSAL_LEAD_V1"
CASE_PROXY = "US_TECH_PROXY_RESPONSE_FOUND_TRUE_FUTURES_PROOF_REQUIRED_V1"
CASE_BLOCKED = "NQ_ES_SOURCE_ACCESS_BLOCKED_V1"
CASE_BIND = "NQ_ES_BIND_FAILED_V1"

NEXT_UNEXPLAINED = "SELECT_NEXT_DRIVER_FOR_UNEXPLAINED_GROUPS_V1"
NEXT_RESOLVE = "RESOLVE_TRUE_NQ_ES_FUTURES_OR_CONTINUE_GAP_DRIVEN_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

PROXY_NQ = "USATECH.IDX-USD"
PROXY_ES = "USA500.IDX-USD"
PROXY_NQ_ROLE = "NQ_TECH_GROWTH_SEMICONDUCTOR_CONTEXT"
PROXY_ES_ROLE = "ES_BROAD_US_RISK_CONTEXT"

TECH_FOCUS = (
    "6857",
    "8035",
    "6920",
    "285A0",
    "7735",
    "6146",
    "6525",
    "6526",
    "6723",
    "6871",
    "6963",
    "6976",
    "6981",
)
TECH_SECTORS = ("電気機器", "精密機器", "機械", "情報･通信業")
FX_OVERNIGHT_SECTORS = ("輸送用機器", "非鉄金属")

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_USED_TO_DESIGN = False
HM1_TUNED = False
PURCHASE_REQUESTED = False
YFINANCE_USED = False
ENTRY_RULES_OPTIMIZED = False
DATACUBE_PURCHASED = False

assert ANALYSIS_ID == "NQ_ES_SECTOR_SYMBOL_CAUSAL_RESPONSE_V1"
assert PARENT_VERDICT == "USDJPY_SECTOR_SPECIFIC_DRIVER_FOUND_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert KABU_50_APPLIED is False
assert PURCHASE_REQUESTED is False
assert ENTRY_RULES_OPTIMIZED is False
assert FWD_HORIZONS == (1, 2, 3, 5, 10)
assert DISCOVERY_TO < "20251127"
assert PROXY_NQ != "NQ"
assert PROXY_ES != "ES"
