"""P3-4: winner-cluster overlap and 600→750 extension-gate audit.

Research only. No new strategy. No ENTRY / EXIT / Clock / score / Runtime change.
No extension-condition change. No counterfactual portfolio.
Label: REUSED_HISTORY_MECHANISM_DIAGNOSTIC.
"""

from research.canonical_fixed_pnl_source_p3_3 import (
    FULL14,
    P1_PF,
    P1_PNL,
    P1_TRADES,
    PREDECLARED_TOP3,
    REST11,
)
from small_paper.v1r_exit_v2_contract import FROZEN_CONTINUATION, FROZEN_GUARD

ANALYSIS_ID = "P3_4_WINNER_CLUSTER_EXTENSION_AUDIT"
DOCUMENT_ID = "P3_4_FIXED_WINNER_CLUSTER_AND_600_750_GATE"
TASK_LABEL = "REUSED_HISTORY_MECHANISM_DIAGNOSTIC"

CLOCK_FULL14 = "CLOCK_EXACT_TIME_SUPPORTED"
CLOCK_REST11 = "CLOCK_NOT_UNIQUELY_SPECIAL"

TOP3_SYMBOLS = ("285A", "4062", "2737")
ANCHOR_0905 = "09:05"
EXTEND_REASON = "CONT_EXTEND_750"
EXIT600_REASON = "CONT_EXIT_600"
REACHED_600_REASONS = (EXIT600_REASON, EXTEND_REASON)

IDENTITY_REL_TOL = 1e-9
MAX_WORKERS = 2

VERDICT_OK = "P3_4_WINNER_CLUSTER_EXTENSION_AUDIT_COMPLETE"
VERDICT_ISSUE = "P3_4_MATERIAL_INTEGRITY_ISSUE"
VERDICT_BLOCKED = "P3_4_BLOCKED"

GATE_SUPPORTED = "EXTENSION_GATE_SUPPORTED"
GATE_MIXED = "EXTENSION_GATE_MIXED"
GATE_NOT = "EXTENSION_GATE_NOT_SUPPORTED"

CLUSTER_SINGLE = "SINGLE_OVERLAPPING_CLUSTER"
CLUSTER_MULTI = "MULTIPLE_PARTLY_INDEPENDENT_CLUSTERS"
CLUSTER_BROAD = "BROAD_WITH_CONCENTRATED_TAIL"
CLUSTER_NONE = "NO_CLEAR_CLUSTER"

MECH_LABEL = "WINNER_LABEL_ONLY"
MECH_INCR = "WINNER_SELECTION_WITH_INCREMENTAL_EXTENSION_VALUE"
MECH_MIXED = "WINNER_SELECTION_BUT_EXTENSION_VALUE_MIXED"
MECH_NODISC = "EXTENSION_GATE_NOT_DISCRIMINATIVE"
MECH_NONE = "NO_CLEAR_EXTENSION_MECHANISM"

FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
P1_TRADES = P1_TRADES
P1_PNL = P1_PNL
P1_PF = P1_PF
FROZEN_CONTINUATION = FROZEN_CONTINUATION
FROZEN_GUARD = FROZEN_GUARD
