"""FUTURES_REVERSAL_CONFIRMED_ENTRY_DAY1_V1.

Do not predict reversal. Enter only after BOTH_UP is actually observed.
Selection frozen on last causal BOTH_DOWN snapshot. Day2 primary freeze unchanged.
"""
from __future__ import annotations

from research.futures_reversal_precursor_day1_v1 import (
    DAY2_PRIMARY,
    DAY2_PRIMARY_ID,
    GRID_END_HM,
    GRID_START_HM,
    ORIGINAL_FIVE,
    SELECTOR,
    TERCILE_N,
    UNIVERSE_N,
)

ANALYSIS_ID = "FUTURES_REVERSAL_CONFIRMED_ENTRY_DAY1_V1"
PARENT_ID = "FUTURES_REVERSAL_PRECURSOR_DAY1_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
TRADING_DATE = "20260911"

ARM_EXPIRY_SEC = 180
STOCK_HORIZONS_SEC = (60, 180, 300, 600)
STOCK_HORIZON_LABEL = {60: "1m", 180: "3m", 300: "5m", 600: "10m"}

DAY2_PRIMARY_UNCHANGED = True

CASE_A = "A"
CASE_B = "B"
CASE_C = "C"
CASE_D = "D"
VERDICT_A = "FUTURES_REVERSAL_CONFIRMED_ACTIVITY_ENTRY_PLAUSIBLE_DAY1_V1"
VERDICT_B = "FUTURES_REVERSAL_CONFIRMED_ACTIVITY_RELATIVE_ONLY_DAY1_V1"
VERDICT_C = "FUTURES_REVERSAL_EDGE_ALREADY_PRICED_DAY1_V1"
VERDICT_D = "FUTURES_REVERSAL_CONFIRMATION_NOT_SUFFICIENT_DAY1_V1"
NEXT_A = "KEEP_DAY2_PRIMARY_AND_FREEZE_CONFIRMED_ENTRY_AS_SEPARATE_DIAGNOSTIC_V1"
NEXT_B = "KEEP_DAY2_PRIMARY_CONFIRMED_ENTRY_NOT_READY_V1"
NEXT_C = "CLOSE_FUTURES_X_STOCK_INTERACTION_AS_ENTRY_MECHANISM_V1"
NEXT_D = "NEED_ADDITIONAL_CAUSAL_INFORMATION_AFTER_REVERSAL_CONFIRMATION_V1"

ENTRY = False
EXIT = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
DAY2_SUBSTITUTIONS_ALLOWED = False
USE_PRECURSORS = False

assert SELECTOR == "OBSERVED_TRADE_N_180S"
assert ARM_EXPIRY_SEC == 180
assert TERCILE_N == 16
assert ORIGINAL_FIVE == ("09:20", "09:40", "10:20", "10:30", "10:40")
assert DAY2_PRIMARY_UNCHANGED is True
assert DAY2_PRIMARY["substitutions_allowed"] is False
assert ENTRY is False and EXIT is False
assert USE_PRECURSORS is False
assert GRID_START_HM == (9, 5)
assert GRID_END_HM == (11, 10)
assert DAY2_PRIMARY_ID == "FUTURES_X_STOCK_STATE_DAY2_CONFIRMATION_V1"
