"""SUPPORT_RESISTANCE_TEST_DESIGN_AUDIT_V1. Audit whether the prior multi-touch zone test represented recognizable S/R. No PnL."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "SUPPORT_RESISTANCE_TEST_DESIGN_AUDIT_V1"
ANALYSIS_ID = "SUPPORT_RESISTANCE_TEST_DESIGN_AUDIT_V1"
PARENT_ANALYSIS_ID = "MULTI_TOUCH_DAILY_ZONE_1M_PRICE_ACTION_V1"
PARENT_VERDICT = "MULTI_TOUCH_ZONE_NO_INCREMENTAL_INFORMATION_V1"
RCA_DEFERRED = "REFERENCE_LEVEL_MECHANISM_RCA_V1"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"

SAMPLE_N = 200
TRANSITION_N = 100
SAMPLE_SEED = 20260916
MATERIAL_OVERLAP_FRAC = 0.50
NEAR_ATR = 2.0
STALE_ATR = 3.0
WEAK_REJECTION_FRAC = 0.80
WEAK_MAG_ATR = 0.40
ORDINARY_REJECTION_FRAC = 0.60
LUNCH_POLICY = "HOLD_THROUGH_LUNCH_RESUME_PM"
SESSION_FLAT = "15:20"

CASE_A = "MACHINE_ZONE_DETECTOR_NOT_FACE_VALID"
CASE_B = "EVENT_STATE_MACHINE_OVERCOUNTS_INTERACTIONS"
CASE_C = "OLD_OUTCOME_GATE_MISALIGNED"
CASE_D = "MULTIPLE_DESIGN_DEFICIENCIES"
CASE_E = "OLD_TEST_DESIGN_CONFIRMED_VALID"

NEXT_REBUILD = "SUPPORT_RESISTANCE_FACE_VALID_FIRST_INTERACTION_REBUILD_V1"
NEXT_STOP_E = "STOP_OLD_NO_INCREMENTAL_INFORMATION_STANDS_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_OPENED = False
NEW_PAID_DATA = False
PROMOTED = False
V27_BOLTED = False
RCA_EXECUTED = False
ZONE_WIDTH_SELECTED_BY_PNL = False
NO_PNL_PARAMETER_TUNING = True
OLD_NO_INFO_MUST_NOT_MEAN_SR_HAS_NO_MARKET_INFORMATION = True

assert ANALYSIS_ID == "SUPPORT_RESISTANCE_TEST_DESIGN_AUDIT_V1"
assert PARENT_VERDICT == "MULTI_TOUCH_ZONE_NO_INCREMENTAL_INFORMATION_V1"
assert RCA_EXECUTED is False
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert OLD_CONFIRMATION_OPENED is False
assert NO_PNL_PARAMETER_TUNING is True
assert ZONE_WIDTH_SELECTED_BY_PNL is False
assert PROMOTED is False
