"""FUTURES_X_STOCK_STATE_DAY2_CONFIRMATION_V1.

Exact frozen Day1 interaction on a new FULL capture day.
PASS = cross-sectional replication only. Not ENTRY / EXIT / Paper.
Secondary rows cannot rescue a primary fail.
"""
from __future__ import annotations

from research.futures_reversal_precursor_day1_v1 import DAY2_PRIMARY, DAY2_PRIMARY_ID
from research.futures_x_stock_state_day1_candidate_mechanism_audit_v1 import (
    DAY1_SECONDARY_ROWS,
    DAY2_ANALYSIS_ID,
    DAY2_SUBSTITUTIONS_ALLOWED,
    FROZEN_CONTEXT,
    FROZEN_CONTEXT_BUCKET,
    FROZEN_CONTEXT_FAMILY,
    FROZEN_DIRECTION,
    FROZEN_HORIZON,
    FROZEN_SELECTOR,
)
from research.futures_x_stock_state_interaction_day1_v1 import MATERIAL_BPS, MIN_CONTEXT_CLOCK_N, TERCILE_N

ANALYSIS_ID = "FUTURES_X_STOCK_STATE_DAY2_CONFIRMATION_V1"
PARENT_ID = "FUTURES_X_STOCK_STATE_DAY1_CANDIDATE_MECHANISM_AUDIT_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
TRADING_DATE = "20260914"
DAY1_TRADING_DATE = "20260911"

PRIMARY_SELECTOR = FROZEN_SELECTOR
PRIMARY_FAMILY = FROZEN_CONTEXT_FAMILY
PRIMARY_BUCKET = FROZEN_CONTEXT_BUCKET
PRIMARY_HORIZON = FROZEN_HORIZON
PRIMARY_DIRECTION = FROZEN_DIRECTION

VERDICT_PASS = "FUTURES_X_STOCK_STATE_DAY2_PRIMARY_PASS_V1"
VERDICT_FAIL = "FUTURES_X_STOCK_STATE_DAY2_PRIMARY_FAIL_V1"
VERDICT_NOT_RUN = "FUTURES_X_STOCK_STATE_DAY2_CONFIRMATION_NOT_RUN_V1"
NEXT_PASS = "DAY2_REPLICATION_ONLY_DO_NOT_BUILD_ENTRY_V1"
NEXT_FAIL = "DAY2_INTERACTION_DID_NOT_REPLICATE_V1"
NEXT_WAIT = "WAIT_20260914_FULL_FUTURES_CAPTURE_THEN_CONFIRM_V1"

ENTRY = False
EXIT = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
SUBSTITUTIONS_ALLOWED = False
SECONDARY_MAY_RESCUE = False

assert ANALYSIS_ID == DAY2_ANALYSIS_ID == DAY2_PRIMARY_ID
assert TRADING_DATE == "20260914"
assert DAY1_TRADING_DATE == "20260911"
assert PRIMARY_SELECTOR == "OBSERVED_TRADE_N_180S"
assert PRIMARY_FAMILY == "AGREEMENT_180S"
assert PRIMARY_BUCKET == "BOTH_DOWN"
assert PRIMARY_HORIZON == "10m"
assert PRIMARY_DIRECTION == "LONG TOP16"
assert DAY2_PRIMARY["substitutions_allowed"] is False
assert SUBSTITUTIONS_ALLOWED is False
assert DAY2_SUBSTITUTIONS_ALLOWED is False
assert SECONDARY_MAY_RESCUE is False
assert TERCILE_N == 16
assert MATERIAL_BPS == 5.0
assert MIN_CONTEXT_CLOCK_N == 3
assert FROZEN_CONTEXT == "AGREEMENT_180S_BOTH_DOWN"
assert ENTRY is False and EXIT is False
assert len(DAY1_SECONDARY_ROWS) == 7
