"""AM WAIT5 Stage2 fill-edge-preserving objective precommit. No training. No performance."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, MIN_COHORT_N, NORMS
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_WAIT5_STAGE2_FILL_EDGE_PRESERVING_OBJECTIVE_PRECOMMIT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_DEV_ID_REQUIRED = "AM_WAIT5_TWO_STAGE_PRECOMMITTED_DEVELOPMENT_V1"
PRIOR_DEV_VERDICT_REQUIRED = "AM_WAIT5_STAGE2_SINGLE_COMPONENT_ONLY"
PRIOR_REASSESS_ID_REQUIRED = "AM_WAIT5_STAGE2_QUALITY_OBJECTIVE_REASSESSMENT_V1"
PRIOR_REASSESS_VERDICT_REQUIRED = "AM_STAGE2_D_GAIN_IS_FILL_REDUCTION"
NEXT_RESEARCH = "AM_WAIT5_MINIMAL_SWAP_STAGE2_DEVELOPMENT"

STAGE1_SCORE = "P_FILL5"
STAGE2_U_TARGET = "U_FILL"
STAGE2_D_TARGET = "D_FILL"
QUALITY_COMBINATION = "MIN_PERCENTILE_RANK"

STAGE1_SHORTLIST_N = 5
FINAL_SELECTION_N = 3
LOCKED_FILL_SLOTS = 2
MAX_MEMBERSHIP_SWAP_PER_COHORT = 1
QUALITY_SLOT_POOL = ("P_FILL_RANK3", "P_FILL_RANK4", "P_FILL_RANK5")

FILL_PRESERVING_BY_CONSTRUCTION = False
FILL_EDGE_PRESERVING_STRUCTURE = True
OLD_TWO_STAGE_INTERFACE_ALLOWED = False
FILL_LOSS_ALLOWED_IN_PASS_GATE = False
SHORTLIST_SEARCH_ALLOWED = False
PROBABILITY_THRESHOLD_ALLOWED = False
U_D_WEIGHT_SEARCH_ALLOWED = False

ALLOWED_DEVELOPMENT_ARMS = ("CONTROL", "FILL_ONLY", "MINIMAL_SWAP_TWO_STAGE")
CONTROL_ARM = "CURRENT Top3"
FILL_ONLY_ARM = "P_FILL5 Top3"
MINIMAL_SWAP_ARM = "P_FILL5 Rank1 + Rank2 + quality winner among P ranks 3-5"
OLD_TWO_STAGE_ARM = "historical reference only. Not a candidate arm."

PARITY_EXPECTED = {
    "FILL_ONLY_FILL_RATE": 0.4375,
    "FILL_ONLY_EXEC_U": 0.00425138097927976,
    "FILL_ONLY_EXEC_D": -0.003854166912748494,
    "OLD_TWO_STAGE_FILL_RATE": 0.4074074074074074,
    "OLD_TWO_STAGE_EXEC_U": 0.003520227056548451,
    "OLD_TWO_STAGE_EXEC_D": -0.003359498074089692,
    "PRED_U_D_SPEARMAN_MEDIAN": -0.7,
    "ACTUAL_U_D_SPEARMAN_MEDIAN": 0.5,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(LOCKED_FILL_SLOTS) == 2
assert int(MAX_MEMBERSHIP_SWAP_PER_COHORT) == 1
assert int(STAGE1_SHORTLIST_N) == 5
assert int(FINAL_SELECTION_N) == 3
assert int(LOCKED_FILL_SLOTS) + 1 == int(FINAL_SELECTION_N)
assert int(MIN_COHORT_N) >= int(STAGE1_SHORTLIST_N)
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert FILL_PRESERVING_BY_CONSTRUCTION is False
assert FILL_EDGE_PRESERVING_STRUCTURE is True
assert OLD_TWO_STAGE_INTERFACE_ALLOWED is False
assert FILL_LOSS_ALLOWED_IN_PASS_GATE is False
assert SHORTLIST_SEARCH_ALLOWED is False
assert PROBABILITY_THRESHOLD_ALLOWED is False
assert U_D_WEIGHT_SEARCH_ALLOWED is False
assert QUALITY_COMBINATION == "MIN_PERCENTILE_RANK"
assert "TWO_STAGE" not in ALLOWED_DEVELOPMENT_ARMS
assert "MINIMAL_SWAP_TWO_STAGE" in ALLOWED_DEVELOPMENT_ARMS

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WEIGHT_SEARCH = False
LOCK_SLOT_SEARCH = False
ALL_THREE_QUALITY_SLOTS = False
P_FILL_GAP_THRESHOLD = False
P_FILL5_TIMES_QUALITY_ALLOWED = False
U_ONLY_STRATEGY_ALLOWED = False
D_ONLY_STRATEGY_ALLOWED = False
WEIGHTED_UD_STRATEGY_ALLOWED = False
PARETO_STRATEGY_ALLOWED = False
OLD_TWO_STAGE_REEVAL_ALLOWED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
DEVELOPMENT_RUN_STARTED = False
PERFORMANCE_EVAL_STARTED = False
ENTRY_RETRAIN_STARTED = False
