"""NEW_FULL_STRATEGY_ARCHITECTURE_INVENTORY_AND_FREEZE_V3. Inventory then freeze at most one unused Full Strategy. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "NEW_FULL_STRATEGY_ARCHITECTURE_INVENTORY_AND_FREEZE_V3"
PARENT_ANALYSIS_ID = "NEW_FULL_STRATEGY_V2_IMPLEMENTATION_AND_DEV_EVAL_V1"
REQUIRED_V4_VERDICT = "NEW_FULL_STRATEGY_V4_COVERAGE_FAIL"
PINNED_V4_TRADE_N = 11
PINNED_V4_FILL_DAY_N = 6
PINNED_V4_TRADES_PER_DAY = 1.1
PINNED_V4_INTEGRITY_PASS_N = 26
PINNED_V4_INTEGRITY_TOTAL_N = 26
WITHDRAWN_V5_ARCHITECTURE_ID = "BB_VOL_IMPULSE_MA_PULLBACK_X1_Z_SUPPORT_FAIL"

SESSION = "AM"
DIRECTLY_ADVANCES_NEW_LOGIC_COMPLETION = True
V4_CLOSED = True
V4_RCA_RUN = False
V4_RETUNE = False
PREVIOUS_V5_PROPOSAL_WITHDRAWN = True
PULLBACK_FAMILY_RESCUE_FORBIDDEN = True
ANOTHER_PRECOMMIT_RUN = False
OLD_ST_RCA_CONTINUED = False
CSB_RCA_RUN = False
NEW_CANDIDATE_PNL_READ_N = 0
NEW_CANDIDATE_ECONOMICS_RUN = False
TRUE_OOS = False
CERTIFIED = False
SIZING = False

CASE_FROZEN = "NEW_FULL_STRATEGY_ARCHITECTURE_V3_FROZEN"
CASE_NONE = "NEW_FULL_STRATEGY_NO_JUSTIFIED_NEW_ARCHITECTURE_V3"
NEXT_IF_FROZEN = "NEW_FULL_STRATEGY_V3_IMPLEMENTATION_AND_DEV_EVAL_V1"
NEXT_IF_NONE = "NEW_INFORMATION_FAMILY_INVENTORY_V1"

assert ANALYSIS_ID == "NEW_FULL_STRATEGY_ARCHITECTURE_INVENTORY_AND_FREEZE_V3"
assert DIRECTLY_ADVANCES_NEW_LOGIC_COMPLETION is True
assert V4_CLOSED is True
assert V4_RCA_RUN is False
assert V4_RETUNE is False
assert PREVIOUS_V5_PROPOSAL_WITHDRAWN is True
assert PULLBACK_FAMILY_RESCUE_FORBIDDEN is True
assert ANOTHER_PRECOMMIT_RUN is False
assert NEW_CANDIDATE_PNL_READ_N == 0
assert NEW_CANDIDATE_ECONOMICS_RUN is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert NEXT_IF_NONE != PFQ_RECON_FORBIDDEN
assert NEXT_IF_FROZEN != "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V1"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert WITHDRAWN_V5_ARCHITECTURE_ID == "BB_VOL_IMPULSE_MA_PULLBACK_X1_Z_SUPPORT_FAIL"
