"""Closed architecture inventory at mechanism level. No PnL. No RCA."""
from __future__ import annotations

from typing import Any


def _card(
    lineage_id: str,
    information_source: str,
    decision_object: str,
    state_machine: str,
    entry_trigger: str,
    exit_mechanism: str,
    portfolio_interaction: str,
    what_makes_it_distinct: str,
) -> dict[str, Any]:
    return {
        "LINEAGE_ID": lineage_id,
        "INFORMATION_SOURCE": information_source,
        "DECISION_OBJECT": decision_object,
        "STATE_MACHINE": state_machine,
        "ENTRY_TRIGGER": entry_trigger,
        "EXIT_MECHANISM": exit_mechanism,
        "PORTFOLIO_INTERACTION": portfolio_interaction,
        "WHAT_MAKES_IT_DISTINCT": what_makes_it_distinct,
        "CLOSED": True,
    }


def closed_architecture_inventory() -> list[dict[str, Any]]:
    cap = "CAP occupancy at ENTRY fill; same-symbol; slot release at EXIT fill; AM 11:29 flatten where Full Causal."
    return [
        _card(
            "SIMPLE_FULL",
            "Completed 1m OHLCV, session VWAP, volume, frozen E1-E5 conjunction.",
            "Per-name 1m boolean conjunction first-cross.",
            "IDLE → first-cross SIGNAL of E-grid.",
            "Standing 1m predicate becomes true after false (E1-E5).",
            "Independent Z1-Z5 grid, not jointly tied to one ENTRY thesis.",
            cap,
            "Grid of 1m conjunctions × X × Z. Not a structural-level episode and not pullback.",
        ),
        _card(
            "E4_VWAP_RECLAIM",
            "Completed 1m Close vs session VWAP.",
            "VWAP location.",
            "IDLE → Close crosses above VWAP.",
            "VWAP reclaim first-cross.",
            "Historically paired X2/Z3; closed as symbol-dependent.",
            cap,
            "Decision object is session VWAP reclaim, not MA/BB/RCI state and not HTF resistance TEST.",
        ),
        _card(
            "SYSTEMATIC_STATE_TRANSITION",
            "Five frozen 1m booleans: MA trend_up, BB-mid, RCI>-80, volume confirm, Close>VWAP.",
            "Temporal occupancy of a 1m technical bit.",
            "PERSIST_NEXT extra bar or HANDOFF_NEXT A→B.",
            "State still true one extra completed 1m, or A then different B next bar.",
            "Universal Z3 two-bar weakness + session close.",
            cap,
            "Persist/handoff of existing 1m booleans. Not cross-sectional, not HTF numeric level.",
        ),
        _card(
            "C1_MULTI_TIMEFRAME",
            "Same-name 1m state plus last completed 3m/5m bar of the SAME predicate.",
            "HTF boolean confirmation of a 1m technical STATE.",
            "1m FALSE→TRUE onset AND HTF asof finalize_t <= 1m t0 of same predicate.",
            "Same-family HTF standing confirmation.",
            "Paired Z1-Z5 on the 1m clock.",
            cap,
            "HTF confirms the same boolean, not a numeric structural price TEST→BREAK.",
        ),
        _card(
            "C4_PORTFOLIO_CROWDING",
            "Candidate timestamps of an already-defined ENTRY stream.",
            "First unique arrival among colliding signals.",
            "Admission overlay on inherited ST/C1-style signals.",
            "First unique candidate timestamp per ENTRY identity.",
            "Inherited from the matched ENTRY/EXIT pair.",
            "CAP remains occupancy; crowding is uniqueness of arrival, not a new alpha.",
            "Collision handling, not a new ENTRY population.",
        ),
        _card(
            "RECOVERY_SEQUENCE",
            "Completed 1m Close/Low/Volume vs session VWAP (or predefined broken location).",
            "Lost location that must be reclaimed on the exact next bar.",
            "RECLAIM_ARM then exact next-bar acceptance/participation.",
            "Path reclaim of a lost VWAP (R1/R2/R3). Fail aborts arm.",
            "Z3.",
            cap,
            "Next-bar reclaim after a broken location, not resistance TEST then later break.",
        ),
        _card(
            "PARTICIPATION_ONSET",
            "Own-name volume vs frozen-universe volume percentile.",
            "Activity onset, not a technical MA/BB/RCI machine.",
            "T1 activity-onset pulse.",
            "Per-name participation start.",
            "Z3 / participation-loss / hybrid.",
            cap,
            "Volume-percentile onset, not price-structure episode.",
        ),
        _card(
            "PFQ",
            "E1_X7 PFQ research program features.",
            "Quality overlay on a closed program.",
            "Program-closed; not a live Full Strategy unit.",
            "PFQ overlay / quality.",
            "Program-closed.",
            "Not a live occupancy Full Strategy.",
            "Closed research overlay, not a new ENTRY class.",
        ),
        _card(
            "OR_OVERLAY",
            "Production open-strength: day-high nearness, update_count, rank, VWAP nearness after PBv2 reject.",
            "Open-drive leader overlay, not standalone Full Strategy.",
            "PBv2-reject fallback → O_R003/OS9 or day_leader → cap_or=1.",
            "Fallback overlay after PBv2 reject.",
            "Shared production structural exit.",
            "Split pools cap_pbv2=4 cap_or=1.",
            "Production overlay identity. Standalone Open Strength is a new derivative, not this freeze.",
        ),
        _card(
            "DYNAMIC_ANCHOR",
            "Fill-time or trailing price geometry after ENTRY already exists.",
            "EXIT/hold anchor, not ENTRY.",
            "Trail/anchor after fill.",
            "Not a new ENTRY class.",
            "Anchor / trail.",
            "Inherited occupancy.",
            "Closed EXIT/hold lineage.",
        ),
        _card(
            "X9_REGIME",
            "Universe-regime / institutional-participation split of the PFQ line.",
            "Regime partition of a closed program.",
            "PFQ split, not a new ENTRY/EXIT state machine.",
            "Regime filter of closed PFQ.",
            "Program-closed.",
            "Not a new occupancy thesis.",
            "Regime split, not a new decision mechanism.",
        ),
        _card(
            "BREAKOUT_CONTINUATION",
            "Completed 1m Close, prior 5 Highs, prior-10 volume median, session VWAP.",
            "Previous-high breakout first-cross.",
            "P1 Close > max(prev 5 Highs) first-cross AND volume>median10 AND Close>VWAP.",
            "First-cross of previous-high breakout with volume and VWAP.",
            "Paired Full Strategy EXIT library (not V4 BREAK_LEVEL).",
            cap,
            "No prior TEST of a pre-existing HTF MA price. No frozen BREAK_LEVEL support-fail.",
        ),
        _card(
            "FAILED_BREAKDOWN_RECLAIM",
            "Lost downside location then reclaim.",
            "Failed breakdown of support.",
            "Breakdown fail then reclaim chase.",
            "Reclaim of a lost downside location.",
            "Family EXIT.",
            cap,
            "Downside fail-then-reclaim, not upside HTF resistance TEST→BREAK.",
        ),
        _card(
            "VWAP_REJECTION_RECLAIM",
            "Session VWAP rejection then reclaim chase.",
            "VWAP as rejection/reclaim location.",
            "Reject then reclaim VWAP.",
            "VWAP rejection-reclaim family.",
            "Family EXIT.",
            cap,
            "VWAP location lifecycle, not 5m EMA21 structural level.",
        ),
        _card(
            "CSB_MA_ONSET",
            "Per-name 1m trend_up plus count of names for which it is true.",
            "Cross-sectional breadth expanding as a market latch gating own-name onset.",
            "N_up[i] > N_up[i-1] AND this name FALSE→TRUE trend_up.",
            "Joint pulse: market MA-breadth expansion AND name onset.",
            "Z_MA_TREND_LOSS (this name trend_up false) or 11:29 flatten.",
            cap,
            "Other-names' trend_up count. Closed DEV G1-G6 fail. Not retuned.",
        ),
        _card(
            "V4_HTF5_MA_RESISTANCE_EPISODE",
            "Completed 5m EMA21 as numeric STRUCTURAL_PRICE_LEVEL; 1m OHLC; S_VOL_CONFIRM_1M.",
            "Pre-existing HTF MA price: TEST then later break of the same LEVEL_VERSION_ID.",
            "IDLE → RESISTANCE_TESTED → ENTRY_PENDING → OPEN; new LEVEL_VERSION expires unfilled.",
            "Later 1m Close > TEST_LEVEL with volume confirm after a prior TEST.",
            "Z_BREAK_LEVEL_SUPPORT_FAIL then Bid1, or 11:29 flatten.",
            cap,
            "Closed COVERAGE_FAIL. Not RCA'd. Not a pullback. Distinct from C1 boolean HTF confirm.",
        ),
        _card(
            "SIMPLE_TECH_PULLBACK_V1",
            "1m EMA9/21, BB, RCI, volume confirm, optional board_support filter.",
            "Trend context then pullback to MA/BB then rebound continuation.",
            "trend_up → pullback_setup (Low touches EMA9, Close stays above BB lower) → RCI/price-action continuation.",
            "Impulse/trend then MA or BB pullback then rebound. Board is filter, not primary alpha.",
            "Not a frozen Full Strategy EXIT in V1 baseline (ENTRY family / deficiency RCA).",
            "Research family; production PBv2 is the live continuation-quality relative.",
            "Canonical pullback family. Changing EMA9 vs EMA21, BB vs MA touch, volume-before, RCI-after, or break of pullback high is the same mechanism.",
        ),
        _card(
            "SIMPLE_TECH_V6_TREND_PULLBACK_STAGE_RCA",
            "Same V1 stages; diagnostic split of trend vs pullback stages.",
            "Stage RCA of SIMPLE_TECH_PULLBACK_V1, not a new ENTRY.",
            "Parent V1 identity unchanged. entry_rule_changed=false.",
            "Not an ENTRY implementation.",
            "Exit forbidden in V6 RCA.",
            "N/A (diagnostic-only).",
            "Closed diagnostic of the pullback family. Not a new architecture.",
        ),
        _card(
            "E1_X6_FCRR_PULLBACK_ACTIVE",
            "Sequential FCRR features: CONTEXT_READY → PULLBACK_ACTIVE → SELLING_EXHAUSTED.",
            "Context → pullback-active → selling exhausted → continuation.",
            "F1/F2 flow profiles R10/R20/R30. SELLING_EXHAUSTED mandatory.",
            "PULLBACK_ACTIVE then exhaustion then trigger. Family ENTRY_UNREACHABLE.",
            "Joint EXIT planned; never reached.",
            "Frozen E1_X5 comparison CAP/EXIT; sequential family.",
            "Explicit PULLBACK_ACTIVE lineage. Closed unreachable. Do not reopen as Full Strategy.",
        ),
    ]


def inventory_ids() -> list[str]:
    return [str(r["LINEAGE_ID"]) for r in closed_architecture_inventory()]
