"""Phase 1: Historical USDJPY 1m → DriverObservation. No alpha, no stock join, no PB1 bind."""
from __future__ import annotations

from research.causal_driver_pb1 import C1_FIRST, C1_LAST, DEV_FIRST, DEV_LAST, FV_FIRST, PROSPECTIVE_FROM

ANALYSIS_ID = "CAUSAL_DRIVER_PHASE1_USDJPY_HISTORICAL_ADAPTER_V1"
PROGRAM_ID = "CAUSAL_DRIVER_PB1_FOUNDATION"

CASE_READY = "CAUSAL_DRIVER_PHASE1_USDJPY_HISTORICAL_ADAPTER_READY_V1"
CASE_BLOCKED = "CAUSAL_DRIVER_PHASE1_USDJPY_HISTORICAL_ADAPTER_BLOCKED_V1"
NEXT_PRECOMMIT_PHASE2 = "PRECOMMIT_PHASE2_USDJPY_STANDALONE_CAUSAL_LEAD_DISCOVERY_V1"
NEXT_RESOLVE = "RESOLVE_USDJPY_HISTORICAL_ADAPTER_BLOCKERS_V1"

SOURCE_ID = "DUKASCOPY_JETTA_1M"
SOURCE_PROVIDER = "DUKASCOPY_JETTA"
INSTRUMENT = "USDJPY"
JETTA_INSTRUMENT = "USD-JPY"
RESOLUTION = "1m"
NATIVE_TIMEZONE = "UTC"
CANONICAL_TIMEZONE = "Asia/Tokyo"
TIMESTAMP_SEMANTICS = "BAR_START"
DRIVER_FAMILY_ID = "FX_USDJPY"
VALUE_SEMANTICS = "DERIVED_MID_CLOSE"
RECEIVED_AT_SEMANTICS = "HISTORICAL_CAUSAL_AVAILABILITY_PROXY"
MID_IS_RAW_SOURCE = False

PHASE1_RUN_MODE_LABEL = "DRIVER_INGEST"
PHASE1_FIREWALL_RUN_MODE = "DRIVER_DISCOVERY"

ALLOWED_JST_FIRST = DEV_FIRST
ALLOWED_JST_LAST = C1_LAST
UTC_FILE_FIRST = "20240916"
UTC_FILE_LAST = C1_LAST

EXPECTED_PHASE0_VERDICT = "CAUSAL_DRIVER_PHASE0_FOUNDATION_READY_V1"
EXPECTED_PHASE0_CONTRACT_SCHEMA_SHA256 = "c74529e79ea031a48ed2a8bef14f5ff3edb3c216bcfbb08649ddbb508780e509"
EXPECTED_PHASE0_FIREWALL_CONFIG_SHA256 = "c5062c631c65e4c813f395ada2c53966ee9268845af2730b085fb4ada3eedb88"
EXPECTED_PHASE0_DATASET_ROLE_CONFIG_SHA256 = "14c0103f34d879b435d4adf372d8e25e506c5c862126ea7713f35d3dbefed9b0"

JAPAN_SESSION_START = (7, 55)
JAPAN_SESSION_END = (15, 30)
JAPAN_SESSION_EXPECTED_N = 456  # 07:55–15:30 inclusive; lunch kept

_ = (C1_FIRST, C1_LAST, DEV_FIRST, DEV_LAST, FV_FIRST, PROSPECTIVE_FROM)
