"""REFERENCE_LEVEL_1M_PRICE_ACTION_DISCOVERY_V1. Causal reference levels × 1m price action. R11 closed. Discovery only."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "REFERENCE_LEVEL_1M_PRICE_ACTION_DISCOVERY_V1"
ANALYSIS_ID = "REFERENCE_LEVEL_1M_PRICE_ACTION_DISCOVERY_V1"
ATLAS_ID = "REFERENCE_LEVEL_RESPONSE_ATLAS_V1"
PARENT_ANALYSIS_ID = "R11_ONLINE_EPISODE_CAUSALITY_AUDIT_V1"
PARENT_VERDICT = "R11_OFFLINE_CLUSTER_LOOKAHEAD_CONFIRMED_V1"
R11_STRATEGY_ID = "NATIVE_1M_R11_VWAP_RECLAIM_V1"
R11_STATUS = "INVALID_AS_CAUSAL_STRATEGY"
R11_ROLE = "HISTORICAL_RESEARCH_CLUE"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"

X1_TAX_BPS = 8.0
OCCUPANCY = 3
REFRACTORY_MIN = 10
APPROACH_BPS = 10.0
NEAR_PDH_BPS = 20.0
GAP_MIN_BPS = 10.0
PATH_BARS = 30
FAVOR_BPS = 8.0
ENTRY_CUTOFF = "14:50"
SESSION_FLAT = "15:20"
LUNCH_POLICY = "HOLD_THROUGH_LUNCH_RESUME_PM"
TIME_STOP_USED = False
TIME_STOP_KIND = None
MAX_PLAYBOOKS = 8
MIN_PLAYBOOKS_TARGET = 3
MIN_EVENT_N = 80
MIN_DAY_N = 25
MIN_SYMBOL_N = 10
MAX_TOP_SYMBOL_POS_SHARE = 0.50
EVAL_BLOCKS = ("D2", "D3", "D4")
TRAIN_BLOCK = "D1"

CASE_STRATEGY = "REFERENCE_LEVEL_COMPLETE_STRATEGY_DESIGN_EVIDENCE_V1"
CASE_PLAYBOOKS = "REFERENCE_LEVEL_PLAYBOOKS_FOUND_NOT_PROMOTED_V1"
CASE_ATLAS = "REFERENCE_LEVEL_RESPONSE_ATLAS_READY_V1"
CASE_NONE = "REFERENCE_LEVEL_NO_STABLE_MECHANISM_V1"
CASE_BIND = "REFERENCE_LEVEL_BIND_FAILED_V1"

NEXT_FREEZE_PRECOMMIT = "REFERENCE_LEVEL_CAUSAL_STRATEGY_FREEZE_PRECOMMIT_V1"
NEXT_RCA = "REFERENCE_LEVEL_MECHANISM_RCA_V1"
NEXT_ATLAS_ONLY = "STOP_REFERENCE_LEVEL_ATLAS_ONLY_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_OPENED = False
R11_REPAIRED = False
PARAMETER_CHANGED = False
NEW_PAID_DATA = False
PROMOTED = False
V27_BOLTED = False
IMPLICIT_1130_TRUNCATION = False

assert ANALYSIS_ID == "REFERENCE_LEVEL_1M_PRICE_ACTION_DISCOVERY_V1"
assert PARENT_VERDICT == "R11_OFFLINE_CLUSTER_LOOKAHEAD_CONFIRMED_V1"
assert R11_STATUS == "INVALID_AS_CAUSAL_STRATEGY"
assert R11_REPAIRED is False
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert OLD_CONFIRMATION_OPENED is False
assert LUNCH_POLICY == "HOLD_THROUGH_LUNCH_RESUME_PM"
assert IMPLICIT_1130_TRUNCATION is False
assert TIME_STOP_USED is False
assert X1_TAX_BPS == 8.0
assert OCCUPANCY == 3
assert PROMOTED is False
assert V27_BOLTED is False
