"""CAUSE_FIRST_MECHANISM_DISCOVERY_V1. First step of COMPLETE_CAUSAL_STRATEGY_RESEARCH_V1."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.daytrade_historical_research_foundation_v2 import ANALYSIS_ID as PARENT_FOUNDATION_ID
from research.fixed_daytrade_universe_v1 import LAST_COMPLETE_TSE_SESSION
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "COMPLETE_CAUSAL_STRATEGY_RESEARCH_V1"
ANALYSIS_ID = "CAUSE_FIRST_MECHANISM_DISCOVERY_V1"
PARENT_VERDICT = "DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2_READY"
KIND = "MECHANISM_DISCOVERY_ONLY"
SEMANTICS = "BAR_START"
PANEL_FROM = "20240917"
PANEL_TO = LAST_COMPLETE_TSE_SESSION
MIN_ACTIVE_SYMBOLS = 80
DISCOVERY_FRAC = 0.60
CONFIRMATION_FRAC = 0.20
FROZEN_VALIDATION_FRAC = 0.20
PRIMARY_CLOCK = "09:30"
PRIMARY_HORIZON_MIN = 15
X1_TAX_BPS = 8.0
MIN_DAY_N = 25
MIN_DAY_STABILITY = 0.55
CLOCKS = ("09:15", "09:30", "10:00", "13:00")
BREADTH_STRONG = 0.60
BREADTH_WEAK = 0.40

CASE_READY = "CAUSE_FIRST_MECHANISM_DISCOVERY_V1_READY"
CASE_NONE = "CAUSE_FIRST_NO_STABLE_MECHANISM_V1"
CASE_BIND = "CAUSE_FIRST_FOUNDATION_BIND_FAILED_V1"
CASE_SPLIT = "CAUSE_FIRST_SPLIT_FREEZE_FAILED_V1"

NEXT_ENTRY = "CAUSE_FIRST_CONTEXT_PLUS_TECHNICAL_ENTRY_V1"
NEXT_REASSESS = "CAUSE_FIRST_MECHANISM_REASSESSMENT_V1"
NEXT_BIND = "REPAIR_DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2_THEN_RETRY_V1"
NEXT_KABU_FORBIDDEN_NOW = "PAPER_DEPLOYABILITY_COMPRESSION_V1"

STRATEGY_SEARCH_STARTED = "mechanism_discovery_only"
COMPLETE_STRATEGY_FROZEN = False
ENTRY_ONLY_SUCCESS_ALLOWED = False
KABU_50_APPLIED = False
UNIVERSE_105_MANDATORY_FINAL = False
HISTORICAL_BID_ASK_INFERRED = False
SAME_BAR_CLOSE_ENTRY = False
FROZEN_VALIDATION_ACCESSED = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
KABU_REGISTRATION_CHANGED = False
LIVE_20260914_CHANGED = False
PNL_ALLOWED_IN_RESEARCH = True
EXTERNAL_ALLOWED = True
ADDITIONAL_RESEARCH_DATA_ALLOWED = True

assert ANALYSIS_ID == "CAUSE_FIRST_MECHANISM_DISCOVERY_V1"
assert PROGRAM_ID == "COMPLETE_CAUSAL_STRATEGY_RESEARCH_V1"
assert PARENT_FOUNDATION_ID == "DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2"
assert PARENT_VERDICT == "DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2_READY"
assert PANEL_TO == "20260911"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert KABU_50_APPLIED is False
assert UNIVERSE_105_MANDATORY_FINAL is False
assert SAME_BAR_CLOSE_ENTRY is False
assert FROZEN_VALIDATION_ACCESSED is False
assert COMPLETE_STRATEGY_FROZEN is False
assert abs(DISCOVERY_FRAC + CONFIRMATION_FRAC + FROZEN_VALIDATION_FRAC - 1.0) < 1e-12
assert NEXT_KABU_FORBIDDEN_NOW != NEXT_ENTRY
