"""Cross-sectional leader-laggard causal discovery precommit. No discovery outcomes."""
from __future__ import annotations

PROGRAM_ID = "CAUSAL_DRIVER_PB1_FOUNDATION"
PRECOMMIT_ID = "CROSS_SECTIONAL_LEADER_LAGGARD_CAUSAL_DISCOVERY_PRECOMMIT_V1"
ANALYSIS_ID = "CROSS_SECTIONAL_LEADER_LAGGARD_CAUSAL_DISCOVERY_PRECOMMIT_V1"

CASE_READY = "CROSS_SECTIONAL_LEADER_LAGGARD_CAUSAL_DISCOVERY_PRECOMMIT_READY_V1"
CASE_BLOCKED = "CROSS_SECTIONAL_LEADER_LAGGARD_CAUSAL_DISCOVERY_PRECOMMIT_BLOCKED_V1"
NEXT_RUN = "RUN_CROSS_SECTIONAL_LEADER_LAGGARD_CAUSAL_DISCOVERY_V1"
NEXT_RESOLVE = "RESOLVE_CROSS_SECTIONAL_LEADER_LAGGARD_PRECOMMIT_BLOCKERS_V1"

FINAL_NEXT_DRIVER_VERDICT = "NEXT_CAUSAL_DRIVER_FINALIZED_CROSS_SECTIONAL_LEADER_LAGGARD_V1"
PRIMARY_NEXT_DRIVER = "CROSS_SECTIONAL_LEADER_LAGGARD"
DRIVER_FAMILY_ID = "CROSS_SECTIONAL_DRIVER"
BACKUP_DRIVER = "SECTOR_BREADTH_DISPERSION"
FUTURES_STATUS = "FUTURES_DRIVER_DATA_NOT_READY"
PHASE0_DRIVER_FAMILY_ENUM_MUTATED = False

PARENT_USDJPY_VERDICT = "USDJPY_STANDALONE_CAUSAL_LEAD_NOT_FOUND_V2"
PARENT_USDJPY_REASON = "USDJPY_CAUSAL_LEAD_DEV_NOT_FOUND_UNDER_CONTRACT_CORRECT_ASOF_RESPONSE"
PARENT_USDJPY_STATUS = "STOPPED_CURRENT_ARCHITECTURE_V2"
PARENT_CANDIDATE_LIST_SHA256 = "f7c7c704d4e46a70abce303a7c874acb1ba3f01c6831d9d2bc6526d167d6b0c0"
EXPECTED_UNIVERSE_MANIFEST_SHA256 = "1d0a78b1bbd21d8ae06b0c4fab823281adba83190a9da9eda8a42fa43b34fbf7"
EXPECTED_UNIVERSE_N = 105

LEADER_N = 8
SECTOR_MIN_CONSTITUENTS = 3
DEV_AM_COVERAGE_MIN = 0.95
LEADER_DAY_COVERAGE_MIN = 0.95
LEADER_PRICE_AGE_SEC = 60
TARGET_PRICE_AGE_SEC = 120
STRICT_TARGET_PRICE_AGE_SEC = 60
GLOBAL_MIN_VALID_LEADERS = 7
PEER_MIN_N = 2
PEER_CLOCK_COVERAGE_MIN = 0.80
GLOBAL_TARGET_MIN_VALID = 80
GLOBAL_TARGET_MIN_FRAC = 0.80
MKT_EX_LEADERS_MIN_VALID = 80
MKT_EX_LEADERS_MIN_FRAC = 0.80

LOOKBACKS_MIN = (1, 3, 5, 10)
RESPONSE_HORIZONS_MIN = (1, 3, 5, 10)
CLOCK_FIRST = "09:10"
CLOCK_LAST = "11:25"
AM_FIRST = "09:00"
AM_LAST = "11:30"
HORIZON_LAST_T = {"1": "11:25", "3": "11:25", "5": "11:25", "10": "11:20"}
PAST_CONTROL_MIN = 5
SCOPE_N = 9
FAMILY_N = 144

BOOTSTRAP_METHOD = "DATE_BLOCK_BOOTSTRAP"
BOOTSTRAP_N = 2000
BOOTSTRAP_SEED = 20240917
DAY_SHUFFLE_N = 1000
DAY_SHUFFLE_SEED = 20251127
DAY_SHUFFLE_METHOD = "SATTOLO_CYCLE_DERANGEMENT_STRATIFIED"
FDR_METHOD = "BENJAMINI_HOCHBERG"
FDR_Q = 0.05
FDR_FAMILY_N = 144

STOCK_PRICE_FIELD = "close"
STOCK_TIMESTAMP_SEMANTICS = "BAR_START"
SAME_SESSION_ONLY = True
RESOLVER = "last_completed_close_available_at_le_T"

OFFSETS_MIN = (-5, -3, -1, 0, 1, 3, 5)
