"""Resolve the stage-order and price-reference gap. No strategy repair."""
from __future__ import annotations

from research.causal_driver_pb1.phase1.dates import assert_ingest_date_allowed

_ = assert_ingest_date_allowed

ANALYSIS_ID = "RESOLVE_SYMBOL_SETUP_FAILURE_EVIDENCE_GAP_V1"
COMPLETE_STRATEGY_ID = "SYMBOL_SETUP_BASELINE_COMPLETE_STRATEGY_V1"
COMPLETE_STRATEGY_SHA256 = "25d8ef6944c4d82a15d57a3bb078e5503f733184ecb92ee5ad6ba95fe4f95f6d"
HISTORICAL_VERDICT = "SYMBOL_SETUP_BASELINE_PRIMARY_DEFICIENCY_NOT_IDENTIFIED_V1"
CANONICAL_STAGE_ORDER = (
    "MA_TREND",
    "BB_LOCATION",
    "RCI_REVERSAL",
    "VOLUME_PARTICIPATION",
    "PRICE_ACTION_TRIGGER",
    "BOARD_SUPPORT_VETO",
)
QUOTE_HORIZONS = (30, 60, 180, 300)
BAR_HORIZONS = (("1m", 60), ("3m", 180), ("5m", 300))
PARITY_ABS_YEN = 1e-6
TIMING_QUOTE_MATERIAL_SEC = 30.0
TIMING_BAR_MATERIAL_SEC = 120.0
CASE_A = "RAW_DIRECTIONAL_EDGE_NOT_ESTABLISHED"
CASE_B = "RAW_EDGE_BELOW_EXECUTION_FRICTION"
CASE_C = "REFERENCE_TIME_CONTRACT_MISMATCH"
CASE_D = "PRICE_REFERENCE_GAP_UNRESOLVED"
VERDICT_PARITY = "SYMBOL_SETUP_FAILURE_DECOMPOSITION_POPULATION_PARITY_FAIL_V1"
VERDICT_PRICE_PARITY = "PRICE_DECOMPOSITION_PARITY_FAIL"
VERDICT_ORDER = "SYMBOL_SETUP_FAILURE_DECOMPOSITION_STAGE_ORDER_INVALID_V1"
VERDICT_RAW = "SYMBOL_SETUP_RAW_DIRECTIONAL_EDGE_NOT_ESTABLISHED_V1"
VERDICT_FRICTION = "SYMBOL_SETUP_DIRECTIONAL_EDGE_BELOW_EXECUTION_FRICTION_V1"
VERDICT_TIME = "SYMBOL_SETUP_FAILURE_EVIDENCE_REFERENCE_CONTRACT_MISMATCH_V1"
VERDICT_OPEN = "SYMBOL_SETUP_FAILURE_EVIDENCE_GAP_REMAINS_V1"
NEXT_PARITY = "RCA_SYMBOL_SETUP_DIAGNOSTIC_PARITY_V1"
NEXT_ORDER = "RERUN_SYMBOL_SETUP_FAILURE_DECOMPOSITION_CANONICAL_ORDER_V1"
NEXT_RAW = "PRECOMMIT_SYMBOL_SETUP_ONE_MECHANISM_REPAIR_V1"
NEXT_FRICTION = "PRECOMMIT_SYMBOL_SETUP_EXECUTABLE_EDGE_REPAIR_RESEARCH_V1"
NEXT_TIME = "CORRECT_SYMBOL_SETUP_FAILURE_DIAGNOSTIC_REFERENCE_CONTRACT_V1"
NEXT_OPEN = "STOP_SYMBOL_SETUP_REPAIR_UNTIL_NEW_EVIDENCE_V1"
NEXT_STOP = "STOP"
