"""Temporal joint model architecture probe. Research only. No runtime adopt. No Exact."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import F2_UNION
from research.entry_sequence_representation import (
    CHANNELS,
    MARK_OFFSETS,
    N_CHANNELS,
    N_MARKS,
    SEQ_FEATURES,
    SEQUENCE_FEATURE_N,
)

ANALYSIS_ID = "TEMPORAL_JOINT_MODEL_ARCHITECTURE_PROBE_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 3
TRUE_OOS = False
NEW_FORWARD_N = 0
TOPK = 3
JOINT_RATE_MIN = 0.50
SEED_N = 3
SEEDS = (101, 202, 303)

WINDOW_SEC = 180.0
STEP_SEC = 5.0
STATIC_FEATURES = tuple(F2_UNION)
STATIC_N = 11
SEQ_T = int(N_MARKS)
SEQ_C = int(N_CHANNELS)

S0_EXPECTED = {
    "TOP3_MFE_DELTA": 0.0006176389596935367,
    "TOP3_DOWNSIDE_DELTA": 0.00006729208305413287,
    "JOINT_COHORT_SUCCESS_RATE": 0.33916083916083917,
}
S1_EXPECTED = {
    "TOP3_MFE_DELTA": 0.0006135166638949457,
    "TOP3_DOWNSIDE_DELTA": 0.00032286028616205456,
    "JOINT_COHORT_SUCCESS_RATE": 0.34265734265734266,
}
PARITY_ABS_TOL = 1e-10
PRIOR_VERDICT_REQUIRED = "SEQUENCE_SIGNAL_NOT_ROBUST"

LR = 0.001
WEIGHT_DECAY = 0.0001
BATCH_SIZE = 256
EPOCHS = 30
DROPOUT = 0.10
CONV1_OUT = 16
CONV2_OUT = 32
KERNEL = 3
DILATION_1 = 1
DILATION_2 = 2
STATIC_HIDDEN = 16
HEAD_HIDDEN = 24

assert len(STATIC_FEATURES) == STATIC_N
assert SEQ_T == 37 and SEQ_C == 7
assert SEQUENCE_FEATURE_N == 259
assert len(MARK_OFFSETS) == 37
assert CHANNELS == (
    "mid_rel_t0_bps",
    "spread_bps",
    "imbalance",
    "log_bid_qty",
    "log_ask_qty",
    "quote_age_sec",
    "valid_mask",
)
assert SEEDS == (101, 202, 303)

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
HYPERPARAMETER_TUNING = False
ARCHITECTURE_CHANGED = False
KERNEL_CHANGED = False
DILATION_CHANGED = False
LAYER_CHANGED = False
HIDDEN_CHANGED = False
EPOCH_CHANGED = False
LR_CHANGED = False
CLASS_WEIGHT_USED = False
GRID_CHANGED = False
WINDOW_CHANGED = False
CHANNEL_CHANGED = False
SEED_SELECTION = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
PNL_USED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
OTHER_TEMPORAL_STARTED = False
LSTM_USED = False
GRU_USED = False
TRANSFORMER_USED = False
ATTENTION_USED = False
XGBOOST_USED = False
LABEL_CHANGED = False
SEQUENCE_CHANGED = False
