stateDiagram-v2
  [*] --> START
  START --> PREFLIGHT
  PREFLIGHT --> CAPTURE_ONLINE
  CAPTURE_ONLINE --> AM
  AM --> AM_FINALIZE
  AM_FINALIZE --> PM
  PM --> PM_FINALIZE
  PM_FINALIZE --> W4S
  W4S --> CAPTURE_1535_FINALIZE
  CAPTURE_1535_FINALIZE --> [*]
