"""Identity reconstruction of Simple Tech V1. No prices, no PnL, no orders."""
from __future__ import annotations

from research.causal_driver_pb1.phase1.dates import assert_ingest_date_allowed

_ = assert_ingest_date_allowed

ANALYSIS_ID = "SYMBOL_SETUP_BASELINE_RECONSTRUCTION_V1"
CASE_READY = "SYMBOL_SETUP_BASELINE_EXISTING_V1_RECONSTRUCTED_READY"
CASE_GAPS = "SYMBOL_SETUP_BASELINE_EXISTING_V1_RECONSTRUCTED_WITH_GAPS"
CASE_UNRESOLVED = "SYMBOL_SETUP_BASELINE_IDENTITY_UNRESOLVED_V1"
NEXT_READY = "PRECOMMIT_SYMBOL_SETUP_BASELINE_COMPLETE_STRATEGY_V1"
NEXT_GAPS = "PRECOMMIT_SYMBOL_SETUP_BASELINE_MINIMAL_COMPLETION_V1"
NEXT_UNRESOLVED = "RCA_SIMPLE_TECH_BASELINE_IDENTITY_V1"
EXPECTED_V1_SPEC_SHA256 = "5188879e7cab0116a7bbd95cde9491d26ef30eecdc6333d59b13b97c55b978b8"
BASELINE_ID = "SIMPLE_TECH_PULLBACK_V1"
BASELINE_ANALYSIS_ID = "SIMPLE_TECH_ENTRY_FAMILY_V1"
