"""RECOVERY_SEQUENCE_FULL_STRATEGY_ARCHITECTURE_V1. 3 next-bar reclaim architectures x 2 ask-executable modes x Z3. E4 closed."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    LODO_TOP3_MIN,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
    VOLUME_WINDOW,
    WAIT_SEC,
)

ANALYSIS_ID = "RECOVERY_SEQUENCE_FULL_STRATEGY_ARCHITECTURE_V1"
E4_X2_Z3_CLOSED = True
PRIOR_E4_VERDICT = "E4_X2_Z3_TRUE_SYMBOL_DEPENDENCE_CONFIRMED"
FOCUS_EXIT = "Z3"
ENTRY_IDS = ("R1", "R2", "R3")
EXEC_IDS = ("X1", "X2")
EXIT_IDS = ("Z3",)
CANDIDATE_N = 6
CANDIDATE_IDS = (
    "R1_X1_Z3",
    "R1_X2_Z3",
    "R2_X1_Z3",
    "R2_X2_Z3",
    "R3_X1_Z3",
    "R3_X2_Z3",
)
ENTRY_NAMES = {
    "R1": "R1_PRICE_FOLLOWTHROUGH",
    "R2": "R2_FULL_ACCEPTANCE",
    "R3": "R3_PARTICIPATION_CONFIRM",
}
EXEC_NAMES = {
    "X1": "X1_IMMEDIATE_ASK",
    "X2": "X2_WAIT_FOR_PRICE_IMPROVEMENT_CROSS",
}
EXIT_NAMES = {"Z3": "Z3_TWO_BAR_WEAKNESS"}
BOARD_FRESHNESS_SEC = 5.0
MIN_QTY = 100.0
PROSPECTIVE_HARVEST_SUSPENDED = True
TRUE_OOS = False
CERTIFIED = False
STRESS_OPENED_THIS_RUN = False
SIZING = False
RETUNE = False

PRIOR_E4 = {
    "candidate_id": "E4_X2_Z3",
    "TRADE_N": 295,
    "TOTAL_PNL": 820060.0,
    "PF": 1.8901,
    "MAXDD": -162200.0,
    "top_symbol": "285A",
    "top_symbol_pnl": 1208000.0,
    "CAUSAL_EX_TOP1_PNL": -380140.0,
    "CAUSAL_EX_TOP1_PF": 0.5576,
    "CAUSAL_EX_TOP1_MAXDD": -389940.0,
    "causal_day_signs": "2/8",
    "CLOSED": True,
}

CASE_A = "RECOVERY_SEQUENCE_FULL_STRATEGY_DEV_SUPPORTED"
CASE_B = "RECOVERY_SEQUENCE_FULL_STRATEGY_NO_ROBUST_CANDIDATE"
CASE_C = "RECOVERY_SEQUENCE_SELECTION_UNSTABLE"
CASE_D = "RECOVERY_SEQUENCE_COVERAGE_FAILED"
CASE_E = "RECOVERY_SEQUENCE_INTEGRITY_FAILED"

assert ANALYSIS_ID == "RECOVERY_SEQUENCE_FULL_STRATEGY_ARCHITECTURE_V1"
assert E4_X2_Z3_CLOSED is True
assert len(CANDIDATE_IDS) == int(CANDIDATE_N) == 6
assert "E4_X2_Z3" not in CANDIDATE_IDS
assert POSITION_CAP == 5
assert SHARES == 100
assert WAIT_SEC == 5.0
assert MAX_RESEARCH_DATE == "20260807"
assert STRESS_OPENED_THIS_RUN is False
assert SIZING is False
assert LODO_TOP3_MIN == 6
assert VOLUME_WINDOW == 10
assert FORBIDDEN_INPUT_DAYS
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert DEVELOPMENT_DAYS
assert MIN_PF == 1.10
assert MIN_TOTAL_TRADES == 40
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
assert FOCUS_EXIT == "Z3"
assert RETUNE is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert PROSPECTIVE_HARVEST_SUSPENDED is True
assert ENTRY_NAMES
assert EXEC_NAMES
assert EXIT_NAMES
assert BOARD_FRESHNESS_SEC == 5.0
assert MIN_QTY == 100.0
assert PRIOR_E4["CLOSED"] is True
assert CASE_A and CASE_B and CASE_C and CASE_D and CASE_E
