"""Numeric-boundary provenance. No retune."""
from __future__ import annotations

from typing import Any

from research.pb1_v4_clarified_machine_implementation import (
    ATR_SANITY_FRAC,
    CONFLUENCE_N1M,
    E1_BODY_N1M,
    E1_NET_N1M,
    E1_RANGE_N1M,
    FAIL_COUNTER_BODY_FRAC,
    FAIL_DRIVE_BODY_MIN,
    FAIL_DRIVE_DISP_MIN,
    FAIL_DRIVE_N_SAME_MIN,
    FAIL_VISIBLE_RANGE_MIN,
    FAILED_ATTEMPT_N,
    FLAT_DISP_MAX,
    FLAT_RANGE_MAX,
    LAST_BODY_MIN,
    ONE_BAR_SHARE_MAX,
    OR_RECROSS_CLOSES,
    REPEATED_NO_EXPANSION_N,
    S0_ATR_RANGE_MIN,
    S0_GAP_ATR_MIN,
    S0_GAP_RANGE_MIN,
    S0_RANGE_MIN,
    TRUE_BODY_FRAC_MIN,
    TRUE_COUNTER_FRAC,
    TRUE_DISP_MIN,
    TRUE_N_SAME_MIN,
    TRUE_RANGE_MIN,
    UNWIND_FRAC,
    WEAK_BAR_BODY_MAX,
    WIDE_REJECTION_BODY_MAX,
)
from research.pb1_v4_clarified_machine_implementation.calibrate import numeric_boundaries


def inventory() -> dict[str, Any]:
    rows = [
        {
            "name": "ATR_SANITY_FRAC",
            "value": ATR_SANITY_FRAC,
            "class": "DEVELOPMENT_LABEL_ENCODING",
            "examples": ["9501/20251113 MICRO ordinary net/ATR"],
            "n_labels_affected": "MICRO + any tiny-clock-median TRUE FP",
            "candidates": [0.25, 0.40, 0.50],
            "more_than_one_candidate": True,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Scale = max(same-clock median, 0.40*ATR20). 0.25 still let 9501 look like a drive. Human TRUE median net/ATR used as a second check.",
        },
        {
            "name": "LAST_BODY_MIN",
            "value": LAST_BODY_MIN,
            "class": "DEVELOPMENT_LABEL_ENCODING",
            "examples": ["6920/20250404 last body 0.06", "9501/20251113 last body 0.17"],
            "n_labels_affected": "MICRO crawl-after-move",
            "candidates": [0.15, 0.25, 0.35],
            "more_than_one_candidate": True,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Continued-intent last-bar crawl cutoff. Two MICRO exemplars plus TRUE last-body median.",
        },
        {
            "name": "ONE_BAR_SHARE_MAX",
            "value": ONE_BAR_SHARE_MAX,
            "class": "DEVELOPMENT_LABEL_ENCODING",
            "examples": ["7011/20241205 first-bar share 0.63, bar2 body 0.18"],
            "n_labels_affected": "one-bar MICRO family",
            "candidates": [{"share": 0.55, "weak": 0.20}],
            "more_than_one_candidate": False,
            "exists_only_to_fix_one_exemplar": True,
            "SINGLE_EXEMPLAR_BOUNDARY": True,
            "why": "Only 7011/20241205 is named. Encodes one-bar domination, no symbol rule. Must be explicit before prospective face.",
        },
        {
            "name": "WEAK_BAR_BODY_MAX",
            "value": WEAK_BAR_BODY_MAX,
            "class": "DEVELOPMENT_LABEL_ENCODING",
            "examples": ["7011/20241205 bar2 body 0.18"],
            "n_labels_affected": "one-bar MICRO family",
            "candidates": [0.20],
            "more_than_one_candidate": False,
            "exists_only_to_fix_one_exemplar": True,
            "SINGLE_EXEMPLAR_BOUNDARY": True,
            "why": "Paired with ONE_BAR_SHARE_MAX on the same exemplar.",
        },
        {
            "name": "FAIL_VISIBLE_RANGE_MIN",
            "value": FAIL_VISIBLE_RANGE_MIN,
            "class": "DEVELOPMENT_LABEL_ENCODING",
            "examples": ["7011/20250523 range/clock 1.89 body 0.017", "4063/20251118 range 1.15 body 0.03"],
            "n_labels_affected": "FAILED_OPEN wide-rejection seeds",
            "candidates": ["body>=0.40 only (rejected)", "wide body<=0.25 with range>=0.80"],
            "more_than_one_candidate": True,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Two FAILED_OPEN exemplars. Direct spec concept: wide doji/range rejection may seed FAILED_OPEN.",
        },
        {
            "name": "WIDE_REJECTION_BODY_MAX",
            "value": WIDE_REJECTION_BODY_MAX,
            "class": "DEVELOPMENT_LABEL_ENCODING",
            "examples": ["7011/20250523", "4063/20251118"],
            "n_labels_affected": "FAILED_OPEN wide-rejection seeds",
            "candidates": [0.25],
            "more_than_one_candidate": True,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Paired with FAIL_VISIBLE_RANGE_MIN. Concept is in clarified V2; number is development correspondence.",
        },
        {
            "name": "FAIL_DRIVE disp/body/n_same",
            "value": {"disp": FAIL_DRIVE_DISP_MIN, "body": FAIL_DRIVE_BODY_MIN, "n_same": FAIL_DRIVE_N_SAME_MIN, "counter_body": FAIL_COUNTER_BODY_FRAC},
            "class": "IMPLEMENTATION_ASSUMPTION",
            "examples": ["3382/20241004 reclaim", "6758/20250613 never reclaims"],
            "n_labels_affected": "FAILED_OPEN opposite-drive establishment",
            "candidates": ["fixed 6-bar lifetime (forbidden)", "reclaim failed-bar close + 2 same-dir bars"],
            "more_than_one_candidate": True,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Spec says opposite drive is a STATE, no N-bar lifetime. Numeric disp/body are inherited correspondence plus 3382 representability.",
        },
        {
            "name": "UNWIND_FRAC",
            "value": UNWIND_FRAC,
            "class": "IMPLEMENTATION_ASSUMPTION",
            "examples": ["LATE leftovers generally"],
            "n_labels_affected": "ACTIVE death by unwind",
            "candidates": ["session-clock (forbidden)", "0.75 given AND remaining <0.25*peak"],
            "more_than_one_candidate": True,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Encodes 'material unwind' as a dual inequality. Slow leftover with residual displacement never fires.",
        },
        {
            "name": "REPEATED_NO_EXPANSION_N",
            "value": REPEATED_NO_EXPANSION_N,
            "class": "IMPLEMENTATION_ASSUMPTION",
            "examples": ["LATE leftovers generally"],
            "n_labels_affected": "ACTIVE stale-range death",
            "candidates": ["N-bar expiry (forbidden)", "3 completed 5m without new extreme"],
            "more_than_one_candidate": True,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Spec requires stale range-resolution as a STATE. Implementation treats ANY new high/low as progress.",
        },
        {
            "name": "E1 net/range/body N1M",
            "value": {"net": E1_NET_N1M, "range": E1_RANGE_N1M, "body": E1_BODY_N1M},
            "class": "INHERITED_CONSTANT",
            "examples": [],
            "n_labels_affected": "E1 only, not thesis identity",
            "candidates": ["inherited leaked E1 correspondence"],
            "more_than_one_candidate": False,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Not optimized. Not RCA medians as a profit search.",
        },
        {
            "name": "TRUE_DISP_MIN / TRUE_RANGE_MIN / TRUE_BODY / TRUE_N_SAME / TRUE_COUNTER",
            "value": {
                "disp": TRUE_DISP_MIN,
                "range": TRUE_RANGE_MIN,
                "body": TRUE_BODY_FRAC_MIN,
                "n_same": TRUE_N_SAME_MIN,
                "counter": TRUE_COUNTER_FRAC,
            },
            "class": "INHERITED_CONSTANT",
            "examples": [],
            "n_labels_affected": "TRUE seed numeric scale",
            "candidates": ["inherited leaked TRUE numeric"],
            "more_than_one_candidate": False,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Kept as correspondence. Continued-intent STATE sits on top. Spec did not freeze these numbers.",
        },
        {
            "name": "S0_RANGE_MIN / S0_GAP_* / S0_ATR_RANGE_MIN",
            "value": {
                "range": S0_RANGE_MIN,
                "gap_atr": S0_GAP_ATR_MIN,
                "gap_range": S0_GAP_RANGE_MIN,
                "atr_range": S0_ATR_RANGE_MIN,
            },
            "class": "INHERITED_CONSTANT",
            "examples": [],
            "n_labels_affected": "WHY_THIS_STOCK day-reach",
            "candidates": [0.75],
            "more_than_one_candidate": False,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Inherited leaked S0. Same-clock ratio replaces first-bar-only normalizer. Not retuned.",
        },
        {
            "name": "FLAT_DISP_MAX / FLAT_RANGE_MAX",
            "value": {"disp": FLAT_DISP_MAX, "range": FLAT_RANGE_MAX},
            "class": "IMPLEMENTATION_ASSUMPTION",
            "examples": ["8058/20250812", "8630/20250911"],
            "n_labels_affected": "FLAT_OR_CRAWL vs TRUE seed",
            "candidates": ["not listed as a V2 frozen number"],
            "more_than_one_candidate": False,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Flat/crawl numeric floor is an implementation assumption around 'not a directional auction'.",
        },
        {
            "name": "FAILED_ATTEMPT_N / OR_RECROSS_CLOSES / CONFLUENCE_N1M",
            "value": {"failed": FAILED_ATTEMPT_N, "recross": OR_RECROSS_CLOSES, "confluence": CONFLUENCE_N1M},
            "class": "IMPLEMENTATION_ASSUMPTION",
            "examples": [],
            "n_labels_affected": "ACTIVE two-sided / recross / family C",
            "candidates": [],
            "more_than_one_candidate": False,
            "exists_only_to_fix_one_exemplar": False,
            "SINGLE_EXEMPLAR_BOUNDARY": False,
            "why": "Operational encodings of spec states. wick_only_n/micro_break_n stay 0 so FAILED_ATTEMPT rarely fires.",
        },
    ]
    for r in rows:
        spec_concept = r["name"] in (
            "ATR_SANITY_FRAC",
            "LAST_BODY_MIN",
            "ONE_BAR_SHARE_MAX",
            "FAIL_VISIBLE_RANGE_MIN",
            "WIDE_REJECTION_BODY_MAX",
            "UNWIND_FRAC",
            "REPEATED_NO_EXPANSION_N",
        )
        if r["class"] == "INHERITED_CONSTANT":
            continue
        if spec_concept and r["class"] == "DEVELOPMENT_LABEL_ENCODING":
            r["also"] = "encodes a clarified-V2 concept; the number is development correspondence"
    calib = numeric_boundaries()
    return {
        "rows": rows,
        "calibrate_log": calib,
        "SINGLE_EXEMPLAR_BOUNDARY_names": [r["name"] for r in rows if r.get("SINGLE_EXEMPLAR_BOUNDARY")],
        "DIRECT_SPEC_CONCEPT_ENCODING": [
            "continued directional intent as STATE (not a frozen efficiency number)",
            "wide doji/range rejection may seed FAILED_OPEN",
            "ACTIVE dies on unwind / two-sided / failed progress / stale / auction end",
            "ATR20 is sanity scale not a profit threshold",
            "same-clock opening baselines",
        ],
        "retuned": False,
    }
