"""P2-1 Dynamic Anchor historical event / causality validation (no PnL, no trades)."""

ANALYSIS_ID = "P2_1_DYNAMIC_ANCHOR_EVENT_VALIDATION"
DOCUMENT_ID = "P2_1_HISTORICAL_EVENT_CAUSALITY"

PERIOD_START = "20260721"
PERIOD_END = "20260821"
MISSING_DAYS = ("20260815", "20260816")

TRIGGER = "T1_VOLP60_GE_DESIGN_Q80"
CONFIRMATION = "C1_POSITIVE_TREND_10M_V1"

CAPTURE_BOUNDARY_INCOMPLETE = "CAPTURE_BOUNDARY_INCOMPLETE"

P0_MISSING = "P0_MISSING"
CHECKPOINT_MISSING = "CHECKPOINT_MISSING"
CHECKPOINT_STALE = "CHECKPOINT_STALE"
INVALID_PRICE = "INVALID_PRICE"
OTHER = "OTHER"

MAX_WORKERS = 4
