"""MARKET_BREADTH_LEADERSHIP_ACQUISITION_V1. Ranking leadership tape. No strategy."""
from __future__ import annotations

ANALYSIS_ID = "MARKET_BREADTH_LEADERSHIP_ACQUISITION_V1"
PARENT_ID = "FUTURES_MICROSTRUCTURE_PRESSURE_DAY1_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"

# Frozen first types. Do not add 3/4 or credit 8-13.
RANKING_TYPES = (1, 2, 5, 6, 7, 14, 15)
FORBIDDEN_TYPES = (3, 4, 8, 9, 10, 11, 12, 13)
EXCHANGE_DIVISION = "T"
PRIMARY_WINDOW_START_HM = (9, 5)
PRIMARY_WINDOW_END_HM = (11, 25)
DEFAULT_CADENCE_SEC = 60
FALLBACK_CADENCE_SEC = 120
FORBIDDEN_BACKFILL_DAYS = ("20260911",)
FORBIDDEN_RESEARCH_OUTCOME_DAYS = ("20260912",)

CASE_MODE_READY = "MARKET_BREADTH_LEADERSHIP_MODE_READY_V1"
CASE_CAPTURE_PROVEN = "MARKET_BREADTH_LEADERSHIP_CAPTURE_PROVEN_V1"
CASE_NOT_USABLE = "MARKET_BREADTH_RANKING_INPUT_NOT_USABLE_V1"
CASE_CAPACITY = "MARKET_BREADTH_API_CAPACITY_BLOCKED_V1"
NEXT_LIVE = "START_FIRST_LIVE_RANKING_CAPTURE_0905_1125_JST_V1"
NEXT_RETRY_PROBE = "LOGIN_STATION_AND_RERUN_RANKING_PROBE_V1"
NEXT_CAPACITY = "REDUCE_RANKING_CADENCE_OR_HOLD_V1"

ENTRY = False
EXIT = False
DAY2_FROZEN_PRICE_RETURN_TEST_CHANGED = False
TRUE_OOS = False
CERTIFIED = False

assert RANKING_TYPES == (1, 2, 5, 6, 7, 14, 15)
assert 3 not in RANKING_TYPES and 8 not in RANKING_TYPES
assert EXCHANGE_DIVISION == "T"
assert ENTRY is False and EXIT is False
assert DAY2_FROZEN_PRICE_RETURN_TEST_CHANGED is False
assert "20260911" in FORBIDDEN_BACKFILL_DAYS
assert "20260912" in FORBIDDEN_RESEARCH_OUTCOME_DAYS
