"""ONE_MINUTE_NATIVE_PLAYBOOK_DISCOVERY_V1. Atlas then complete playbooks. Discovery only. No paid data."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "ONE_MINUTE_NATIVE_PLAYBOOK_DISCOVERY_V1"
ANALYSIS_ID = "ONE_MINUTE_NATIVE_PLAYBOOK_DISCOVERY_V1"
ATLAS_ID = "ONE_MINUTE_BEHAVIOR_ATLAS_V1"
PARENT_ANALYSIS_ID = "TRUE_CME_NQ_ES_COST_AND_COVERAGE_AUDIT_V1"
PARENT_VERDICT = "TRUE_CME_NQ_ES_SOURCE_BLOCKED_V1"
KIND = "NATIVE_1M_PATH_PLAYBOOK_DISCOVERY"
SEMANTICS = "BAR_START"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_HM1_ANCHOR_SHA256 = "2b26609cce4f14f50c25a77727e2c77fc037261ea74965fa7e195a0c8cfb9e23"
HM1_ID = "HM1_CONTROLLED_PULLBACK_RECLAIM"
HM1_ROLE = "NEAR_THRESHOLD_STOCK_ONLY_LEAD_ONE_PLAYBOOK_CANDIDATE"
X1_TAX_BPS = 8.0
OCCUPANCY = 3
EPISODE_GAP_MIN = 10
LOOKBACK_BARS = 20
IMPULSE_SIGMA = 2.0
VOL_EXPAND = 1.5
RANGE_EXPAND = 1.5
COMPRESSION = 0.60
PATH_BARS = 30
TIME_STOP_MIN = 20
ENTRY_CUTOFF = "14:50"
SESSION_FLAT = "15:20"
FAVOR_BPS = 8.0
MIN_SECTOR_N = 3
MIN_SEQ_N = 80
MIN_SEQ_DAY_N = 25
MIN_PLAYBOOK_TRADE_N = 40
MIN_PLAYBOOK_DAY_N = 20
MIN_PLAYBOOK_SYMBOL_N = 5
MAX_PLAYBOOKS = 8
MIN_PLAYBOOKS_TARGET = 3

CASE_PLAYBOOKS = "ONE_MINUTE_NATIVE_PLAYBOOKS_FOUND_V1"
CASE_ATLAS = "ONE_MINUTE_BEHAVIOR_ATLAS_READY_NO_COMPLETE_PLAYBOOK_V1"
CASE_NONE = "ONE_MINUTE_NATIVE_NO_STABLE_MECHANISM_V1"
CASE_BIND = "ONE_MINUTE_NATIVE_BIND_FAILED_V1"

NEXT_FREEZE_REVIEW = "FREEZE_REVIEW_NATIVE_PLAYBOOKS_V1"
NEXT_SELECT = "SELECT_STRONGEST_NATIVE_SEQUENCES_V1"
NEXT_REASSESS = "NATIVE_PATH_REASSESSMENT_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_USED_TO_DESIGN = False
HM1_TUNED = False
PURCHASE_REQUESTED = False
YFINANCE_USED = False
ENTRY_RULES_OPTIMIZED = False
DATACUBE_PURCHASED = False
KRX_PURCHASED = False
TWSE_PURCHASED = False
DATABENTO_PURCHASED = False
NEW_PAID_DATA = False
FIVE_MINUTE_GRID = False

assert ANALYSIS_ID == "ONE_MINUTE_NATIVE_PLAYBOOK_DISCOVERY_V1"
assert ATLAS_ID == "ONE_MINUTE_BEHAVIOR_ATLAS_V1"
assert PARENT_VERDICT == "TRUE_CME_NQ_ES_SOURCE_BLOCKED_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert HM1_TUNED is False
assert NEW_PAID_DATA is False
assert FIVE_MINUTE_GRID is False
assert KABU_50_APPLIED is False
assert EPISODE_GAP_MIN == 10
assert X1_TAX_BPS == 8.0
assert OCCUPANCY == 3
assert MAX_PLAYBOOKS == 8
