"""PB1_V4_SEMANTIC_SPEC_CLARIFICATION_V1.

Clarify frozen V4 semantics. Do not implement a machine. Do not overwrite READY_V1.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.pb1_v3_2_face_failure_rca import PARENT_V32_SHA, SEMANTIC_RCA_N
from research.pb1_v4_implementation_correction import V4_LEGACY_LEAKED_IMPLEMENTATION
from research.pb1_v4_implementation_correction.definitions import machine_sha256 as corrected_machine_sha256
from research.pb1_v4_implementation_correction_rca import CASE_SPEC as PARENT_RCA_VERDICT
from research.pb1_v4_implementation_correction_rca import NEXT_CLARIFY as PARENT_RCA_NEXT
from research.pb1_v4_implementation_correction_rca import V4_CORRECTED_MACHINE_SHA256
from research.pb1_v4_machine_implementation.definitions import machine_sha256 as leaked_machine_sha256
from research.pb1_v4_opening_drive_location_reaccel_spec import CASE_READY as PARENT_SPEC_VERDICT
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "PB1_V4_SEMANTIC_SPEC_CLARIFICATION"
ANALYSIS_ID = "PB1_V4_SEMANTIC_SPEC_CLARIFICATION_V1"
PARENT_SPEC_PROGRAM = "PB1_V4_OPENING_DRIVE_LOCATION_REACCEL_SPEC"
PARENT_RCA_PROGRAM = "PB1_V4_IMPLEMENTATION_CORRECTION_RCA"
assert PARENT_SPEC_VERDICT == "PB1_V4_SEMANTIC_SPEC_READY_V1"
assert PARENT_RCA_VERDICT == "PB1_V4_SEMANTIC_SPEC_CLARIFICATION_REQUIRED_V1"
assert PARENT_RCA_NEXT == "PB1_V4_SEMANTIC_SPEC_CLARIFICATION_V1"
assert PARENT_V32_SHA == "56edb2c2576805e46193528824fb61faebb5ae7c85be0201f0331e90f9a67f43"
assert SEMANTIC_RCA_N == 88
assert V4_CORRECTED_MACHINE_SHA256 == "21fc72eb420afe5d21ff27bee3b0aa8c28cc6cb35d2a4a441544e4d7e5f5053e"
assert leaked_machine_sha256() == V4_LEGACY_LEAKED_IMPLEMENTATION
assert corrected_machine_sha256() == V4_CORRECTED_MACHINE_SHA256

PRIMARY_SETUP_TIMEFRAME = "5m"
TIMEFRAME_INTERPRETATION = "B"
TIMEFRAME_INTERPRETATION_NAME = "5M_THESIS_PLUS_CAUSAL_INTRABAR_EXECUTION"
V4_IS_1M_STRATEGY = False
ONE_M_CAN_CREATE_STOCK_SELECTION = False
ONE_M_CAN_CREATE_DIRECTION = False
ONE_M_CAN_CREATE_OPENING_DRIVE = False
ONE_M_CAN_CREATE_LOCATION_IDENTITY = False
ONE_M_MAY_OBSERVE_PREIDENTIFIED_LEVEL = True
OPENING_DRIVE_IS_PERMANENT_0915_LABEL = False
PATH_EFFICIENCY_THRESHOLD_FROZEN = False
NORMAL_OPENING_FIRST_BAR_ONLY = False
SAME_CLOCK_OPENING_BASELINES_REQUIRED = True
FAIL_EXTEND_MAX_BARS_IN_SPEC = False
LAST_BREAK_IN_SPEC = False
S4_NUMERIC_SCALE_IN_SPEC = False
S4_REQUIRES_HUGE_BREAKOUT_BAR = False
E1_CAN_CREATE_TRADE_WITHOUT_THESIS_READY = False
E1_CAN_INVENT_SUPPORT_RESISTANCE = False
MACHINE_IMPLEMENTED = False
V4_1_CREATED = False
NUMERIC_THRESHOLD_FROZEN = False

VALID_DRIVE_SEEDS = ("TRUE_OPENING_DRIVE_SEED", "FAILED_OPEN_SEED")
INVALID_DRIVE_SEEDS = ("NO_VALID_DRIVE_SEED",)
OPENING_TAXONOMY = (
    "TRUE_OPENING_DRIVE",
    "FAILED_OPEN_THEN_REAL_DRIVE",
    "TWO_SIDED_OPEN",
    "FLAT_OR_CRAWL",
    "LATE_RANGE_RESOLUTION",
    "MICRO_OR_LEAK",
)
VALID_ACTIVE_DRIVES = ("TRUE_OPENING_DRIVE", "FAILED_OPEN_THEN_REAL_DRIVE")

CASE_READY = "PB1_V4_SEMANTIC_SPEC_CLARIFIED_V2"
CASE_BIND = "PB1_V4_CLARIFIED_SPEC_BIND_FAILED_V1"
NEXT_MACHINE = "PB1_V4_CLARIFIED_MACHINE_IMPLEMENTATION_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

OLD_CONFIRMATION_OPENED = False
FROZEN_VALIDATION_OPENED = False
KABU50_APPLIED = False
PNL_OPTIMIZATION = False
THRESHOLD_OPTIMIZED = False
ANY_RULE_CHANGED = False
FEATURE_MINING = FEATURE_MINING_CLOSED
LIVE_DATE = LIVE_TRADING_DATE
_ = corrected_machine_sha256, leaked_machine_sha256, PARENT_RCA_VERDICT, PARENT_RCA_NEXT
