"""POST_OPEN_CAUSAL_DOWNSIDE_MECHANISM_DISCOVERY_V1. Short, execution-aware. No strategy."""
from __future__ import annotations

from research.post_open_causal_upside_mechanism_discovery_v1 import (
    ANCHOR_HMS,
    BOARD_FRESHNESS_SEC,
    DEVELOPMENT_DAYS,
    FEATURE_IDS,
    PRIMARY_HORIZON_SEC,
    SECONDARY_HORIZONS_SEC,
    SESSION_FLATTEN_HM,
)
from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "POST_OPEN_CAUSAL_DOWNSIDE_MECHANISM_DISCOVERY_V1"
PARENT_ID = "POST_OPEN_EXECUTION_TAX_DECOMPOSITION_V1"
REQUIRED_PARENT_VERDICT = "POST_OPEN_EXECUTION_TAX_MATERIAL_BUT_ALPHA_INSUFFICIENT_V1"
REQUIRED_PARENT_NEXT = "EXISTING_CAPTURE_POST_OPEN_INFORMATION_CONTENT_LIMIT_CONFIRMED_V1"
KIND = "DIRECTION_OBJECTIVE_REDESIGN"
CANDIDATE_STRATEGY_N = 0
SESSION = "AM"
CONTROL_ID = "SHORT_X1_IMMEDIATE_BID"
TREATMENT_ID = "SHORT_W5_FROZEN_ASK_MIRROR"
W5_WAIT_SEC = 5.0
RIDGE_ALPHA = 1.0

EXPECTED_ANCHOR_N = 6500
EXPECTED_EXECUTABLE_N = 4375
EXPECTED_PRIMARY_N = 4345
EXPECTED_LONG_X1_MEAN = -19.887523938008446
EXPECTED_LONG_X1_MEDIAN = -17.905102954341988
PARITY_ABS_TOL = 1e-9

TREE_MAX_DEPTH = 3
TREE_MAX_LEAF_NODES = 8
TREE_MIN_LEAF_N = 100
MAX_TREE_FEATURES = 6
MIN_BLOCK_AGREE = 4
LEAF_MIN_DAY_N = 8
LEAF_MIN_SYMBOL_N = 30
LEAF_MIN_N = 100
LOBO_MIN_POS = 3
POS_BLOCK_MIN = 3

CASE_A = "POST_OPEN_STABLE_CAUSAL_DOWNSIDE_MECHANISM_FOUND_V1"
NEXT_A = "POST_OPEN_SHORT_COMPLETE_FULL_CAUSAL_STRATEGY_CONSTRUCTION_V1"
CASE_B = "POST_OPEN_DOWNSIDE_DRIFT_PRESENT_BUT_NOT_SELECTABLE_V1"
NEXT_B = "NEW_CAUSAL_INFORMATION_ACQUISITION_V1"
CASE_C = "CURRENT_CAPTURE_BIDIRECTIONAL_INFORMATION_LIMIT_CONFIRMED_V1"
NEXT_C = "NEW_CAUSAL_INFORMATION_ACQUISITION_V1"
CASE_PARITY = "POST_OPEN_DOWNSIDE_PARENT_PARITY_FAIL_V1"

TRUE_OOS = False
CERTIFIED = False
MBO_WORK = False
FUTURES_WORK = False
SIZING = False
V5_RESCUE = False

assert ANALYSIS_ID == "POST_OPEN_CAUSAL_DOWNSIDE_MECHANISM_DISCOVERY_V1"
assert REQUIRED_PARENT_VERDICT == "POST_OPEN_EXECUTION_TAX_MATERIAL_BUT_ALPHA_INSUFFICIENT_V1"
assert REQUIRED_PARENT_NEXT == "EXISTING_CAPTURE_POST_OPEN_INFORMATION_CONTENT_LIMIT_CONFIRMED_V1"
assert KIND == "DIRECTION_OBJECTIVE_REDESIGN"
assert int(CANDIDATE_STRATEGY_N) == 0
assert float(W5_WAIT_SEC) == 5.0
assert len(ANCHOR_HMS) == 13
assert len(FEATURE_IDS) == 30
assert TRUE_OOS is False
assert V5_RESCUE is False
assert len(DEVELOPMENT_DAYS) == 10
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert len(FOLD_BLOCKS) == 5
assert PRIMARY_HORIZON_SEC == 600.0
assert SESSION_FLATTEN_HM == (11, 29)
assert BOARD_FRESHNESS_SEC
assert SECONDARY_HORIZONS_SEC == (300.0, 900.0)
