"""CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1. Discovery-unit H5 gate, then frozen O1/O2/O3. Not a Full Strategy."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BOARD_FRESHNESS_SEC,
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS, PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1"
PARENT_DISCOVERY_ID = "PROFITABLE_MOVE_MECHANISM_DISCOVERY_V1"
PARENT_REASSESS_ID = "DISCOVERY_SEARCH_SPACE_REASSESSMENT_V1"
REQUIRED_DISCOVERY_VERDICT = "NO_STABLE_PROFITABLE_MOVE_MECHANISM_FOUND_V1"
REQUIRED_REASSESS_VERDICT = "DISCOVERY_MECHANISM_SEARCH_SPACE_INSUFFICIENT_V1"
REQUIRED_RAW_PREDICATE_N = 12
REQUIRED_PARENT_CANDIDATE_MECHANISM_N = 72
REQUIRED_PARENT_COVERAGE_QUALIFIED_N = 68
REQUIRED_PARENT_PASS_D1_D11_N = 0

P1_ID = "R2_X1_Z3"
P2_ID = "ST_HANDOFF_NEXT__S_CLOSE_ABOVE_VWAP__S_RCI_ABOVE_NEG80"
P1_STATE_A = "S_CLOSE_ABOVE_VWAP"
P2_STATE_A = "S_CLOSE_ABOVE_VWAP"
P2_STATE_B = "S_RCI_ABOVE_NEG80"

SESSION = "AM"
SHARES_LABEL = 100
FIXED_HORIZONS = (3, 5, 10)
PRIMARY_DISCOVERY_HORIZON = 5
BOARD_FRESHNESS_SEC = float(BOARD_FRESHNESS_SEC)
EVENT_N_MIN = 40
EVENT_DAY_N_MIN = 8
POSITIVE_BLOCK_MIN = 4
Q_VALUE_H5_MAX = 0.05
PERM_ITERS = 10000
PERM_SEED = 20260807
TOP_MECHANISM_N = 3
FEATURE_LOOKAHEAD_N = 0
HORIZON_SEARCH = False
THRESHOLD_SEARCH = False
NEW_NUMERIC_THRESHOLD_SEARCH = False
STRATEGY_EXIT_USED_FOR_DISCOVERY = False
FULL_STRATEGY_FROZEN = False
FULL_CAUSAL_PORTFOLIO_RUN = False
TRUE_OOS = False
CERTIFIED = False
SIZING = False
CAP_BEFORE_RAW_SIGNAL_MEASURE = False
OCCUPANCY_BEFORE_RAW_SIGNAL_MEASURE = False

OPERATORS = ("O1_PERSIST_NEXT", "O2_HANDOFF_NEXT", "O3_RECLAIM_ACCEPT_NEXT")
RECLAIM_ACCEPT_IDS = ("R1", "R2", "R3")

CASE_PARITY = "MECHANISM_REPRESENTATION_CONTROL_PARITY_FAILED_V1"
CASE_UNIT = "DISCOVERY_UNIT_MISMATCH_PORTFOLIO_ADMISSION_MATTERS_V1"
CASE_A = "PROFITABLE_MOVE_MECHANISM_FOUND_V1"
CASE_B = "ONLY_CLOSED_MECHANISMS_SHOW_EDGE_V1"
CASE_C = "NO_STABLE_PROFITABLE_MOVE_MECHANISM_FOUND_V1"

NEXT_PARITY = "FIX_REPRESENTATION_ONLY"
NEXT_UNIT = "PORTFOLIO_ADMISSION_AWARE_MECHANISM_DISCOVERY_DESIGN_V1"
NEXT_A = "FULL_STRATEGY_FROM_DISCOVERED_MECHANISM_V1"
NEXT_B = "CLOSED_EDGE_TO_FULL_STRATEGY_DECISION_V1"
NEXT_C = "NO_FURTHER_FINITE_OPERATOR_EXPANSION_V1"

assert ANALYSIS_ID == "CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1"
assert REQUIRED_DISCOVERY_VERDICT == "NO_STABLE_PROFITABLE_MOVE_MECHANISM_FOUND_V1"
assert REQUIRED_REASSESS_VERDICT == "DISCOVERY_MECHANISM_SEARCH_SPACE_INSUFFICIENT_V1"
assert tuple(FIXED_HORIZONS) == (3, 5, 10)
assert int(PRIMARY_DISCOVERY_HORIZON) == 5
assert HORIZON_SEARCH is False
assert THRESHOLD_SEARCH is False
assert NEW_NUMERIC_THRESHOLD_SEARCH is False
assert FEATURE_LOOKAHEAD_N == 0
assert FULL_STRATEGY_FROZEN is False
assert FULL_CAUSAL_PORTFOLIO_RUN is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert CAP_BEFORE_RAW_SIGNAL_MEASURE is False
assert OCCUPANCY_BEFORE_RAW_SIGNAL_MEASURE is False
assert tuple(OPERATORS) == ("O1_PERSIST_NEXT", "O2_HANDOFF_NEXT", "O3_RECLAIM_ACCEPT_NEXT")
assert NEXT_A != PFQ_RECON_FORBIDDEN
assert NEXT_UNIT != PFQ_RECON_FORBIDDEN
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert abs(float(BOARD_FRESHNESS_SEC) - 5.0) < 1e-12
