"""Complete-strategy precommit. No PnL and no prospective rows."""
from __future__ import annotations

ANALYSIS_ID = "PRECOMMIT_SECTOR_STATE_ALPHA_COMPLETE_STRATEGY_V1_1"
CASE_READY = "SECTOR_STATE_ALPHA_COMPLETE_STRATEGY_PRECOMMIT_READY_V1_1"
CASE_BLOCKED = "SECTOR_STATE_ALPHA_COMPLETE_STRATEGY_PRECOMMIT_BLOCKED_V1"
NEXT_READY = "RUN_SECTOR_STATE_ALPHA_COMPLETE_STRATEGY_ECONOMIC_FEASIBILITY_V1"
CANCELLED_NEXT = "ACTIVATE_SECTOR_STATE_ALPHA_SIGNAL_SHADOW_PROSPECTIVE_V1"
