"""E1_X7 Pullback Flow Quality (PFQ) — independent family, not TAER V2."""

DOCUMENT_ID = "E1_X7_PULLBACK_FLOW_QUALITY"
FAMILY_ID = "PFQ"
STUDY_TYPE = "INDEPENDENT_ENTRY_EXIT_JOINT_STUDY"
SOURCE_ANALYSIS = "E1_X6_TAER_FAILURE_SOURCE_ANALYSIS_V4"
SOURCE_RUN = "e1x6_taer_fsa_v4_20260804_071044"
