"""C1_MULTI_TIMEFRAME_ENTRY_EXIT_PAIR_PRECOMMIT_V2. EXIT semantic uniqueness. No economics."""
from __future__ import annotations

from research.c1_multi_timeframe_entry_exit_pair_precommit_v1 import (
    EXECUTION_ID,
    EXIT_IDS,
    EXIT_SOURCE_FUNCTION,
    EXIT_SOURCE_KEYS,
    EXIT_SOURCE_MODULE,
    EXIT_SOURCE_PATH,
    RAW_CANDIDATE_IDS,
    RAW_STRATEGY_N,
    REQUIRED_PRIOR_HASHES,
    SIMPLE_FULL_X1_ID,
)
from research.c1_multi_timeframe_precommit_v1 import (
    ARCHITECTURE_CLASS,
    BURNED_HOLDOUT_DAYS,
    C4_CLASS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SESSION,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_ID

ANALYSIS_ID = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_PAIR_PRECOMMIT_V2"
PRIOR_PAIR_ANALYSIS_ID = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_PAIR_PRECOMMIT_V1"
PRIOR_PAIR_VERDICT_REQUIRED = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_LIBRARY_FROZEN"
PRIOR_Z3_ONLY_ANALYSIS_ID = "C1_MULTI_TIMEFRAME_FULL_STRATEGY_V1"
PRIOR_Z3_ONLY_VERDICT_REQUIRED = "C1_MULTI_TIMEFRAME_NO_ROBUST_CANDIDATE"

CASE_A = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_LIBRARY_V2_FROZEN"
CASE_B = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_LIBRARY_V1_UNIQUENESS_CONFIRMED"
CASE_E = "C1_MULTI_TIMEFRAME_EXIT_SEMANTIC_DEDUP_INTEGRITY_FAILED"

NEXT_IF_A = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2"
NEXT_IF_B = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V1"
NEXT_IF_E = "Resolve only the failed EXIT-domain proof. Do not run economics. Do not change ENTRY/EXIT rules."

DEV_CLASSIFICATION = "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
EXPECTED_EXIT_FILE_SHA256 = "1a2798c6bcee0885615751a7ced6f479973620822787202fba054c9d2b5b538e"
Z3_PREVIOUSLY_OBSERVED_PAIR_N = 10
MISMATCH_EXAMPLE_CAP = 20
PAIRWISE_EXIT_PAIRS = (
    ("Z1_VWAP_LOSS", "Z2_STRUCTURE_LOSS"),
    ("Z1_VWAP_LOSS", "Z3_TWO_BAR_WEAKNESS"),
    ("Z1_VWAP_LOSS", "Z4_TRAILING_STRUCTURE"),
    ("Z1_VWAP_LOSS", "Z5_HYBRID_SIMPLE"),
    ("Z2_STRUCTURE_LOSS", "Z3_TWO_BAR_WEAKNESS"),
    ("Z2_STRUCTURE_LOSS", "Z4_TRAILING_STRUCTURE"),
    ("Z2_STRUCTURE_LOSS", "Z5_HYBRID_SIMPLE"),
    ("Z3_TWO_BAR_WEAKNESS", "Z4_TRAILING_STRUCTURE"),
    ("Z3_TWO_BAR_WEAKNESS", "Z5_HYBRID_SIMPLE"),
    ("Z4_TRAILING_STRUCTURE", "Z5_HYBRID_SIMPLE"),
)

assert ANALYSIS_ID == "C1_MULTI_TIMEFRAME_ENTRY_EXIT_PAIR_PRECOMMIT_V2"
assert CASE_A != CASE_B != CASE_E
assert NEXT_IF_A != NEXT_IF_B
assert EXECUTION_ID == "X1_IMMEDIATE_ASK"
assert len(EXIT_IDS) == 5
assert len(PAIRWISE_EXIT_PAIRS) == 10
assert len(RAW_CANDIDATE_IDS) == 10
assert int(RAW_STRATEGY_N) == 50
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert CANARY_ID == "RECOVERY_R2_X1_Z3"
assert CANARY_EXPECTED
assert DEV_CLASSIFICATION == "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
assert EXPECTED_EXIT_FILE_SHA256
assert REQUIRED_PRIOR_HASHES
assert FORBIDDEN_INPUT_DAYS
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert SESSION == "AM"
assert ARCHITECTURE_CLASS == "C1_MULTI_TIMEFRAME"
assert C4_CLASS == "C4_PORTFOLIO_CROWDING"
assert SIMPLE_FULL_X1_ID == "X1_PASSIVE_BID_THEN_CANCEL"
assert EXIT_SOURCE_PATH.endswith("exits.py")
assert EXIT_SOURCE_FUNCTION == "technical_fire_i"
assert EXIT_SOURCE_MODULE
assert EXIT_SOURCE_KEYS["Z4_TRAILING_STRUCTURE"] == "Z4"
assert Z3_PREVIOUSLY_OBSERVED_PAIR_N == 10
assert MISMATCH_EXAMPLE_CAP > 0
