"""FUTURES_REVERSAL_PRECURSOR_DAY1_V1.

Can T-time causal features foreshadow a later futures reversal?
T+3m reversal is LABEL only. Not an ENTRY input. Day2 primary freeze unchanged.
"""
from __future__ import annotations

ANALYSIS_ID = "FUTURES_REVERSAL_PRECURSOR_DAY1_V1"
PARENT_ID = "FUTURES_X_STOCK_STATE_DAY1_CANDIDATE_MECHANISM_AUDIT_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
TRADING_DATE = "20260911"

DAY2_PRIMARY_ID = "FUTURES_X_STOCK_STATE_DAY2_CONFIRMATION_V1"
DAY2_PRIMARY_UNCHANGED = True

GRID_START_HM = (9, 5)
GRID_END_HM = (11, 10)
RET_WINDOWS_SEC = (30, 60, 180)
LABEL_HORIZONS_MIN = (1, 3)
STOCK_HORIZONS_SEC = (60, 180, 300, 600)
STOCK_HORIZON_LABEL = {60: "1m", 180: "3m", 300: "5m", 600: "10m"}
SELECTOR = "OBSERVED_TRADE_N_180S"
TERCILE_N = 16
UNIVERSE_N = 48

ORIGINAL_FIVE = ("09:20", "09:40", "10:20", "10:30", "10:40")
PRIMARY_PRECURSORS = ("P1", "P2", "P3", "P4")
COMBINATIONS = ("C1", "C2")

DAY2_PRIMARY = {
    "context": "AGREEMENT_180S_BOTH_DOWN",
    "selector": "OBSERVED_TRADE_N_180S",
    "rank": "TOP16 / BOTTOM16",
    "horizon": "10m",
    "direction": "LONG TOP16",
    "substitutions_allowed": False,
}

VERDICT_A = "FUTURES_REVERSAL_PRECURSOR_PLAUSIBLE_DAY1_V1"
VERDICT_B = "FUTURES_REVERSAL_PRECURSOR_PARTIAL_DAY1_V1"
VERDICT_C = "FUTURES_REVERSAL_NOT_CAUSALLY_IDENTIFIABLE_DAY1_V1"
NEXT_A = "KEEP_DAY2_PRIMARY_FREEZE_AND_CONFIRM_PRECURSOR_AS_SEPARATE_DIAGNOSTIC_V1"
NEXT_B = "KEEP_DAY2_PRIMARY_FREEZE_PRECURSOR_NOT_ENTRY_V1"
NEXT_C = "KEEP_DAY2_PRIMARY_CONFIRMATION_ONLY_POST_HOC_REVERSAL_DEPENDENT_V1"

ENTRY = False
EXIT = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
DAY2_SUBSTITUTIONS_ALLOWED = False

assert RET_WINDOWS_SEC == (30, 60, 180)
assert LABEL_HORIZONS_MIN == (1, 3)
assert 5 not in LABEL_HORIZONS_MIN
assert 10 not in LABEL_HORIZONS_MIN
assert SELECTOR == "OBSERVED_TRADE_N_180S"
assert ORIGINAL_FIVE == ("09:20", "09:40", "10:20", "10:30", "10:40")
assert COMBINATIONS == ("C1", "C2")
assert DAY2_PRIMARY_UNCHANGED is True
assert DAY2_PRIMARY["substitutions_allowed"] is False
assert ENTRY is False and EXIT is False
assert GRID_START_HM == (9, 5)
assert GRID_END_HM == (11, 10)
