"""SELECTION_SURFACE_MECHANISM_RCA_V1. Existing-artifact ST stability RCA. No replay."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "SELECTION_SURFACE_MECHANISM_RCA_V1"
PARENT_ANALYSIS_ID = "GENERALIZATION_FAILURE_COMPONENT_RCA_V1"
PARENT_VERDICT_REQUIRED = "GENERALIZATION_COMPONENT_TWO_STAGE_FAILURE_CONFIRMED"
PARENT_NEXT_REQUIRED = "SELECTION_SURFACE_MECHANISM_RCA_V1"
PARENT_PRIMARY_COMPONENT = "CROSS_LINEAGE_CONCENTRATION_FRAGILITY"
PARENT_RESIDUAL_BOTTLENECK = "ST_SPECIFIC_SELECTION_SURFACE_GENERALIZATION"

ST_STUDY_ID = "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1"
ST_WINNER_ID = "ST_HANDOFF_NEXT__S_CLOSE_ABOVE_VWAP__S_RCI_ABOVE_NEG80"
ST_TRADE_N = 75
ST_BASE_PNL = 220580.0
ST_BASE_PF = 2.7365769170209417
ST_TRAIN_TOP3_N = 2
ST_FOLD_SELECTED_TEST_TOTAL_PNL = -67720.0

B1_PNL = 10100.0
B2_PNL = 153000.0
B3_PNL = 72200.0
B4_PNL = -8500.0
B5_PNL = -6219.999999999993

FAILING_S1 = "S1_TRAIN_TOP3_RECURRENCE"
FAILING_S4 = "S4_FOLD_SELECTED_HELDOUT_TRANSFER"

VERDICT_INCONCLUSIVE = "SELECTION_SURFACE_MECHANISM_RCA_INCONCLUSIVE"
NEXT_EVIDENCE_GAP = "SELECTION_SURFACE_EVIDENCE_GAP_V1"
NEXT_ELIGIBILITY = "TRAIN_GATE_MARGIN_MECHANISM_RCA_V1"
NEXT_RANK = "TRAIN_RANK_SURFACE_RCA_V1"
NEXT_BOTH = "TRAIN_SELECTION_COMPONENT_RCA_V1"

RECURRENCE_INCONCLUSIVE = "INCONCLUSIVE_MISSING_FOLD_EVIDENCE"
N3_UNKNOWN = "N3_UNKNOWN"

TRUE_OOS = False
CERTIFIED = False
SIZING = False
NEW_REPLAY = False
NEW_FOLD_RUN = False
NEW_FOLD_ECONOMICS = False
NEW_ENTRY = False
NEW_EXIT = False
NEW_CANDIDATE = False
RAW_CAPTURE_READ_N = 0
ST_SPECIFIC = True
L1_WIDE = False
CROSS_LINEAGE_SELECTION = False

assert ANALYSIS_ID == "SELECTION_SURFACE_MECHANISM_RCA_V1"
assert NEW_REPLAY is False
assert NEW_FOLD_RUN is False
assert NEW_FOLD_ECONOMICS is False
assert ST_SPECIFIC is True
assert L1_WIDE is False
assert CROSS_LINEAGE_SELECTION is False
assert RAW_CAPTURE_READ_N == 0
assert NEXT_EVIDENCE_GAP != PFQ_RECON_FORBIDDEN
assert TRUE_OOS is False
assert CERTIFIED is False
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
