"""AM WAIT5 two-stage ENTRY objective precommit. No training. No PnL. No Exact."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_WAIT5_TWO_STAGE_OBJECTIVE_PRECOMMIT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_ANALYSIS_ID_REQUIRED = "WAIT5_SESSION_TARGET_LEARNABILITY_V1"
PRIOR_AM_TARGET_STATUS_REQUIRED = "TWO_STAGE_TARGETS_LEARNABLE"
PRIOR_AM_NEXT_REQUIRED = "AM_WAIT5_TWO_STAGE_OBJECTIVE_PRECOMMIT"
NEXT_RESEARCH = "AM_WAIT5_TWO_STAGE_PRECOMMITTED_DEVELOPMENT"

STAGE1_TARGET = "Y_FILL5_AM"
STAGE1_SCORE = "P_FILL5"
STAGE2_U_TARGET = "U_FILL"
STAGE2_D_TARGET = "D_FILL"
QUALITY_COMBINATION = "MIN_PERCENTILE_RANK"
ARCHITECTURE = "STAGE1_FILLABILITY→STAGE2_CONDITIONAL_QUALITY"

U_D_WEIGHT_SEARCH_ALLOWED = False
STAGE1_STAGE2_SINGLE_SCALAR_ALLOWED = False
BEST_REPRESENTATION_ADOPTED = False

ALLOWED_DEVELOPMENT_ARMS = ("CONTROL", "FILL_ONLY", "TWO_STAGE")
CONTROL_ARM = "CURRENT Top3"
FILL_ONLY_ARM = "P_FILL5 Top3"
TWO_STAGE_ARM = "precommitted Stage1 + Joint Quality rule"

PARITY_EXPECTED = {
    "AM_LABELED_N": 6441,
    "AM_Y_FILL5_POS_N": 698,
    "AM_Y_FILL5_RATE": 0.10836826579723645,
    "AM_CURRENT_TOP3_FILL5_RATE": 0.37962962962962965,
    "AM_CONDITIONAL_FILL_N": 698,
    "AM_FILLABILITY_TOP3_DELTA": 0.05787037037037035,
    "AM_U_FILL_SPEARMAN": 0.2499120386589144,
    "AM_D_FILL_SPEARMAN": 0.2564831497987338,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert COMMON_AM_PM_MODEL_ALLOWED is False
assert COMMON_AM_PM_TARGET_ALLOWED is False
assert U_D_WEIGHT_SEARCH_ALLOWED is False
assert STAGE1_STAGE2_SINGLE_SCALAR_ALLOWED is False
assert BEST_REPRESENTATION_ADOPTED is False
assert QUALITY_COMBINATION == "MIN_PERCENTILE_RANK"

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
ENTRY_RETRAIN_STARTED = False
SESSION_INDICATOR_COMMON_MODEL = False
QUALITY_SCALAR_WEIGHT = False
JOINT_BINARY_TARGET = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
PARETO_TARGET_ADOPTED = False
PARETO_KNEE_SEARCH = False
WEIGHT_SEARCH = False
U_ONLY_STRATEGY_ALLOWED = False
D_ONLY_STRATEGY_ALLOWED = False
WEIGHTED_UD_STRATEGY_ALLOWED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
W10_RESELECTED = False
STAGE1_THRESHOLD_CREATED = False
TOPN_SHORTLIST_CREATED = False
PROBABILITY_CUTOFF_CREATED = False
DEVELOPMENT_RUN_STARTED = False
