"""P3-2: post-fill execution-price vs MID direction decomposition.

Research only. No new strategy. No score / ENTRY / EXIT / Clock / Runtime change.
P3-0R filled set is SoT. P3-1 SELECTION_EDGE = EXECUTION_DOMINANT is frozen.
Label: REUSED_HISTORY_MECHANISM_DIAGNOSTIC.
"""

from research.fixed_anchor_mechanism_audit_p3_0 import (
    CLOCK_EXACT_TIME_SUPPORTED,
    CLOCK_NOT_UNIQUELY_SPECIAL,
)
from research.fixed_selection_diagnostic_reconcile_p3_0r import (
    FULL14,
    PREDECLARED_TOP3,
    REST11,
)

ANALYSIS_ID = "P3_2_POST_FILL_EDGE_DECOMPOSITION"
DOCUMENT_ID = "P3_2_EXECUTION_PRICE_VS_POST_FILL_DIRECTION"
TASK_LABEL = "REUSED_HISTORY_MECHANISM_DIAGNOSTIC"

CLOCK_FULL14 = CLOCK_EXACT_TIME_SUPPORTED
CLOCK_REST11 = CLOCK_NOT_UNIQUELY_SPECIAL

SOT_SELECTED_N = 1115
SOT_SELECTED_FILL_N = 286
SOT_NOT_SELECTED_N = 9943
SOT_NOT_SELECTED_FILL_N = 291

HORIZONS_SEC = (1, 10, 60, 180, 600)
PRIMARY_DIR_HORIZONS = (60, 180, 600)
MICRO_HORIZONS = (1, 10)

DIR_SUPPORTED = "POST_FILL_DIRECTION_SUPPORTED"
DIR_MIXED = "POST_FILL_DIRECTION_MIXED"
DIR_NOT = "POST_FILL_DIRECTION_NOT_SUPPORTED"

MECH_PURE_EXEC = "PURE_EXECUTION_PRICE_ADVANTAGE"
MECH_PLUS_DIR = "EXECUTION_PLUS_POST_FILL_DIRECTION"
MECH_ADVERSE = "EXECUTION_WITH_POST_FILL_ADVERSE_SELECTION"
MECH_MIXED = "EXECUTION_PLUS_POST_FILL_MIXED"
MECH_NONE = "NO_CLEAR_FILL_MECHANISM"

VERDICT_OK = "P3_2_POST_FILL_EDGE_DECOMPOSITION_COMPLETE"
VERDICT_ISSUE = "P3_2_MATERIAL_DIAGNOSTIC_ISSUE"
VERDICT_BLOCKED = "P3_2_BLOCKED"

IDENTITY_REL_TOL = 1e-9
MAX_WORKERS = 2
FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
