"""AM WAIT5 two-stage precommitted development. 3 frozen arms. No Exact. No PnL."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from research.wait5_session_target_learnability import (
    POS_REP_DENOM,
    POS_REP_MIN,
    RF_CLF_PARAMS,
    RF_REG_PARAMS,
)
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_WAIT5_TWO_STAGE_PRECOMMITTED_DEVELOPMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_OBJECTIVE_ID = "AM_WAIT5_TWO_STAGE_OBJECTIVE_PRECOMMIT_V1"
PRIOR_OBJECTIVE_VERDICT = "AM_WAIT5_TWO_STAGE_OBJECTIVE_PRECOMMITTED"
PRIOR_INTERFACE_ID = "AM_WAIT5_TWO_STAGE_INTERFACE_PRECOMMIT_V1"
PRIOR_INTERFACE_VERDICT = "AM_WAIT5_TWO_STAGE_INTERFACE_PRECOMMITTED"
PRIOR_LEARNABILITY_ID = "WAIT5_SESSION_TARGET_LEARNABILITY_V1"

STAGE1_SHORTLIST_N = 5
FINAL_SELECTION_N = 3
SLOTS = 3

PARITY_EXPECTED = {
    "AM_LABELED_N": 6441,
    "AM_Y_FILL5_POS_N": 698,
    "AM_CURRENT_TOP3_FILL5_RATE": 0.37962962962962965,
    "AM_FILLABILITY_TOP3_DELTA": 0.05787037037037035,
    "AM_U_FILL_SPEARMAN": 0.2499120386589144,
    "AM_D_FILL_SPEARMAN": 0.2564831497987338,
    "STAGE1_SHORTLIST_N": 5,
    "FINAL_SELECTION_N": 3,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(STAGE1_SHORTLIST_N) == 5
assert int(FINAL_SELECTION_N) == 3
assert int(SLOTS) == 3
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(POS_REP_MIN) == 6
assert int(POS_REP_DENOM) == 9
assert RF_CLF_PARAMS.get("class_weight") is None
assert int(RF_REG_PARAMS["n_estimators"]) == 500
assert int(RF_REG_PARAMS["max_depth"]) == 6
assert COMMON_AM_PM_MODEL_ALLOWED is False

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
SHORTLIST_SEARCH = False
U_ONLY_STRATEGY_ALLOWED = False
D_ONLY_STRATEGY_ALLOWED = False
WEIGHTED_UD_STRATEGY_ALLOWED = False
PARETO_STRATEGY_ALLOWED = False
P_FILL5_TIMES_QUALITY_ALLOWED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
DEVELOPMENT_RUN_STARTED = True
