"""PB1_V3_2_FACE_FAILURE_RCA_V1.

Why frozen V3.2 failed independent semantic holdout.
No V3.3. No rule change. No PnL. No future outcome.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.pb1_v3_1_face_validity_fix import PARENT_V2_SHA, PARENT_V3_SHA
from research.pb1_v3_2_opening_drive_and_reacceleration_semantics import PARENT_V31_SHA
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "PB1_V3_2_FACE_FAILURE_RCA"
ANALYSIS_ID = "PB1_V3_2_FACE_FAILURE_RCA_V1"
PARENT_V32_PROGRAM = "PB1_V3_2_OPENING_DRIVE_AND_REACCELERATION_SEMANTICS"
PARENT_V32_SHA = "56edb2c2576805e46193528824fb61faebb5ae7c85be0201f0331e90f9a67f43"
PARENT_UNSEEN_PROGRAM = "PB1_V3_2_DISCOVERY_UNSEEN_FACE_VERIFY"
PARENT_UNSEEN_VERDICT = "PB1_V3_2_DISCOVERY_UNSEEN_FACE_FAIL_V1"
PARENT_UNSEEN_N = 21
PARENT_V3_FACE_N = 67
SEMANTIC_RCA_N = 88
MANIFEST_FINAL_N = 352
assert PARENT_V31_SHA == "24089d94b2610eb8eaf19160d503b6477347f970a27650b6a04282884f436c65"
assert PARENT_V3_SHA == "4348b941f9eb0a827db743041752c49f91be8cd9f92a1920c4ffd7c6c0dc8f89"
assert PARENT_V2_SHA == "3ebe0220fd9cb1e5749e39833fa1bab0146759cce5dc9daaacf0e3b3d3daf3fd"

EXEMPLAR_EARLY_REVERSAL = ("3382", "20241004", "bear")

OPENING_STATES = (
    "TRUE_OPENING_DRIVE",
    "FAILED_OPEN_THEN_REAL_DRIVE",
    "TWO_SIDED_OPEN",
    "FLAT_OR_CRAWL",
    "LATE_RANGE_RESOLUTION",
    "MICRO_OR_LEAK",
)
LOCATION_KINDS = (
    "OR_ONLY_DEFENSE",
    "PRIOR_SR_ZONE_DEFENSE",
    "CLEARED_ZONE_RETEST",
    "PDH_PDL_DEFENSE",
    "VWAP_CONFLUENCE",
    "DAILY_LEVEL_CONFLUENCE",
    "NO_MEANINGFUL_LEVEL",
)
ATTR_TAGS = (
    "NO_TRUE_OPENING_DRIVE",
    "TWO_SIDED_OPEN",
    "EARLY_REVERSAL_FALSE_POSITIVE",
    "ORDINARY_ACTIVITY_NOT_IN_PLAY",
    "OR_BOUNDARY_NOT_REAL_STRUCTURE",
    "NO_MEANINGFUL_DEFENDED_LOCATION",
    "WEAK_REACCELERATION",
    "MICRO_CROSS_ONLY",
    "LATE_RANGE_RESOLUTION",
    "OPENING_THESIS_ALREADY_LOST",
    "HIGHER_TIMEFRAME_CONFLICT",
    "RETEST_PROBLEM",
    "OTHER",
)
LAYERS = (
    "STOCK_SELECTION",
    "OPENING_DRIVE",
    "LOCATION",
    "RETEST",
    "REACCELERATION",
    "MULTI_TIMEFRAME_CONTEXT",
)
RANK_LEVELS = ("PRIMARY", "SECONDARY", "CONTRIBUTING", "NOT_SUPPORTED")

CASE_REBUILD = "PB1_SEMANTIC_REBUILD_V4"
CASE_OR_WEAK = "PB1_OR_FRAMEWORK_TOO_WEAK_V1"
CASE_LABELS = "PB1_HUMAN_LABELS_UNSTABLE_V1"
CASE_BIND = "PB1_V3_2_FACE_FAILURE_RCA_BIND_FAILED_V1"
CASE_INCOMPLETE = "PB1_V3_2_FACE_FAILURE_RCA_LABELS_INCOMPLETE_V1"
NEXT_V4 = "PB1_V4_OPENING_DRIVE_LOCATION_REACCEL_SPEC_V1"
NEXT_STOP_OR = "STOP_PB1_OPENING_RANGE_CONTINUATION_V1"
NEXT_LABEL = "COMPLETE_SECOND_PASS_LABELS_THEN_RETRY_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KAPPA_UNSTABLE = 0.40

OLD_CONFIRMATION_OPENED = False
FROZEN_VALIDATION_OPENED = False
KABU50_APPLIED = False
PNL_OPTIMIZATION = False
THRESHOLD_OPTIMIZED = False
V32_RULE_CHANGED = False
V33_CREATED = False
PROSPECTIVE_CAPTURE_USED = False
FEATURE_MINING = FEATURE_MINING_CLOSED
LIVE_DATE = LIVE_TRADING_DATE
_ = OPENING_STATES, LOCATION_KINDS, ATTR_TAGS, LAYERS, RANK_LEVELS
