"""Second-pass human labels. Charts through trigger only. No machine auction/trigger/previous label displayed."""
from __future__ import annotations

from collections import Counter
from typing import Any


def _lab(
    pattern: str,
    opening_state: str,
    opening: str,
    location: str,
    location_kind: str,
    retest: str,
    trigger: str,
    *attrs: str,
    note: str,
    htf_role: str = "contextual",
    late: bool = False,
) -> dict[str, Any]:
    return {
        "sp_pattern": pattern,
        "sp_opening_state": opening_state,
        "sp_opening": opening,
        "sp_location": location,
        "sp_location_kind": location_kind,
        "sp_retest": retest,
        "sp_trigger": trigger,
        "sp_attrs": list(attrs),
        "sp_htf_role": htf_role,
        "sp_late": late,
        "sp_note": note,
        "sp_future_used": False,
    }


def _r(
    pattern: str,
    state: str,
    opening: str,
    loc: str,
    kind: str,
    retest: str,
    trig: str,
    note: str,
    *attrs: str,
    late: bool = False,
) -> dict[str, Any]:
    return _lab(pattern, state, opening, loc, kind, retest, trig, *attrs, note=note, htf_role="contextual", late=late)


# rca_id 1-67 = V3 semantic-dev. 68-88 = independent-failed 21.
# Second pass from 5m opening sequence + daily/1m charts through trigger. Not a copy of first pass.
HUMAN_LABELS: dict[int, dict[str, Any]] = {
    1: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "09:36 micro OR_HIGH leak; 5m not a drive.", "NO_TRUE_OPENING_DRIVE", "MICRO_CROSS_ONLY", "OR_BOUNDARY_NOT_REAL_STRUCTURE", late=True),
    2: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Three same-dir 5m bars then first OR_HIGH hold and expansion."),
    3: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Two-sided 5m; R=3 grind.", "NO_TRUE_OPENING_DRIVE", "TWO_SIDED_OPEN", "WEAK_REACCELERATION"),
    4: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Post-split two-sided crawl.", "NO_TRUE_OPENING_DRIVE", "TWO_SIDED_OPEN"),
    5: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "PDH_PDL_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "Late OR sit already at PDH.", "LATE_RANGE_RESOLUTION", "OPENING_THESIS_ALREADY_LOST", late=True),
    6: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Same-dir 5m but displacement is a crawl, not a drive.", "NO_TRUE_OPENING_DRIVE", "WEAK_REACCELERATION"),
    7: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening high then dump through OR_LOW; 5m same-dir."),
    8: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Two-sided open then tiny leak.", "TWO_SIDED_OPEN", "NO_TRUE_OPENING_DRIVE"),
    9: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "24m grind after break; HTF conflict.", "TWO_SIDED_OPEN", "LATE_RANGE_RESOLUTION", "HIGHER_TIMEFRAME_CONFLICT", late=True),
    10: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Real 5m drive but immediately into overhead bands.", "NO_MEANINGFUL_DEFENDED_LOCATION", "OR_BOUNDARY_NOT_REAL_STRUCTURE"),
    11: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Falling daily + OR_HIGH leak.", "NO_TRUE_OPENING_DRIVE", "HIGHER_TIMEFRAME_CONFLICT", late=True),
    12: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Large 5m displacement then first retest and expansion."),
    13: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Gap-up sold idea but 5m two-sided and trigger body is empty.", "TWO_SIDED_OPEN", "WEAK_REACCELERATION", "MICRO_CROSS_ONLY", "HIGHER_TIMEFRAME_CONFLICT"),
    14: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "09:53 leftover leak on daily uptrend.", "LATE_RANGE_RESOLUTION", "HIGHER_TIMEFRAME_CONFLICT", late=True),
    15: _r("QUESTIONABLE", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "QUESTIONABLE_LOCATION", "NO_MEANINGFUL_LEVEL", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "5m dump exists but planned R is not a location.", "NO_MEANINGFUL_DEFENDED_LOCATION"),
    16: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "Opening dump then 21m grind.", "OPENING_THESIS_ALREADY_LOST", "LATE_RANGE_RESOLUTION", late=True),
    17: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Early break on a tight crawl.", "NO_TRUE_OPENING_DRIVE", "MICRO_CROSS_ONLY"),
    18: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "10:07 late morning leak.", "LATE_RANGE_RESOLUTION", late=True),
    19: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Grind then 09:17 leak.", "TWO_SIDED_OPEN", "NO_TRUE_OPENING_DRIVE"),
    20: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Micro leak after a daily crash.", "TWO_SIDED_OPEN", "ORDINARY_ACTIVITY_NOT_IN_PLAY"),
    21: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Tiny OR_HIGH then immediate retest.", "NO_TRUE_OPENING_DRIVE", "MICRO_OR_LEAK", "MICRO_CROSS_ONLY"),
    22: _r("CLEAR_CONTINUATION", "FAILED_OPEN_THEN_REAL_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Reversal 5m then cleared PDH/OR cluster and far-side retest."),
    23: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "10:06 after a long grind.", "LATE_RANGE_RESOLUTION", late=True),
    24: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "R=5 crawl along OR_HIGH.", "TWO_SIDED_OPEN", "NO_TRUE_OPENING_DRIVE"),
    25: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening drive 22600-23000 then first retest."),
    26: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "R=8 grind.", "NO_TRUE_OPENING_DRIVE", "FLAT_OR_CRAWL"),
    27: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "10:08 leftover.", "LATE_RANGE_RESOLUTION", late=True),
    28: _r("QUESTIONABLE", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Opening jump then grind leak, not reacceleration.", "WEAK_REACCELERATION", "OR_BOUNDARY_NOT_REAL_STRUCTURE"),
    29: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Tiny leak after a daily dump.", "NO_TRUE_OPENING_DRIVE", "HIGHER_TIMEFRAME_CONFLICT"),
    30: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening dump through 1700, cleared zone, far-side retest."),
    31: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening dump 4120-4050 then OR_LOW retest."),
    32: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "10:01 late range leak.", "LATE_RANGE_RESOLUTION", late=True),
    33: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "09:15 dump, leave, first retest of cleared zone."),
    34: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "09:46 after a long grind.", "LATE_RANGE_RESOLUTION", late=True),
    35: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Tiny OR_LOW leak.", "NO_TRUE_OPENING_DRIVE", "MICRO_OR_LEAK", "HIGHER_TIMEFRAME_CONFLICT"),
    36: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "R=2.5 micro OR_LOW leak.", "TWO_SIDED_OPEN", "MICRO_OR_LEAK"),
    37: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Zone cleared but R=2 crawl.", "TWO_SIDED_OPEN", "WEAK_REACCELERATION", "HIGHER_TIMEFRAME_CONFLICT"),
    38: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "NO_MEANINGFUL_LEVEL", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "ZONE_NOT_CLEARED crawl.", "OR_BOUNDARY_NOT_REAL_STRUCTURE", "NO_MEANINGFUL_DEFENDED_LOCATION", "HIGHER_TIMEFRAME_CONFLICT"),
    39: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "09:17 dump, cleared zone, 09:19 far-side retest."),
    40: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "16m leave then grind retest.", "RETEST_PROBLEM", "LATE_RANGE_RESOLUTION", late=True),
    41: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "09:49 R=3 late leak.", "LATE_RANGE_RESOLUTION", late=True),
    42: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening drive, zone break, first far-side retest."),
    43: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Sitting on OR_HIGH then late retest.", "LATE_RANGE_RESOLUTION", late=True),
    44: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "Opening drive already completed; leftover OR leak.", "OPENING_THESIS_ALREADY_LOST", "LATE_RANGE_RESOLUTION", late=True),
    45: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "09:33 grind leak.", "TWO_SIDED_OPEN", "NO_TRUE_OPENING_DRIVE"),
    46: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "09:15 tiny OR_HIGH leak.", "NO_TRUE_OPENING_DRIVE", "MICRO_OR_LEAK"),
    47: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening drive 4700-4930 then first OR_HIGH retest."),
    48: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Tiny leak after a daily crash; not state B.", "NO_TRUE_OPENING_DRIVE", "EARLY_REVERSAL_FALSE_POSITIVE", "HIGHER_TIMEFRAME_CONFLICT"),
    49: _r("QUESTIONABLE", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Opening bounce into pink immediately above.", "NO_MEANINGFUL_DEFENDED_LOCATION", "OR_BOUNDARY_NOT_REAL_STRUCTURE"),
    50: _r("QUESTIONABLE", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Drive into overhead bands; HTF conflict.", "NO_MEANINGFUL_DEFENDED_LOCATION", "HIGHER_TIMEFRAME_CONFLICT"),
    51: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "R=7 grind along OR_HIGH.", "NO_TRUE_OPENING_DRIVE", "FLAT_OR_CRAWL"),
    52: _r("NOT_CONTINUATION", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "INVALID_TRIGGER", "10:10 after 30m; not opening continuation.", "LATE_RANGE_RESOLUTION", "OPENING_THESIS_ALREADY_LOST", "RETEST_PROBLEM", late=True),
    53: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening dump through the zone, far-side retest."),
    54: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Dump thesis but 5m has two counter bars and a tiny trigger.", "TWO_SIDED_OPEN", "WEAK_REACCELERATION", "MICRO_CROSS_ONLY"),
    55: _r("CLEAR_CONTINUATION", "FAILED_OPEN_THEN_REAL_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "09:15 dump and first retest of cleared OR/zone; trigger is small."),
    56: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "09:44 leftover.", "LATE_RANGE_RESOLUTION", "HIGHER_TIMEFRAME_CONFLICT", late=True),
    57: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "R=9 crawl of OR_LOW.", "TWO_SIDED_OPEN", "HIGHER_TIMEFRAME_CONFLICT"),
    58: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening dump, cleared zone, far-side retest."),
    59: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening dump 3470-3370 through the zone."),
    60: _r("NOT_CONTINUATION", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "INVALID_TRIGGER", "10:00 leak after an hour of range.", "LATE_RANGE_RESOLUTION", "OPENING_THESIS_ALREADY_LOST", "HIGHER_TIMEFRAME_CONFLICT", late=True),
    61: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "09:49 R=7 late leak.", "LATE_RANGE_RESOLUTION", "HIGHER_TIMEFRAME_CONFLICT", late=True),
    62: _r("QUESTIONABLE", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Opening drip then micro OR_LOW leak.", "WEAK_REACCELERATION", "MICRO_CROSS_ONLY", "HIGHER_TIMEFRAME_CONFLICT"),
    63: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "09:15 dump, 09:26 first OR_LOW retest still in the opening window."),
    64: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "09:34 crawl of OR_HIGH.", "TWO_SIDED_OPEN", "NO_TRUE_OPENING_DRIVE"),
    65: _r("CLEAR_CONTINUATION", "TRUE_OPENING_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "Opening grind-up then first OR_HIGH retest."),
    66: _r("QUESTIONABLE", "FAILED_OPEN_THEN_REAL_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "Dump already happened; 19m later leftover retest.", "OPENING_THESIS_ALREADY_LOST", "RETEST_PROBLEM", late=True),
    67: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "10:03 late morning leak.", "LATE_RANGE_RESOLUTION", late=True),
    68: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "Failed-open bounce already completed; 10:15 leftover leak.", "EARLY_REVERSAL_FALSE_POSITIVE", "OPENING_THESIS_ALREADY_LOST", "LATE_RANGE_RESOLUTION", "NO_TRUE_OPENING_DRIVE", late=True),
    69: _r("CLEAR_CONTINUATION", "FAILED_OPEN_THEN_REAL_DRIVE", "CLEAR_DIRECTIONAL_AUCTION", "CLEAR_DEFENDED_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "VALID_REACCELERATION", "3382 exemplar: large failed-open 5m body then sustained dump, OR_LOW hold, continuation."),
    70: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "CLEARED_ZONE_RETEST", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Tight crawl then micro drip; zone tag is not a drive.", "NO_TRUE_OPENING_DRIVE", "TWO_SIDED_OPEN", "WEAK_REACCELERATION"),
    71: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Flat opening range; tiny OR_HIGH leak.", "NO_TRUE_OPENING_DRIVE", "TWO_SIDED_OPEN", "ORDINARY_ACTIVITY_NOT_IN_PLAY"),
    72: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "EARLY_REVERSAL tag on an OR_HIGH grind, not state B.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "MICRO_OR_LEAK"),
    73: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Micro OR_HIGH poke; expansion vs a tiny retest bar.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "MICRO_CROSS_ONLY"),
    74: _r("NOT_CONTINUATION", "TWO_SIDED_OPEN", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "NO_MEANINGFUL_LEVEL", "QUESTIONABLE_RETEST", "INVALID_TRIGGER", "Flat 155 tape. Not continuation.", "NO_TRUE_OPENING_DRIVE", "TWO_SIDED_OPEN", "EARLY_REVERSAL_FALSE_POSITIVE", "HIGHER_TIMEFRAME_CONFLICT"),
    75: _r("NOT_CONTINUATION", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Daily waterfall; tiny OR_HIGH leak.", "NO_TRUE_OPENING_DRIVE", "EARLY_REVERSAL_FALSE_POSITIVE", "HIGHER_TIMEFRAME_CONFLICT"),
    76: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "PDH_PDL_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Micro leak into PDH cluster.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "MICRO_OR_LEAK"),
    77: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Slow drip, not a failed-open dump.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE"),
    78: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "Hour of range then leftover leak.", "EARLY_REVERSAL_FALSE_POSITIVE", "LATE_RANGE_RESOLUTION", "OPENING_THESIS_ALREADY_LOST", late=True),
    79: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Extremely tight OR_HIGH crawl.", "NO_TRUE_OPENING_DRIVE", "FLAT_OR_CRAWL", "MICRO_CROSS_ONLY", "ORDINARY_ACTIVITY_NOT_IN_PLAY"),
    80: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Early OR_LOW poke on a flat line.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "HIGHER_TIMEFRAME_CONFLICT"),
    81: _r("NOT_CONTINUATION", "TWO_SIDED_OPEN", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Countertrend leak at the high of a vertical daily.", "NO_TRUE_OPENING_DRIVE", "HIGHER_TIMEFRAME_CONFLICT", "OR_BOUNDARY_NOT_REAL_STRUCTURE"),
    82: _r("QUESTIONABLE", "FAILED_OPEN_THEN_REAL_DRIVE", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Dip-and-grind through OR_HIGH; not a dominant drive.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "NO_MEANINGFUL_DEFENDED_LOCATION"),
    83: _r("QUESTIONABLE", "LATE_RANGE_RESOLUTION", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "21m sit then leftover drip.", "LATE_RANGE_RESOLUTION", "OPENING_THESIS_ALREADY_LOST", "HIGHER_TIMEFRAME_CONFLICT", late=True),
    84: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "CLEARED_ZONE_RETEST", "STALE_OR_EXHAUSTED", "WEAK_REACCELERATION", "19m grind; cleared-zone leak is still a crawl.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "LATE_RANGE_RESOLUTION", late=True),
    85: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "TWO_SIDED_OR_RANGE", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "QUESTIONABLE_RETEST", "WEAK_REACCELERATION", "Late-morning micro OR_HIGH leak.", "EARLY_REVERSAL_FALSE_POSITIVE", "LATE_RANGE_RESOLUTION", "NO_TRUE_OPENING_DRIVE", late=True),
    86: _r("QUESTIONABLE", "FLAT_OR_CRAWL", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "PDH_PDL_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Parabolic daily; flat 10000 crawl into PDH.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "ORDINARY_ACTIVITY_NOT_IN_PLAY"),
    87: _r("QUESTIONABLE", "TWO_SIDED_OPEN", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Small OR_LOW crawl, not a distinctive selloff.", "NO_TRUE_OPENING_DRIVE", "TWO_SIDED_OPEN"),
    88: _r("QUESTIONABLE", "MICRO_OR_LEAK", "AMBIGUOUS_OPEN", "QUESTIONABLE_LOCATION", "OR_ONLY_DEFENSE", "VALID_FIRST_RETEST", "WEAK_REACCELERATION", "Tiny OR_HIGH leak on a recovering daily.", "EARLY_REVERSAL_FALSE_POSITIVE", "NO_TRUE_OPENING_DRIVE", "MICRO_OR_LEAK"),
}


def apply_second_pass(rows: list[dict[str, Any]]) -> dict[str, Any]:
    labeled: list[dict[str, Any]] = []
    missing = 0
    for ev in rows:
        rid = int(ev.get("rca_id") or 0)
        lab = dict(HUMAN_LABELS.get(rid) or {})
        reviewed = bool(lab)
        if not reviewed:
            missing += 1
        labeled.append({**ev, **lab, "sp_reviewed": reviewed})
    n = sum(1 for r in labeled if r.get("sp_reviewed"))
    states = Counter(str(r.get("sp_opening_state")) for r in labeled if r.get("sp_reviewed"))
    kinds = Counter(str(r.get("sp_location_kind")) for r in labeled if r.get("sp_reviewed"))
    patterns = Counter(str(r.get("sp_pattern")) for r in labeled if r.get("sp_reviewed"))
    return {
        "reviewed_n": n,
        "missing_n": missing,
        "universe_n": len(rows),
        "actual_second_pass": missing == 0 and n == len(rows) and n > 0,
        "sp_pattern_counts": dict(patterns),
        "sp_opening_state_counts": dict(states),
        "sp_location_kind_counts": dict(kinds),
        "CLEAR_CONTINUATION": int(patterns.get("CLEAR_CONTINUATION") or 0),
        "QUESTIONABLE": int(patterns.get("QUESTIONABLE") or 0),
        "NOT_CONTINUATION": int(patterns.get("NOT_CONTINUATION") or 0),
        "rows": labeled,
        "future_used": False,
    }
