"""SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1. Frozen 25 + Recovery R2 canary. DEV only."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1"
CANARY_ID = "RECOVERY_R2_X1_Z3"
CANARY_SOURCE = "RECOVERY_SEQUENCE_FULL_STRATEGY_ARCHITECTURE_V1"
CANARY_ENTRY = "R2_FULL_ACCEPTANCE"
LEGACY_E4_X3_CANARY = False

CASE_A = "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_DEV_SUPPORTED"
CASE_B = "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_NO_ROBUST_CANDIDATE"
CASE_C = "SYSTEMATIC_STATE_TRANSITION_SELECTION_UNSTABLE"
CASE_D = "SYSTEMATIC_STATE_TRANSITION_COVERAGE_FAILED"
CASE_E = "SYSTEMATIC_STATE_TRANSITION_INTEGRITY_FAILED"
CASE_CANARY = "SYSTEMATIC_STATE_TRANSITION_ENGINE_PARITY_FAILED"

BOARD_FRESHNESS_SEC = 5.0
MIN_QTY = 100.0
PORTFOLIO_WAIT_SEC = 0.05
SESSION = "AM"
PROSPECTIVE_HARVEST_SUSPENDED = True
TRUE_OOS = False
CERTIFIED = False
STRESS_OPENED_THIS_RUN = False
SIZING = False
RETUNE = False
SELECTED_STRATEGY_SYMBOL_FILTER = False
TOP_SYMBOL_EXCLUSION_PROPAGATED_TO_STRATEGY = False

CANARY_EXPECTED = {
    "signal_n": 490,
    "fill_n": 334,
    "trade_n": 334,
    "PnL": 341340.0,
    "PF": 1.4202607699979068,
    "MaxDD": -258560.0,
    "positive_days": 2,
    "negative_days": 8,
    "EX_BEST": -197910.0,
}
CANARY_OPTIONAL = {
    "top_symbol": "285A",
    "top_symbol_pnl": 498000.0,
    "CAUSAL_EX_TOP1": -156760.0,
    "CAUSAL_EX_TOP1_PF": 0.7887644688792766,
}

assert ANALYSIS_ID == "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1"
assert CANARY_ID == "RECOVERY_R2_X1_Z3"
assert LEGACY_E4_X3_CANARY is False
assert SELECTED_STRATEGY_SYMBOL_FILTER is False
assert TOP_SYMBOL_EXCLUSION_PROPAGATED_TO_STRATEGY is False
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert STRESS_OPENED_THIS_RUN is False
assert SIZING is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert MIN_PF == 1.10
assert MIN_TOTAL_TRADES == 40
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
assert CASE_A and CASE_B and CASE_C and CASE_D and CASE_E and CASE_CANARY
