"""DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1. Bounded information-object decision. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)

ANALYSIS_ID = "DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"
PARENT_ID = "FULL_CAUSAL_MECHANISM_DISCOVERY_V1"
REQUIRED_PARENT_VERDICT = "FULL_CAUSAL_MECHANISM_DISCOVERY_NO_ROBUST_CANDIDATE_V1"

PIN_MECHANISM_LIBRARY_N = 42
PIN_SELECTABLE_N = 25
PIN_COVERAGE_PASS_N = 10
PIN_G1_G5_SURVIVOR_N = 0
PIN_BASE_QUALIFIED_N = 0
PIN_INTEGRITY_PASS = "25/25"
PIN_CANARY_SIGNAL_N = 490
PIN_CANARY_TRADE_N = 334
PIN_CANARY_PNL = 341340
PIN_CANARY_PF = 1.4202607699979068

CURRENT_O1_O2_O3_LINE_CLOSED = True
CURRENT_42_RETUNE = False
ALL_INFORMATION_EXHAUSTION_ALREADY_PROVEN = False
ENTRY_SIDE_CAUSED_FAILURE = False
EXIT_SIDE_CAUSED_FAILURE = False
JOINT_FULL_STRATEGY_IDENTITY_FAILURE = True
OUTCOME_READ_N = 0
ECONOMICS_RUN = False
THRESHOLD_SEARCH = False
TRUE_OOS = False
CERTIFIED = False
SIZING = False
PREOPEN_EXECUTION_VALID = False

IOAR_EXACT_MECHANISM = (
    "sell pressure → absorption (sells without downside + bid replenish) → "
    "sell exhaustion → buy-flow reversal"
)
IOAR_VERDICT = "IOAR_STRATEGY_REJECTED"
IOAR_HYPOTHESIS = "IOAR_HYPOTHESIS_NO_EDGE"
UEIA_VERDICT = "UEIA_NO_VALIDATED_EDGE"

CASE_A = "NEW_CAUSAL_INFORMATION_OBJECT_SELECTED_V1"
CASE_B = "EXISTING_DEV_INFORMATION_OBJECT_SPACE_EXHAUSTED_V1"
NEXT_A = "FULL_CAUSAL_STRATEGY_ARCHITECTURE_FROM_INFORMATION_OBJECT_V1"
NEXT_B = "EXISTING_DATA_STRATEGY_RESEARCH_STOP_REASSESSMENT_V1"

STATUSES = (
    "CLOSED_PRIMARY_ALPHA_OBJECT",
    "EXACT_MECHANISM_CLOSED_OBJECT_BROADER",
    "USED_AS_FILTER_ONLY",
    "USED_AS_EXECUTION_ONLY",
    "DIAGNOSTIC_ONLY",
    "UNDEREXPLORED_CAUSAL_OBJECT",
    "SEMANTICS_INVALID",
    "DATA_INSUFFICIENT",
)

assert ANALYSIS_ID == "DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"
assert REQUIRED_PARENT_VERDICT == "FULL_CAUSAL_MECHANISM_DISCOVERY_NO_ROBUST_CANDIDATE_V1"
assert CURRENT_O1_O2_O3_LINE_CLOSED is True
assert CURRENT_42_RETUNE is False
assert ALL_INFORMATION_EXHAUSTION_ALREADY_PROVEN is False
assert ENTRY_SIDE_CAUSED_FAILURE is False
assert EXIT_SIDE_CAUSED_FAILURE is False
assert OUTCOME_READ_N == 0
assert ECONOMICS_RUN is False
assert THRESHOLD_SEARCH is False
assert PREOPEN_EXECUTION_VALID is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
