"""FUTURES_MICROSTRUCTURE_PRESSURE_DAY1_V1. Book pressure, not price-return retune."""
from __future__ import annotations

ANALYSIS_ID = "FUTURES_MICROSTRUCTURE_PRESSURE_DAY1_V1"
PARENT_ID = "FUTURES_CONTEXT_DAY1_LEAD_LAG_RCA_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
TRADING_DATE = "20260911"

# Snapshots frozen before looking at results. Price returns are outcomes/controls only.
IMB_MEDIAN_WINDOW_SEC = 30
QUOTE_PRESSURE_WINDOW_SEC = 60
PLACEBO_SHIFT_SEC = 120  # T+2m NONCAUSAL_DIAGNOSTIC vs stock 5m
MATERIAL_BPS = 5.0

SIGNED_FEATURES = (
    "NK_L1_IMB",
    "TOPIX_L1_IMB",
    "NK_DEPTH10_IMB",
    "TOPIX_DEPTH10_IMB",
    "NK_QUOTE_PRESSURE_60S",
    "TOPIX_QUOTE_PRESSURE_60S",
    "CROSS_L1_AGREEMENT",
)
STAGE1_HORIZONS_SEC = (30, 60)
STAGE2_HORIZONS_SEC = (60, 180, 300)
STAGE2_LABEL = {60: "1m", 180: "3m", 300: "5m"}

GRID_START_HM = (9, 5)
GRID_END_HM = (11, 10)
EARLY_END_HM = (10, 5)
LATE_START_HM = (10, 6)

CASE_A = "FUTURES_MICROSTRUCTURE_LEAD_CANDIDATE_DAY1_V1"
CASE_B = "FUTURES_MICROSTRUCTURE_PRICE_ONLY_DAY1_V1"
CASE_C = "FUTURES_MICROSTRUCTURE_NO_LEAD_DAY1_V1"
NEXT_A = "CONFIRM_FUTURES_MICROSTRUCTURE_ON_DAY2_V1"
NEXT_B = "REPEAT_EXACT_FROZEN_EFFECT_TEST_ON_DAY2_V1"
NEXT_C = "REPEAT_EXACT_FROZEN_EFFECT_TEST_ON_DAY2_V1+NEXT_NEW_CAUSAL_INFORMATION_SOURCE_V1"

ENTRY = False
EXIT = False
DAY2_FROZEN_PRICE_RETURN_TEST_CHANGED = False
TRUE_OOS = False
CERTIFIED = False

assert SIGNED_FEATURES == (
    "NK_L1_IMB",
    "TOPIX_L1_IMB",
    "NK_DEPTH10_IMB",
    "TOPIX_DEPTH10_IMB",
    "NK_QUOTE_PRESSURE_60S",
    "TOPIX_QUOTE_PRESSURE_60S",
    "CROSS_L1_AGREEMENT",
)
assert "NK_RET_30S" not in SIGNED_FEATURES
assert "NK_RET_180S" not in SIGNED_FEATURES
assert IMB_MEDIAN_WINDOW_SEC == 30
assert PLACEBO_SHIFT_SEC == 120
assert ENTRY is False and EXIT is False
assert DAY2_FROZEN_PRICE_RETURN_TEST_CHANGED is False
