"""AM WAIT5 minimal-swap Stage2 development. Frozen OOF only. No refit. No Exact. No PnL."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from research.wait5_session_target_learnability import POS_REP_DENOM, POS_REP_MIN
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_WAIT5_MINIMAL_SWAP_STAGE2_DEVELOPMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_PRECOMMIT_ID = "AM_WAIT5_STAGE2_FILL_EDGE_PRESERVING_OBJECTIVE_PRECOMMIT_V1"
PRIOR_PRECOMMIT_VERDICT = "AM_WAIT5_STAGE2_FILL_EDGE_OBJECTIVE_PRECOMMITTED"

STAGE1_SHORTLIST_N = 5
FINAL_SELECTION_N = 3
LOCKED_FILL_SLOTS = 2
MAX_MEMBERSHIP_SWAP_PER_COHORT = 1
SLOTS = 3
QUALITY_COMBINATION = "MIN_PERCENTILE_RANK"
QUALITY_SLOT_POOL = ("R3", "R4", "R5")

PARITY_EXPECTED = {
    "FILL_ONLY_FILL_RATE": 0.4375,
    "FILL_ONLY_EXEC_U": 0.00425138097927976,
    "FILL_ONLY_EXEC_D": -0.003854166912748494,
    "CONTROL_FILL_RATE": 0.37962962962962965,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(LOCKED_FILL_SLOTS) == 2
assert int(MAX_MEMBERSHIP_SWAP_PER_COHORT) == 1
assert QUALITY_COMBINATION == "MIN_PERCENTILE_RANK"
assert tuple(QUALITY_SLOT_POOL) == ("R3", "R4", "R5")
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(POS_REP_MIN) == 6
assert int(POS_REP_DENOM) == 9

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WEIGHT_SEARCH = False
LOCK_SLOT_SEARCH = False
OLD_TWO_STAGE_ALLOWED = False
U_ONLY_STRATEGY_ALLOWED = False
D_ONLY_STRATEGY_ALLOWED = False
FILL_LOSS_TOLERANCE = False
P_FILL_TOLERANCE = False
PROBABILITY_CUTOFF = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
MODEL_REFIT_N = 0
FROZEN_OOF_REPLAY_ONLY = True
ENTRY_RETRAIN_STARTED = False
