"""AUDIT_FIXED_DAYTRADE_UNIVERSE_COMPOSITION_V1. Factor coverage only. No strategy. V1 immutable."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.fixed_daytrade_universe_v1 import LAST_COMPLETE_TSE_SESSION, UNIVERSE_ID
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

ANALYSIS_ID = "AUDIT_FIXED_DAYTRADE_UNIVERSE_COMPOSITION_V1"
PARENT_VERDICT = "FIXED_DAYTRADE_UNIVERSE_FROZEN_V1"
KIND = "COMPOSITION_AUDIT_ONLY"
REQUIRED_UNIVERSE_ID = UNIVERSE_ID
PROBE_DATE = LAST_COMPLETE_TSE_SESSION
FORBIDDEN_DATA_FROM = "20260914"
V1_1_ID = "FIXED_DAYTRADE_UNIVERSE_V1_1_CANDIDATE"

CASE_APPROVED = "FIXED_DAYTRADE_UNIVERSE_COMPOSITION_APPROVED_V1"
CASE_GAPS = "FIXED_DAYTRADE_UNIVERSE_COMPOSITION_APPROVED_WITH_GAPS_V1"
CASE_EXPAND = "FIXED_DAYTRADE_UNIVERSE_EXPANSION_RECOMMENDED_V1"
CASE_REDESIGN = "FIXED_DAYTRADE_UNIVERSE_COMPOSITION_REDESIGN_REQUIRED_V1"
CASE_UNIVERSE = "FROZEN_UNIVERSE_MANIFEST_INVALID_V1"
CASE_DAILY = "COMPOSITION_AUDIT_DAILY_SOURCE_UNAVAILABLE_V1"

NEXT_PANEL = "ACQUIRE_JQUANTS_MINUTE_ADDON_THEN_RETRY_PANEL_V1"
NEXT_V11 = "REVIEW_FIXED_DAYTRADE_UNIVERSE_V1_1_CANDIDATE_THEN_RESUME_PANEL_V1"
NEXT_REDESIGN = "REDESIGN_FIXED_DAYTRADE_UNIVERSE_COMPOSITION_V1"

STRATEGY_SEARCH_STARTED = False
ENTRY = False
EXIT = False
PNL_USED = False
FUTURE_RETURN_USED = False
PAPER_RESULT_USED = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
LIVE_20260914_CHANGED = False
UNIVERSE_CHANGED = False
V1_REWRITTEN = False

CORR_REDUNDANT = 0.85
ENDPOINT_TOPIX = "/v2/indices/bars/daily/topix"
WINDOW_FIRST = "20260618"
WINDOW_LAST = "20260911"

assert ANALYSIS_ID == "AUDIT_FIXED_DAYTRADE_UNIVERSE_COMPOSITION_V1"
assert REQUIRED_UNIVERSE_ID == "FIXED_DAYTRADE_UNIVERSE_V1"
assert PROBE_DATE == "20260911"
assert PROBE_DATE < FORBIDDEN_DATA_FROM
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert STRATEGY_SEARCH_STARTED is False
assert UNIVERSE_CHANGED is False
assert V1_REWRITTEN is False
assert CORR_REDUNDANT == 0.85
