"""P4-2: recovering-winner vs persistent-failure path decomposition.

Research only. No new EXIT / no threshold / no counterfactual PnL / no Runtime.
P4-1 MID_HOLD_NO_PROGRESS_V1 remains CLOSED.
Label: REUSED_HISTORY_EXPLORATORY_MECHANISM_DISCOVERY.
"""

from research.canonical_fixed_pnl_source_p3_3 import (
    FULL14,
    P1_PF,
    P1_PNL,
    P1_TRADES,
    PREDECLARED_TOP3,
    REST11,
)
from research.fixed_winner_cluster_extension_p3_4 import EXIT600_REASON, EXTEND_REASON
from research.mid_hold_state_separability_p4_0 import STATE_VARS

ANALYSIS_ID = "P4_2_RECOVERY_FAILURE_PATH"
DOCUMENT_ID = "P4_2_MID_HOLD_PATH_DECOMPOSITION"
TASK_LABEL = "REUSED_HISTORY_EXPLORATORY_MECHANISM_DISCOVERY"

CHECKPOINTS_SEC = (120, 180, 240, 300, 360, 420, 480, 540, 600)
PRIMARY_CHECKPOINTS = (120, 180, 240, 300, 360)
SECONDARY_CHECKPOINTS = (420, 480, 540)
CASEBOOK_CHECKPOINTS = CHECKPOINTS_SEC

SNAPSHOT_VARS = STATE_VARS
TRAJECTORY_VARS = (
    "delta_bid_120_to_t",
    "delta_bid_prev_checkpoint",
    "delta_mfe_prev_checkpoint",
    "delta_mae_prev_checkpoint",
    "rebound_from_low_t",
    "underwater_checkpoint_count",
    "consecutive_underwater_count",
)

MECH_RECOVERY = "RECOVERY_MOMENTUM_SEPARATES"
MECH_DRAWDOWN = "PERSISTENT_DRAWDOWN_SEPARATES"
MECH_MFE = "MFE_STAGNATION_SEPARATES"
MECH_MULTI = "MULTIPLE_PATH_MECHANISMS"
MECH_SNAPSHOT = "SNAPSHOT_ONLY_NO_TRAJECTORY_INCREMENT"
MECH_NOT = "RECOVERING_WINNER_AND_FAILURE_NOT_CLEANLY_SEPARABLE"
MECH_TOP3 = "TOP3_CONFOUNDED"
MECH_DATA = "MATERIAL_DATA_ISSUE"

VERDICT_OK = "P4_2_RECOVERY_FAILURE_PATH_DECOMPOSITION_COMPLETE"
VERDICT_ISSUE = "P4_2_MATERIAL_INTEGRITY_ISSUE"
VERDICT_BLOCKED = "P4_2_BLOCKED"

MAX_WORKERS = 2
CACHE_VERSION = 1

FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
P1_TRADES = P1_TRADES
P1_PNL = P1_PNL
P1_PF = P1_PF
EXIT600_REASON = EXIT600_REASON
EXTEND_REASON = EXTEND_REASON
STATE_VARS = STATE_VARS
