"""W5 precommit development candidate. Diagnostic only. Runtime WAIT unchanged."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.multiobjective_feasibility import JOINT_FEASIBLE_MIN_RATE
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "PASSIVE_WAIT5_PRECOMMIT_DEVELOPMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
RATE_MIN = float(JOINT_FEASIBLE_MIN_RATE)
PARITY_ABS_TOL = 1e-10
SURVIVAL_EXACT = 1.0
CLOCK_IMPROVE_MIN_FRAC = 0.50
WAIT_POLICY_CANDIDATE = "W5"
CONTROL_WAIT_ID = "W1"
CANDIDATE_WAIT_ID = "W5"
REFERENCE_WAIT_IDS = ("W2", "W10")

PRIOR_VERDICT_REQUIRED = "PASSIVE_WAIT_EXTENSION_FEASIBLE"

PARITY_EXPECTED = {
    "W1_ANY_RATE": 0.4076655052264808,
    "W1_MULTI_RATE": 0.18466898954703834,
    "W5_ANY_RATE": 0.7317073170731707,
    "W5_MULTI_RATE": 0.5156794425087108,
    "W5_WOULD_FILL_N": 852,
    "W5_FILLABLE_JOINT_RATE": 0.34843205574912894,
    "W5_JOINT_SURVIVAL": 1.0,
    "W5_NEW_FILL_N": 594,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(RATE_MIN) == 0.50
assert float(CLOCK_IMPROVE_MIN_FRAC) == 0.50
assert WAIT_POLICY_CANDIDATE == "W5"

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
WAIT_INTERPOLATION = False
REPRICING = False
LIMIT_CHANGED = False
FILL_RULE_CHANGED = False
MARKETABLE_ASSUMED = False
TAKER_FILL_ADDED = False
POSITION_CAP_APPLIED = False
OCCUPANCY_APPLIED = False
REENTRY_APPLIED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
PRICE_POLICY_STARTED = False
NEW_TARGET_CREATED = False
ENTRY_RETRAIN_STARTED = False
W2_RESELECTED = False
W10_RESELECTED = False
