"""Diagnostic decomposition of the frozen failed complete strategy. No repair."""
from __future__ import annotations

from research.causal_driver_pb1.phase1.dates import assert_ingest_date_allowed

_ = assert_ingest_date_allowed

ANALYSIS_ID = "SYMBOL_SETUP_BASELINE_COMPLETE_STRATEGY_FAILURE_DECOMPOSITION_V1"
COMPLETE_STRATEGY_ID = "SYMBOL_SETUP_BASELINE_COMPLETE_STRATEGY_V1"
COMPLETE_STRATEGY_SHA256 = "25d8ef6944c4d82a15d57a3bb078e5503f733184ecb92ee5ad6ba95fe4f95f6d"
CASE_PARITY = "RCA_POPULATION_PARITY_FAIL"
CASE_IDENTIFIED = "SYMBOL_SETUP_BASELINE_PRIMARY_DEFICIENCY_IDENTIFIED_V1"
CASE_MULTIPLE = "SYMBOL_SETUP_BASELINE_MULTIPLE_FAILURE_MECHANISMS_V1"
CASE_UNKNOWN = "SYMBOL_SETUP_BASELINE_PRIMARY_DEFICIENCY_NOT_IDENTIFIED_V1"
NEXT_REPAIR = "PRECOMMIT_SYMBOL_SETUP_ONE_MECHANISM_REPAIR_V1"
NEXT_PRIORITIZE = "PRIORITIZE_SYMBOL_SETUP_FAILURE_MECHANISM_V1"
NEXT_GAP = "RESOLVE_SYMBOL_SETUP_FAILURE_EVIDENCE_GAP_V1"
NEXT_STOP = "STOP"
QUOTE_HORIZONS = (30, 60, 180, 300)
BAR_HORIZONS = (1, 3, 5)
FILL_MARK_HORIZONS = (60, 180, 300, 600)
POST_EXIT_HORIZONS = (60, 180, 300)
# Frozen before any trade row is classified. No threshold was fit to the seven fills.
PATH_LABELS = (
    "IMMEDIATE_ADVERSE",
    "NO_PROGRESS",
    "PROFIT_THEN_FAILURE",
    "DIP_THEN_RECOVERY",
    "CLEAN_WINNER",
    "SESSION_STALE",
    "OTHER",
)
