"""NEW_INFORMATION_SOURCE_POLICY_DECISION_V1. Policy only. No acquisition. No strategy. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)

ANALYSIS_ID = "NEW_INFORMATION_SOURCE_POLICY_DECISION_V1"
PARENT_ID = "RESEARCH_PAUSE_AND_DATA_REQUIREMENTS_REDESIGN_V1"
REQUIRED_PARENT_VERDICT = "RESEARCH_PAUSED_EXTERNAL_INFORMATION_DECISION_REQUIRED_V1"
REQUIRED_PARENT_NEXT = "NEW_INFORMATION_SOURCE_POLICY_DECISION_V1"
REQUIRED_PAUSE_PROTOCOL_SHA256 = "85f8567c950ed654794ab45d01bf8bc7b07c477a84a9aaa8269377ad1e31f2f1"
REQUIRED_CLOSED_ARCHITECTURE_N = 23
REQUIRED_ELIGIBLE_METHOD_N = 0

LEGACY_DEV_DAYS = DEVELOPMENT_DAYS
QUARANTINE_DAYS = ("20260903", "20260904")

NEW_DEV_MIN_VALID_DAYS = 20
NEW_DEV_MIN_CALENDAR_WEEKS = 4
INTERNAL_FOLD_N = 5
TRUE_OOS_MIN_VALID_DAYS = 10

GAP_CATEGORIES = (
    "ORDER_LEVEL_ADD_CANCEL_EXECUTE",
    "QUEUE_POSITION",
    "NATIVE_AGGRESSOR_TRADE_SIDE",
    "EXCHANGE_NATIVE_EXECUTION_TAPE",
    "BROAD_MARKET_FUTURES_CONTEXT",
    "AUCTION_BEYOND_CAPTURED_FIELDS",
)
PRIMARY_SOURCE_FAMILIES = (
    "ORDER_LEVEL_ADD_CANCEL_EXECUTE",
    "EXCHANGE_NATIVE_EXECUTION_TAPE",
    "BROAD_MARKET_FUTURES_CONTEXT",
)
CONSOLIDATED_FEED_ID = "EXCHANGE_NATIVE_ORDER_EVENT_FEED"

CASE_A = "EXTERNAL_CAUSAL_INFORMATION_SOURCE_POLICY_SELECTED_V1"
CASE_B = "EXTERNAL_INFORMATION_SOURCE_POLICY_AMBIGUOUS_V1"
CASE_C = "NO_JUSTIFIED_EXTERNAL_INFORMATION_SOURCE_V1"
CASE_D = "EXTERNAL_SOURCE_REQUIRES_PROSPECTIVE_COLLECTION_ONLY_V1"
NEXT_A = "NEW_INFORMATION_ACQUISITION_FEASIBILITY_DESIGN_V1"
NEXT_B = "RESOLVE_EXTERNAL_SOURCE_DOCUMENTATION_GAPS_V1"
NEXT_C = "STRATEGY_RESEARCH_PAUSED_NO_JUSTIFIED_RESTART_PATH_V1"
NEXT_D = "PROSPECTIVE_COLLECTION_POLICY_DECISION_V1"

NEW_STRATEGY_CREATED = False
NEW_ENTRY_CREATED = False
NEW_EXIT_CREATED = False
NEW_MODEL_CREATED = False
NEW_THRESHOLD_CREATED = False
NEW_CANDIDATE_LIBRARY_CREATED = False
ACTUAL_EXTERNAL_DATA_ACQUIRED = False
EXTERNAL_MARKET_DATA_DOWNLOADED = False
EXTERNAL_MARKET_DATA_STREAM_STARTED = False
SUBSCRIPTION_CHANGED = False
ACCOUNT_CREATED = False
API_KEY_CREATED = False
CAPTURE_SCHEMA_CHANGED = False
RUNTIME_CHANGED = False
PNL_COMPUTED = False
FUTURE_DATASET_DATES_ASSIGNED = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False
QUEUE_POSITION_ALPHA_POLICY_ELIGIBLE = False
NATIVE_AGGRESSOR_SOURCE_POLICY_ELIGIBLE = False
AUCTION_SOURCE_POLICY_ELIGIBLE = False
LEGACY_DEV_REOPENED = False
BURNED_DATA_RECLASSIFIED = False
QUARANTINE_CHANGED = False
PROSPECTIVE_DATA_READ = False

assert ANALYSIS_ID == "NEW_INFORMATION_SOURCE_POLICY_DECISION_V1"
assert REQUIRED_PARENT_VERDICT == "RESEARCH_PAUSED_EXTERNAL_INFORMATION_DECISION_REQUIRED_V1"
assert REQUIRED_PAUSE_PROTOCOL_SHA256 == "85f8567c950ed654794ab45d01bf8bc7b07c477a84a9aaa8269377ad1e31f2f1"
assert NEW_STRATEGY_CREATED is False
assert ACTUAL_EXTERNAL_DATA_ACQUIRED is False
assert EXTERNAL_MARKET_DATA_DOWNLOADED is False
assert QUEUE_POSITION_ALPHA_POLICY_ELIGIBLE is False
assert NATIVE_AGGRESSOR_SOURCE_POLICY_ELIGIBLE is False
assert AUCTION_SOURCE_POLICY_ELIGIBLE is False
assert FUTURE_DATASET_DATES_ASSIGNED is False
assert len(GAP_CATEGORIES) == 6
assert len(PRIMARY_SOURCE_FAMILIES) == 3
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert QUARANTINE_DAYS == ("20260903", "20260904")
assert int(NEW_DEV_MIN_VALID_DAYS) == 20
assert int(TRUE_OOS_MIN_VALID_DAYS) == 10
