"""AM ENTRY / execution-policy coupling reassessment. Frozen DIRECT OOF. No new model."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from research.passive_wait_policy_reassessment import WAIT_IDS, WAIT_SEC_BY_ID
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_ENTRY_EXECUTION_POLICY_COUPLING_REASSESSMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
FINAL_SELECTION_N = 3
SLOTS = 3
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_DEVELOPMENT_ID = "AM_DIRECT_EXEC_U_PRECOMMITTED_DEVELOPMENT_V1"
PRIOR_DEVELOPMENT_VERDICT = "AM_DIRECT_EXEC_U_SACRIFICES_FILL"

FROZEN_WAITS = WAIT_IDS
assert tuple(FROZEN_WAITS) == ("W1", "W2", "W5", "W10")
assert float(WAIT_SEC_BY_ID["W1"]) == 1.0
assert float(WAIT_SEC_BY_ID["W5"]) == 5.0
assert float(WAIT_SEC_BY_ID["W10"]) == 10.0

PARITY_EXPECTED = {
    "FILL_ONLY_FILL_RATE_W5": 0.4375,
    "DIRECT_FILL_RATE_W5": 0.4212962962962963,
    "DELTA_FILL_W5": -0.013888888888888895,
    "FILL_ONLY_EXEC_U_W5": 0.00425138097927976,
    "DIRECT_EXEC_U_W5": 0.004658690357172961,
    "DELTA_EXEC_U_W5": 0.0003315625253401478,
    "FILL_ONLY_EXEC_D_W5": -0.003854166912748494,
    "DIRECT_EXEC_D_W5": -0.004511240037607862,
    "DIRECT_NE_FILL_ONLY_COHORT_RATE": 0.8402777777777778,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(FINAL_SELECTION_N) == 3
assert int(SLOTS) == 3

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WEIGHT_SEARCH = False
STAGE1_ALLOWED = False
STAGE2_ALLOWED = False
D_TRAINING_TARGET_ALLOWED = False
FILL_LOSS_ALLOWED_IN_PASS_GATE = False
SHORTLIST_SEARCH = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
ENTRY_RETRAIN_STARTED = False
W5_RUNTIME_ADOPTED = False
W10_ADOPTED = False
WAIT_SEARCH_N = 0
MODEL_REFIT_N = 0
SELECTION_REOPTIMIZATION_N = 0
ORACLE_SELECTION_USE_N = 0
NEW_TARGET_CREATED = False
FROZEN_OOF_REPLAY_ONLY = True
FROZEN_WAIT_IDS_ONLY = True
