"""C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2. Fold-local eligibility parity then 40-arm economics."""
from __future__ import annotations

from research.c1_multi_timeframe_entry_exit_pair_precommit_v2 import EXPECTED_EXIT_FILE_SHA256
from research.c1_multi_timeframe_full_strategy_v1 import (
    FOLD_TRAIN_FILL_DAYS_MIN,
    FOLD_TRAIN_TRADE_N_MIN,
    FOLD_TRAIN_TRADES_PER_DAY_MIN,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
)
from research.c4_portfolio_crowding_precommit_v1 import KEPT_EXIT_IDS  # noqa: F401
from research.c4_portfolio_crowding_precommit_v2 import (
    CONTROL_POLICY_ID,
    EXECUTION_ID,
    MIN_INFORMATIVE_BLOCK_N,
    TREATMENT_POLICY_ID,
)
from research.c4_portfolio_crowding_precommit_v2.spec import arm_id
from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_ID, CANARY_SOURCE
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS, PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2"
PRECOMMIT_ANALYSIS_ID = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V2"
PRECOMMIT_VERDICT_REQUIRED = "C4_PORTFOLIO_CROWDING_LIBRARY_V2_FROZEN"
PRECOMMIT_NEXT_REQUIRED = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2"
DEV_CLASSIFICATION = "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"

CASE_A = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_DEV_SUPPORTED"
CASE_B = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_NO_ROBUST_CANDIDATE"
CASE_C = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_SELECTION_UNSTABLE"
CASE_E = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2_INTEGRITY_FAILED"
CASE_CANARY = "C4_PORTFOLIO_CROWDING_ENGINE_PARITY_FAILED"

NEXT_IF_A = "STOP. FULL_STRATEGY_DEV_FROZEN. Stress sealed. TRUE_OOS=false."
NEXT_IF_B = "RESEARCH_OBJECTIVE_REBASE_V1"
NEXT_IF_C = "RESEARCH_OBJECTIVE_REBASE_V1"
NEXT_IF_E = "Fix integrity only. Do not invent another C4 rule. No economics."
NEXT_IF_CANARY = "STOP. Engine parity failed. Do not run arm economics."
NEXT_IF_FULL_STRATEGY_FAILS = "RESEARCH_OBJECTIVE_REBASE_V1"

FROZEN_ELIGIBLE_IDS = (
    "ST_PERSIST_NEXT__S_MA_TREND_UP",
    "ST_PERSIST_NEXT__S_BB_ABOVE_MID",
    "ST_PERSIST_NEXT__S_RCI_ABOVE_NEG80",
    "ST_PERSIST_NEXT__S_VOL_CONFIRM_1M",
    "ST_PERSIST_NEXT__S_CLOSE_ABOVE_VWAP",
)

DROPPED_EXIT_IDS = ("Z4_TRAILING_STRUCTURE",)
EXIT_FIRE_KEY = {
    "Z1_VWAP_LOSS": "Z1",
    "Z2_STRUCTURE_LOSS": "Z2",
    "Z3_TWO_BAR_WEAKNESS": "Z3",
    "Z5_HYBRID_SIMPLE": "Z5",
}

EXPECTED_V2_POLICY_SHA256 = "bd3a834e5a3abddd52558144ec4b26cfbf7bc19761b1b977d58b6024c19287c1"
EXPECTED_EXIT_FILE_SHA256_PIN = EXPECTED_EXIT_FILE_SHA256
ELIGIBLE_ENTRY_N = 5
EXIT_N = 4
MATCHED_STRATEGY_N = 20
CONTROL_ARM_N = 20
TREATMENT_ARM_N = 20
TOTAL_ARM_N = 40

BOARD_FRESHNESS_SEC = 5.0
MIN_QTY = 100.0
PORTFOLIO_WAIT_SEC = 0.05
SESSION = "AM"
PROSPECTIVE_HARVEST_SUSPENDED = True
TRUE_OOS = False
CERTIFIED = False
STRESS_OPENED_THIS_RUN = False
SIZING = False
RETUNE = False
SELECTED_STRATEGY_SYMBOL_FILTER = False
TOP_SYMBOL_EXCLUSION_PROPAGATED_TO_STRATEGY = False

FROZEN_ARM_IDS = tuple(
    arm_id(eid, pol, z)
    for eid in FROZEN_ELIGIBLE_IDS
    for z in KEPT_EXIT_IDS
    for pol in (CONTROL_POLICY_ID, TREATMENT_POLICY_ID)
)

assert ANALYSIS_ID == "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2"
assert PRECOMMIT_VERDICT_REQUIRED == "C4_PORTFOLIO_CROWDING_LIBRARY_V2_FROZEN"
assert CASE_E == "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2_INTEGRITY_FAILED"
assert NEXT_IF_B == NEXT_IF_FULL_STRATEGY_FAILS == "RESEARCH_OBJECTIVE_REBASE_V1"
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert TREATMENT_POLICY_ID == "C4_FIRST_ARRIVAL_PER_EXACT_T0_V2"
assert TREATMENT_POLICY_ID != "C4_FIRST_UNIQUE_T0"
assert CONTROL_POLICY_ID == "C4_CONTROL_NONE"
assert EXECUTION_ID == "X1_IMMEDIATE_ASK"
assert len(FROZEN_ELIGIBLE_IDS) == ELIGIBLE_ENTRY_N == 5
assert len(KEPT_EXIT_IDS) == EXIT_N == 4
assert "Z4_TRAILING_STRUCTURE" not in KEPT_EXIT_IDS
assert DROPPED_EXIT_IDS == ("Z4_TRAILING_STRUCTURE",)
assert ELIGIBLE_ENTRY_N * EXIT_N == MATCHED_STRATEGY_N
assert CONTROL_ARM_N + TREATMENT_ARM_N == TOTAL_ARM_N == 40
assert len(FROZEN_ARM_IDS) == TOTAL_ARM_N
assert all("Z4_TRAILING_STRUCTURE" not in a for a in FROZEN_ARM_IDS)
assert all(EXECUTION_ID in a for a in FROZEN_ARM_IDS)
assert sum(1 for a in FROZEN_ARM_IDS if CONTROL_POLICY_ID in a) == CONTROL_ARM_N
assert sum(1 for a in FROZEN_ARM_IDS if TREATMENT_POLICY_ID in a) == TREATMENT_ARM_N
assert CANARY_ID == "RECOVERY_R2_X1_Z3"
assert CANARY_EXPECTED["signal_n"] == 490
assert CANARY_EXPECTED["fill_n"] == 334
assert CANARY_EXPECTED["trade_n"] == 334
assert CANARY_EXPECTED["PnL"] == 341340.0
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert MIN_PF == 1.10
assert MIN_TOTAL_TRADES == 40
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
assert FOLD_TRAIN_TRADE_N_MIN == 32
assert FOLD_TRAIN_FILL_DAYS_MIN == 7
assert FOLD_TRAIN_TRADES_PER_DAY_MIN == 4.0
assert MIN_INFORMATIVE_BLOCK_N == 3
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert STRESS_OPENED_THIS_RUN is False
assert SESSION == "AM"
assert DEV_CLASSIFICATION == "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
assert EXIT_FIRE_KEY["Z5_HYBRID_SIMPLE"] == "Z5"
assert CANARY_SOURCE
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
assert EXPECTED_V2_POLICY_SHA256
assert EXPECTED_EXIT_FILE_SHA256_PIN
assert SELECTED_STRATEGY_SYMBOL_FILTER is False
assert TOP_SYMBOL_EXCLUSION_PROPAGATED_TO_STRATEGY is False
assert PROSPECTIVE_HARVEST_SUSPENDED is True
assert RETUNE is False
assert BOARD_FRESHNESS_SEC
assert MIN_QTY
assert PORTFOLIO_WAIT_SEC
