"""Passive WAIT policy reassessment. Diagnostic only. Runtime WAIT unchanged."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.multiobjective_feasibility import JOINT_FEASIBLE_MIN_RATE
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "PASSIVE_WAIT_POLICY_REASSESSMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
RATE_MIN = float(JOINT_FEASIBLE_MIN_RATE)
SURVIVAL_LOW_MAX = 0.50
PARITY_ABS_TOL = 1e-10

PRIOR_VERDICT_REQUIRED = "PASSIVE_EXECUTION_OPPORTUNITY_TOO_SPARSE"

WAIT_IDS = ("W1", "W2", "W5", "W10")
WAIT_SEC_BY_ID = {"W1": 1.0, "W2": 2.0, "W5": 5.0, "W10": 10.0}
EXTENDED_IDS = ("W2", "W5", "W10")

W1_EXPECTED = {
    "ALL_WOULD_FILL_N": 258,
    "FILLABLE_ANY_COHORT_N": 117,
    "FILLABLE_ANY_COHORT_RATE": 0.4076655052264808,
    "MULTI_FILLABLE_COHORT_N": 53,
    "MULTI_FILLABLE_COHORT_RATE": 0.18466898954703834,
    "VALID_BOARD_WITHIN_WAIT_RATE": 0.24169804861348854,
    "ASK_CROSS_GIVEN_VALID_BOARD_RATE": 0.09152181624689606,
    "JOINT_POSITIVE_WOULD_FILL_N": 64,
    "FILLABLE_JOINT_AVAILABLE_COHORT_N": 43,
    "FILLABLE_JOINT_AVAILABLE_RATE": 0.14982578397212543,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(WAIT_SEC_BY_ID["W1"]) == float(WAIT_SEC)
assert float(RATE_MIN) == 0.50

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
WAIT_INTERPOLATION = False
REPRICING = False
LIMIT_CHANGED = False
FILL_RULE_CHANGED = False
MARKETABLE_ASSUMED = False
TAKER_FILL_ADDED = False
POSITION_CAP_APPLIED = False
OCCUPANCY_APPLIED = False
REENTRY_APPLIED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
PRICE_POLICY_STARTED = False
NEW_TARGET_CREATED = False
