"""AM WAIT5 fillability-upside architecture geometry audit. Oracle diagnostic only. No model."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from research.wait5_session_target_learnability import POS_REP_DENOM, POS_REP_MIN
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_WAIT5_FILLABILITY_UPSIDE_ARCHITECTURE_GEOMETRY_AUDIT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
SLOTS = 3
FINAL_SELECTION_N = 3
SPEARMAN_MIN_N = 3
MAJORITY_RATE = 0.50
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_ANALYSIS_ID = "AM_WAIT5_FILLABILITY_FIRST_REASSESSMENT_V1"
PRIOR_VERDICT = "AM_WAIT5_FILLABILITY_QUALITY_TAX"

RANK_BUCKETS = ("R1_3", "R4_5", "R6_10", "R11_PLUS")

PARITY_EXPECTED = {
    "CONTROL_FILL_RATE": 0.37962962962962965,
    "FILL_ONLY_FILL_RATE": 0.4375,
    "NET_ADDITIONAL_FILL_N": 25,
    "CONTROL_COND_U": 0.010616151312603702,
    "FILL_ONLY_COND_U": 0.010184098639284996,
    "DELTA_COND_U": -0.0004320526733187068,
    "CONTROL_COND_D": -0.009396719708716202,
    "FILL_ONLY_COND_D": -0.009080470762772642,
    "DELTA_COND_D": 0.00031624894594355947,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(SLOTS) == 3
assert int(FINAL_SELECTION_N) == 3
assert float(MAJORITY_RATE) == 0.50
assert RANK_BUCKETS == ("R1_3", "R4_5", "R6_10", "R11_PLUS")
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(POS_REP_MIN) == 6
assert int(POS_REP_DENOM) == 9

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
NEW_OBJECTIVE_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WEIGHT_SEARCH = False
LOCK_SLOT_SEARCH = False
SHORTLIST_SEARCH = False
OLD_TWO_STAGE_ALLOWED = False
MINIMAL_SWAP_STAGE2_ALLOWED = False
STAGE2_ARM_ALLOWED = False
DIRECT_EXEC_U_TRAINING = False
P_FILL_TIMES_U_PRED = False
ORACLE_USED_AS_STRATEGY = False
FILL_TOLERANCE = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
MODEL_REFIT_N = 0
FROZEN_OOF_REPLAY_ONLY = True
ENTRY_RETRAIN_STARTED = False
W5_RUNTIME_ADOPTED = False
