"""NATIVE_PATH_STATE_DISCRIMINATION_V1. Entry-time path-type discrimination. Discovery design evidence. No promotion."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "NATIVE_PATH_STATE_DISCRIMINATION_V1"
ANALYSIS_ID = "NATIVE_PATH_STATE_DISCRIMINATION_V1"
PARENT_ANALYSIS_ID = "BG_CONT_VWAP_LARGEST_CAUSAL_DEFICIENCY_V1"
PARENT_VERDICT = "BG_CONT_VWAP_EXIT_GIVEBACK_NOT_CAUSALLY_RESCUABLE_V1"
ATLAS_ANALYSIS_ID = "ONE_MINUTE_NATIVE_PLAYBOOK_DISCOVERY_V1"
ATLAS_VERDICT = "ONE_MINUTE_BEHAVIOR_ATLAS_READY_NO_COMPLETE_PLAYBOOK_V1"
ATLAS_ID = "ONE_MINUTE_BEHAVIOR_ATLAS_V1"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_ATLAS_EPISODE_N = 100482
BG_CONT_VWAP_CLOSED = True
HM1_ID = "HM1_CONTROLLED_PULLBACK_RECLAIM"
X1_TAX_BPS = 8.0
OCCUPANCY = 3
EPISODE_GAP_MIN = 10
LOOKBACK_BARS = 20
PATH_BARS = 30
TIME_STOP_MIN = 20
ENTRY_CUTOFF = "14:50"
SESSION_FLAT = "15:20"
FAVOR_BPS = 8.0
LARGE_WINNER_BPS = 40.0
MIN_SECTOR_N = 3
IMPULSE_SIGMA = 2.0

FAVORABLE_CLASSES = ("SUSTAINED_CONTINUATION", "LARGE_WINNER")
FAILURE_CLASSES = ("IMMEDIATE_FAILURE", "SMALL_PROGRESS_THEN_FAILURE")
STALL_CLASS = "STALL"
OUTCOME_CLASSES = (
    "IMMEDIATE_FAILURE",
    "SMALL_PROGRESS_THEN_FAILURE",
    "STALL",
    "SUSTAINED_CONTINUATION",
    "LARGE_WINNER",
    "OTHER",
    "UNLABELED",
)

TREE_MAX_DEPTH = 3
TREE_MIN_SAMPLES_LEAF = 400
TREE_RANDOM_STATE = 0
TREE_CRITERION = "gini"
LOGISTIC_C = 1.0
LOGISTIC_PENALTY = "l2"
PRED_CUTOFF = 0.5
MIN_AUC = 0.55
MIN_LIFT = 0.03
MIN_ABLATION_AUC = 0.01
MAX_EXTRACT_RULES = 3
MIN_RULE_LIFT = 0.05
MIN_RULE_N = 400
MAX_TOP_SYMBOL_POS_SHARE = 0.50
EVAL_BLOCKS = ("D2", "D3", "D4")
TRAIN_BLOCK = "D1"
GROUP_NAMES = (
    "CONTINUATION",
    "MEAN_REVERSION",
    "SECTOR_LEADER",
    "SECTOR_LAGGARD",
    "SECTOR_LAGGARD_CATCHUP",
    "OPENING_MOMENTUM",
)

CASE_FOUND = "NATIVE_1M_PATH_STATE_DISCRIMINATION_FOUND_V1"
CASE_NONE = "NATIVE_1M_PATH_STATE_NOT_DISCRIMINATIVE_V1"
CASE_BIND = "NATIVE_PATH_STATE_BIND_FAILED_V1"

NEXT_FREEZE = "NATIVE_1M_PATH_STATE_STRATEGY_FREEZE_V1"
NEXT_STOP = "STOP_NATIVE_1M_HAND_MINING_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_USED_TO_DESIGN = False
HM1_TUNED = False
NEW_PAID_DATA = False
FIVE_MINUTE_GRID = False
PROMOTED = False
V27_BOLTED = False
RANDOM_CV = False
SYMBOL_ONEHOT = False

assert ANALYSIS_ID == "NATIVE_PATH_STATE_DISCRIMINATION_V1"
assert PARENT_VERDICT == "BG_CONT_VWAP_EXIT_GIVEBACK_NOT_CAUSALLY_RESCUABLE_V1"
assert BG_CONT_VWAP_CLOSED is True
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert PROMOTED is False
assert V27_BOLTED is False
assert RANDOM_CV is False
assert SYMBOL_ONEHOT is False
assert TREE_MAX_DEPTH == 3
assert X1_TAX_BPS == 8.0
assert FAVOR_BPS == 8.0
assert LARGE_WINNER_BPS == 40.0
assert PRED_CUTOFF == 0.5
assert OCCUPANCY == 3
