"""PRIOR_CLOSE_RECAPTURE_SUSTAINED_MECHANISM_V1. Discovery only. V5 CLOSED."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "PRIOR_CLOSE_RECAPTURE_SUSTAINED_MECHANISM_V1"
PARENT_ID = "POST_OPEN_PRIOR_CLOSE_RECAPTURE_FULL_STRATEGY_V1"
REQUIRED_PARENT_VERDICT = "POST_OPEN_PRIOR_CLOSE_RECAPTURE_COVERAGE_FAIL_V1"
PARENT_STRATEGY_ID = "PRIOR_CLOSE_RECAPTURE_X1_Z_PRIOR_CLOSE_LOSS_V1"
PARENT_EXIT_ID = "Z_PRIOR_CLOSE_LOSS"
OPENING_LINE_STATUS = "CLOSED"
ISQ_LINE_STATUS = "CLOSED"
AOP_LINE_STATUS = "CLOSED"
CALC_PRICE_STATUS = "INPUT_SUPPORTED_STRATEGY_CLOSED"
NATIVE_STATUS_LINE = "CLOSED"
V5_STATUS = "CLOSED"
KIND = "MECHANISM_DISCOVERY_ONLY"
V5_RESCUE = False
THRESHOLD_OPTIMIZATION = False
EXECUTION_ID = "X1_IMMEDIATE_ASK"
EXEC_EVAL_ID = "X1"
SHARES_N = 100
SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
BOARD_FRESHNESS_SEC = 5.0
POSITION_CAP_N = 5
LABEL_SUSTAINED = "SUSTAINED_RECAPTURE"
LABEL_FAILED = "FAILED_RECAPTURE"
LABEL_UNRESOLVED = "EXECUTION_UNRESOLVED"
MIN_DAY_SUPPORT = 8
MIN_BLOCK_AGREE = 4
TREE_MAX_DEPTH = 2
TREE_MAX_LEAF_NODES = 4
TREE_MIN_LEAF_N = 40
MAX_TREE_FEATURES = 5

CASE_FOUND = "PRIOR_CLOSE_RECAPTURE_SUSTAINED_MECHANISM_FOUND_V1"
CASE_NONE = "PRIOR_CLOSE_RECAPTURE_NO_STABLE_SUCCESS_MECHANISM_V1"
NEXT_FOUND = "PRIOR_CLOSE_RECAPTURE_SUSTAINED_FULL_STRATEGY_V1"
NEXT_NONE = "NEXT_NON_OPENING_POST_OPEN_ARCHITECTURE_V6"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

MBO_WORK = False
FUTURES_WORK = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

FEATURE_IDS = (
    "MAX_DEPTH_BELOW_PCLOSE_BPS",
    "MAX_DEPTH_BELOW_PCLOSE_TICKS",
    "BELOW_DWELL_SEC",
    "BELOW_OTU_N",
    "BELOW_DISTINCT_PRICE_N",
    "BELOW_TRADING_VOLUME_DELTA",
    "BELOW_TRADING_VALUE_DELTA",
    "RECAPTURE_OVERSHOOT_BPS",
    "RECAPTURE_OVERSHOOT_TICKS",
    "PRIOR_RECAPTURE_N",
    "TIME_SINCE_PREVIOUS_RECAPTURE_SEC",
    "SPREAD_BPS",
    "BID1_QTY",
    "ASK1_QTY",
    "CALCPRICE_MINUS_CURRENT",
    "CALCPRICE_MINUS_PCLOSE",
    "UNDER_BUY_QTY",
    "OVER_SELL_QTY",
    "UNDER_MINUS_OVER",
    "MINUTES_FROM_0900",
)

assert ANALYSIS_ID == "PRIOR_CLOSE_RECAPTURE_SUSTAINED_MECHANISM_V1"
assert REQUIRED_PARENT_VERDICT == "POST_OPEN_PRIOR_CLOSE_RECAPTURE_COVERAGE_FAIL_V1"
assert KIND == "MECHANISM_DISCOVERY_ONLY"
assert V5_RESCUE is False
assert THRESHOLD_OPTIMIZATION is False
assert TRUE_OOS is False
assert len(FEATURE_IDS) == 20
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert int(POSITION_CAP) == 5
assert SHARES
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert MAX_RESEARCH_DATE == "20260807"
