"""V1R EXIT Global Search — nested CV across EXIT families. ENTRY frozen."""

ANALYSIS_ID = "V1R_EXIT_GLOBAL_SEARCH"
DOCUMENT_ID = "V1R_EXIT_GLOBAL_SEARCH"
FORBIDDEN_FROM = "20260810"
LOCKED_HOLDOUT = "20260810"
BASELINE_ID = "FIXED600"
