"""DELAYED_OPEN_BUY_SPECIAL_QUOTE_RELEASE_FULL_STRATEGY_V1. One Complete Full Causal strategy. LEGACY_DEV only."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_OPTIONAL

ANALYSIS_ID = "DELAYED_OPEN_BUY_SPECIAL_QUOTE_RELEASE_FULL_STRATEGY_V1"
PARENT_ID = "OPENING_LOGIC_INPUT_CAPABILITY_AUDIT_V1"
REQUIRED_PARENT_VERDICT = "OPENING_LOGIC_PREOPEN_INPUT_NOT_SUPPORTED_V1"
STRATEGY_ID = "DO_BSQ_OPEN_RELEASE_ACCEPTANCE_V1"
CANARY_ROW_ID = "R2_X1_Z3"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
TECHNICAL_EXIT_ID = "Z_RELEASE_PRICE_ACCEPTANCE_LOST"
SHARES_N = 100
SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
PORTFOLIO_WAIT_SEC = 0.05
BOARD_FRESHNESS_SEC = 5.0
MAX_FILLED_ENTRY_PER_SYMBOL_SESSION = 1
STRATEGY_N = 1

CASE_PASS = "DELAYED_OPEN_BUY_SPECIAL_QUOTE_COMPLETE_LOGIC_FOUND_V1"
CASE_FAIL = "DELAYED_OPEN_BUY_SPECIAL_QUOTE_FULL_STRATEGY_FAIL_V1"
CASE_COVERAGE = "DELAYED_OPEN_BUY_SPECIAL_QUOTE_COVERAGE_FAIL_V1"
CASE_DUP = "DELAYED_OPEN_SPECIAL_QUOTE_COMPLETE_STRATEGY_DUPLICATE_V1"
CASE_PARITY = "DELAYED_OPEN_ENGINE_PARITY_FAILED_V1"
CASE_DIRECTION = "BUY_SPECIAL_QUOTE_DIRECTION_NOT_PROVEN_V1"
NEXT_PASS = "FROZEN_LOGIC_EXISTING_DATA_CONFIRMATION_V1"
NEXT_REDIRECT = "NON_OPENING_POST_OPEN_COMPLETE_STRATEGY_REDIRECT_V1"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

MBO_WORK = False
FUTURES_WORK = False
EXTERNAL_ACQUISITION = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False
POST_RESULT_ENTRY_CHANGE = False
POST_RESULT_EXIT_CHANGE = False
SECOND_STRATEGY_ATTEMPTED = False

assert ANALYSIS_ID == "DELAYED_OPEN_BUY_SPECIAL_QUOTE_RELEASE_FULL_STRATEGY_V1"
assert REQUIRED_PARENT_VERDICT == "OPENING_LOGIC_PREOPEN_INPUT_NOT_SUPPORTED_V1"
assert STRATEGY_ID == "DO_BSQ_OPEN_RELEASE_ACCEPTANCE_V1"
assert int(STRATEGY_N) == 1
assert int(POSITION_CAP) == 5
assert int(SHARES_N) == 100
assert int(SHARES) == 100
assert int(MAX_FILLED_ENTRY_PER_SYMBOL_SESSION) == 1
assert tuple(SESSION_FLATTEN_HM) == (11, 29)
assert CANARY_EXPECTED["signal_n"] == 490
assert CANARY_EXPECTED["trade_n"] == 334
assert MBO_WORK is False
assert FUTURES_WORK is False
assert SIZING is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert CANARY_OPTIONAL
assert float(MIN_PF) == 1.10
assert int(MIN_TOTAL_TRADES) == 40
assert int(MIN_TRADING_DAYS_WITH_FILL) == 8
assert float(MIN_TRADES_PER_DAY) == 4.0
