"""Frozen Phase 2 research contract. No outcomes. No retune knobs."""
from __future__ import annotations

from typing import Any

from research.causal_driver_pb1 import C1_FIRST, C1_LAST, DEV_FIRST, DEV_LAST, FV_FIRST, FV_LAST, PROSPECTIVE_FROM
from research.causal_driver_pb1.identity.ids import sha256_obj
from research.causal_driver_pb1.phase2_precommit import (
    BOOTSTRAP_METHOD,
    BOOTSTRAP_N,
    BOOTSTRAP_SEED,
    CLOCK_FIRST,
    CLOCK_LAST,
    DAY_ELIGIBILITY_EXPECTED_N,
    DAY_ELIGIBILITY_MIN_COVERAGE,
    DAY_ELIGIBILITY_WINDOW,
    DAY_SHUFFLE_N,
    DAY_SHUFFLE_SEED,
    FDR_METHOD,
    FDR_Q,
    FX_LOOKBACKS_MIN,
    HORIZON_LAST_T,
    MKT105_MIN_VALID_SYMBOLS,
    PRECOMMIT_ID,
    RESPONSE_HORIZONS_MIN,
    SECTOR_CLOCK_COVERAGE_MIN,
    SECTOR_MIN_CONSTITUENTS,
    STOCK_PRICE_FIELD,
)


def frozen_contract(*, stock: dict[str, Any], sectors: dict[str, Any], folds: dict[str, Any], phase1: dict[str, Any]) -> dict[str, Any]:
    target_scopes = list(sectors.get("target_scopes") or ["MKT105_EQW"])
    search_n = len(FX_LOOKBACKS_MIN) * len(RESPONSE_HORIZONS_MIN) * len(target_scopes)
    contract = {
        "precommit_id": PRECOMMIT_ID,
        "research_question": (
            "Does a USDJPY change observable by time T carry reproducible lead information "
            "for subsequent Japan-stock returns?"
        ),
        "phase_role": "Driver lead discovery. Not sector-symbol freeze. Not Alpha. Not PB1. Not Complete Strategy.",
        "eligible_periods": {
            "DEVELOPMENT": {"first": DEV_FIRST, "last": DEV_LAST, "role": "candidate_discovery"},
            "ECONOMIC_DEVELOPMENT_EXPOSED": {"first": C1_FIRST, "last": C1_LAST, "role": "locked_oot_discovery_confirmation_not_final_certification"},
            "FROZEN_VALIDATION": {"first": FV_FIRST, "last": FV_LAST, "access": "DENY"},
            "PROSPECTIVE": {"first": PROSPECTIVE_FROM, "access": "DENY"},
        },
        "research_universe": {
            "id": "FIXED_RESEARCH_OBSERVATION_UNIVERSE_105_V1",
            "n": 105,
            "sha256": sectors.get("universe105_sha256"),
            "dynamic40": False,
            "pb1_candidates": False,
            "v1_578_trades": False,
            "unit": "eligible_date x eligible_minute x 105_symbols",
        },
        "target_scopes": {
            "market": "MKT105_EQW",
            "sector_pattern": "TSE33_<sector_id>_EQW",
            "eligible_now": target_scopes,
            "weighting": "equal_weight",
            "price_weighted": False,
            "sector_min_constituents": SECTOR_MIN_CONSTITUENTS,
            "sector_clock_valid_coverage_min": SECTOR_CLOCK_COVERAGE_MIN,
            "mkt105_min_valid_symbols": MKT105_MIN_VALID_SYMBOLS,
            "no_symbol_interpolation": True,
        },
        "stock_response_source_identity": {
            "source_id": "JQUANTS_EQUITY_MINUTE_105",
            "provider": "JQUANTS",
            "endpoint": "/v2/equities/bars/minute",
            "resolution": "1m",
            "timestamp_semantics": "BAR_START",
            "timezone": "Asia/Tokyo",
            "price_field": STOCK_PRICE_FIELD,
            "mid_fabricated": False,
            "access_first": DEV_FIRST,
            "access_last": C1_LAST,
            "on_disk_filename_last": "20260911",
            "row_filter": "DEV_FIRST <= date <= C1_LAST",
            "fv_rows_forbidden": True,
        },
        "stock_response": {
            "class": "INFORMATION_DISCOVERY_OUTCOME",
            "not_execution_price": True,
            "not_tradable_pnl": True,
            "start": "last completed 1m close with available_at <= T",
            "end": "last completed 1m close with available_at <= T+h",
            "return_unit": "bps log optional vs simple; Phase 2 run uses 10000*log(P_{T+h}/P_T) consistently with FX_RET",
            "stock_return_definition": "10000 * log(close_available_at_le_TplusH / close_available_at_le_T)",
        },
        "research_clock": {
            "grid": "native_1m",
            "first": CLOCK_FIRST,
            "last": CLOCK_LAST,
            "timezone": "Asia/Tokyo",
            "lunch_cross": False,
            "horizon_last_T": dict(HORIZON_LAST_T),
            "not_single_5m_grid": True,
            "minute_mod5_subgrids": [0, 1, 2, 3, 4],
            "dependence_unit": "date_block",
        },
        "usdjpy_feature_family": {
            "only": "USDJPY_causal_return",
            "mid": "(bid_close+ask_close)/2",
            "MID_IS_RAW_SOURCE": False,
            "lookbacks_min": list(FX_LOOKBACKS_MIN),
            "no_posthoc_lookbacks": True,
            "definition": "FX_RET_w(T) = 10000 * log(mid_T / mid_TminusW) where both mids have available_at <= T",
            "gap_fill": False,
            "missing_if_endpoint_missing_rejected_degraded": True,
            "missing_if_unexpected_missing_inside_lookback": True,
        },
        "response_horizons_min": list(RESPONSE_HORIZONS_MIN),
        "primary_model": {
            "family": "linear_causal_ols",
            "formula_sector": "future_return_bps = b_fx*FX_RET_w + b_self*target_past_5m + b_market*MKT105_past_5m + minute_of_day_FE + e",
            "formula_market": "future_return_bps = b_fx*FX_RET_w + b_self*MKT105_past_5m + minute_of_day_FE + e",
            "market_control_not_duplicated_on_mkt105": True,
            "controls_only_at_or_before_T": True,
            "no_pb1_features": True,
            "no_posthoc_technicals": True,
            "no_ml": True,
            "forbidden_models": ["random_forest", "xgboost", "neural_net", "large_feature_grid", "hyperparameter_tuning"],
            "baseline_model0": "target_past_5m + market_past_5m + minute_of_day_FE",
            "model1": "model0 + FX_RET_w",
            "incremental_information": "USDJPY must add information beyond stock/sector/market momentum and time-of-day",
        },
        "nonparametric": {
            "dev_fx_quintiles": ["Q1", "Q2", "Q3", "Q4", "Q5"],
            "boundaries_frozen_on_development": True,
            "c1_uses_dev_boundaries": True,
            "stats": ["Q5_future", "Q1_future", "Q5_minus_Q1"],
            "direction_locked_on_dev": True,
            "not_an_entry_threshold_search": True,
        },
        "bootstrap_method": BOOTSTRAP_METHOD,
        "bootstrap_n": BOOTSTRAP_N,
        "bootstrap_seed": BOOTSTRAP_SEED,
        "bootstrap_seed_sha": sha256_obj({"method": BOOTSTRAP_METHOD, "n": BOOTSTRAP_N, "seed": BOOTSTRAP_SEED}),
        "multiple_testing_method": FDR_METHOD,
        "fdr_q": FDR_Q,
        "discovery_search_n": search_n,
        "dev_candidate_gate": {
            "D1": "sign(b_fx) identical on DEV_EARLY and DEV_LATE",
            "D2": "pooled Development date-block bootstrap 95% CI excludes 0",
            "D3": "BH FDR q <= 0.05 on Development discovery family",
            "D4": "Q5-Q1 spread direction matches sign(b_fx)",
            "D5": ">= 4/5 minute-mod-5 subgrids same sign",
            "D6": "leave-one-month-out >= 75% same sign",
            "all_required": True,
        },
        "c1_confirmation_gate": {
            "applies_to": "DEV-locked candidates only",
            "no_c1_rule_selection": True,
            "C1": "pooled C1 b_fx same sign as DEV",
            "C2": "C1 date-block bootstrap 95% CI excludes 0",
            "C3": ">= 2/3 of C1_EARLY/MIDDLE/LATE same sign as DEV",
            "C4": "any opposite-sign fold with |effect| > 1.5x DEV pooled effect FAIL",
            "C5": "C1 Q5-Q1 same direction as DEV",
            "C6": "C1 leave-one-month-out >= 75% same sign",
            "all_required": True,
        },
        "offset_placebo_gate": {
            "offsets_min": [-10, -5, -3, -1, 0, 1, 3, 5, 10],
            "causal_side": "offset <= 0",
            "noncausal_placebo": "offset > 0",
            "future_offsets_not_usable_as_alpha": True,
            "L1": "offset 0 C1-confirmed",
            "L2": "at least one of -1/-3/-5 same sign",
            "L3": "not vanished on causal side while strong only on future offsets",
            "L4": "|effect offset 0| >= 0.50 * max(|+1|,|+3|,|+5|)",
            "fail_label": "FOLLOWER_OR_CONTEMPORANEOUS_NOT_LEAD",
        },
        "day_shuffle_gate": {
            "n": DAY_SHUFFLE_N,
            "seed": DAY_SHUFFLE_SEED,
            "strata": ["calendar_month", "weekday_when_feasible"],
            "assignment": "permute USDJPY days onto stock days within stratum",
            "requirement": "real |statistic| >= empirical 95th percentile of |shuffled statistic|",
        },
        "concentration_gate": {
            "sector": "leave-one-symbol-out >= 80% same sign AND remove top absolute contributor still same sign",
            "market": "remove top 1 symbol and top 5 symbols still same sign",
        },
        "missingness_policy": {
            "audit_by_driver_strength": ["fx_feature_missing_rate", "stock_target_missing_rate", "sector_basket_coverage"],
            "selection_bias_if_missing_tracks_fx_state": "FAIL_or_BLOCK",
            "missing_as_zero_return": False,
            "no_fx_gap_fill": True,
            "no_stock_interpolation": True,
        },
        "day_eligibility": {
            "basis": "USDJPY VALID paired coverage only; no outcome peek",
            "window_jst": f"{DAY_ELIGIBILITY_WINDOW[0]}-{DAY_ELIGIBILITY_WINDOW[1]}",
            "expected_n": DAY_ELIGIBILITY_EXPECTED_N,
            "min_ratio": DAY_ELIGIBILITY_MIN_COVERAGE,
            "named_date_exclusions_forbidden": True,
            "stock_clock_drop_if_mkt_valid_symbols_lt": MKT105_MIN_VALID_SYMBOLS,
            "sector_clock_drop_if_coverage_lt": SECTOR_CLOCK_COVERAGE_MIN,
        },
        "c1_lock_protocol": {
            "order": ["Development discovery", "candidate list lock", "candidate_list_sha256", "C1 evaluated once"],
            "forbidden_after_c1_peek": ["window change", "sector change", "horizon change", "sign change"],
            "dev_zero_candidates": "USDJPY_CAUSAL_LEAD_DEV_NOT_FOUND; do not open C1 outcomes for exploration",
        },
        "phase2_pass_requires": [
            "dev_candidate_gate",
            "c1_confirmation_gate",
            "offset_placebo_gate",
            "day_shuffle_gate",
            "concentration_gate",
        ],
        "phase2_pass_is_not": ["alpha_edge_proven", "complete_strategy_edge_proven", "profit"],
        "future_verdicts": {
            "PASS": "USDJPY_STANDALONE_CAUSAL_LEAD_FOUND_V1",
            "FAIL": "USDJPY_STANDALONE_CAUSAL_LEAD_NOT_FOUND_V1",
            "BLOCK": "USDJPY_STANDALONE_CAUSAL_LEAD_DISCOVERY_BLOCKED_V1",
        },
        "parent_phase1": phase1,
        "stock_timestamp_semantics_proven": bool(stock.get("stock_timestamp_semantics_proven")),
        "sector_mapping_sha256": sectors.get("sector_mapping_sha256"),
        "development_fold_boundaries": folds.get("development_fold_boundaries"),
        "c1_fold_boundaries": folds.get("c1_fold_boundaries"),
        "fold_boundary_sha256": folds.get("fold_boundary_sha256"),
        "PHASE2_OUTCOMES_OPENED": False,
        "candidate_list_sha256": None,
        "candidate_list_sha256_required_before_c1": True,
    }
    contract["precommit_sha256"] = sha256_obj(contract)
    return contract
