"""Phase 0 enumerations. Separate driver quality from Alpha status."""
from __future__ import annotations

from enum import Enum


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


class QualityStatus(str, Enum):
    VALID = "VALID"
    STALE = "STALE"
    MISSING = "MISSING"
    DEGRADED = "DEGRADED"
    REJECTED = "REJECTED"


class AlphaStatus(str, Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    INVALIDATED = "INVALIDATED"
    SUPERSEDED = "SUPERSEDED"
    RESEARCH = "RESEARCH"


class DatasetRole(str, Enum):
    DEVELOPMENT = "DEVELOPMENT"
    ECONOMIC_DEVELOPMENT_EXPOSED = "ECONOMIC_DEVELOPMENT_EXPOSED"
    FROZEN_VALIDATION = "FROZEN_VALIDATION"
    PROSPECTIVE = "PROSPECTIVE"
    RUNTIME_CAPTURE = "RUNTIME_CAPTURE"
    SYNTHETIC_TEST = "SYNTHETIC_TEST"


class RunMode(str, Enum):
    FOUNDATION_TEST = "FOUNDATION_TEST"
    DRIVER_DISCOVERY = "DRIVER_DISCOVERY"
    ALPHA_DEVELOPMENT = "ALPHA_DEVELOPMENT"
    FROZEN_VALIDATION = "FROZEN_VALIDATION"
    PROSPECTIVE_PAPER = "PROSPECTIVE_PAPER"


class AccessKind(str, Enum):
    METADATA = "METADATA"
    PAYLOAD = "PAYLOAD"
    ECONOMIC_PAYLOAD = "ECONOMIC_PAYLOAD"


class DriverFamily(str, Enum):
    FX = "FX"
    JP_FUT = "JP_FUT"
    US_FUT = "US_FUT"
    ASIA = "ASIA"
    RATES = "RATES"
    COMMODITY = "COMMODITY"
    JP_INTERNAL = "JP_INTERNAL"
    SYNTHETIC = "SYNTHETIC"


class TargetScope(str, Enum):
    MARKET = "MARKET"
    SECTOR = "SECTOR"
    SYMBOL = "SYMBOL"


class MechanismStatus(str, Enum):
    RESEARCH = "RESEARCH"
    CANDIDATE = "CANDIDATE"
    FROZEN = "FROZEN"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class AdapterVerdict(str, Enum):
    AGREE = "AGREE"
    REJECT = "REJECT"


class RejectReason(str, Enum):
    ALPHA_EXPIRED = "ALPHA_EXPIRED"
    ALPHA_DIRECTION_MISMATCH = "ALPHA_DIRECTION_MISMATCH"
    PB1_NOT_ACTIVE = "PB1_NOT_ACTIVE"
    PB1_NO_LOCATION = "PB1_NO_LOCATION"
    PB1_THESIS_LOST = "PB1_THESIS_LOST"
    E0_NOT_CONFIRMED = "E0_NOT_CONFIRMED"
    E1_NOT_CONFIRMED = "E1_NOT_CONFIRMED"
    DATA_STALE = "DATA_STALE"
    DATA_MISSING = "DATA_MISSING"
    NOT_TRADABLE = "NOT_TRADABLE"
    NOT_REGISTERED = "NOT_REGISTERED"
    NOT_IN_TRANSMISSION_SCOPE = "NOT_IN_TRANSMISSION_SCOPE"
    QUALITY_DEGRADED_FAIL_CLOSED = "QUALITY_DEGRADED_FAIL_CLOSED"
    CAUSAL_TIME = "CAUSAL_TIME"
    FIREWALL = "FIREWALL"
    NO_ALPHA = "NO_ALPHA"


class EventType(str, Enum):
    DRIVER_OBSERVED = "DRIVER_OBSERVED"
    DRIVER_REJECTED = "DRIVER_REJECTED"
    DATASET_ACCESS = "DATASET_ACCESS"
    IDENTITY_BOUND = "IDENTITY_BOUND"
