"""AM direct EXEC_U precommitted development. Frozen target. No Stage2. No Exact. No PnL."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from research.wait5_session_target_learnability import POS_REP_DENOM, POS_REP_MIN, RF_REG_PARAMS
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_DIRECT_EXEC_U_PRECOMMITTED_DEVELOPMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
FINAL_SELECTION_N = 3
SLOTS = 3
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_PRECOMMIT_ID = "AM_DIRECT_EXECUTION_ADJUSTED_UPSIDE_TARGET_PRECOMMIT_V1"
PRIOR_PRECOMMIT_VERDICT = "AM_DIRECT_EXECUTION_ADJUSTED_UPSIDE_TARGET_PRECOMMITTED"
PRIOR_GEOMETRY_ID = "AM_WAIT5_FILLABILITY_UPSIDE_ARCHITECTURE_GEOMETRY_AUDIT_V1"

DIRECT_TARGET = "EXEC_U_TARGET"
NONFILL_TARGET_VALUE = 0.0
MODEL_FAMILY = "RandomForestRegressor"
SELECTION_RULE = "PRED_EXEC_U_TOP3"
PRIMARY_REFERENCE = "FILL_ONLY"
ALLOWED_DEVELOPMENT_ARMS = ("CONTROL", "FILL_ONLY", "DIRECT_EXEC_U")

PARITY_EXPECTED = {
    "FILL_ONLY_FILL_RATE": 0.4375,
    "FILL_ONLY_EXEC_U": 0.00425138097927976,
    "FILL_ONLY_EXEC_D": -0.003854166912748494,
    "FILL_NONWORSE_U_IMPROVE_RATE": 0.8055555555555556,
    "SAME_FILL_U_IMPROVE_RATE": 0.5833333333333334,
    "FILL_NONWORSE_U_D_NONWORSE_RATE": 0.5416666666666666,
    "FILL_ONLY_DOMINATED_IN_FILL_U_RATE": 0.8194444444444444,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(FINAL_SELECTION_N) == 3
assert int(SLOTS) == 3
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(POS_REP_MIN) == 6
assert int(POS_REP_DENOM) == 9
assert int(RF_REG_PARAMS["n_estimators"]) == 500
assert int(RF_REG_PARAMS["max_depth"]) == 6
assert int(RF_REG_PARAMS["min_samples_leaf"]) == 20
assert float(RF_REG_PARAMS["max_features"]) == 1.0
assert RF_REG_PARAMS["bootstrap"] is True
assert int(RF_REG_PARAMS["random_state"]) == 42
assert COMMON_AM_PM_MODEL_ALLOWED is False

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WEIGHT_SEARCH = False
STAGE1_ALLOWED = False
STAGE2_ALLOWED = False
OLD_TWO_STAGE_ALLOWED = False
MINIMAL_SWAP_STAGE2_ALLOWED = False
D_TRAINING_TARGET_ALLOWED = False
FILL_LOSS_ALLOWED_IN_PASS_GATE = False
P_FILL_TIMES_U_PRED = False
SHORTLIST_SEARCH = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
ENTRY_RETRAIN_STARTED = False
DEVELOPMENT_RUN_STARTED = True
W5_RUNTIME_ADOPTED = False
MODEL_HYPERPARAMETERS_FROZEN = True
MODEL_HYPERPARAMETER_SEARCH_N = 0
ORACLE_SELECTION_USE_N = 0
