"""GENERALIZATION_FAILURE_COMPONENT_RCA_V1. Coverage-corrected two-component RCA. No replay."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "GENERALIZATION_FAILURE_COMPONENT_RCA_V1"
PARENT_ANALYSIS_ID = "GENERALIZATION_FAILURE_RCA_V1"
PARENT_VERDICT_REQUIRED = "GENERALIZATION_FAILURE_MIXED_MECHANISMS"
PARENT_MODE_REQUIRED = "MIXED_CONCENTRATION_AND_SELECTION_INSTABILITY"
PARENT_NEXT_REQUIRED = "GENERALIZATION_FAILURE_COMPONENT_RCA_V1"

CASE_A = "GENERALIZATION_COMPONENT_TWO_STAGE_FAILURE_CONFIRMED"
VERDICT_IF_A = CASE_A
NEXT_IF_A = "SELECTION_SURFACE_MECHANISM_RCA_V1"

ST_WINNER_ID = "ST_HANDOFF_NEXT__S_CLOSE_ABOVE_VWAP__S_RCI_ABOVE_NEG80"
ST_TRADE_N = 75
ST_BASE_PNL = 220580.0
ST_BASE_PF = 2.7365769170209417
ST_EX_BEST = 56280.0
ST_CAUSAL_PNL = 77580.0
ST_CAUSAL_PF = 1.61076995748701
ST_TRAIN_TOP3_N = 2
ST_FOLD_TEST_PNL = -67720.0

LOW_SUPPORT_IDS = (
    "ST_HANDOFF_NEXT__S_MA_TREND_UP__S_RCI_ABOVE_NEG80",
    "ST_HANDOFF_NEXT__S_MA_TREND_UP__S_CLOSE_ABOVE_VWAP",
    "ST_HANDOFF_NEXT__S_BB_ABOVE_MID__S_RCI_ABOVE_NEG80",
)

ORIGINAL_G1G2_N = 13
EXPECTED_LOW_SUPPORT_N = 3
EXPECTED_VALID_N = 10

PRIMARY_COMPONENT = "CROSS_LINEAGE_CONCENTRATION_FRAGILITY"
RESIDUAL_BOTTLENECK = "ST_SPECIFIC_SELECTION_SURFACE_GENERALIZATION"
COMPONENT_STRUCTURE = "SEQUENTIAL_TWO_COMPONENT_FAILURE"

SELECTION_FORMALLY_TESTED_STUDY_IDS = ("SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1",)

TRUE_OOS = False
CERTIFIED = False
SIZING = False
NEW_REPLAY = False
NEW_FULL_CAUSAL_RUN = False
NEW_PNL_SIMULATION = False
NEW_FOLD_RUN = False
NEW_ENTRY = False
NEW_EXIT = False
NEW_THRESHOLD = False
NEW_CANDIDATE = False
RAW_CAPTURE_READ_N = 0
TEMPORAL_SPLIT = False
L1_WIDE_SELECTION_INSTABILITY_PROVEN = False
L2_SELECTION_INSTABILITY_PROVEN = False

assert ANALYSIS_ID == "GENERALIZATION_FAILURE_COMPONENT_RCA_V1"
assert EXPECTED_VALID_N == ORIGINAL_G1G2_N - EXPECTED_LOW_SUPPORT_N == 10
assert len(LOW_SUPPORT_IDS) == 3
assert TEMPORAL_SPLIT is False
assert L1_WIDE_SELECTION_INSTABILITY_PROVEN is False
assert L2_SELECTION_INSTABILITY_PROVEN is False
assert NEW_REPLAY is False
assert RAW_CAPTURE_READ_N == 0
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert TRUE_OOS is False
assert CERTIFIED is False
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
