"""SUPPORT_RESISTANCE_FIRST_INTERACTION_MATCHED_CAUSAL_TEST_V1. Frozen face-valid detector. Matched path test. Not a strategy."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE
from research.support_resistance_face_valid_first_interaction_rebuild_v1 import (
    CONFIRM_ATR,
    ZONE_HALF_ATR,
)

PROGRAM_ID = "SUPPORT_RESISTANCE_FIRST_INTERACTION_MATCHED_CAUSAL_TEST_V1"
ANALYSIS_ID = "SUPPORT_RESISTANCE_FIRST_INTERACTION_MATCHED_CAUSAL_TEST_V1"
PARENT_ANALYSIS_ID = "SUPPORT_RESISTANCE_FACE_VALID_FIRST_INTERACTION_REBUILD_V1"
PARENT_VERDICT = "SUPPORT_RESISTANCE_FACE_VALID_REBUILD_READY_V1"
RCA_DEFERRED = "REFERENCE_LEVEL_MECHANISM_RCA_V1"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"

FROZEN_CONFIRM_ATR = 0.75
FROZEN_ZONE_HALF_ATR = 0.15
LUNCH_POLICY = "HOLD_THROUGH_LUNCH_RESUME_PM"
SESSION_FLAT = "15:20"
EVAL_BLOCKS = ("D2", "D3", "D4")
BOOT_N = 400
BOOT_SEED = 20260917
MIN_PAIR_N = 80
MIN_DAY_N = 25
MIN_SYMBOL_N = 10
MOM5_TOL = 0.002
MOM3_TOL = 0.002
MOM1_TOL = 0.003
VOL_REL_TOL = 0.40
RNG_REL_TOL = 0.25
PRIMARY_METRIC = "p20_before_m20"
EXPECTED_PRIMARY_FIRST_TEST_N = 2713
EXPECTED_FIRST_TEST_N = 6646

PRIMARY_SLOTS = (
    "NEAREST_ACTIVE_RESISTANCE_ABOVE",
    "NEAREST_ACTIVE_SUPPORT_BELOW",
)
SECONDARY_SLOTS = (
    "NEAREST_BROKEN_RESISTANCE_BELOW",
    "NEAREST_BROKEN_SUPPORT_ABOVE",
)

CASE_SEP = "FACE_VALID_SR_MATCHED_PATH_SEPARATION_FOUND_V1"
CASE_NONE = "FACE_VALID_SR_NO_MATCHED_PATH_SEPARATION_V1"
CASE_INCON = "FACE_VALID_SR_MATCHED_TEST_INCONCLUSIVE_V1"
CASE_BIND = "SR_MATCHED_CAUSAL_TEST_BIND_FAILED_V1"
CASE_HASH = "SR_MATCHED_CAUSAL_TEST_DETECTOR_HASH_FAILED_V1"

NEXT_NOT_STRATEGY = "SUPPORT_RESISTANCE_MATCHED_SEPARATION_NOT_A_STRATEGY_V1"
NEXT_STOP_NONE = "STOP_FACE_VALID_SR_NO_MATCHED_INCREMENTAL_PATH_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"
NEXT_HASH = "REPAIR_FROZEN_DETECTOR_HASH_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_OPENED = False
NEW_PAID_DATA = False
PROMOTED = False
V27_BOLTED = False
RCA_EXECUTED = False
NO_PNL_PARAMETER_TUNING = True
X0_X1_USED_TO_SELECT_RULES = False
DETECTOR_RETUNED = False
FIVE_PP_CONTINUATION_SOLE_GATE = False

assert CONFIRM_ATR == FROZEN_CONFIRM_ATR == 0.75
assert ZONE_HALF_ATR == FROZEN_ZONE_HALF_ATR == 0.15
assert DETECTOR_RETUNED is False
assert FIVE_PP_CONTINUATION_SOLE_GATE is False
assert PARENT_VERDICT == "SUPPORT_RESISTANCE_FACE_VALID_REBUILD_READY_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert OLD_CONFIRMATION_OPENED is False
assert PROMOTED is False
assert X0_X1_USED_TO_SELECT_RULES is False
