"""R11_ONLINE_EPISODE_CAUSALITY_AUDIT_V1. Temporal realizability of last-event clustering. No Confirmation. No Frozen Validation. No retune."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "R11_ONLINE_EPISODE_CAUSALITY_AUDIT_V1"
ANALYSIS_ID = "R11_ONLINE_EPISODE_CAUSALITY_AUDIT_V1"
PARENT_ANALYSIS_ID = "NATIVE_1M_PATH_STATE_STRATEGY_FREEZE_V1"
PARENT_VERDICT = "NATIVE_1M_R11_STRATEGY_FROZEN_V1"
STRATEGY_ID = "NATIVE_1M_R11_VWAP_RECLAIM_V1"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_ATLAS_EPISODE_N = 100482
EXPECTED_CANDIDATE_N = 4149
EXPECTED_TRADE_N_D2D4 = 908
EXPECTED_X0_D2D4 = 47.38213942863883
EPISODE_GAP_MIN = 10
ENTRY_CUTOFF = "14:50"
SESSION_FLAT = "15:20"
TIME_STOP_MIN = 20
OCCUPANCY = 3
X1_TAX_BPS = 8.0
PATH_BARS = 30
EVAL_BLOCKS = ("D2", "D3", "D4")
TRAIN_BLOCK = "D1"

CASE_PROVEN = "R11_ONLINE_EPISODE_CAUSALITY_PROVEN_V1"
CASE_LOOKAHEAD = "R11_OFFLINE_CLUSTER_LOOKAHEAD_CONFIRMED_V1"
CASE_BIND = "R11_ONLINE_CAUSALITY_BIND_FAILED_V1"
CASE_OFFLINE = "R11_ONLINE_CAUSALITY_OFFLINE_PARITY_FAILED_V1"

NEXT_CONFIRM = "R11_SECONDARY_CONFIRMATION_NOT_PRISTINE_V1"
NEXT_STOP = "STOP_R11_CAUSAL_GENERATOR_INVALID_NO_CONFIRMATION_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"
NEXT_OFFLINE = "REPAIR_OFFLINE_GENERATOR_PARITY_THEN_RETRY_CAUSALITY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_OPENED = False
PARAMETER_CHANGED = False
THRESHOLD_TUNED = False
EXIT_CHANGED = False
CAP_CHANGED = False
SELECTED_DELAYED_OR_FIRST = False
NEW_PAID_DATA = False
PROMOTED = False
V27_BOLTED = False

assert ANALYSIS_ID == "R11_ONLINE_EPISODE_CAUSALITY_AUDIT_V1"
assert PARENT_VERDICT == "NATIVE_1M_R11_STRATEGY_FROZEN_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert OLD_CONFIRMATION_OPENED is False
assert PARAMETER_CHANGED is False
assert THRESHOLD_TUNED is False
assert EXIT_CHANGED is False
assert CAP_CHANGED is False
assert SELECTED_DELAYED_OR_FIRST is False
assert EPISODE_GAP_MIN == 10
assert SESSION_FLAT == "15:20"
assert TIME_STOP_MIN == 20
assert OCCUPANCY == 3
