"""EXISTING_DATA_STRATEGY_RESEARCH_STOP_REASSESSMENT_V1. Method audit only. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)

ANALYSIS_ID = "EXISTING_DATA_STRATEGY_RESEARCH_STOP_REASSESSMENT_V1"
FDG_PARENT_ID = "FULL_CAUSAL_FDG_RELATIVE_GEOMETRY_MIGRATION_V1"
OBJECT_PARENT_ID = "DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"

REQUIRED_FDG_VERDICT = "FDG_RELATIVE_GEOMETRY_FULL_STRATEGY_COVERAGE_FAIL_V1"
REQUIRED_FDG_STRATEGY_ID = "FDG_RELATIVE_GEOMETRY_MIGRATION_ONSET_X1_Z_BASELINE_LOSS"
REQUIRED_FDG_SPEC_SHA256 = "45d31abddade34813ecae969058898501d75cb159ed0dfc624a6118540a7d59f"
REQUIRED_FDG_INTEGRITY = "33/33"
REQUIRED_FDG_SIGNAL_N = 18875
REQUIRED_FDG_TRADE_N = 4613
REQUIRED_FDG_PNL = -6253240
REQUIRED_FDG_PF = 0.11412138040460135
REQUIRED_FDG_DAYS = "0/10/0"
REQUIRED_FDG_EX_BEST = -6031140
REQUIRED_FDG_UNFILLED = 17

REQUIRED_OBJECT_VERDICT = "NEW_CAUSAL_INFORMATION_OBJECT_SELECTED_V1"
REQUIRED_RAW_OBJECT_N = 13
REQUIRED_UNDEREXPLORED_N = 1
REQUIRED_SELECTED_OBJECT = "FULL_DEPTH_GEOMETRY"

NEW_INFORMATION_OBJECT_SEARCH_CLOSED = True
FDG_RESCUE = False
NEW_STRATEGY_CREATED = False
NEW_ENTRY_CREATED = False
NEW_EXIT_CREATED = False
THRESHOLD_SEARCH = False
NEW_ECONOMIC_RUN = False
NEW_OUTCOME_READ = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

PRIMARY_DECISION_UNIT = (
    "ENTRY + EXECUTION + EXIT + CAP + SAME-SYMBOL + OCCUPANCY + "
    "SLOT RELEASE + REENTRY + SESSION CLOSE"
)

METHOD_IDS = ("M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10")
BOUNDED_DATA_DRIVEN_ID = "BOUNDED_DATA_DRIVEN_FULL_CAUSAL_STRATEGY_LEARNING"

CASE_A = "ONE_EXISTING_DATA_RESEARCH_METHOD_REMAINS_V1"
CASE_B = "EXISTING_SEALED_DEV_STRATEGY_RESEARCH_JUSTIFIABLY_EXHAUSTED_V1"
NEXT_A = "BOUNDED_FULL_CAUSAL_DATA_DRIVEN_STRATEGY_DESIGN_V1"
NEXT_B = "RESEARCH_PAUSE_AND_DATA_REQUIREMENTS_REDESIGN_V1"

assert ANALYSIS_ID == "EXISTING_DATA_STRATEGY_RESEARCH_STOP_REASSESSMENT_V1"
assert FDG_RESCUE is False
assert NEW_ECONOMIC_RUN is False
assert NEW_OUTCOME_READ is False
assert NEW_STRATEGY_CREATED is False
assert NEW_ENTRY_CREATED is False
assert NEW_EXIT_CREATED is False
assert THRESHOLD_SEARCH is False
assert SIZING is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert NEW_INFORMATION_OBJECT_SEARCH_CLOSED is True
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert len(METHOD_IDS) == 10
