"""Frozen architecture-family and method-class inventory from prior verdicts. No PnL recompute."""
from __future__ import annotations

from typing import Any

from research.discovery_information_object_expansion_decision_v1 import IOAR_VERDICT, UEIA_VERDICT
from research.systematic_state_transition_library_precommit_v1 import OR_FINAL_STATUS, PFQ_LINE, PFQ_VERDICT


def architecture_inventory() -> list[dict[str, Any]]:
    return [
        {
            "ARCHITECTURE_ID": "SIMPLE_FULL",
            "PRIOR_RUN_IDS": ["SIMPLE_FULL_STRATEGY_DISCOVERY_V1"],
            "FINAL_VERDICT": "SIMPLE_FULL_STRATEGY_NO_ROBUST_CANDIDATE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "NOTE": "Prewritten 75 E×X×Z library. Not data-learned definitions.",
        },
        {
            "ARCHITECTURE_ID": "SIMPLE_TECH",
            "PRIOR_RUN_IDS": ["SIMPLE_TECH_ENTRY_FAMILY", "simple_tech_redesign/strategy_level_entry_rebase_v1"],
            "FINAL_VERDICT": "SIMPLE_TECH_ENTRY_FAMILY_ABSOLUTE_EDGE_EXHAUSTED",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY then family redesign closed",
            "NOTE": "Do not reopen exact closed SIMPLE_TECH identities.",
        },
        {
            "ARCHITECTURE_ID": "SYSTEMATIC_STATE_TRANSITION",
            "PRIOR_RUN_IDS": ["SYSTEMATIC_STATE_TRANSITION_LIBRARY_PRECOMMIT_V1", "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1"],
            "FINAL_VERDICT": "SYSTEMATIC_STATE_TRANSITION_SELECTION_UNSTABLE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "NOTE": "Precommitted 25-state library.",
        },
        {
            "ARCHITECTURE_ID": "RECOVERY_SEQUENCE",
            "PRIOR_RUN_IDS": ["RECOVERY_SEQUENCE_FULL_STRATEGY_ARCHITECTURE_V1"],
            "FINAL_VERDICT": "RECOVERY_SEQUENCE_FULL_STRATEGY_NO_ROBUST_CANDIDATE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
        },
        {
            "ARCHITECTURE_ID": "PARTICIPATION_ONSET",
            "PRIOR_RUN_IDS": ["PARTICIPATION_ONSET_FULL_STRATEGY_V1"],
            "FINAL_VERDICT": "PARTICIPATION_ONSET_FULL_STRATEGY_NO_ROBUST_CANDIDATE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
        },
        {
            "ARCHITECTURE_ID": "C1_MULTI_TIMEFRAME",
            "PRIOR_RUN_IDS": [
                "C1_MULTI_TIMEFRAME_FULL_STRATEGY_V1",
                "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2",
            ],
            "FINAL_VERDICT": "C1_MULTI_TIMEFRAME_ENTRY_EXIT_NO_ROBUST_CANDIDATE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "NOTE": "Precommitted MTF library then Full Causal.",
        },
        {
            "ARCHITECTURE_ID": "C4_PORTFOLIO_CROWDING",
            "PRIOR_RUN_IDS": ["C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2"],
            "FINAL_VERDICT": "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_NO_ROBUST_CANDIDATE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "NOTE": "Admission-aware precommitted arms.",
        },
        {
            "ARCHITECTURE_ID": "CSB",
            "PRIOR_RUN_IDS": ["CSB_MA_ONSET", "CSB_V3"],
            "FINAL_VERDICT": "CSB_V3 negative control / CSB_MA_ONSET closed lineage",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY as control; not a remaining method",
            "NOTE": "CSB_RCA_RUN=false; do not retune.",
        },
        {
            "ARCHITECTURE_ID": "V4_RESISTANCE_EPISODE",
            "PRIOR_RUN_IDS": ["NEW_FULL_STRATEGY_V2_IMPLEMENTATION_AND_DEV_EVAL_V1"],
            "FINAL_VERDICT": "NEW_FULL_STRATEGY_V4_COVERAGE_FAIL",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "NOTE": "V4_RETUNE=false.",
        },
        {
            "ARCHITECTURE_ID": "PULLBACK_FAMILY",
            "PRIOR_RUN_IDS": ["E1_X5", "E1_X6_TAER", "NEW_FULL_STRATEGY_ARCHITECTURE_INVENTORY_AND_FREEZE_V3"],
            "FINAL_VERDICT": "PULLBACK_FAMILY_RESCUE_FORBIDDEN; E1_X6_NO_ROBUST_ENTRY_EXIT_PAIR",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "DECISION_UNIT": "ENTRY / ENTRY-EXIT pair; not current occupancy unit at selection",
        },
        {
            "ARCHITECTURE_ID": "PFQ",
            "PRIOR_RUN_IDS": ["E1_X7_X8_X9_FINAL_CLOSURE"],
            "FINAL_VERDICT": PFQ_VERDICT,
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "DECISION_UNIT": "INDEPENDENT_ENTRY_EXIT_JOINT_STUDY",
            "NOTE": PFQ_LINE,
        },
        {
            "ARCHITECTURE_ID": "OR",
            "PRIOR_RUN_IDS": ["OR_OVERLAY_CAUSAL_CONTRIBUTION_RECONCILIATION_V1"],
            "FINAL_VERDICT": "OR_OVERLAY_CAUSAL_RECONCILIATION_UNRESOLVABLE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "DECISION_UNIT": OR_FINAL_STATUS,
        },
        {
            "ARCHITECTURE_ID": "DYNAMIC_ANCHOR",
            "PRIOR_RUN_IDS": ["DYNAMIC_ANCHOR_TRAIL10"],
            "FINAL_VERDICT": "closed lineage DYNAMIC_ANCHOR_TRAIL10",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "DECISION_UNIT": "ENTRY / trail research; E1_X14 design-only thresholds",
        },
        {
            "ARCHITECTURE_ID": "BREAKOUT",
            "PRIOR_RUN_IDS": ["NEW_ENTRY_BREAKOUT_CONTINUATION_V1"],
            "FINAL_VERDICT": "NEW_ENTRY_BREAKOUT_CONTINUATION_DEV_FAILED",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY on DEV; Holdout unread this run",
        },
        {
            "ARCHITECTURE_ID": "FAILED_BREAKDOWN_RECLAIM",
            "PRIOR_RUN_IDS": ["NEW_ENTRY_FAILED_BREAKDOWN_RECLAIM_V1"],
            "FINAL_VERDICT": "FAILED_BREAKDOWN_RECLAIM_DEV_ALPHA_FAILED",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
        },
        {
            "ARCHITECTURE_ID": "VWAP_RECLAIM_REJECTION",
            "PRIOR_RUN_IDS": ["NEW_ENTRY_VWAP_REJECTION_RECLAIM_V1"],
            "FINAL_VERDICT": "NEW_ENTRY_VWAP_RECLAIM_DEV_FAILED",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
        },
        {
            "ARCHITECTURE_ID": "IOAR",
            "PRIOR_RUN_IDS": ["DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"],
            "FINAL_VERDICT": IOAR_VERDICT,
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "exact mechanism closed; do not reopen",
        },
        {
            "ARCHITECTURE_ID": "UEIA",
            "PRIOR_RUN_IDS": ["DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"],
            "FINAL_VERDICT": UEIA_VERDICT,
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "DECISION_UNIT": "validated-edge program closed",
        },
        {
            "ARCHITECTURE_ID": "RPFE",
            "PRIOR_RUN_IDS": ["E1_X15_RPFE_EPISODE_INCREMENTAL_ENTRY_GATE"],
            "FINAL_VERDICT": "RPFE incremental ENTRY gate; closed lineage RPFE",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "DECISION_UNIT": "ENTRY-quality / horizon labels from E1_X14",
        },
        {
            "ARCHITECTURE_ID": "E1_X14",
            "PRIOR_RUN_IDS": ["E1_X14_BOARD_INDEPENDENT_ENTRY_SIGNAL_AUDIT"],
            "FINAL_VERDICT": "E1_X14_STABLE_COMPONENT_SIGNAL_FOUND then Holdout mixed (Holdout unread this run)",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "DECISION_UNIT": "ENTRY component signal vs future-return horizons 30/60/180/300s",
        },
        {
            "ARCHITECTURE_ID": "FDG_STATIC_SPAN",
            "PRIOR_RUN_IDS": ["FULL_CAUSAL_STRATEGY_ARCHITECTURE_FROM_INFORMATION_OBJECT_V1"],
            "FINAL_VERDICT": "FDG_PRICE_GEOMETRY_FULL_STRATEGY_COVERAGE_FAIL_V1",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
        },
        {
            "ARCHITECTURE_ID": "FDG_RELATIVE_MIGRATION",
            "PRIOR_RUN_IDS": ["FULL_CAUSAL_FDG_RELATIVE_GEOMETRY_MIGRATION_V1"],
            "FINAL_VERDICT": "FDG_RELATIVE_GEOMETRY_FULL_STRATEGY_COVERAGE_FAIL_V1",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "NOTE": "Justified FDG mechanism space exhausted. Do not rescue.",
        },
        {
            "ARCHITECTURE_ID": "FCMD_42",
            "PRIOR_RUN_IDS": ["FULL_CAUSAL_MECHANISM_DISCOVERY_V1"],
            "FINAL_VERDICT": "FULL_CAUSAL_MECHANISM_DISCOVERY_NO_ROBUST_CANDIDATE_V1",
            "CURRENTLY_CLOSED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "DECISION_UNIT": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "NOTE": "42 prewritten O1/O2/O3 mechanisms. BASE_QUALIFIED_N=0.",
        },
    ]


def method_taxonomy() -> list[dict[str, Any]]:
    return [
        {
            "METHOD_ID": "M1",
            "NAME": "HAND-DESIGNED DETERMINISTIC RULE",
            "PRIOR_RUN_IDS": [
                "FDG_STATIC_SPAN",
                "FDG_RELATIVE_MIGRATION",
                "BREAKOUT",
                "VWAP_RECLAIM_REJECTION",
                "FAILED_BREAKDOWN_RECLAIM",
                "V4_RESISTANCE_EPISODE",
                "IOAR",
            ],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV Capture",
            "DECISION_UNIT_USED": "COMPLETE_FULL_CAUSAL_STRATEGY for FDG/V4/new-entry families",
            "ENTRY_ONLY": False,
            "FIXED_EXIT_USED": False,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "CAP_INCLUDED": True,
            "SLOT_RELEASE_INCLUDED": True,
            "CAUSAL_EX_TOP_INCLUDED": True,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "closed; FDG last hand-designed FDG mechanism failed C4",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": True,
            "STATUS": "EXECUTED_AND_CLOSED_UNDER_CURRENT_UNIT",
        },
        {
            "METHOD_ID": "M2",
            "NAME": "FINITE PRECOMMITTED RULE LIBRARY",
            "PRIOR_RUN_IDS": [
                "SIMPLE_FULL_STRATEGY_DISCOVERY_V1",
                "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1",
                "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2",
                "FULL_CAUSAL_MECHANISM_DISCOVERY_V1",
            ],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV",
            "DECISION_UNIT_USED": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "ENTRY_ONLY": False,
            "FIXED_EXIT_USED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "CAP_INCLUDED": True,
            "SLOT_RELEASE_INCLUDED": True,
            "CAUSAL_EX_TOP_INCLUDED": True,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "no robust Full Causal candidate from frozen libraries",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": True,
            "STATUS": "EXECUTED_AND_CLOSED_UNDER_CURRENT_UNIT",
        },
        {
            "METHOD_ID": "M3",
            "NAME": "DATA-FIRST OUTCOME-LABELED MECHANISM DISCOVERY",
            "PRIOR_RUN_IDS": [
                "PROFITABLE_MOVE_MECHANISM_DISCOVERY_V1",
                "DISCOVERY_SEARCH_SPACE_REASSESSMENT_V1",
                "CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1",
            ],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV",
            "DECISION_UNIT_USED": "fixed-horizon H5 raw-signal labels; FULL_CAUSAL_PORTFOLIO_RUN=false",
            "ENTRY_ONLY": True,
            "FIXED_EXIT_USED": False,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "CAP_INCLUDED": False,
            "SLOT_RELEASE_INCLUDED": False,
            "CAUSAL_EX_TOP_INCLUDED": False,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "NO_STABLE_PROFITABLE_MOVE_MECHANISM_FOUND_V1 then DISCOVERY_UNIT_MISMATCH",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": False,
            "STATUS": "EXECUTED_H5_DISCOVERY_UNIT_NOT_FULL_CAUSAL_SELECTION",
        },
        {
            "METHOD_ID": "M4",
            "NAME": "SUPERVISED PREDICTIVE MODEL",
            "PRIOR_RUN_IDS": [
                "E1_X14",
                "entry_target_architecture",
                "multiobjective_feasibility",
                "multioutput_model_probe",
                "temporal_model_probe",
                "raw_event_prediction_probe",
                "joint_feature_architecture",
                "C3_CANONICAL_RETRAIN",
            ],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed historical Capture / Watch50 era; not current Full Causal occupancy",
            "DECISION_UNIT_USED": "ENTRY-quality or future-return / horizon labels",
            "ENTRY_ONLY": True,
            "FIXED_EXIT_USED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "CAP_INCLUDED": False,
            "SLOT_RELEASE_INCLUDED": False,
            "CAUSAL_EX_TOP_INCLUDED": False,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "ENTRY-unit models; not Complete Full Causal at selection",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": False,
            "STATUS": "EXECUTED_ENTRY_UNIT_ONLY",
        },
        {
            "METHOD_ID": "M5",
            "NAME": "DATA-LEARNED THRESHOLD / PARAMETER MODEL",
            "PRIOR_RUN_IDS": ["E1_X14 DESIGN q80", "E1_X15 RPFE", "dynamic_anchor VOLUME_PERCENTILE_MIN"],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV / Design windows",
            "DECISION_UNIT_USED": "ENTRY component / percentile thresholds",
            "ENTRY_ONLY": True,
            "FIXED_EXIT_USED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "CAP_INCLUDED": False,
            "SLOT_RELEASE_INCLUDED": False,
            "CAUSAL_EX_TOP_INCLUDED": False,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": False,
            "RESULT": "thresholds frozen from ENTRY labels; Full Causal selection not used",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": False,
            "STATUS": "EXECUTED_ENTRY_UNIT_ONLY",
        },
        {
            "METHOD_ID": "M6",
            "NAME": "UNSUPERVISED / STATE-CLUSTER DISCOVERY",
            "PRIOR_RUN_IDS": ["mid_hold_state_separability_p4_0"],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "prior mid-hold diagnostics",
            "DECISION_UNIT_USED": "diagnostic cluster/separability; not a strategy",
            "ENTRY_ONLY": True,
            "FIXED_EXIT_USED": False,
            "FULL_CAUSAL_OCCUPANCY_USED": False,
            "CAP_INCLUDED": False,
            "SLOT_RELEASE_INCLUDED": False,
            "CAUSAL_EX_TOP_INCLUDED": False,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": False,
            "RESULT": "not an executable Full Causal strategy method",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": False,
            "STATUS": "DIAGNOSTIC_ONLY_NOT_STRATEGY_METHOD",
        },
        {
            "METHOD_ID": "M7",
            "NAME": "SEQUENCE / TRAJECTORY REPRESENTATION",
            "PRIOR_RUN_IDS": [
                "RECOVERY_SEQUENCE_FULL_STRATEGY_ARCHITECTURE_V1",
                "CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1",
                "am_event_sequence_architecture",
            ],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV",
            "DECISION_UNIT_USED": "Recovery Full Causal; O1/O2/O3 H5 then FCMD Full Causal; AM event sequence ENTRY",
            "ENTRY_ONLY": False,
            "FIXED_EXIT_USED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "CAP_INCLUDED": True,
            "SLOT_RELEASE_INCLUDED": True,
            "CAUSAL_EX_TOP_INCLUDED": True,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "Recovery closed; finite operator expansion closed; AM sequence degraded edge",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": True,
            "STATUS": "EXECUTED_AND_CLOSED_UNDER_CURRENT_UNIT",
        },
        {
            "METHOD_ID": "M8",
            "NAME": "PORTFOLIO-STATE / ADMISSION-AWARE DISCOVERY",
            "PRIOR_RUN_IDS": ["C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2", "FULL_CAUSAL_MECHANISM_DISCOVERY_V1"],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV",
            "DECISION_UNIT_USED": "COMPLETE_FULL_CAUSAL_STRATEGY",
            "ENTRY_ONLY": False,
            "FIXED_EXIT_USED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "CAP_INCLUDED": True,
            "SLOT_RELEASE_INCLUDED": True,
            "CAUSAL_EX_TOP_INCLUDED": True,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "C4 no robust candidate; FCMD occupancy already in unit",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": True,
            "STATUS": "EXECUTED_AND_CLOSED_UNDER_CURRENT_UNIT",
        },
        {
            "METHOD_ID": "M9",
            "NAME": "JOINT ENTRY-EXIT FULL STRATEGY SEARCH",
            "PRIOR_RUN_IDS": [
                "SIMPLE_FULL_STRATEGY_DISCOVERY_V1",
                "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2",
                "E1_X6_TAER",
                "E1_X28_EXECUTABLE_JOINT",
            ],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV / E1 discovery-eval windows",
            "DECISION_UNIT_USED": "SIMPLE_FULL and C1 = Complete Full Causal; E1_X6/X28 = pair executable yen not occupancy",
            "ENTRY_ONLY": False,
            "FIXED_EXIT_USED": False,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "CAP_INCLUDED": True,
            "SLOT_RELEASE_INCLUDED": True,
            "CAUSAL_EX_TOP_INCLUDED": True,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "prewritten Full Causal joint search closed; E1 pair factory not current unit",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": True,
            "STATUS": "EXECUTED_AND_CLOSED_UNDER_CURRENT_UNIT",
        },
        {
            "METHOD_ID": "M10",
            "NAME": "EXECUTION-POLICY SEARCH",
            "PRIOR_RUN_IDS": [
                "SIMPLE_FULL_STRATEGY_DISCOVERY_V1",
                "am_wait5_two_stage",
                "e1_x34a_execution_policy",
                "am_direct_exec_u_development",
            ],
            "ACTUALLY_EXECUTED": True,
            "DATA_USED": "sealed DEV",
            "DECISION_UNIT_USED": "X1/X2/X3 inside SIMPLE_FULL Full Causal; wait5/E1_X34 fillability not occupancy selection",
            "ENTRY_ONLY": False,
            "FIXED_EXIT_USED": True,
            "FULL_CAUSAL_OCCUPANCY_USED": True,
            "CAP_INCLUDED": True,
            "SLOT_RELEASE_INCLUDED": True,
            "CAUSAL_EX_TOP_INCLUDED": True,
            "TEMPORAL_SELECTION_CHECK_INCLUDED": True,
            "RESULT": "execution policies already inside Full Causal grid; standalone wait5 closed as fillability",
            "CURRENTLY_CLOSED": True,
            "METHODOLOGICALLY_EQUIVALENT_TO_CURRENT_UNIT": True,
            "STATUS": "EXECUTED_AND_CLOSED_UNDER_CURRENT_UNIT",
        },
    ]


def e1_model_audit() -> dict[str, Any]:
    return {
        "E1_X5_DECISION_UNIT": "production PBv2 / entry_score_v2 continuation-quality ENTRY; Runtime/paper occupancy, not research Complete Full Causal selection",
        "E1_X6_DECISION_UNIT": "TAER ENTRY-EXIT pair study; canonical E1_X6_NO_ROBUST_ENTRY_EXIT_PAIR; CAP/occupancy/slot-release not the selection unit",
        "E1_X7_X8_X9_DECISION_UNIT": "PFQ independent ENTRY-EXIT joint study; E1_X7_X9_RESEARCH_PROGRAM_CLOSED_NO_ROBUST_STRATEGY",
        "E1_X14_DECISION_UNIT": "board-independent ENTRY components vs LABEL_HORIZONS 30/60/180/300s future-return style labels",
        "ENTRY_EDGE_MASTER_DECISION_UNIT": "event-flow / trade-flow PRIMARY_ALPHA; inventoried CLOSED in information-object audit",
        "E1_X28_DECISION_UNIT": "8254 ENTRY×EXIT executable pairs; Discovery/Evaluation split; pair-level yen, not CAP=5 occupancy selection",
        "PRIOR_MODEL_METHOD_ENTRY_UNIT_ONLY": True,
        "COMPLETE_FULL_CAUSAL_AT_SELECTION_TIME": False,
        "NOTE": "ENTRY-only prior result cannot prove Full Causal data-driven method was tested. That does not auto-revive ML.",
    }


def joint_full_strategy_audit() -> dict[str, Any]:
    return {
        "PREWRITTEN_FULL_CAUSAL_LIBRARY_ALREADY_TESTED": True,
        "PREWRITTEN_IDS": [
            "SIMPLE_FULL_STRATEGY_DISCOVERY_V1",
            "SYSTEMATIC_STATE_TRANSITION_FULL_STRATEGY_V1",
            "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2",
            "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2",
            "FULL_CAUSAL_MECHANISM_DISCOVERY_V1",
            "FDG_STATIC_SPAN",
            "FDG_RELATIVE_MIGRATION",
        ],
        "DATA_LEARNED_FULL_CAUSAL_STRATEGY_ALREADY_TESTED": False,
        "DATA_LEARNED_NOTE": (
            "No prior run learned candidate definitions on TRAIN while judging quality with "
            "Complete Full Causal occupancy economics. FCMD replayed a frozen H5-era library."
        ),
        "BOUNDED_DATA_DRIVEN_EQUIVALENT_PRIOR_RUN_ID": None,
        "FCMD_RELATION": (
            "FULL_CAUSAL_MECHANISM_DISCOVERY_V1 is type A: prewritten candidate library + Full Causal replay. "
            "BASE_QUALIFIED_N=0 on the 42. Not type B data-learned construction."
        ),
        "H5_RELATION": (
            "PROFITABLE_MOVE_MECHANISM_DISCOVERY_V1 and CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1 "
            "are data-first but H5-labeled. Representation NEXT PORTFOLIO_ADMISSION_AWARE_MECHANISM_DISCOVERY_DESIGN_V1 "
            "was not run as a new generator; FCMD evaluated the already-frozen 42 instead."
        ),
    }
