"""MULTI_TOUCH_DAILY_ZONE_1M_PRICE_ACTION_V1. Causal multi-touch daily S/R zones × 1m price action. Discovery only."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "MULTI_TOUCH_DAILY_ZONE_1M_PRICE_ACTION_V1"
ANALYSIS_ID = "MULTI_TOUCH_DAILY_ZONE_1M_PRICE_ACTION_V1"
PARENT_ANALYSIS_ID = "REFERENCE_LEVEL_1M_PRICE_ACTION_DISCOVERY_V1"
PARENT_VERDICT = "REFERENCE_LEVEL_PLAYBOOKS_FOUND_NOT_PROMOTED_V1"
RCA_DEFERRED = "REFERENCE_LEVEL_MECHANISM_RCA_V1"
PDH_CONTROL_ID = "PB_PDH_BREAK"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"

ZONE_HALF_ATR = 0.15
ZONE_HALF_ATR_DIAG = (0.10, 0.20)
LOOKBACK_DAYS = 60
LOOKBACK_DIAG = (20, 120)
REJECTION_CLOSE_FRAC = 0.60
MIN_RANGE_ATR = 0.30
MIN_TOUCHES = 2
ATR_N = 20
REFRACTORY_MIN = 10
PATH_BARS = 30
FAVOR_BPS = 8.0
ENTRY_CUTOFF = "14:50"
SESSION_FLAT = "15:20"
LUNCH_POLICY = "HOLD_THROUGH_LUNCH_RESUME_PM"
TIME_STOP_USED = False
OCCUPANCY = 3
X1_TAX_BPS = 8.0
EVAL_BLOCKS = ("D2", "D3", "D4")
MIN_EVENT_N = 80
MIN_DAY_N = 25
MIN_SYMBOL_N = 10
SEP_PP = 0.05

CASE_NO_INFO = "MULTI_TOUCH_ZONE_NO_INCREMENTAL_INFORMATION_V1"
CASE_PATH = "MULTI_TOUCH_ZONE_PATH_SEPARATION_FOUND_V1"
CASE_PARTICIPATION = "MULTI_TOUCH_ZONE_USEFUL_ONLY_WITH_PARTICIPATION_V1"
CASE_STRATEGY = "MULTI_TOUCH_ZONE_COMPLETE_STRATEGY_DESIGN_EVIDENCE_V1"
CASE_BIND = "MULTI_TOUCH_ZONE_BIND_FAILED_V1"
CASE_ATLAS = "MULTI_TOUCH_ZONE_ATLAS_READY_NO_MECHANISM_V1"

NEXT_STOP_NO_INFO = "STOP_MULTI_TOUCH_ZONE_NO_INCREMENTAL_INFORMATION_V1"
NEXT_RCA_ZONE = "MULTI_TOUCH_ZONE_MECHANISM_RCA_V1"
NEXT_FREEZE = "MULTI_TOUCH_ZONE_CAUSAL_STRATEGY_FREEZE_PRECOMMIT_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"
NEXT_PARTICIPATION = "MULTI_TOUCH_ZONE_PARTICIPATION_CONDITIONING_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_OPENED = False
NEW_PAID_DATA = False
PROMOTED = False
V27_BOLTED = False
IMPLICIT_1130_TRUNCATION = False
RCA_EXECUTED = False
ZONE_WIDTH_SELECTED_BY_PNL = False
EXPIRY_SELECTED_BY_PNL = False
TOUCH_COUNT_SELECTED_BY_PNL = False

assert ANALYSIS_ID == "MULTI_TOUCH_DAILY_ZONE_1M_PRICE_ACTION_V1"
assert PARENT_VERDICT == "REFERENCE_LEVEL_PLAYBOOKS_FOUND_NOT_PROMOTED_V1"
assert RCA_EXECUTED is False
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert OLD_CONFIRMATION_OPENED is False
assert LUNCH_POLICY == "HOLD_THROUGH_LUNCH_RESUME_PM"
assert ZONE_HALF_ATR == 0.15
assert LOOKBACK_DAYS == 60
assert ZONE_WIDTH_SELECTED_BY_PNL is False
assert V27_BOLTED is False
assert PROMOTED is False
