"""FULL_CAUSAL_STRATEGY_ARCHITECTURE_FROM_INFORMATION_OBJECT_V1. FDG price-span geometry."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BOARD_FRESHNESS_SEC,
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_OPTIONAL
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "FULL_CAUSAL_STRATEGY_ARCHITECTURE_FROM_INFORMATION_OBJECT_V1"
PARENT_ID = "DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"
REQUIRED_PARENT_VERDICT = "NEW_CAUSAL_INFORMATION_OBJECT_SELECTED_V1"
REQUIRED_OBJECT_ID = "FULL_DEPTH_GEOMETRY"
REQUIRED_OBJECT_SHA256 = "edec6d0d4a375042fa188be260edca5510e7a945d252cde80be42a4425150b6c"

STRATEGY_ID = "FDG_ASK_SPAN_GT_BID_SPAN_ONSET_X1_Z_SPAN_NORMALIZE"
ARCHITECTURE_CLASS = "FULL_DEPTH_PRICE_GEOMETRY_ASYMMETRY"
TECHNICAL_EXIT_ID = "Z_FDG_SPAN_NORMALIZATION"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
EXEC_EVAL_ID = "X1"
CANARY_ROW_ID = "R2_X1_Z3"

SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
PORTFOLIO_WAIT_SEC = 0.05
BOARD_FRESHNESS_SEC = float(BOARD_FRESHNESS_SEC)
SHARES = int(SHARES)
POSITION_CAP = int(POSITION_CAP)
SAME_SYMBOL_BLOCK = True
PREOPEN_EXECUTION_VALID = False
RANK_PRESENCE_AS_PRIMARY_ALPHA = False
DEPTH_MIGRATION_RULE_USED = False
CURRENT_42_RETUNE = False
MULTI_CANDIDATE_SELECTION = False
LOBO_SELECTION_TRANSFER = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

INTERNAL_HOLE_RATE_MAX = 0.01
SC1_MIN_SIGNAL_N = 40
SC2_MIN_SIGNAL_DAY_N = 8

PRIMARY_DECISION_UNIT = (
    "ENTRY + X1 EXECUTION + TECHNICAL EXIT + CAP=5 + SAME-SYMBOL + OCCUPANCY + "
    "SLOT RELEASE + REENTRY + 11:29 SESSION FLATTEN"
)

CASE_A = "FDG_PRICE_GEOMETRY_DEV_CANDIDATE_FOUND_V1"
CASE_B = "FDG_PRICE_GEOMETRY_STRUCTURAL_COVERAGE_FAIL_V1"
CASE_C = "FDG_PRICE_GEOMETRY_FULL_STRATEGY_COVERAGE_FAIL_V1"
CASE_D = "FDG_PRICE_GEOMETRY_ECONOMIC_FAIL_V1"
CASE_E = "FDG_PRICE_GEOMETRY_NOT_ROBUST_V1"
CASE_SEMANTIC = "FDG_DEPTH_RANK_SEMANTICS_UNRESOLVED_V1"
CASE_INTEGRITY = "FDG_FULL_STRATEGY_INTEGRITY_FAILED_V1"
CASE_PARITY = "FDG_FULL_CAUSAL_ENGINE_PARITY_FAILED_V1"

NEXT_A = "NEW_FULL_STRATEGY_VALIDATION_DESIGN_V1"
NEXT_REMAINING = "FULL_DEPTH_GEOMETRY_REMAINING_MECHANISM_DECISION_V1"
NEXT_SEMANTIC = "FULL_DEPTH_STORAGE_SEMANTICS_RESOLUTION_V1"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

FORBIDDEN_TRANSFORMS = (
    "canonical_depth_imbalance",
    "depth_imb_d3",
    "depth_imb_d5",
    "depth_imb_d10",
    "depth_ratio_3",
    "depth_ratio_5",
    "depth_ratio_10",
    "weighted_depth_imbalance",
    "PBv2 board token",
    "L1-only bid_depth revival",
    "top1 imbalance",
    "net_bid_pressure",
    "net_ask_pressure",
    "imbalance_change",
    "IOAR exact mechanism",
    "numeric weighting search",
    "k-level search",
    "quantity threshold search",
)

assert ANALYSIS_ID == "FULL_CAUSAL_STRATEGY_ARCHITECTURE_FROM_INFORMATION_OBJECT_V1"
assert STRATEGY_ID == "FDG_ASK_SPAN_GT_BID_SPAN_ONSET_X1_Z_SPAN_NORMALIZE"
assert REQUIRED_OBJECT_SHA256 == "edec6d0d4a375042fa188be260edca5510e7a945d252cde80be42a4425150b6c"
assert RANK_PRESENCE_AS_PRIMARY_ALPHA is False
assert DEPTH_MIGRATION_RULE_USED is False
assert CURRENT_42_RETUNE is False
assert PREOPEN_EXECUTION_VALID is False
assert MULTI_CANDIDATE_SELECTION is False
assert POSITION_CAP == 5
assert SHARES == 100
assert abs(float(BOARD_FRESHNESS_SEC) - 5.0) < 1e-12
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert FOLD_BLOCKS["B1"] == ("20260722", "20260728")
assert CANARY_EXPECTED["signal_n"] == 490
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert MIN_PF == 1.10
assert MIN_TOTAL_TRADES == 40
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
assert CANARY_OPTIONAL
