"""Frozen fixed-entry-support candidate. Paper-compatible session engine. No order path."""

CANDIDATE_ID = "EVENT_TIME_IMPULSE_COMPLETE_STRATEGY_FIXED_ENTRY_SUPPORT_CANDIDATE_V1"
PARENT_STRATEGY_ID = "EVENT_TIME_IMPULSE_COMPLETE_STRATEGY_V2"
STATUS = "CURRENT_RESEARCH_SELECTED_CANDIDATE"
VALIDATION = "EXISTING_DATA_VALIDATED"
KNOWN_LIMITATION = "FIXED_SUPPORT_IMPROVEMENT_SYMBOL_CONCENTRATED"
PREVIOUS_BASELINE = "EVENT_TIME_IMPULSE_COMPLETE_STRATEGY_V2"
CAPTURE_FIRST = "20260722"
CAPTURE_LAST = "20260910"
MAX_CONCURRENT = 5
SHARES = 100
RECONFIRM_GAP_SEC = 30.0
SUBMIT = 0
CANCEL = 0
LIVE = 0
