"""BEHAVIOR_GROUP_SEQUENCE_MECHANISM_V1. Prequential group × causal sequence. Discovery only."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "BEHAVIOR_GROUP_SEQUENCE_MECHANISM_V1"
ANALYSIS_ID = "BEHAVIOR_GROUP_SEQUENCE_MECHANISM_V1"
PARENT_ANALYSIS_ID = "ONE_MINUTE_NATIVE_PLAYBOOK_DISCOVERY_V1"
PARENT_VERDICT = "ONE_MINUTE_BEHAVIOR_ATLAS_READY_NO_COMPLETE_PLAYBOOK_V1"
ATLAS_ID = "ONE_MINUTE_BEHAVIOR_ATLAS_V1"
KIND = "BEHAVIOR_GROUP_X_CAUSAL_SEQUENCE"
SEMANTICS = "BAR_START"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_HM1_ANCHOR_SHA256 = "2b26609cce4f14f50c25a77727e2c77fc037261ea74965fa7e195a0c8cfb9e23"
HM1_ID = "HM1_CONTROLLED_PULLBACK_RECLAIM"
HM1_ROLE = "FROZEN_NEAR_THRESHOLD_REFERENCE"
HM1_X0_BPS = 4.69
HM1_X1_BPS = -3.31
X1_TAX_BPS = 8.0
OCCUPANCY = 3
EPISODE_GAP_MIN = 10
LOOKBACK_BARS = 20
PATH_BARS = 30
TIME_STOP_MIN = 20
NO_PROGRESS_MIN = 10
ENTRY_CUTOFF = "14:50"
SESSION_FLAT = "15:20"
FAVOR_BPS = 8.0
MIN_SECTOR_N = 3
LAG_RANK_FRAC = 0.70
LEAD_STREAK_MIN = 5
MATERIAL_BPS = 2.0
MIN_COMPARE_TRADE_N = 40
MIN_PLAYBOOK_TRADE_N = 40
MIN_PLAYBOOK_DAY_N = 20
MIN_PLAYBOOK_SYMBOL_N = 5
MIN_CONTINUATION_SYMBOL_N = 3
MIN_PROFILE_EPISODE_N = 20
GROUP_SCORE_FLOOR = 0.45
GROUP_SCORE_STRONG = 0.80
EVAL_BLOCKS = ("D2", "D3", "D4")
TRAIN_BLOCK = "D1"

CASE_EXECUTABLE = "BEHAVIOR_GROUP_EXECUTABLE_MECHANISM_FOUND_V1"
CASE_IMPROVES = "BEHAVIOR_GROUP_CONDITIONING_MATERIAL_FREEZE_DEFS_V1"
CASE_DESCRIPTIVE = "ATLAS_DESCRIPTIVE_NOT_STRATEGY_DISCRIMINATIVE_V1"
CASE_BIND = "BEHAVIOR_GROUP_SEQUENCE_BIND_FAILED_V1"

NEXT_FREEZE = "FREEZE_GROUP_MECHANISM_DEFINITIONS_V1"
NEXT_STOP_SPLIT = "STOP_NATIVE_GROUP_SPLITTING_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_USED_TO_DESIGN = False
HM1_TUNED = False
PURCHASE_REQUESTED = False
YFINANCE_USED = False
ENTRY_RULES_OPTIMIZED = False
DATACUBE_PURCHASED = False
KRX_PURCHASED = False
TWSE_PURCHASED = False
DATABENTO_PURCHASED = False
NEW_PAID_DATA = False
FIVE_MINUTE_GRID = False
FULL_DISCOVERY_GROUP_LEAKAGE = False

ZERO_TRADE_CAUSE = (
    "PB_NATIVE_LAG_CATCHUP required simultaneous lagging + leader impulse in the prior 1-5 minutes "
    "+ target impulse_up on the same bar; episode classify() then ranked pullback/compression/"
    "vol-expand/impulse-pause ahead of LAG_THEN_CATCHUP, so the sequence never populated. "
    "Implementation mismatch, not an economic null."
)

assert ANALYSIS_ID == "BEHAVIOR_GROUP_SEQUENCE_MECHANISM_V1"
assert PARENT_VERDICT == "ONE_MINUTE_BEHAVIOR_ATLAS_READY_NO_COMPLETE_PLAYBOOK_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert HM1_TUNED is False
assert NEW_PAID_DATA is False
assert FIVE_MINUTE_GRID is False
assert KABU_50_APPLIED is False
assert FULL_DISCOVERY_GROUP_LEAKAGE is False
assert X1_TAX_BPS == 8.0
assert OCCUPANCY == 3
assert MATERIAL_BPS == 2.0
