"""EXISTING_DATA_ENTRY_ALIGNED_FULL_CAUSAL_LOGIC_COMPLETION_V1. Thesis-aligned EXIT. LEGACY_DEV only."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_OPTIONAL
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "EXISTING_DATA_ENTRY_ALIGNED_FULL_CAUSAL_LOGIC_COMPLETION_V1"
CANARY_ROW_ID = "R2_X1_Z3"
CANARY_ID = "RECOVERY_R2_X1_Z3"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
EXEC_EVAL_ID = "X1"
SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
PORTFOLIO_WAIT_SEC = 0.05
BOARD_FRESHNESS_SEC = 5.0

STATE_IDS = (
    "S_MA_TREND_UP",
    "S_BB_ABOVE_MID",
    "S_RCI_ABOVE_NEG80",
    "S_VOL_CONFIRM_1M",
    "S_CLOSE_ABOVE_VWAP",
)
STRUCTURAL_IDS = ("S_MA_TREND_UP", "S_BB_ABOVE_MID", "S_CLOSE_ABOVE_VWAP")
RCI_ID = "S_RCI_ABOVE_NEG80"
VOL_ID = "S_VOL_CONFIRM_1M"

RAW_ENTRY_N = 25
PERSIST_N = 5
HANDOFF_N = 20
STRUCTURALLY_INELIGIBLE_N = 1
SELECTABLE_N = 24

CASE_A = "ENTRY_ALIGNED_COMPLETE_LOGIC_FOUND_V1"
CASE_B = "ENTRY_ALIGNED_STATE_TRANSITION_NOT_ROBUST_V1"
CASE_C = "ENTRY_ALIGNED_STATE_TRANSITION_ECONOMIC_FAIL_V1"
CASE_PARITY = "ENTRY_ALIGNED_ENGINE_PARITY_FAILED_V1"
NEXT_A = "FROZEN_LOGIC_EXISTING_DATA_CONFIRMATION_V1"
NEXT_BC = "NEXT_COMPLETE_STRATEGY_ARCHITECTURE_CONSTRUCTION_V1"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

MBO_WORK_THIS_RUN = False
JPX_ID_WORK = False
JPX_SPEC_WORK = False
PROVIDER_CONTACT = False
EXTERNAL_DATA_READ = False
LEGACY_DEV_CONSTRUCTION_ONLY = True
Z3_CANDIDATE_EXIT = False
UNIVERSAL_EXIT = False
EXIT_CROSS_PRODUCT = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False
POST_RESULT_ENTRY_CHANGE = False
POST_RESULT_EXIT_CHANGE = False
POST_RESULT_ROLE_CHANGE = False

assert ANALYSIS_ID == "EXISTING_DATA_ENTRY_ALIGNED_FULL_CAUSAL_LOGIC_COMPLETION_V1"
assert tuple(DEVELOPMENT_DAYS) == (
    "20260722",
    "20260728",
    "20260729",
    "20260730",
    "20260731",
    "20260803",
    "20260804",
    "20260805",
    "20260806",
    "20260807",
)
assert int(RAW_ENTRY_N) == 25
assert int(SELECTABLE_N) == 24
assert Z3_CANDIDATE_EXIT is False
assert UNIVERSAL_EXIT is False
assert EXIT_CROSS_PRODUCT is False
assert MBO_WORK_THIS_RUN is False
assert SIZING is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert int(POSITION_CAP) == 5
assert int(SHARES) == 100
assert tuple(SESSION_FLATTEN_HM) == (11, 29)
assert float(MIN_PF) == 1.10
assert int(MIN_TOTAL_TRADES) == 40
assert int(MIN_TRADING_DAYS_WITH_FILL) == 8
assert float(MIN_TRADES_PER_DAY) == 4.0
assert MAX_RESEARCH_DATE == "20260807"
assert len(FOLD_BLOCKS) == 5
assert CANARY_EXPECTED["signal_n"] == 490
assert CANARY_EXPECTED["trade_n"] == 334
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
