"""Sector breadth/dispersion precommit V1.3. Non-overlapping future offset placebo only. No beta rerun."""
from __future__ import annotations

PROGRAM_ID = "CAUSAL_DRIVER_PB1_FOUNDATION"
PRECOMMIT_ID = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_V1_3"
ANALYSIS_ID = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_V1_3"

CASE_READY = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_READY_V1_3"
CASE_BLOCKED = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_BLOCKED_V1_3"
NEXT_RUN = "RUN_SECTOR_BREADTH_DISPERSION_NONOVERLAP_OFFSET_CORRECTION_V1"
NEXT_RESOLVE = "RESOLVE_NONOVERLAPPING_OFFSET_PLACEBO_CONTRACT_V1"

PARENT_PRECOMMIT_ID = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_V1_2"
PARENT_PRECOMMIT_SHA256 = "d93a65804cd316462deeec01a0723b8565bbf2b4504e54244059ccac75c73598"
CANDIDATE_LIST_SHA256 = "848b0d72a748a0705af5079038f90db9c057068f8a1a4ba7f8989fad046e3985"

INVALIDATION_VERDICT = "SECTOR_BREADTH_DISPERSION_TECHNICALLY_INVALIDATED_BY_OVERLAPPING_FUTURE_OFFSET_PLACEBO_V1"
INVALIDATION_REASON = "FUTURE_DRIVER_WINDOW_OVERLAPS_TARGET_OUTCOME_WINDOW"
OLD_PUBLISHED_VERDICT = "SECTOR_BREADTH_DISPERSION_CAUSAL_LEAD_NOT_FOUND_V2"
OLD_PUBLISHED_NEXT = "REASSESS_NEW_CAUSAL_INFORMATION_ACQUISITION_V2"
OLD_DISCOVERY_CLASSIFICATION = "INVALID_FOR_FINAL_CAUSAL_DRIVER_DECISION"
REASON_RAW = "NO_C1_CONFIRMED_ROBUST_CANDIDATE"
DECISION_STATUS = "C1_CONFIRMED_CANDIDATES_PENDING_VALID_NONOVERLAPPING_OFFSET_PLACEBO"

EXPECTED_C1_CONFIRMED_N = 8
EXPECTED_DEV_CANDIDATE_N = 11
OLD_FUTURE_OFFSETS = (1, 3, 5)
CAUSAL_OFFSETS = (-5, -3, -1, 0)
OFFSET_ABS_RATIO = 0.50
SESSION_OPEN = "09:00"
SESSION_CLOSE = "11:30"

FAIL_VERDICT_IF_ALL_OFFSET_FAIL = "SECTOR_BREADTH_DISPERSION_CAUSAL_LEAD_NOT_FOUND_V3"
FAIL_REASON_IF_ALL_OFFSET_FAIL = "ALL_C1_CONFIRMED_CANDIDATES_FAILED_NONOVERLAPPING_OFFSET_PLACEBO"
FAIL_NEXT_IF_ALL_OFFSET_FAIL = "REASSESS_NEW_CAUSAL_INFORMATION_ACQUISITION_V2"
PASS_VERDICT = "SECTOR_BREADTH_DISPERSION_CAUSAL_LEAD_FOUND_V1"
PASS_NEXT = "PRECOMMIT_SECTOR_STATE_SYMBOL_TRANSMISSION_V1"
