"""FULL_CAUSAL_MECHANISM_DISCOVERY_V1. Complete Full Causal strategies from frozen O1/O2/O3."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BOARD_FRESHNESS_SEC,
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_OPTIONAL
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "FULL_CAUSAL_MECHANISM_DISCOVERY_V1"
PARENT_ID = "CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1"
REQUIRED_PARENT_VERDICT = "DISCOVERY_UNIT_MISMATCH_PORTFOLIO_ADMISSION_MATTERS_V1"
REQUIRED_LIBRARY_SHA256 = "e6d3db92b00d18ae6cd107bc23da2b0f425a147a6fe5d8adff876fc6dc158c1e"
CANDIDATE_MECHANISM_N = 42
O1_N = 12
O2_N = 27
O3_N = 3

CANARY_ROW_ID = "R2_X1_Z3"
CANARY_ID = "RECOVERY_R2_X1_Z3"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
EXEC_EVAL_ID = "X1"
SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
PORTFOLIO_WAIT_SEC = 0.05
BOARD_FRESHNESS_SEC = float(BOARD_FRESHNESS_SEC)
SHARES = int(SHARES)
POSITION_CAP = int(POSITION_CAP)
SAME_SYMBOL_BLOCK = True

EXIT_O1 = "Z_O1_STATE_INVALIDATION"
EXIT_O2 = "Z_O2_HANDOFF_STATE_INVALIDATION"
EXIT_O3 = "Z_O3_RECLAIM_LEVEL_FAILURE"

PRIMARY_DECISION_UNIT = "COMPLETE_FULL_CAUSAL_STRATEGY"
RAW_SIGNAL_SCREENING_AS_PRIMARY_DECISION_UNIT = False
ADMISSION_COMPONENT_CAUSAL_ATTRIBUTION_CLAIMED = False
CAP_ALONE_CAUSES_EDGE = False
EXIT_SEARCH = False
ENTRY_EXIT_GRID = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False
THRESHOLD_SEARCH = False
HORIZON_SEARCH = False
TIMEFRAME_SEARCH = False
POST_RESULT_MECHANISM_CHANGE = False
POST_RESULT_EXIT_CHANGE = False
POST_RESULT_CAP_CHANGE = False
POST_RESULT_THRESHOLD_CHANGE = False
POST_RESULT_TIMEFRAME_CHANGE = False
POST_RESULT_CANDIDATE_ADD = False
MECHANISM_LIBRARY_CHANGED = False
NEW_MECHANISM_GENERATED = False
NEW_MECHANISM_OUTCOMES_PREVIOUSLY_READ = False

CASE_A = "FULL_CAUSAL_DISCOVERED_STRATEGY_CANDIDATE_FOUND_V1"
CASE_B = "FULL_CAUSAL_MECHANISM_DISCOVERY_SELECTION_UNSTABLE_V1"
CASE_C = "FULL_CAUSAL_MECHANISM_DISCOVERY_NO_ROBUST_CANDIDATE_V1"
CASE_D = "FULL_CAUSAL_DISCOVERY_ONLY_CLOSED_EDGE_FOUND_V1"
CASE_INTEGRITY = "FULL_CAUSAL_DISCOVERY_INTEGRITY_FAILED"
CASE_PARITY = "FULL_CAUSAL_DISCOVERY_ENGINE_PARITY_FAILED"
NEXT_A = "NEW_FULL_STRATEGY_VALIDATION_DESIGN_V1"
NEXT_B = "DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

PIN_R2_RAW_SIGNAL_N = 490
PIN_R2_RAW_H5_MEAN = -235.48319327731093
PIN_R2_TRADE_N = 334
PIN_R2_EXECUTED_H5_MEAN = 329.96913580246917
PIN_R2_DEV_TOTAL_PNL = 341340
PIN_P2_RAW_SIGNAL_N = 77
PIN_P2_RAW_H5_MEAN = 2955.135135135135
PIN_P2_TRADE_N = 75
PIN_P2_EXECUTED_H5_MEAN = 3065.0
PIN_P2_DEV_TOTAL_PNL = 220580

OPERATOR_RANK = {"O1_PERSIST_NEXT": 0, "O2_HANDOFF_NEXT": 1, "O3_RECLAIM_ACCEPT_NEXT": 2}

assert ANALYSIS_ID == "FULL_CAUSAL_MECHANISM_DISCOVERY_V1"
assert REQUIRED_PARENT_VERDICT == "DISCOVERY_UNIT_MISMATCH_PORTFOLIO_ADMISSION_MATTERS_V1"
assert REQUIRED_LIBRARY_SHA256 == "e6d3db92b00d18ae6cd107bc23da2b0f425a147a6fe5d8adff876fc6dc158c1e"
assert int(CANDIDATE_MECHANISM_N) == 42
assert RAW_SIGNAL_SCREENING_AS_PRIMARY_DECISION_UNIT is False
assert ADMISSION_COMPONENT_CAUSAL_ATTRIBUTION_CLAIMED is False
assert CAP_ALONE_CAUSES_EDGE is False
assert EXIT_SEARCH is False
assert ENTRY_EXIT_GRID is False
assert SIZING is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert MECHANISM_LIBRARY_CHANGED is False
assert NEW_MECHANISM_GENERATED is False
assert int(POSITION_CAP) == 5
assert int(SHARES) == 100
assert abs(float(BOARD_FRESHNESS_SEC) - 5.0) < 1e-12
assert tuple(SESSION_FLATTEN_HM) == (11, 29)
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert MIN_PF == 1.10
assert MIN_TOTAL_TRADES == 40
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
assert CANARY_EXPECTED["signal_n"] == PIN_R2_RAW_SIGNAL_N
assert CANARY_EXPECTED["trade_n"] == PIN_R2_TRADE_N
assert abs(float(CANARY_EXPECTED["PnL"]) - float(PIN_R2_DEV_TOTAL_PNL)) < 1e-6
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
