"""PARTICIPATION_ONSET_FULL_STRATEGY_V1. Frozen T1 activity onset + X1 Ask + Z3/ZP/ZH. DEV-only Full Causal."""
from __future__ import annotations

from research.dynamic_anchor_p2_0b import MIN_RS_UNIVERSE, VOLUME_PERCENTILE_MIN
from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    LODO_TOP3_MIN,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)

ANALYSIS_ID = "PARTICIPATION_ONSET_FULL_STRATEGY_V1"
RECOVERY_CLOSED = True
PRIOR_RECOVERY_VERDICT = "RECOVERY_SEQUENCE_FULL_STRATEGY_NO_ROBUST_CANDIDATE"
ENTRY_IDS = ("P1",)
EXEC_IDS = ("X1",)
EXIT_IDS = ("Z3", "ZP", "ZH")
CANDIDATE_N = 3
CANDIDATE_IDS = (
    "P1_X1_Z3",
    "P1_X1_ZP",
    "P1_X1_ZH",
)
ENTRY_NAMES = {"P1": "P1_T1_ACTIVITY_ONSET"}
EXEC_NAMES = {"X1": "X1_IMMEDIATE_ASK"}
EXIT_NAMES = {
    "Z3": "Z3_PRICE_WEAKNESS",
    "ZP": "ZP_PARTICIPATION_LOSS",
    "ZH": "ZH_HYBRID_FIRST_FIRE",
}
VOLUME_PERCENTILE_THRESHOLD = float(VOLUME_PERCENTILE_MIN)
ABOVE_VWAP_ENTRY_FILTER = False
INDEPENDENT_ALPHA_CLAIM = False
RPFE_EPISODE_INDEPENDENCE_CLAIM = False
THRESHOLD_RETUNED = False
BOARD_FRESHNESS_SEC = 5.0
MIN_QTY = 100.0
WAIT_SEC = 0.05
PROSPECTIVE_HARVEST_SUSPENDED = True
TRUE_OOS = False
CERTIFIED = False
STRESS_OPENED_THIS_RUN = False
SIZING = False
RETUNE = False
GRID_SEC = 10

PRIOR_RECOVERY = {
    "ANALYSIS_ID": "RECOVERY_SEQUENCE_FULL_STRATEGY_ARCHITECTURE_V1",
    "candidate_n": 6,
    "coverage_pass_n": 6,
    "economic_pass_n": 0,
    "VERDICT": PRIOR_RECOVERY_VERDICT,
    "CLOSED": True,
    "all_causal_ex_top1_negative": True,
}

CASE_A = "PARTICIPATION_ONSET_FULL_STRATEGY_DEV_SUPPORTED"
CASE_B = "PARTICIPATION_ONSET_FULL_STRATEGY_NO_ROBUST_CANDIDATE"
CASE_C = "PARTICIPATION_ONSET_SELECTION_UNSTABLE"
CASE_D = "PARTICIPATION_ONSET_COVERAGE_FAILED"
CASE_E = "PARTICIPATION_ONSET_INTEGRITY_FAILED"

assert ANALYSIS_ID == "PARTICIPATION_ONSET_FULL_STRATEGY_V1"
assert RECOVERY_CLOSED is True
assert PRIOR_RECOVERY["CLOSED"] is True
assert len(CANDIDATE_IDS) == int(CANDIDATE_N) == 3
assert CANDIDATE_IDS == ("P1_X1_Z3", "P1_X1_ZP", "P1_X1_ZH")
assert VOLUME_PERCENTILE_THRESHOLD == 0.6486486486486487
assert MIN_RS_UNIVERSE == 20
assert ABOVE_VWAP_ENTRY_FILTER is False
assert INDEPENDENT_ALPHA_CLAIM is False
assert RPFE_EPISODE_INDEPENDENCE_CLAIM is False
assert THRESHOLD_RETUNED is False
assert RETUNE is False
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert STRESS_OPENED_THIS_RUN is False
assert SIZING is False
assert LODO_TOP3_MIN == 6
assert MIN_PF == 1.10
assert MIN_TOTAL_TRADES == 40
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
assert TRUE_OOS is False
assert CERTIFIED is False
assert PROSPECTIVE_HARVEST_SUSPENDED is True
assert GRID_SEC == 10
assert FORBIDDEN_INPUT_DAYS
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert DEVELOPMENT_DAYS
assert CASE_A and CASE_B and CASE_C and CASE_D and CASE_E
