"""FIXED_UNIVERSE_HISTORICAL_RESEARCH_FOUNDATION_V1.

Phase 0 only: Fixed Universe design, data-provider audit, time alignment,
research/validation split. No strategy search. No PnL. No purchase.
20260914 live capture / Day2 frozen confirmation unchanged.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import (
    TRADING_DATE as LIVE_TRADING_DATE,
)

ANALYSIS_ID = "FIXED_UNIVERSE_HISTORICAL_RESEARCH_FOUNDATION_V1"
PARENT_ID = "PRIMARY_RESEARCH_TRACK_REDIRECT_V1"
KIND = "FOUNDATION_AUDIT_ONLY"
PRIMARY_RESEARCH_TRACK = True
PHASE = 0

TARGET_UNIVERSE_MIN = 40
TARGET_UNIVERSE_MAX = 50
RECOMMENDED_STOCK_N = 45
UNIVERSE_FROZEN = False
PANEL_CONDITIONED = True
CLAIM_RETROSPECTIVE_UNIVERSE_SELECTABILITY = False

HISTORICAL_MIN_YEARS = 1
HISTORICAL_PREFERRED_YEARS = 2
EQUITY_MINUTE_HISTORY_YEARS_OFFICIAL = 2

CASE_READY = "FIXED_UNIVERSE_HISTORICAL_RESEARCH_FOUNDATION_READY_V1"
CASE_STOCK_BLOCKED = "HISTORICAL_STOCK_MINUTE_SOURCE_BLOCKED_V1"
CASE_PARTIAL_EXTERNAL = "HISTORICAL_FOUNDATION_PARTIAL_EXTERNAL_CONTEXT_V1"
NEXT_FREEZE = "FREEZE_FIXED_DAYTRADE_UNIVERSE_V1"
NEXT_PANEL = "BUILD_ALIGNED_HISTORICAL_PANEL_V1"
NEXT_MECHANISM = "CAUSE_FIRST_MECHANISM_DISCOVERY_V1"

STRATEGY_SEARCH_STARTED = False
PROFIT_OPTIMIZATION = False
LARGE_GRID_ALLOWED = False
NEW_ENTRY_CREATED = False
NEW_EXIT_CREATED = False
NEW_MODEL_CREATED = False
NEW_THRESHOLD_CREATED = False
DATA_PURCHASED = False
HISTORICAL_DATA_DOWNLOADED = False
CONTINUOUS_FUTURES_AUTOSPLICED = False
SAME_BAR_CLOSE_ENTRY_ALLOWED = False
RANDOM_SPLIT_PRIMARY = False
TEST_SET_REUSE_AFTER_PARAM_CHANGE = False

LIVE_20260914_CHANGED = False
DAY1_MINING_REOPENED = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
CAPTURE_CHANGED = False
ENTRY = False
EXIT = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False
SUBMIT_N = 0
CANCEL_N = 0
LIVE_ORDER_N = 0

LIVE_REPOSITIONING = "PROSPECTIVE_CONTEXT_VALIDATION_TAPE"
LIVE_REPOSITIONING_SCRIPT_CHANGE = False

FACTOR_LAYERS = (
    "GLOBAL_DRIVER",
    "JAPAN_MARKET_REGIME",
    "SECTOR_RESPONSE",
    "STOCK_STATE",
    "TECHNICAL_TRIGGER",
)
FUTURE_STRATEGY_FAMILIES = (
    "A_TREND_CONTINUATION",
    "B_BREAKOUT",
    "C_PULLBACK_RECLAIM",
    "D_REVERSAL",
    "E_RELATIVE_STRENGTH",
)

RCI_PERIODS = (9, 26)
RSI_PERIODS = (14,)
SMA_PERIODS = (5, 25)
EMA_PERIODS = (9, 21)
BB_PERIOD = 20
BB_SIGMA = 2.0
SAME_CLOCK_BASELINE_N_DAYS = (10, 20)
UNIVERSE_REVIEW_CADENCE = ("quarterly", "semiannual")

assert ANALYSIS_ID == "FIXED_UNIVERSE_HISTORICAL_RESEARCH_FOUNDATION_V1"
assert PHASE == 0
assert STRATEGY_SEARCH_STARTED is False
assert PROFIT_OPTIMIZATION is False
assert UNIVERSE_FROZEN is False
assert PANEL_CONDITIONED is True
assert CLAIM_RETROSPECTIVE_UNIVERSE_SELECTABILITY is False
assert SAME_BAR_CLOSE_ENTRY_ALLOWED is False
assert CONTINUOUS_FUTURES_AUTOSPLICED is False
assert RANDOM_SPLIT_PRIMARY is False
assert TEST_SET_REUSE_AFTER_PARAM_CHANGE is False
assert DATA_PURCHASED is False
assert HISTORICAL_DATA_DOWNLOADED is False
assert LIVE_20260914_CHANGED is False
assert DAY1_MINING_REOPENED is False
assert RUNTIME_CHANGED is False
assert PAPER_CHANGED is False
assert CAPTURE_CHANGED is False
assert ENTRY is False and EXIT is False
assert int(SUBMIT_N) == 0 and int(CANCEL_N) == 0 and int(LIVE_ORDER_N) == 0
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert LIVE_REPOSITIONING_SCRIPT_CHANGE is False
assert int(RECOMMENDED_STOCK_N) == 45
assert TARGET_UNIVERSE_MIN <= RECOMMENDED_STOCK_N <= TARGET_UNIVERSE_MAX
assert RCI_PERIODS == (9, 26)
assert SAME_CLOCK_BASELINE_N_DAYS == (10, 20)
assert FACTOR_LAYERS[0] == "GLOBAL_DRIVER"
assert FACTOR_LAYERS[-1] == "TECHNICAL_TRIGGER"
