"""Official-first data provider audit. No purchase. No download. No fake readiness."""
from __future__ import annotations

from typing import Any

# Status:
# CONFIRMED = public official spec inspected
# CANDIDATE = usable after contract/sample confirmation
# GAP = not 1-minute causal-ready from inspected official source
# UNKNOWN_FIELD = field exists but semantics incomplete


def source_rows() -> list[dict[str, Any]]:
    return [
        {
            "instrument": "TSE_EQUITY_MINUTE",
            "provider": "J-Quants API V2",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": True,
            "historical_depth": "past_2_years",
            "timestamp_timezone": "JST_implied_session_clock",
            "dst_handling": "Japan_no_DST",
            "delay": "daily_delivery_not_realtime",
            "price_type": "unadjusted_OHLCV_plus_Va",
            "api_csv": "API_/v2/equities/bars/minute_and_CSV_bulk",
            "cost": "Light_1650_plus_addon_5500_JPY_month_tax_in",
            "license": "retail_individual_no_redistribution",
            "causal_research_usability": "YES_AFTER_TIME_FIELD_CONFIRM",
            "status": "CONFIRMED_SOURCE_PARTIAL_TIMESTAMP",
            "notes": (
                "JPX 2026-01-19: equity minute/tick add-on, derivatives excluded. "
                "Empty minutes omitted. Time=HH:mm. Adj fields not in minute endpoint; "
                "use daily AdjFactor. Not a realtime ENTRY source."
            ),
            "url": "https://jpx-jquants.com/en/spec/eq-bars-minute",
        },
        {
            "instrument": "TSE_EQUITY_TICK",
            "provider": "J-Quants API V2 bulk CSV",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": False,
            "historical_depth": "past_2_years",
            "timestamp_timezone": "JST_execution_HHMMSS_ffffff",
            "dst_handling": "Japan_no_DST",
            "delay": "daily_delivery_not_realtime",
            "price_type": "as_traded_print",
            "api_csv": "CSV_only_equities/trades",
            "cost": "same_5500_JPY_month_addon",
            "license": "retail_individual_no_redistribution",
            "causal_research_usability": "YES_FOR_BAR_SEMANTIC_AUDIT",
            "status": "CONFIRMED",
            "notes": "Use to confirm whether minute Time is bar start. Not ENTRY source.",
            "url": "https://jpx-jquants.com/en/spec/eq-trades",
        },
        {
            "instrument": "TSE_EQUITY_DAILY_ADJ",
            "provider": "J-Quants API V2",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": False,
            "historical_depth": "plan_dependent_Light_5y_Standard_10y_Premium_20y",
            "timestamp_timezone": "JST_date",
            "dst_handling": "Japan_no_DST",
            "delay": "EOD",
            "price_type": "unadjusted_and_adjusted_plus_AdjFactor",
            "api_csv": "API_/v2/equities/bars/daily_and_CSV",
            "cost": "included_in_plan",
            "license": "retail_individual_no_redistribution",
            "causal_research_usability": "YES_FOR_CORPORATE_ACTIONS",
            "status": "CONFIRMED",
            "notes": "Minute series has no Adj*. Apply CumAdj from daily.",
            "url": "https://jpx-jquants.com/en/spec/eq-bars-daily/adj",
        },
        {
            "instrument": "TSE_OSE_CALENDAR",
            "provider": "J-Quants API V2",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": False,
            "historical_depth": "from_2008_plan_dependent",
            "timestamp_timezone": "JST_date",
            "dst_handling": "Japan_no_DST",
            "delay": "calendar",
            "price_type": "na",
            "api_csv": "API_/v2/markets/calendar_CSV_even_on_Free",
            "cost": "included",
            "license": "retail_individual",
            "causal_research_usability": "YES",
            "status": "CONFIRMED",
            "notes": "HolDiv includes OSE holiday trading. Canonical calendar source.",
            "url": "https://jpx-jquants.com/en/spec/mkt-cal",
        },
        {
            "instrument": "NK225_FUTURES_1MIN",
            "provider": "J-Quants DataCube",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": True,
            "historical_depth": "from_201201_monthly_files",
            "timestamp_timezone": "JST_Interval_Time_HHMM",
            "dst_handling": "Japan_no_DST",
            "delay": "historical_CSV_monthly_plus_Tplus_lag_to_5th_bd",
            "price_type": "per_contract_month_OHLC_volume_VWAP",
            "api_csv": "CSV_DataCube_future_ohlc_minute_18",
            "cost": "personal_220_JPY_per_month_of_data_tax_in",
            "license": "personal_academic_or_corporate_self_use_no_redistrib_unless_paid",
            "causal_research_usability": "YES_NO_AUTOSPLICE",
            "status": "CONFIRMED",
            "notes": (
                "Per-contract. Session_ID 999 day / 003 night. "
                "Do not auto-build continuous contract. Empty minutes omitted. "
                "Not in J-Quants API equity minute add-on."
            ),
            "url": "https://dc.jpx-jquants.com/ja/product/future_ohlc_minute_18_YYYYMM",
        },
        {
            "instrument": "NK225MINI_FUTURES_1MIN",
            "provider": "J-Quants DataCube",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": True,
            "historical_depth": "from_201201",
            "timestamp_timezone": "JST_Interval_Time_HHMM",
            "dst_handling": "Japan_no_DST",
            "delay": "historical_CSV",
            "price_type": "per_contract_month",
            "api_csv": "CSV_DataCube_future_ohlc_minute_19",
            "cost": "personal_220_JPY_per_month_of_data",
            "license": "personal_academic",
            "causal_research_usability": "YES_ALIGNABLE_WITH_LIVE_CAPTURE",
            "status": "CONFIRMED",
            "notes": "Preferred if matching 20260914 live NK225mini capture. Still not continuous.",
            "url": "https://dc.jpx-jquants.com/ja/product/future_ohlc_minute_19_YYYYMM",
        },
        {
            "instrument": "TOPIX_FUTURES_1MIN",
            "provider": "J-Quants DataCube",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": True,
            "historical_depth": "from_201403",
            "timestamp_timezone": "JST_Interval_Time_HHMM",
            "dst_handling": "Japan_no_DST",
            "delay": "historical_CSV",
            "price_type": "per_contract_month",
            "api_csv": "CSV_DataCube_future_ohlc_minute_05",
            "cost": "personal_220_JPY_per_month_of_data",
            "license": "personal_academic",
            "causal_research_usability": "YES_NO_AUTOSPLICE",
            "status": "CONFIRMED",
            "notes": "Aligns with live TOPIX futures slot. Night session via Session_ID.",
            "url": "https://dc.jpx-jquants.com/ja/product/future_ohlc_minute_05_YYYYMM",
        },
        {
            "instrument": "JGB_FUTURES_1MIN",
            "provider": "J-Quants DataCube",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": True,
            "historical_depth": "from_201403",
            "timestamp_timezone": "JST_Interval_Time_HHMM",
            "dst_handling": "Japan_no_DST",
            "delay": "historical_CSV",
            "price_type": "per_contract_month",
            "api_csv": "CSV_DataCube_future_ohlc_minute_01",
            "cost": "personal_220_JPY_per_month_of_data",
            "license": "personal_academic",
            "causal_research_usability": "YES_JAPAN_RATES_PROXY",
            "status": "CONFIRMED",
            "notes": "Japan rates 1-minute official path. Cash JGB 1-min not used.",
            "url": "https://dc.jpx-jquants.com/ja/product/future_ohlc_minute_01_YYYYMM",
        },
        {
            "instrument": "NK225_VI_FUTURES_1MIN",
            "provider": "J-Quants DataCube",
            "official_or_vendor": "official_JPXI",
            "one_minute_available": True,
            "historical_depth": "from_201202",
            "timestamp_timezone": "JST_Interval_Time_HHMM",
            "dst_handling": "Japan_no_DST",
            "delay": "historical_CSV",
            "price_type": "per_contract_month",
            "api_csv": "CSV_DataCube_future_ohlc_minute_15",
            "cost": "personal_220_JPY_per_month_of_data",
            "license": "personal_academic",
            "causal_research_usability": "YES_JAPAN_VOL_PROXY",
            "status": "CONFIRMED",
            "notes": "Japan vol context. Do not treat as US VIX.",
            "url": "https://dc.jpx-jquants.com/ja/product/future_ohlc_minute_15_YYYYMM",
        },
        {
            "instrument": "USDJPY",
            "provider": "Dukascopy_historical_ticks_bars",
            "official_or_vendor": "vendor",
            "one_minute_available": True,
            "historical_depth": "multi_year",
            "timestamp_timezone": "store_as_UTC_then_convert_JST",
            "dst_handling": "MUST_USE_UTC_NOT_BROKER_DST",
            "delay": "historical",
            "price_type": "FX_bid_ask_or_mid_vendor",
            "api_csv": "tick_or_m1_export",
            "cost": "free_export_typical_license_check_required",
            "license": "vendor_terms_research_use_check",
            "causal_research_usability": "CONDITIONAL_UTC_ONLY",
            "status": "CANDIDATE",
            "notes": (
                "No official BOJ 1-minute. Reject if timestamps cannot be unified to UTC. "
                "Do not use Yahoo daily as 1-minute FX."
            ),
            "url": "https://www.dukascopy.com/",
        },
        {
            "instrument": "ES_NQ_FUTURES_1MIN",
            "provider": "Databento_GLBX.MDP3",
            "official_or_vendor": "vendor_CME_derived",
            "one_minute_available": True,
            "historical_depth": "multi_year",
            "timestamp_timezone": "UTC_nanosecond",
            "dst_handling": "exchange_schedule_in_UTC_no_naive_ET",
            "delay": "historical_or_licensed_live",
            "price_type": "ohlcv-1m_plus_trades_optional",
            "api_csv": "API_ohlcv-1m",
            "cost": "metered_USD_get_cost_before_pull_125_credit_typical",
            "license": "Databento_plus_exchange_constraints_historical_no_monthly_license",
            "causal_research_usability": "YES_AFTER_TS_EVENT_MAP",
            "status": "CANDIDATE",
            "notes": "US risk/tech context. Confirm ohlcv-1m ts_event vs interval start before join.",
            "url": "https://databento.com/docs/quickstart",
        },
        {
            "instrument": "WTI_CL_FUTURES_1MIN",
            "provider": "Databento_GLBX.MDP3",
            "official_or_vendor": "vendor_CME_derived",
            "one_minute_available": True,
            "historical_depth": "multi_year",
            "timestamp_timezone": "UTC_nanosecond",
            "dst_handling": "UTC",
            "delay": "historical",
            "price_type": "ohlcv-1m",
            "api_csv": "API_ohlcv-1m",
            "cost": "metered_USD",
            "license": "Databento_historical",
            "causal_research_usability": "YES_AFTER_TS_EVENT_MAP",
            "status": "CANDIDATE",
            "notes": "Primary oil path. OSE/TOCOM crude DataCube is alternate Japan-hours oil.",
            "url": "https://databento.com/docs/quickstart",
        },
        {
            "instrument": "BRENT_FUTURES_1MIN",
            "provider": "Databento_or_ICE_licensed_vendor",
            "official_or_vendor": "vendor",
            "one_minute_available": True,
            "historical_depth": "vendor_dependent",
            "timestamp_timezone": "UTC_if_Databento",
            "dst_handling": "UTC",
            "delay": "historical",
            "price_type": "ohlcv-1m",
            "api_csv": "API",
            "cost": "metered_or_ICE_license",
            "license": "exchange_constraints",
            "causal_research_usability": "CONDITIONAL",
            "status": "CANDIDATE_SECONDARY",
            "notes": "Not required to start if WTI is present. Do not fake Brent with WTI.",
            "url": "https://databento.com/docs/quickstart",
        },
        {
            "instrument": "ZT_ZN_US_TREASURY_FUTURES_1MIN",
            "provider": "Databento_GLBX.MDP3",
            "official_or_vendor": "vendor_CME_derived",
            "one_minute_available": True,
            "historical_depth": "multi_year",
            "timestamp_timezone": "UTC",
            "dst_handling": "UTC",
            "delay": "historical",
            "price_type": "ohlcv-1m",
            "api_csv": "API",
            "cost": "metered_USD",
            "license": "Databento_historical",
            "causal_research_usability": "YES_AS_US2Y_US10Y_PROXY",
            "status": "CANDIDATE",
            "notes": "Cash US2Y/US10Y 1-minute does not exist at FRED. Use futures proxy and label as proxy.",
            "url": "https://databento.com/docs/quickstart",
        },
        {
            "instrument": "VIX",
            "provider": "CBOE_via_vendor_or_Databento_if_dataset_licensed",
            "official_or_vendor": "vendor",
            "one_minute_available": "vendor_dependent",
            "historical_depth": "vendor_dependent",
            "timestamp_timezone": "America/Chicago_or_UTC_vendor",
            "dst_handling": "US_DST_must_be_explicit",
            "delay": "historical",
            "price_type": "index_or_VX_futures",
            "api_csv": "vendor",
            "cost": "unknown_until_dataset_chosen",
            "license": "CBOE_constraints",
            "causal_research_usability": "CONDITIONAL",
            "status": "GAP_OPTIONAL",
            "notes": "Japan NK225 VI futures is the startable vol context. Do not wait for VIX.",
            "url": "",
        },
        {
            "instrument": "KOSPI_KOSPI200",
            "provider": "KRX_vendor_TBD",
            "official_or_vendor": "unknown",
            "one_minute_available": "not_confirmed_official",
            "historical_depth": "unknown",
            "timestamp_timezone": "KST_no_DST_if_official",
            "dst_handling": "Korea_no_DST",
            "delay": "unknown",
            "price_type": "unknown",
            "api_csv": "unknown",
            "cost": "unknown",
            "license": "unknown",
            "causal_research_usability": "NOT_YET",
            "status": "GAP",
            "notes": "Asia context incomplete. Do not use Yahoo daily as 1-minute KOSPI.",
            "url": "",
        },
        {
            "instrument": "HSI",
            "provider": "HKEX_vendor_TBD",
            "official_or_vendor": "unknown",
            "one_minute_available": "not_confirmed_official",
            "historical_depth": "unknown",
            "timestamp_timezone": "HKT",
            "dst_handling": "HongKong_no_DST",
            "delay": "unknown",
            "price_type": "unknown",
            "api_csv": "unknown",
            "cost": "unknown",
            "license": "unknown",
            "causal_research_usability": "NOT_YET",
            "status": "GAP",
            "notes": "Asia context incomplete.",
            "url": "",
        },
        {
            "instrument": "CSI300_A50",
            "provider": "SGX_A50_or_CFFEX_vendor_TBD",
            "official_or_vendor": "unknown",
            "one_minute_available": "not_confirmed_official",
            "historical_depth": "unknown",
            "timestamp_timezone": "CST_or_SGT",
            "dst_handling": "China_Singapore_no_DST",
            "delay": "unknown",
            "price_type": "unknown",
            "api_csv": "unknown",
            "cost": "unknown",
            "license": "unknown",
            "causal_research_usability": "NOT_YET",
            "status": "GAP",
            "notes": "Do not substitute CSI300 cash with A50 without labeling.",
            "url": "",
        },
        {
            "instrument": "US2Y_US10Y_CASH",
            "provider": "FRED",
            "official_or_vendor": "official_daily",
            "one_minute_available": False,
            "historical_depth": "decades_daily",
            "timestamp_timezone": "US_date",
            "dst_handling": "daily_not_intraday",
            "delay": "daily",
            "price_type": "yield",
            "api_csv": "FRED_API",
            "cost": "free",
            "license": "public",
            "causal_research_usability": "DAILY_ONLY_NOT_INTRADAY",
            "status": "GAP_FOR_1MIN",
            "notes": "May be used as prior-session overnight context only, never as same-minute feature.",
            "url": "https://fred.stlouisfed.org/",
        },
        {
            "instrument": "YFINANCE_DAILY",
            "provider": "Yahoo_unofficial",
            "official_or_vendor": "vendor_unofficial",
            "one_minute_available": False,
            "historical_depth": "unstable",
            "timestamp_timezone": "unreliable",
            "dst_handling": "unreliable",
            "delay": "unknown",
            "price_type": "adjusted_mix_risk",
            "api_csv": "library",
            "cost": "free_unstable",
            "license": "ToS_restrictive",
            "causal_research_usability": "NO_FOR_THIS_TRACK",
            "status": "REJECT",
            "notes": "Existing repo yfinance daily is not the historical 1-minute research source.",
            "url": "",
        },
    ]


def jquants_equity_minute_usable() -> dict[str, Any]:
    return {
        "usable": True,
        "blocked": False,
        "realtime_entry_source": False,
        "history_years": 2,
        "requires_paid_plan": "Light_or_higher",
        "requires_addon": True,
        "addon_jpy_month": 5500,
        "light_jpy_month": 1650,
        "csv_bulk": True,
        "includes_futures": False,
        "adjusted_in_minute_endpoint": False,
        "empty_minutes_omitted": True,
        "time_field_start_vs_end": "NOT_FULLY_SPECIFIED_OFFICIAL",
        "conservative_mapping": "treat_Time_as_bar_start_availability_T_plus_1min",
        "confirm_with": "tick_CSV_vs_minute_OHLC_sample",
    }


def futures_historical() -> dict[str, Any]:
    return {
        "nk225_1min_official": True,
        "nk225mini_1min_official": True,
        "topix_1min_official": True,
        "api_equity_addon_includes_futures": False,
        "source": "J-Quants DataCube per-contract CSV",
        "continuous_series_official": False,
        "autosplice_forbidden": True,
        "if_front_month_used": "document_roll_as_highest_volume_contract_on_that_trade_date_no_price_ratio_adjust",
        "day_night": "Session_ID_999_day_003_night",
        "holiday_trading_from": "202209",
        "price_adjustment": "none_per_contract_as_traded",
        "timestamp_field": "Interval_Time_HHMM",
        "interval_language": "VWAP_from_interval_start_to_end_implies_bar_start_label",
        "cost_personal_jpy_per_product_per_month": 220,
        "one_year_nk225_plus_topix_jpy": 220 * 12 * 2,
        "two_year_nk225_plus_topix_jpy": 220 * 24 * 2,
    }


def cost_estimate() -> dict[str, Any]:
    return {
        "jquants_light_plus_minute_addon_jpy_month": 1650 + 5500,
        "jquants_standard_plus_addon_jpy_month": 3300 + 5500,
        "optional_premium_plus_addon_jpy_month": 16500 + 5500,
        "datacube_nk225_1y_personal_jpy": 220 * 12,
        "datacube_topix_1y_personal_jpy": 220 * 12,
        "datacube_nk225mini_1y_personal_jpy": 220 * 12,
        "datacube_jgb_1y_personal_jpy": 220 * 12,
        "recommended_start_bundle_jpy_first_month": (
            1650 + 5500 + 220 * 12 * 2
        ),
        "recommended_start_bundle_note": (
            "Light+addon ongoing; DataCube NK225+TOPIX one year personal. "
            "Add NK225mini and JGB if matching live/rates. Databento ES/NQ/CL/ZT/ZN metered TBD. "
            "Dukascopy USDJPY typically $0 plus license check."
        ),
        "databento_us_oil_rates": "metered_get_cost_before_pull",
        "asia_cash_1min": "unknown_not_in_start_bundle",
        "currency": "JPY_except_Databento_USD",
        "known": True,
        "exact_total_unknown_until_Databento_quote": True,
    }


def gaps() -> list[dict[str, Any]]:
    return [
        {
            "gap_id": "EQUITY_MINUTE_TIME_OPEN_VS_CLOSE",
            "severity": "BLOCKER_BEFORE_PANEL",
            "detail": "J-Quants /v2/equities/bars/minute Time field is not officially labeled start vs end.",
        },
        {
            "gap_id": "DATABENTO_OHLCV_TS_EVENT",
            "severity": "BLOCKER_BEFORE_EXTERNAL_JOIN",
            "detail": "Map Databento ohlcv-1m ts_event to canonical [T,T+1) before using as feature.",
        },
        {
            "gap_id": "ASIA_CASH_1MIN",
            "severity": "NON_BLOCKING_START",
            "detail": "KOSPI/HSI/CSI300/A50 official 1-minute not confirmed. Start without them.",
        },
        {
            "gap_id": "VIX_1MIN",
            "severity": "NON_BLOCKING_START",
            "detail": "Use NK225 VI futures as Japan vol. VIX optional later.",
        },
        {
            "gap_id": "BRENT_OPTIONAL",
            "severity": "NON_BLOCKING_START",
            "detail": "WTI sufficient to start. Do not alias Brent.",
        },
        {
            "gap_id": "CASH_US_RATES_1MIN",
            "severity": "NON_BLOCKING_START",
            "detail": "Use ZT/ZN futures proxy. FRED daily is overnight-only.",
        },
        {
            "gap_id": "NO_DATA_PURCHASED",
            "severity": "BLOCKER_BEFORE_PANEL",
            "detail": "Phase 0 does not purchase or download. Panel build requires subscription.",
        },
    ]


def minimum_required() -> dict[str, Any]:
    return {
        "fixed_stocks_40_50": "READY_SOURCE_JQUANTS_MINUTE",
        "japan_index_futures": "READY_SOURCE_DATACUBE",
        "usdjpy": "CANDIDATE_DUKASCOPY_UTC",
        "us_risk_tech": "CANDIDATE_DATABENTO_ES_NQ",
        "oil": "CANDIDATE_DATABENTO_CL",
        "asia": "GAP_START_WITHOUT",
        "sector_proxy": "DERIVE_FROM_PANEL_PLUS_OPTIONAL_ETF",
        "wait_for_100": False,
        "enough_to_start_after_purchase_and_time_confirm": True,
    }


assert any(r["instrument"] == "TSE_EQUITY_MINUTE" and r["one_minute_available"] is True for r in source_rows())
assert any(r["instrument"] == "NK225_FUTURES_1MIN" and r["one_minute_available"] is True for r in source_rows())
assert jquants_equity_minute_usable()["blocked"] is False
assert futures_historical()["autosplice_forbidden"] is True
assert minimum_required()["wait_for_100"] is False
