"""NEW_ARCHITECTURE_CLASS_RETHINK_V1. Select one Architecture Class. No rules this run."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import (
    FOLD_BLOCKS,
    OR_FINAL_STATUS,
    PFQ_DOCUMENT_ID,
    PFQ_LINE,
    PFQ_RECON_FORBIDDEN,
    PFQ_VERDICT,
)

ANALYSIS_ID = "NEW_ARCHITECTURE_CLASS_RETHINK_V1"

CASE_A = "NEW_ARCHITECTURE_CLASS_FOUND"
CASE_B = "EXISTING_DATA_ARCHITECTURE_SPACE_EXHAUSTED"
CASE_E = "NEW_ARCHITECTURE_CLASS_RETHINK_INTEGRITY_FAILED"

NEXT_IF_B = "RESEARCH_OBJECTIVE_REBASE_V1"
SESSION = "AM"

CLASS_IDS = (
    "C1_MULTI_TIMEFRAME",
    "C2_EPISODE_AGE",
    "C3_FAILURE_ROUTING",
    "C4_PORTFOLIO_CROWDING",
)

ELIGIBILITY_FIELDS = (
    "CLASS_ID",
    "STRUCTURALLY_DISTINCT",
    "PRIOR_FULL_CAUSAL_TESTED",
    "CLOSED_LINEAGE_MATCH",
    "CAUSAL_INPUTS_AVAILABLE",
    "TIMESTAMP_SEMANTICS_PROVEN",
    "FULL_CAUSAL_REPLAY_FEASIBLE",
    "NEW_PARAMETER_REQUIRED",
    "LABEL_LEAKAGE_REQUIRED",
    "PRIMITIVE_AVAILABLE_DAY_N",
    "MISSING_REQUIRED_FIELDS",
    "ELIGIBLE",
    "WHY",
)

CLOSED_LINEAGE_IDS = (
    "TEMPORAL_STATE_TRANSITION",
    "SIMPLE_TECH_ENTRY_FAMILY",
    "SIMPLE_TECH_BRANCH_U",
    "SIMPLE_TECH_BRANCH_P",
    "SIMPLE_FULL_STRATEGY_75_GRID",
    "RECOVERY_SEQUENCE",
    "PARTICIPATION_ONSET",
    "BREAKOUT_CONTINUATION",
    "VWAP_REJECTION_RECLAIM",
    "FAILED_BREAKDOWN_RECLAIM",
    "E4_X2_Z3",
    "AM_C0",
    "DYNAMIC_ANCHOR_TRAIL10",
    "RPFE",
    "VCIE",
    "E1_X6R3_CONT_PULL_BREAK",
    "E1_X7_PFQ",
    "PRODUCTION_OR_OPEN_STRENGTH_OVERLAY",
)

assert ANALYSIS_ID == "NEW_ARCHITECTURE_CLASS_RETHINK_V1"
assert CASE_A != CASE_B != CASE_E
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert len(CLASS_IDS) == 4
assert len(ELIGIBILITY_FIELDS) == 13
assert len(DEVELOPMENT_DAYS) == 10
assert len(BURNED_HOLDOUT_DAYS) == 8
assert len(STRESS_DAYS) == 4
assert MAX_RESEARCH_DATE == "20260807"
assert POSITION_CAP == 5
assert SHARES == 100
assert FOLD_BLOCKS
assert FORBIDDEN_INPUT_DAYS
assert OR_FINAL_STATUS
assert PFQ_DOCUMENT_ID and PFQ_VERDICT and PFQ_LINE
assert PFQ_RECON_FORBIDDEN
