"""DISCOVERY_SEARCH_SPACE_REASSESSMENT_V1. Calibrate why discovery H5 hard labels found no mechanism. Not a new strategy."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import PORTFOLIO_WAIT_SEC, POSITION_CAP
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "DISCOVERY_SEARCH_SPACE_REASSESSMENT_V1"
PARENT_ANALYSIS_ID = "PROFITABLE_MOVE_MECHANISM_DISCOVERY_V1"
REQUIRED_PARENT_VERDICT = "NO_STABLE_PROFITABLE_MOVE_MECHANISM_FOUND_V1"
REQUIRED_RAW_PREDICATE_N = 12
REQUIRED_CANDIDATE_MECHANISM_N = 72
REQUIRED_COVERAGE_QUALIFIED_N = 68
REQUIRED_PASS_D1_D11_N = 0

P1_ID = "R2_X1_Z3"
P2_ID = "ST_HANDOFF_NEXT__S_CLOSE_ABOVE_VWAP__S_RCI_ABOVE_NEG80"
NEGATIVE_CONTROL_ID = "CSB_V3"

FIXED_HORIZONS = (3, 5, 10)
FEATURE_LOOKAHEAD_N = 0
THRESHOLD_SEARCH = False
HORIZON_SEARCH = False
NEW_MECHANISM_SEARCH = False
NEW_STRATEGY_CREATED = False
FULL_STRATEGY_FROZEN = False
TRUE_OOS = False
CERTIFIED = False
SIZING = False

CASE_A = "DISCOVERY_CALIBRATION_CONTROL_INSUFFICIENT_V1"
CASE_B = "DISCOVERY_FIXED_HORIZON_HARD_GATE_INVALID_V1"
CASE_C = "DISCOVERY_MECHANISM_SEARCH_SPACE_INSUFFICIENT_V1"
NEXT_A = "RECOVER_DISCOVERY_CALIBRATION_CONTROLS_V1"
NEXT_B = "PATH_AWARE_PROFITABLE_MOVE_DISCOVERY_DESIGN_V1"
NEXT_C = "CAUSAL_MECHANISM_REPRESENTATION_EXPANSION_V1"

P1_EXPECTED_TRADE_N = 334
P1_EXPECTED_PNL = 341340.0
P2_EXPECTED_TRADE_N = 75
P2_EXPECTED_PNL = 220580.0
CSB_EXPECTED_TRADE_N = 677
CSB_EXPECTED_PNL = -526070.0

assert ANALYSIS_ID == "DISCOVERY_SEARCH_SPACE_REASSESSMENT_V1"
assert REQUIRED_PARENT_VERDICT == "NO_STABLE_PROFITABLE_MOVE_MECHANISM_FOUND_V1"
assert tuple(FIXED_HORIZONS) == (3, 5, 10)
assert THRESHOLD_SEARCH is False
assert HORIZON_SEARCH is False
assert NEW_MECHANISM_SEARCH is False
assert NEW_STRATEGY_CREATED is False
assert FULL_STRATEGY_FROZEN is False
assert FEATURE_LOOKAHEAD_N == 0
assert TRUE_OOS is False
assert CERTIFIED is False
assert NEXT_B != PFQ_RECON_FORBIDDEN
assert int(POSITION_CAP) == 5
assert abs(float(PORTFOLIO_WAIT_SEC) - 0.05) < 1e-12
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
