"""Live order safety error codes (Phase687W2/W3).

These codes mirror string reject_reason values used by LiveOrderSafetyEngine.precheck
and related paths. They are the formal taxonomy for design docs and Discord payloads;
runtime still stores the string code as reject_reason.
"""

from __future__ import annotations

# Prefix families (design consistency)
ERROR_CODE_PREFIXES = (
    "PRECHECK_",
    "CAPITAL_",
    "DUPLICATE_",
    "DATA_STALE_",
    "BROKER_",
    "RECONCILIATION_",
    "JOURNAL_",
    "STATE_TRANSITION_",
    "KILL_SWITCH_",
    "CONFIG_",
    "REQUEST_",
)

# Config / gate
CONFIG_LIVE_TRADING_ENABLED = "CONFIG_LIVE_TRADING_ENABLED"
CONFIG_ORDER_ENABLED = "CONFIG_ORDER_ENABLED"
CONFIG_DRY_RUN_REQUIRED = "CONFIG_DRY_RUN_REQUIRED"

# Precheck
PRECHECK_KILL_SWITCH_OR_RECOVERY = "PRECHECK_KILL_SWITCH_OR_RECOVERY"
PRECHECK_SYMBOL_NOT_REGISTERED = "PRECHECK_SYMBOL_NOT_REGISTERED"
PRECHECK_SAME_SYMBOL_POSITION = "PRECHECK_SAME_SYMBOL_POSITION"
PRECHECK_PENDING_ORDER = "PRECHECK_PENDING_ORDER"
PRECHECK_POSITION_CAP = "PRECHECK_POSITION_CAP"
PRECHECK_LOT_SIZE = "PRECHECK_LOT_SIZE"
PRECHECK_NO_POSITION = "PRECHECK_NO_POSITION"

# Capital (API failure vs zero balance are distinct)
CAPITAL_API_OFFLINE = "CAPITAL_API_OFFLINE"
CAPITAL_ZERO_BALANCE = "CAPITAL_ZERO_BALANCE"
CAPITAL_RESPONSE_INVALID = "CAPITAL_RESPONSE_INVALID"
CAPITAL_TIMEOUT = "CAPITAL_TIMEOUT"
CAPITAL_AUTH_FAILED = "CAPITAL_AUTH_FAILED"
CAPITAL_UNAVAILABLE = "CAPITAL_UNAVAILABLE"  # maps buying_power_unavailable
CAPITAL_INSUFFICIENT_MARGIN = "CAPITAL_INSUFFICIENT_MARGIN"

# Data freshness
DATA_STALE_PRICE = "DATA_STALE_PRICE"
DATA_STALE_BOARD = "DATA_STALE_BOARD"

# Broker
BROKER_OFFLINE = "BROKER_OFFLINE"
BROKER_TOKEN_INVALID = "BROKER_TOKEN_INVALID"
BROKER_REJECT = "BROKER_REJECT"
BROKER_TIMEOUT_BEFORE_SUBMIT = "BROKER_TIMEOUT_BEFORE_SUBMIT"
BROKER_TIMEOUT_AFTER_SUBMIT = "BROKER_TIMEOUT_AFTER_SUBMIT"
BROKER_SUBMIT_HARD_FAIL = "BROKER_SUBMIT_HARD_FAIL"

# Duplicate
DUPLICATE_ENTRY_SIGNAL = "DUPLICATE_ENTRY_SIGNAL"
DUPLICATE_EXIT_SIGNAL = "DUPLICATE_EXIT_SIGNAL"

# Reconciliation
RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
RECONCILIATION_BROKER_ONLY_POSITION = "RECONCILIATION_BROKER_ONLY_POSITION"
RECONCILIATION_LOCAL_ONLY_POSITION = "RECONCILIATION_LOCAL_ONLY_POSITION"
RECONCILIATION_UNKNOWN_ORDER = "RECONCILIATION_UNKNOWN_ORDER"

# Journal / state
JOURNAL_WRITE_FAILURE = "JOURNAL_WRITE_FAILURE"
STATE_TRANSITION_ILLEGAL = "STATE_TRANSITION_ILLEGAL"

# Kill switch
KILL_SWITCH_MANUAL = "KILL_SWITCH_MANUAL"
KILL_SWITCH_DAILY_LOSS = "KILL_SWITCH_DAILY_LOSS"

# Request contract (Phase687W5) — payload mutation / builder gates
REQUEST_MUTATION_DETECTED = "REQUEST_MUTATION_DETECTED"
REQUEST_POLICY_NOT_SELECTED = "REQUEST_POLICY_NOT_SELECTED"
REQUEST_INVALID = "REQUEST_INVALID"

# Map legacy short reject_reason strings → formal codes
LEGACY_REJECT_TO_CODE: dict[str, str] = {
    "live_trading_enabled": CONFIG_LIVE_TRADING_ENABLED,
    "order_enabled": CONFIG_ORDER_ENABLED,
    "dry_run_required": CONFIG_DRY_RUN_REQUIRED,
    "kill_switch_or_recovery": PRECHECK_KILL_SWITCH_OR_RECOVERY,
    "broker_offline": BROKER_OFFLINE,
    "token_invalid": BROKER_TOKEN_INVALID,
    "stale_price": DATA_STALE_PRICE,
    "stale_board": DATA_STALE_BOARD,
    "symbol_not_registered": PRECHECK_SYMBOL_NOT_REGISTERED,
    "same_symbol_position": PRECHECK_SAME_SYMBOL_POSITION,
    "pending_order": PRECHECK_PENDING_ORDER,
    "position_cap": PRECHECK_POSITION_CAP,
    "buying_power_unavailable": CAPITAL_UNAVAILABLE,
    "buying_power_zero": CAPITAL_ZERO_BALANCE,
    "insufficient_margin": CAPITAL_INSUFFICIENT_MARGIN,
    "daily_loss_threshold": KILL_SWITCH_DAILY_LOSS,
    "lot_size": PRECHECK_LOT_SIZE,
    "jsonl_write_failure": JOURNAL_WRITE_FAILURE,
    "no_position": PRECHECK_NO_POSITION,
    "timeout_before_submit": BROKER_TIMEOUT_BEFORE_SUBMIT,
}


def to_error_code(reject_reason: str) -> str:
    return LEGACY_REJECT_TO_CODE.get(reject_reason, reject_reason)
