"""AM constrained dual-signal geometry reassessment. Frozen OOF only. No selection policy."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from research.wait5_session_target_learnability import POS_REP_DENOM, POS_REP_MIN
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_CONSTRAINED_EXECUTION_AWARE_TARGET_ARCHITECTURE_REASSESSMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
FINAL_SELECTION_N = 3
SLOTS = 3
MAJORITY_RATE = 0.50
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_DEVELOPMENT_ID = "AM_DIRECT_EXEC_U_PRECOMMITTED_DEVELOPMENT_V1"
PRIOR_DEVELOPMENT_VERDICT = "AM_DIRECT_EXEC_U_SACRIFICES_FILL"
PRIOR_COUPLING_ID = "AM_ENTRY_EXECUTION_POLICY_COUPLING_REASSESSMENT_V1"
PRIOR_GEOMETRY_ID = "AM_WAIT5_FILLABILITY_UPSIDE_ARCHITECTURE_GEOMETRY_AUDIT_V1"
PRIOR_COUPLING_VERDICT = "AM_DIRECT_EXEC_U_PASSIVE_ACCESS_CONFLICT"
SPEARMAN_MIN_N = 3

PARITY_EXPECTED = {
    "FILL_ONLY_FILL_RATE_W5": 0.4375,
    "DIRECT_FILL_RATE_W5": 0.4212962962962963,
    "DIRECT_MINUS_FILL_ONLY_W5": -0.013888888888888895,
    "DIRECT_EXEC_U_DELTA_W5": 0.0003315625253401478,
    "DIRECT_EXEC_D_DELTA_W5": -0.00048592052638915615,
    "DIRECT_ONLY_P_FILL_MEDIAN": 0.31132049351583985,
    "FILL_ONLY_ONLY_P_FILL_MEDIAN": 0.4147983108860475,
    "DIRECT_ONLY_RECOVER_RATE_W10": 0.15483870967741936,
    "DIRECT_ONLY_NEVER_CROSS_10S_RATE": 0.7578125,
    "FILL_NONWORSE_U_IMPROVE_RATE": 0.8055555555555556,
    "SAME_FILL_U_IMPROVE_RATE": 0.5833333333333334,
    "FILL_NONWORSE_U_D_NONWORSE_RATE": 0.5416666666666666,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(FINAL_SELECTION_N) == 3
assert int(SLOTS) == 3
assert float(MAJORITY_RATE) == 0.50
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(POS_REP_MIN) == 6
assert int(POS_REP_DENOM) == 9

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WEIGHT_SEARCH = False
STAGE1_ALLOWED = False
STAGE2_ALLOWED = False
SHORTLIST_SEARCH = False
P_FILL_TIMES_U_PRED = False
D_TRAINING_TARGET_ALLOWED = False
W10_ADOPTED = False
WAIT_SEARCH_N = 0
MODEL_REFIT_N = 0
SELECTION_REOPTIMIZATION_N = 0
ORACLE_SELECTION_USE_N = 0
POLICY_FROM_PARETO_N = 0
NEW_TARGET_CREATED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
ENTRY_RETRAIN_STARTED = False
W5_RUNTIME_ADOPTED = False
FROZEN_OOF_REPLAY_ONLY = True
PARETO_AS_STRATEGY = False
