"""C4_PORTFOLIO_CROWDING_PRECOMMIT_V1. Matched CONTROL/TREATMENT freeze. No economics."""
from __future__ import annotations

from research.c1_multi_timeframe_entry_exit_pair_precommit_v2 import EXPECTED_EXIT_FILE_SHA256
from research.c1_multi_timeframe_precommit_v1 import C4_CLASS
from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_ID, CANARY_SOURCE
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS, PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V1"
PRIOR_C1_ANALYSIS_ID = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2"
PRIOR_C1_VERDICT_REQUIRED = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_NO_ROBUST_CANDIDATE"
PRIOR_RETHINK_ANALYSIS_ID = "NEW_ARCHITECTURE_CLASS_RETHINK_V1"
PRIOR_ST_LIBRARY_ANALYSIS_ID = "SYSTEMATIC_STATE_TRANSITION_LIBRARY_PRECOMMIT_V1"
PRIOR_ST_LIBRARY_VERDICT_REQUIRED = "SYSTEMATIC_STATE_TRANSITION_LIBRARY_FROZEN"
PRIOR_EXIT_ANALYSIS_ID = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_PAIR_PRECOMMIT_V2"
PRIOR_EXIT_VERDICT_REQUIRED = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_LIBRARY_V2_FROZEN"

CASE_A = "C4_PORTFOLIO_CROWDING_MATCHED_LIBRARY_FROZEN"
CASE_B = "C4_PORTFOLIO_CROWDING_CAUSAL_ORDER_UNRESOLVABLE"
CASE_E = "C4_PORTFOLIO_CROWDING_PRECOMMIT_INTEGRITY_FAILED"

NEXT_IF_A = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V1"
NEXT_IF_B = "RESEARCH_OBJECTIVE_REBASE_V1"
NEXT_IF_E = "Resolve only the missing integrity proof. No economics. Do not invent another C4 rule."
NEXT_IF_FULL_STRATEGY_FAILS = "RESEARCH_OBJECTIVE_REBASE_V1"

DEV_CLASSIFICATION = "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
CONTROL_POLICY_ID = "C4_CONTROL_NONE"
TREATMENT_POLICY_ID = "C4_FIRST_ARRIVAL_PER_EXACT_T0"
C4_SCOPE = "PER_ENTRY_ID"

KEPT_EXIT_IDS = (
    "Z1_VWAP_LOSS",
    "Z2_STRUCTURE_LOSS",
    "Z3_TWO_BAR_WEAKNESS",
    "Z5_HYBRID_SIMPLE",
)
DROPPED_EXIT_IDS = ("Z4_TRAILING_STRUCTURE",)

ENTRY_N = 25
EXIT_N = 4
MATCHED_STRATEGY_N = 100
CONTROL_ARM_N = 100
TREATMENT_ARM_N = 100
TOTAL_ARM_N = 200

SESSION = "AM"
TRUE_OOS = False
CERTIFIED = False
SIZING = False
STRESS_OPENED_THIS_RUN = False
CANDIDATE_ECONOMICS_RUN = False
CONTROL_ECONOMICS_RUN = False
TREATMENT_ECONOMICS_RUN = False

EXPECTED_ST_LIBRARY_SHA256 = "7f7045f1f0cd7048c646ec74f014868a368445ce4dcac866ea070afb60aa5ba3"
EXPECTED_EXIT_FILE_SHA256_PIN = EXPECTED_EXIT_FILE_SHA256

assert ANALYSIS_ID == "C4_PORTFOLIO_CROWDING_PRECOMMIT_V1"
assert CASE_A != CASE_B != CASE_E
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert NEXT_IF_A != NEXT_IF_B
assert CONTROL_POLICY_ID != TREATMENT_POLICY_ID
assert TREATMENT_POLICY_ID != "C4_FIRST_UNIQUE_T0"
assert C4_SCOPE == "PER_ENTRY_ID"
assert EXECUTION_ID == "X1_IMMEDIATE_ASK"
assert C4_CLASS == "C4_PORTFOLIO_CROWDING"
assert len(KEPT_EXIT_IDS) == 4 == EXIT_N
assert "Z4_TRAILING_STRUCTURE" not in KEPT_EXIT_IDS
assert ENTRY_N * EXIT_N == MATCHED_STRATEGY_N
assert CONTROL_ARM_N + TREATMENT_ARM_N == TOTAL_ARM_N
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert CANARY_ID == "RECOVERY_R2_X1_Z3"
assert CANARY_EXPECTED
assert CANARY_SOURCE
assert CANDIDATE_ECONOMICS_RUN is False
assert CONTROL_ECONOMICS_RUN is False
assert TREATMENT_ECONOMICS_RUN is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert STRESS_OPENED_THIS_RUN is False
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
assert SESSION == "AM"
assert DEV_CLASSIFICATION == "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
assert EXPECTED_ST_LIBRARY_SHA256
assert EXPECTED_EXIT_FILE_SHA256_PIN
assert DROPPED_EXIT_IDS == ("Z4_TRAILING_STRUCTURE",)
assert NEXT_IF_FULL_STRATEGY_FAILS == "RESEARCH_OBJECTIVE_REBASE_V1"
assert PRIOR_C1_ANALYSIS_ID
assert PRIOR_RETHINK_ANALYSIS_ID
assert PRIOR_ST_LIBRARY_ANALYSIS_ID
assert PRIOR_EXIT_ANALYSIS_ID
assert PRIOR_C1_VERDICT_REQUIRED
assert PRIOR_ST_LIBRARY_VERDICT_REQUIRED
assert PRIOR_EXIT_VERDICT_REQUIRED
