"""INTRADAY_SPECIAL_QUOTE_RESOLUTION_FULL_STRATEGY_V1. LEGACY_DEV only. No Sign direction."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_OPTIONAL

ANALYSIS_ID = "INTRADAY_SPECIAL_QUOTE_RESOLUTION_FULL_STRATEGY_V1"
PARENT_ID = "DELAYED_OPEN_BUY_SPECIAL_QUOTE_RELEASE_FULL_STRATEGY_V1"
REQUIRED_PARENT_VERDICT = "BUY_SPECIAL_QUOTE_DIRECTION_NOT_PROVEN_V1"
REQUIRED_PARENT_NEXT = "NON_OPENING_POST_OPEN_COMPLETE_STRATEGY_REDIRECT_V1"
OPENING_LINE_STATUS = "CLOSED"

CANARY_ROW_ID = "R2_X1_Z3"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
EXEC_EVAL_ID = "X1"
SHARES_N = 100
SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
PORTFOLIO_WAIT_SEC = 0.05
BOARD_FRESHNESS_SEC = 5.0
POSITION_CAP_N = 5
CANDIDATE_N_MAX = 3

THESIS_U = "ISQ_UPWARD_RELEASE_ACCEPTANCE"
THESIS_D = "ISQ_DOWNWARD_RELEASE_FAILURE_RECLAIM"
CANDIDATE_U = "ISQ_UP_ACCEPT_X1_Z_RELEASE_LOSS_V1"
CANDIDATE_D = "ISQ_DOWN_FAIL_RECLAIM_X1_Z_PRESPECIAL_LOSS_V1"
CANDIDATE_C = "ISQ_LONG_RESOLUTION_COMBINED_V1"
EXIT_U = "Z_ISQ_UP_RELEASE_ACCEPTANCE_LOST"
EXIT_D = "Z_ISQ_PRE_SPECIAL_RECLAIM_LOST"

CASE_PASS = "INTRADAY_SPECIAL_QUOTE_RESOLUTION_COMPLETE_LOGIC_FOUND_V1"
CASE_COVERAGE = "INTRADAY_SPECIAL_QUOTE_RESOLUTION_COVERAGE_FAIL_V1"
CASE_FAIL = "INTRADAY_SPECIAL_QUOTE_RESOLUTION_FULL_STRATEGY_FAIL_V1"
CASE_DUP = "ISQ_RESOLUTION_ALL_THESES_DUPLICATE_V1"
CASE_PARITY = "ISQ_RESOLUTION_ENGINE_PARITY_FAIL_V1"
CASE_TESTS = "ISQ_RESOLUTION_IMPLEMENTATION_SEMANTICS_FAIL_V1"
CASE_INTEGRITY = "ISQ_RESOLUTION_TRADE_STREAM_INTEGRITY_FAIL_V1"
NEXT_PASS = "FROZEN_LOGIC_EXISTING_DATA_CONFIRMATION_V1"
NEXT_V2 = "NEXT_NON_OPENING_POST_OPEN_ARCHITECTURE_V2"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

MBO_WORK = False
FUTURES_WORK = False
EXTERNAL_ACQUISITION = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

assert ANALYSIS_ID == "INTRADAY_SPECIAL_QUOTE_RESOLUTION_FULL_STRATEGY_V1"
assert REQUIRED_PARENT_VERDICT == "BUY_SPECIAL_QUOTE_DIRECTION_NOT_PROVEN_V1"
assert OPENING_LINE_STATUS == "CLOSED"
assert int(CANDIDATE_N_MAX) == 3
assert int(POSITION_CAP) == 5
assert int(POSITION_CAP_N) == 5
assert int(SHARES_N) == 100
assert int(SHARES) == 100
assert tuple(SESSION_FLATTEN_HM) == (11, 29)
assert CANARY_EXPECTED["signal_n"] == 490
assert CANARY_EXPECTED["fill_n"] == 334
assert CANARY_EXPECTED["trade_n"] == 334
assert MBO_WORK is False
assert FUTURES_WORK is False
assert SIZING is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert CANARY_OPTIONAL
assert float(MIN_PF) == 1.10
assert int(MIN_TOTAL_TRADES) == 40
assert int(MIN_TRADING_DAYS_WITH_FILL) == 8
assert float(MIN_TRADES_PER_DAY) == 4.0
