"""P3-3: canonical Fixed PnL source decomposition.

Research only. No new strategy. No ENTRY / EXIT / Clock / score / Runtime change.
Primary SoT is P1 CURRENT_RUNTIME_REPLAY PRIMARY_FULL14.
Label: REUSED_HISTORY_MECHANISM_DIAGNOSTIC.
"""

from research.fixed_anchor_mechanism_audit_p3_0 import (
    CLOCK_EXACT_TIME_SUPPORTED,
    CLOCK_NOT_UNIQUELY_SPECIAL,
)
from research.fixed_selection_diagnostic_reconcile_p3_0r import (
    FULL14,
    PREDECLARED_TOP3,
    REST11,
)
from small_paper.v1r_primary_runtime import CLOCK_GRID

ANALYSIS_ID = "P3_3_CANONICAL_FIXED_PNL_SOURCE"
DOCUMENT_ID = "P3_3_TAIL_EXIT_ANCHOR_EXECUTABLE_PATH"
TASK_LABEL = "REUSED_HISTORY_MECHANISM_DIAGNOSTIC"

CLOCK_FULL14 = CLOCK_EXACT_TIME_SUPPORTED
CLOCK_REST11 = CLOCK_NOT_UNIQUELY_SPECIAL

P1_TRADES = 267
P1_PNL = 2289100.0
P1_PF = 3.5711557901830844
P1_MAXDD = -210300.0
P1_REF_TRADES = 331
P1_REF_PNL = 2288850.0

HORIZONS_SEC = (1, 10, 60, 180, 600)
ANCHORS = tuple(f"{h:02d}:{m:02d}" for h, m in CLOCK_GRID)
TAIL_NS = (1, 3, 5, 10, 20)

VERDICT_OK = "P3_3_CANONICAL_FIXED_PNL_SOURCE_COMPLETE"
VERDICT_ISSUE = "P3_3_MATERIAL_INTEGRITY_ISSUE"
VERDICT_BLOCKED = "P3_3_BLOCKED"

MAX_WORKERS = 2
FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
