"""Sector-state symbol transmission run. No alpha and no execution."""
from __future__ import annotations

PROGRAM_ID = "CAUSAL_DRIVER_PB1_FOUNDATION"
ANALYSIS_ID = "SECTOR_STATE_SYMBOL_TRANSMISSION_V1"
PRECOMMIT_ID = "SECTOR_STATE_SYMBOL_TRANSMISSION_PRECOMMIT_V1_1"
PRECOMMIT_SHA256 = "bf852da52636a3ae2c0c141d1d25cd8c29b541b81e621346a4e45bb72008babb"

CASE_FOUND = "SECTOR_STATE_SYMBOL_TRANSMISSION_FOUND_V1"
CASE_NOT_FOUND = "SECTOR_STATE_SYMBOL_TRANSMISSION_NOT_FOUND_V1"
CASE_BLOCKED = "SECTOR_STATE_SYMBOL_TRANSMISSION_BLOCKED_V1"
NEXT_ALPHA = "PRECOMMIT_SECTOR_STATE_ALPHA_SIGNAL_V1"
NEXT_REASSESS = "REASSESS_ALPHA_ARCHITECTURE_AFTER_AGGREGATE_ONLY_DRIVER_V1"
