"""Complete strategy on the frozen event-time impulse. Immediate ask. Thesis exit."""

ANALYSIS_ID = "EVENT_TIME_IMPULSE_COMPLETE_STRATEGY_V2"
PARENT_ANALYSIS_ID = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_DISCOVERY_V1"
PARENT_VERDICT = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_MECHANISM_SUPPORTED_V1"
REQUIRED_SIGNAL_SHA256 = "06345e9f7ddd2fcdf21a7beac49241495d3a4b6607715c879cf2ef0a307b4f68"
ENTRY_EXECUTION_ID = "EVENT_TIME_IMPULSE_IMMEDIATE_ASK_V2"
COMPLETE_STRATEGY_ID = "EVENT_TIME_IMPULSE_COMPLETE_STRATEGY_V2"
CAPTURE_FIRST = "20260722"
CAPTURE_LAST = "20260910"
MAX_CONCURRENT = 5
SHARES = 100
RECONFIRM_GAP_SEC = 30.0
CONCENTRATION_CAP = 0.80
MIN_TRADES = 100

VERDICT_SUPPORTED = "EVENT_TIME_IMPULSE_COMPLETE_STRATEGY_V2_SUPPORTED"
VERDICT_NOT = "EVENT_TIME_IMPULSE_COMPLETE_STRATEGY_V2_NOT_SUPPORTED"
VERDICT_SUPPORT = "EVENT_TIME_IMPULSE_V2_INSUFFICIENT_TRADE_SUPPORT"
VERDICT_MISMATCH = "ENTRY_SIGNAL_IDENTITY_MISMATCH"
NEXT_AUDIT = "ROBUSTNESS_AND_FAILURE_AUDIT_EVENT_TIME_IMPULSE_V2"
NEXT_STOP = "STOP"
