"""Sector breadth/dispersion precommit V1.1. Inference freeze only. No discovery."""
from __future__ import annotations

from research.causal_driver_pb1.sector_breadth_precommit import (
    BOOTSTRAP_N,
    BOOTSTRAP_SEED,
    EXPECTED_SECTOR_IDS,
    EXPECTED_SECTOR_MAPPING_SHA256,
    EXPECTED_SECTOR_N,
    EXPECTED_UNIVERSE_N,
    EXPECTED_UNIVERSE_SHA256,
    FAMILY_N,
    FDR_FAMILY_N,
    FDR_Q,
    HORIZONS,
    LOOKBACKS,
    METRICS,
    PARENT_C1_CONFIRMED_N,
    PARENT_CANDIDATE_LIST_SHA256,
    PARENT_DECISION_REASON,
    PARENT_DEV_CANDIDATE_N,
    PARENT_FINAL_PASS_N,
    PARENT_PRECOMMIT_SHA256,
    PARENT_REPORT_REASON_RAW,
    PARENT_STATUS,
    PARENT_VERDICT,
    PHASE0_DRIVER_FAMILY_ENUM_MUTATED,
    PHASE0_DRIVER_FAMILY_VALUES,
    PRIMARY_NEXT_DRIVER,
    RESEARCH_FAMILY_ID,
    SCOPE_N,
)

PROGRAM_ID = "CAUSAL_DRIVER_PB1_FOUNDATION"
PRECOMMIT_ID = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_V1_1"
ANALYSIS_ID = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_V1_1"

CASE_READY = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_READY_V1_1"
CASE_BLOCKED = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_BLOCKED_V1_1"
NEXT_RUN = "RUN_SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_V1"
NEXT_RESOLVE = "RESOLVE_SECTOR_BREADTH_DISPERSION_PRECOMMIT_BLOCKERS_V1_1"

SUPERSEDES_PRECOMMIT_ID = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_V1"
SUPERSEDES_PRECOMMIT_SHA256 = "1dfc54fe98cb5a7ecce13ea4a4cfb6832b5c3aa2befbfa859722e0ac7b998c44"

V1_ELIGIBLE_DAY_SHA256 = "9b97f2cb1f9bbee2800623f4b899722014db9d72939dcc82131ef247765da20c"
V1_FOLD_BOUNDARY_SHA256 = "fc03a260483786125295012d84c1b6e8559b9667885b9bd905292f8c03547934"
V1_PERMUTATION_SHA256 = "d65197857e48f0cda457ac56a11622f51fefdf4be5cc6c8c9ab7dae3a8258ebc"
V1_FAMILY_384_SHA256 = "265fe8b2c598bf4ee5902c4fe83233c1636d8a7b71bdd4446c0a0a45e3bd683a"
V1_ELIGIBLE_DEV_N = 260
V1_ELIGIBLE_C1_N = 89

CI_METHOD = "BOOTSTRAP_PERCENTILE_CI"
P_VALUE_METHOD = "BOOTSTRAP_TWO_SIDED_SIGN_TAIL_PLUS_ONE"
BH_METHOD = "BENJAMINI_HOCHBERG_MONOTONE_Q"
QUANTILE_INTERPOLATION = "linear"
RNG_LIBRARY = "numpy.random.RandomState"
RNG_ALGORITHM = "MT19937"

_ = (
    BOOTSTRAP_N,
    BOOTSTRAP_SEED,
    EXPECTED_SECTOR_IDS,
    EXPECTED_SECTOR_MAPPING_SHA256,
    EXPECTED_SECTOR_N,
    EXPECTED_UNIVERSE_N,
    EXPECTED_UNIVERSE_SHA256,
    FAMILY_N,
    FDR_FAMILY_N,
    FDR_Q,
    HORIZONS,
    LOOKBACKS,
    METRICS,
    PARENT_C1_CONFIRMED_N,
    PARENT_CANDIDATE_LIST_SHA256,
    PARENT_DECISION_REASON,
    PARENT_DEV_CANDIDATE_N,
    PARENT_FINAL_PASS_N,
    PARENT_PRECOMMIT_SHA256,
    PARENT_REPORT_REASON_RAW,
    PARENT_STATUS,
    PARENT_VERDICT,
    PHASE0_DRIVER_FAMILY_ENUM_MUTATED,
    PHASE0_DRIVER_FAMILY_VALUES,
    PRIMARY_NEXT_DRIVER,
    RESEARCH_FAMILY_ID,
    SCOPE_N,
)
