"""NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V1. Freeze one complete Full Strategy. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V1"

CASE_A = "NEW_FULL_STRATEGY_ARCHITECTURE_FROZEN"
CASE_B = "NEW_FULL_STRATEGY_NO_JUSTIFIED_ARCHITECTURE"
NEXT_IF_A = "NEW_FULL_STRATEGY_IMPLEMENTATION_AND_DEV_EVAL_V1"
NEXT_IF_B = "NEW_ARCHITECTURE_INFORMATION_INVENTORY_V1"

OLD_RCA_ENDPOINT = "SELECTION_SURFACE_MECHANISM_RCA_V1"
OLD_RCA_VERDICT = "SELECTION_SURFACE_MECHANISM_RCA_INCONCLUSIVE"
FORBIDDEN_NEXT_RUNS = (
    "SELECTION_SURFACE_EVIDENCE_GAP_V1",
    "TRAIN_GATE_MARGIN_MECHANISM_RCA_V1",
    "TRAIN_RANK_SURFACE_RCA_V1",
    "TRAIN_SELECTION_COMPONENT_RCA_V1",
)

SESSION = "AM"
AM_START_HM = (9, 0)
AM_END_HM = (11, 30)

Q1_NEW_LOGIC_COMPLETION_DIRECT = True
Q2_BLOCKING_WITHOUT_THIS_RUN = True
Q3_OLD_RCA_AS_PURPOSE = False

TRUE_OOS = False
CERTIFIED = False
SIZING = False
NEW_REPLAY = False
NEW_ARCHITECTURE_ECONOMICS_RUN = False
NEW_ARCHITECTURE_PNL_READ_N = 0
RAW_CAPTURE_READ_N = 0
VWAP_ENTRY_USED = False
VWAP_EXIT_USED = False
VWAP_FILTER_USED = False
BOARD_PRIMARY_ALPHA = False
OLD_ST_RCA_CONTINUED = False

CLOSED_LINEAGE_IDS = (
    "SIMPLE_FULL",
    "E4",
    "SYSTEMATIC_STATE_TRANSITION",
    "C1_MULTI_TIMEFRAME",
    "C4_PORTFOLIO_CROWDING",
    "RECOVERY_SEQUENCE",
    "PARTICIPATION_ONSET",
    "PFQ",
    "OR",
    "DYNAMIC_ANCHOR",
    "X9",
)

assert ANALYSIS_ID == "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V1"
assert Q1_NEW_LOGIC_COMPLETION_DIRECT is True
assert Q2_BLOCKING_WITHOUT_THIS_RUN is True
assert Q3_OLD_RCA_AS_PURPOSE is False
assert OLD_ST_RCA_CONTINUED is False
assert NEXT_IF_B not in FORBIDDEN_NEXT_RUNS
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert VWAP_ENTRY_USED is False
assert BOARD_PRIMARY_ALPHA is False
assert NEW_ARCHITECTURE_ECONOMICS_RUN is False
assert NEW_ARCHITECTURE_PNL_READ_N == 0
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert TRUE_OOS is False
assert CERTIFIED is False
