"""IDENTIFY_MINIMUM_MISSING_EXTERNAL_CAUSAL_INFORMATION_V1. HM1 frozen. NK/TOPIX first. No purchase."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "COMPLETE_CAUSAL_STRATEGY_RESEARCH_V1"
ANALYSIS_ID = "IDENTIFY_MINIMUM_MISSING_EXTERNAL_CAUSAL_INFORMATION_V1"
PARENT_ANALYSIS_ID = "HIGHER_MAGNITUDE_STATE_DISCOVERY_V1"
PARENT_VERDICT = "STOCK_PANEL_MAGNITUDE_LIMIT_CONFIRMED_V1"
KIND = "MINIMUM_EXTERNAL_DIRECTION_INFORMATION"
SEMANTICS = "BAR_START"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
HM1_ID = "HM1_CONTROLLED_PULLBACK_RECLAIM"
HM2_ID = "HM2_COMPRESSION_BREAKOUT_EXPANSION"
PROXY_NK = "1321"
PROXY_TOPIX = "1306"
LOOKBACKS_SEC = (60, 180, 300)
LOOKBACK_30S_MINUTE_PROXY = False

CASE_FUTURES = "FUTURES_INCREMENTAL_DIRECTION_FOUND_V1"
CASE_PROXY = "HISTORICAL_PROXY_SIGNAL_FOUND_TRUE_FUTURES_VALIDATION_REQUIRED_V1"
CASE_INSUFFICIENT = "NK_TOPIX_INCREMENTAL_INFORMATION_INSUFFICIENT_V1"
CASE_SOURCE = "HISTORICAL_FUTURES_SOURCE_NOT_AVAILABLE_V1"
CASE_BIND = "EXTERNAL_INFO_BIND_FAILED_V1"

NEXT_BUILD = "BUILD_FUTURES_CONDITIONED_COMPLETE_STRATEGY_V1"
NEXT_ACCUM = "ACCUMULATE_AND_VALIDATE_TRUE_FUTURES_PROSPECTIVELY_V1"
NEXT_USDJPY = "USDJPY_MINIMUM_MISSING_INFORMATION_TEST_V1"
NEXT_BRIDGE = "PROXY_PLUS_PROSPECTIVE_FUTURES_BRIDGE_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_USED_TO_DESIGN = False
HM1_TUNED = False
PURCHASE_REQUESTED = False
YFINANCE_USED = False

assert ANALYSIS_ID == "IDENTIFY_MINIMUM_MISSING_EXTERNAL_CAUSAL_INFORMATION_V1"
assert PARENT_VERDICT == "STOCK_PANEL_MAGNITUDE_LIMIT_CONFIRMED_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert HM1_TUNED is False
assert PURCHASE_REQUESTED is False
assert PROXY_NK == "1321"
assert PROXY_TOPIX == "1306"
