"""Execution-aware entry target feasibility. Diagnostic only. No model. No Exact."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.multiobjective_feasibility import JOINT_FEASIBLE_MIN_RATE
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "EXECUTION_AWARE_ENTRY_TARGET_FEASIBILITY_AUDIT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
TOPK = 3
RATE_MIN = float(JOINT_FEASIBLE_MIN_RATE)  # 0.50 inherited
PARITY_ABS_TOL = 1e-10
SUPPORT_MIN_LODO_TRAIN_N = 50
SUPPORT_MIN_DAY_N = 1

PRIOR_VERDICT_REQUIRED = "JOINT_OPPORTUNITY_NOT_PASSIVELY_ACCESSIBLE"

FILL_EXPECTED = {
    "ALL_CANDIDATE_N": 11684,
    "ALL_WOULD_FILL_N": 258,
    "ALL_WOULD_FILL_RATE": 0.02208147894556659,
    "JOINT_POSITIVE_WOULD_FILL_N": 64,
    "CURRENT_TOP3_WOULD_FILL_N": 90,
    "FILLABLE_JOINT_AVAILABLE_COHORT_N": 43,
    "FILLABLE_JOINT_AVAILABLE_RATE": 0.14982578397212543,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(RATE_MIN) == 0.50

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WAIT_CHANGED = False
LIMIT_CHANGED = False
FILL_RULE_CHANGED = False
MARKETABLE_ASSUMED = False
TAKER_FILL_ADDED = False
POSITION_CAP_APPLIED = False
OCCUPANCY_APPLIED = False
REENTRY_APPLIED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
EXECUTION_REDESIGN_STARTED = False
NEW_TARGET_CREATED = False
TARGET_MODEL_STARTED = False
