"""Joint opportunity execution feasibility. Diagnostic only. No model. No Exact."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.multiobjective_feasibility import JOINT_FEASIBLE_MIN_RATE
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "JOINT_OPPORTUNITY_EXECUTION_FEASIBILITY_REASSESSMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
TOPK = 3
FILLABLE_JOINT_MIN_RATE = float(JOINT_FEASIBLE_MIN_RATE)  # 0.50 inherited
SURVIVAL_LOW_MAX = 0.50  # frozen diagnostic bar; not searched
PARITY_ABS_TOL = 1e-10

PRIOR_VERDICT_REQUIRED = "RAW_EVENT_DESCRIPTORS_NOT_PREDICTIVE"

ORACLE_EXPECTED = {
    "JOINT_LABEL_POSITIVE_N": 3382,
    "JOINT_LABEL_NEGATIVE_N": 8302,
    "JOINT_AVAILABLE_COHORT_N": 284,
    "LABELED_COHORT_N": 287,
    "JOINT_AVAILABLE_RATE": 0.9895470383275261,
}

EARLY_HORIZONS_SEC = (1.0, 5.0, 30.0)
NONFILL_CLASSES = (
    "NO_ASK_CROSS_WITHIN_WAIT",
    "BOARD_BECAME_NONEXECUTABLE",
    "NO_VALID_CONTINUOUS_BOARD",
    "OTHER",
)

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(FILLABLE_JOINT_MIN_RATE) == 0.50

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WAIT_CHANGED = False
LIMIT_CHANGED = False
FILL_RULE_CHANGED = False
MARKETABLE_ASSUMED = False
TAKER_FILL_ADDED = False
POSITION_CAP_APPLIED = False
OCCUPANCY_APPLIED = False
REENTRY_APPLIED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
EXECUTION_REDESIGN_STARTED = False
NEW_TARGET_CREATED = False
