"""FULL_CAUSAL_FDG_RELATIVE_GEOMETRY_MIGRATION_V1. Translation-invariant deep-rank migration."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BOARD_FRESHNESS_SEC,
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_OPTIONAL
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "FULL_CAUSAL_FDG_RELATIVE_GEOMETRY_MIGRATION_V1"
OBJECT_PARENT_ID = "DISCOVERY_INFORMATION_OBJECT_EXPANSION_DECISION_V1"
STATIC_PARENT_ID = "FULL_CAUSAL_STRATEGY_ARCHITECTURE_FROM_INFORMATION_OBJECT_V1"
REQUIRED_OBJECT_VERDICT = "NEW_CAUSAL_INFORMATION_OBJECT_SELECTED_V1"
REQUIRED_OBJECT_ID = "FULL_DEPTH_GEOMETRY"
REQUIRED_OBJECT_SHA256 = "edec6d0d4a375042fa188be260edca5510e7a945d252cde80be42a4425150b6c"
REQUIRED_STATIC_VERDICT = "FDG_PRICE_GEOMETRY_FULL_STRATEGY_COVERAGE_FAIL_V1"
CLOSED_STATIC_STRATEGY_ID = "FDG_ASK_SPAN_GT_BID_SPAN_ONSET_X1_Z_SPAN_NORMALIZE"

PIN_STATIC_TRADE_N = 21064
PIN_STATIC_PNL = -25076050
PIN_STATIC_PF = 0.08750356158920203
PIN_STATIC_DAYS = "0/10/0"
PIN_STATIC_UNFILLED = 17
PIN_BID_HOLE_N = 0
PIN_ASK_HOLE_N = 0

STRATEGY_ID = "FDG_RELATIVE_GEOMETRY_MIGRATION_ONSET_X1_Z_BASELINE_LOSS"
ARCHITECTURE_CLASS = "FULL_DEPTH_RELATIVE_GEOMETRY_MIGRATION"
TECHNICAL_EXIT_ID = "Z_FDG_RELATIVE_GEOMETRY_BASELINE_LOSS"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
EXEC_EVAL_ID = "X1"
CANARY_ROW_ID = "R2_X1_Z3"

SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
PORTFOLIO_WAIT_SEC = 0.05
BOARD_FRESHNESS_SEC = float(BOARD_FRESHNESS_SEC)
SHARES = int(SHARES)
POSITION_CAP = int(POSITION_CAP)
SAME_SYMBOL_BLOCK = True
PREOPEN_EXECUTION_VALID = False
STATIC_SPAN_STRATEGY_CLOSED = True
STATIC_SPAN_RETUNE = False
STATIC_SPAN_FAMILY_CLOSED = True
SESSION_EXIT_FIX_AS_RESCUE = False
DEEP_RANKS_REQUIRED = True
DEPTH_RANK_SEMANTICS_VALID = True
MULTI_CANDIDATE_SELECTION = False
SELECTION_TRANSFER_RUN = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

SC1_MIN_SIGNAL_N = 40
SC2_MIN_SIGNAL_DAY_N = 8
SC3_MIN_SIGNAL_SYMBOL_N = 10

PRIMARY_DECISION_UNIT = (
    "ENTRY + X1 EXECUTION + TECHNICAL EXIT + CAP=5 + SAME-SYMBOL + OCCUPANCY + "
    "SLOT RELEASE + REENTRY + SESSION FLATTEN"
)

CASE_A = "FDG_RELATIVE_GEOMETRY_DEV_CANDIDATE_FOUND_V1"
CASE_B = "FDG_RELATIVE_GEOMETRY_MIGRATION_INSUFFICIENT_COVERAGE_V1"
CASE_C = "FDG_RELATIVE_GEOMETRY_FULL_STRATEGY_COVERAGE_FAIL_V1"
CASE_D = "FDG_RELATIVE_GEOMETRY_ECONOMIC_FAIL_V1"
CASE_E = "FDG_RELATIVE_GEOMETRY_NOT_ROBUST_V1"
CASE_INTEGRITY = "FDG_RELATIVE_GEOMETRY_MIGRATION_INTEGRITY_FAILED_V1"
CASE_PARITY = "FDG_RELATIVE_GEOMETRY_ENGINE_PARITY_FAILED_V1"
NEXT_A = "NEW_FULL_STRATEGY_VALIDATION_DESIGN_V1"
NEXT_STOP = "EXISTING_DATA_STRATEGY_RESEARCH_STOP_REASSESSMENT_V1"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

assert STRATEGY_ID != CLOSED_STATIC_STRATEGY_ID
assert STATIC_SPAN_RETUNE is False
assert SESSION_EXIT_FIX_AS_RESCUE is False
assert STATIC_SPAN_FAMILY_CLOSED is True
assert DEEP_RANKS_REQUIRED is True
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert FOLD_BLOCKS["B5"] == ("20260806", "20260807")
assert CANARY_EXPECTED["signal_n"] == 490
assert CANARY_OPTIONAL
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert MIN_PF == 1.10
assert MIN_TOTAL_TRADES == 40
assert abs(float(BOARD_FRESHNESS_SEC) - 5.0) < 1e-12
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
