"""P3-4R: align extension outcomes to Dual Lane 600_DECISION time.

Research only. P3-4 winner cluster frozen. No new strategy.
No ENTRY / EXIT / Clock / score / Runtime / extension-condition change.
"""

from research.canonical_fixed_pnl_source_p3_3 import (
    FULL14,
    P1_PF,
    P1_PNL,
    P1_TRADES,
    PREDECLARED_TOP3,
    REST11,
)
from research.fixed_winner_cluster_extension_p3_4 import (
    EXIT600_REASON,
    EXTEND_REASON,
    REACHED_600_REASONS,
)

ANALYSIS_ID = "P3_4R_EXTENSION_DECISION_ALIGNMENT"
DOCUMENT_ID = "P3_4R_DECISION_TIME_OUTCOME_RECONCILE"
TASK_LABEL = "REUSED_HISTORY_MECHANISM_DIAGNOSTIC"
FROZEN_CLUSTER = "MULTIPLE_PARTLY_INDEPENDENT_CLUSTERS"

IDENTITY_REL_TOL = 1e-9
MAX_WORKERS = 2

VERDICT_OK = "P3_4R_EXTENSION_DECISION_ALIGNMENT_RECONCILED"
VERDICT_ISSUE = "P3_4R_MATERIAL_DIAGNOSTIC_ISSUE"
VERDICT_BLOCKED = "P3_4R_BLOCKED"

GATE_SUPPORTED = "EXTENSION_GATE_SUPPORTED"
GATE_MIXED = "EXTENSION_GATE_MIXED"
GATE_NOT = "EXTENSION_GATE_NOT_SUPPORTED"

MECH_POST = "WINNER_SELECTION_WITH_POST_DECISION_EXTENSION_VALUE"
MECH_MIXED = "WINNER_SELECTION_BUT_POST_DECISION_VALUE_MIXED"
MECH_PRE = "WINNER_LABEL_WITH_PREDECISION_MOVE"
MECH_NODISC = "EXTENSION_GATE_NOT_DISCRIMINATIVE"
MECH_NONE = "NO_CLEAR_EXTENSION_MECHANISM"

PLUS150_LABEL = "STANDARDIZED_POST_DECISION_150S_DIAGNOSTIC"
OLD_LABEL = "OLD_NOMINAL_600_BASED"

FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
P1_TRADES = P1_TRADES
P1_PNL = P1_PNL
P1_PF = P1_PF
EXTEND_REASON = EXTEND_REASON
EXIT600_REASON = EXIT600_REASON
REACHED_600_REASONS = REACHED_600_REASONS
