"""DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2. Pool + minute panel. No strategy. V1 immutable."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.fixed_daytrade_universe_v1 import LAST_COMPLETE_TSE_SESSION, UNIVERSE_ID
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

ANALYSIS_ID = "DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2"
KIND = "HISTORICAL_RESEARCH_FOUNDATION"
V1_SEED_ID = UNIVERSE_ID
V1_1_REJECTED_ID = "FIXED_DAYTRADE_UNIVERSE_V1_1_CANDIDATE"
PROBE_SYMBOL = "7203"
PROBE_DATE = LAST_COMPLETE_TSE_SESSION
FORBIDDEN_DATA_FROM = "20260914"
WINDOW_FIRST = "20260618"
WINDOW_LAST = "20260911"
WINDOW_N = 60
MINUTE_FROM_PREFERRED = "20240917"
MINUTE_TO = "20260911"
LIQUIDITY_TOP_N = 80
ACTIVITY_TOP_N = 40
RUNTIME_STOCK_MAX = 48
KABU_SLOT_MAX = 50
PRIME_MKT = "0111"
RANGE_BPS_TRADE_FLOOR = 60.0
ACTIVE_MINUTE_RATIO_FLOOR = 0.25
NOTIONAL_REVIEW_JPY = 1_000_000.0
PAPER_LOT_QTY = 100
TSE_REGULAR_MINUTE_N_FULL = 330

CASE_READY = "DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2_READY"
CASE_PARTIAL = "DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2_PARTIAL"
CASE_ENTITLEMENT = "JQUANTS_MINUTE_ENTITLEMENT_NOT_ACTIVE_V2"
CASE_TIME = "DAYTRADE_HISTORICAL_V2_TIME_SEMANTICS_BLOCKED"
CASE_DAILY = "DAYTRADE_HISTORICAL_V2_DAILY_SOURCE_FAILED"

NEXT_RUNTIME = "DESIGN_KABU_50_SLOT_RUNTIME_UNIVERSE_V1"
NEXT_ENTITLEMENT = "CONFIRM_JQUANTS_MINUTE_TICK_ADDON_ACTIVE_V2"
NEXT_TIME = "PROVE_EQUITY_MINUTE_TIME_SEMANTICS_THEN_RETRY_V2"

STRATEGY_SEARCH_STARTED = False
ENTRY = False
EXIT = False
PNL_USED = False
FUTURE_RETURN_USED = False
V1_MODIFIED = False
V1_1_ADOPTED = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
LIVE_20260914_CHANGED = False
SAME_BAR_CLOSE_ENTRY = False

ENDPOINT_MINUTE = "/v2/equities/bars/minute"
ENDPOINT_DAILY = "/v2/equities/bars/daily"

assert ANALYSIS_ID == "DAYTRADE_HISTORICAL_RESEARCH_FOUNDATION_V2"
assert PROBE_DATE == "20260911"
assert PROBE_SYMBOL == "7203"
assert V1_1_ADOPTED is False
assert V1_MODIFIED is False
assert STRATEGY_SEARCH_STARTED is False
assert FEATURE_MINING_CLOSED is True
assert LIVE_TRADING_DATE == "20260914"
assert RUNTIME_STOCK_MAX + 2 == KABU_SLOT_MAX
