"""Event-time volume-confirmed impulse. Existing capture only. No entry freeze."""

ANALYSIS_ID = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_DISCOVERY_V1"
CAPTURE_FIRST = "20260722"
CAPTURE_LAST = "20260910"
PROSPECTIVE_FROM = "20260924"
FV_FROM = "20260911"

WINDOWS_SEC = (10, 30, 60)
PRIOR_BINS_10 = 6
PRIOR_BINS_30 = 4
HORIZONS = (30, 60, 180, 300)
PRIMARY_HORIZON = 180
MIN_FULL_N = 30
ESSENTIALLY_ALL_SHARE = 0.80
FRESH_SEC = 5.0
MIN_QTY = 100.0

VERDICT_SUPPORTED = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_MECHANISM_SUPPORTED_V1"
VERDICT_NOT = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_MECHANISM_NOT_SUPPORTED_V1"
VERDICT_SUPPORT = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_INSUFFICIENT_SUPPORT_V1"
NEXT_PRECOMMIT = "PRECOMMIT_EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_ENTRY_V1"
NEXT_STOP = "STOP"
INFORMATION_NOT_ESTABLISHED = "SUB_MINUTE_STOCK_MICROSTRUCTURE_EDGE_NOT_ESTABLISHED_V1"
