"""FUTURES_X_STOCK_STATE_DAY1_CANDIDATE_MECHANISM_AUDIT_V1.

Explain the frozen Day1 candidate. No new search. No retuning.
"""
from __future__ import annotations

ANALYSIS_ID = "FUTURES_X_STOCK_STATE_DAY1_CANDIDATE_MECHANISM_AUDIT_V1"
PARENT_ID = "FUTURES_X_STOCK_STATE_INTERACTION_DAY1_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
TRADING_DATE = "20260911"

DAY2_ANALYSIS_ID = "FUTURES_X_STOCK_STATE_DAY2_CONFIRMATION_V1"

FROZEN_CONTEXT = "AGREEMENT_180S_BOTH_DOWN"
FROZEN_CONTEXT_FAMILY = "AGREEMENT_180S"
FROZEN_CONTEXT_BUCKET = "BOTH_DOWN"
FROZEN_SELECTOR = "OBSERVED_TRADE_N_180S"
FROZEN_HORIZON = "10m"
FROZEN_DIRECTION = "LONG TOP16"
TERCILE_N = 16
UNIVERSE_N = 48

FROZEN_CLOCKS = (
    "09:20",
    "09:40",
    "10:20",
    "10:30",
    "10:40",
)

ACTIVITY_FAMILY = (
    "OBSERVED_TRADE_N_180S",
    "TRADING_VALUE_DELTA_180S",
    "BID_UPDATE_N_60S",
    "UNDER_BUY_QTY",
    "OVER_SELL_QTY",
)

DAY1_SECONDARY_ROWS = (
    ("OBSERVED_TRADE_N_180S", "NK_RET_180S", "DOWN", "10m"),
    ("TRADING_VALUE_DELTA_180S", "AGREEMENT_180S", "BOTH_DOWN", "10m"),
    ("BID_UPDATE_N_60S", "AGREEMENT_180S", "BOTH_DOWN", "10m"),
    ("UNDER_BUY_QTY", "NK_RET_180S", "DOWN", "3m"),
    ("UNDER_BUY_QTY", "AGREEMENT_180S", "BOTH_DOWN", "5m"),
    ("UNDER_BUY_QTY", "AGREEMENT_180S", "BOTH_DOWN", "10m"),
    ("OVER_SELL_QTY", "AGREEMENT_180S", "BOTH_DOWN", "10m"),
)

CLASS_A = "RISK_OFF_ACTIVITY_RESILIENCE"
CLASS_B = "RISK_OFF_ACTIVITY_CONTINUATION"
CLASS_C = "FUTURE_REVERSAL_DEPENDENT"
CLASS_D = "RIGHT_TAIL_WINNER_DRIVEN"
CLASS_E = "MECHANISM_UNRESOLVED"

VERDICT_SUPPORTED = "FUTURES_X_STOCK_STATE_DAY1_MECHANISM_SUPPORTED_V1"
VERDICT_WINNER = "FUTURES_X_STOCK_STATE_DAY1_RELATIVE_ONLY_WINNER_DRIVEN_V1"
VERDICT_REVERSAL = "FUTURES_X_STOCK_STATE_DAY1_CURRENT_CONTEXT_INSUFFICIENT_V1"
NEXT_DAY2 = "RUN_EXACT_FROZEN_DAY2_CONFIRMATION_V1"

ENTRY = False
EXIT = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
DAY2_SUBSTITUTIONS_ALLOWED = False

assert FROZEN_SELECTOR == "OBSERVED_TRADE_N_180S"
assert FROZEN_CONTEXT_BUCKET == "BOTH_DOWN"
assert FROZEN_HORIZON == "10m"
assert FROZEN_CLOCKS == ("09:20", "09:40", "10:20", "10:30", "10:40")
assert len(FROZEN_CLOCKS) == 5
assert TERCILE_N == 16
assert DAY2_SUBSTITUTIONS_ALLOWED is False
assert ENTRY is False and EXIT is False
assert "SPREAD_BPS" not in ACTIVITY_FAMILY
assert len(DAY1_SECONDARY_ROWS) == 7
