"""P4-1: precommitted MID_HOLD_NO_PROGRESS_V1 one-shot exact-replay falsification.

Research only. Does not adopt the Gate into Runtime.
Does not change Early Guard / 600_DECISION / Extension / 750 / ENTRY / Clock / score.
Label: REUSED_HISTORY_PRECOMMITTED_CANDIDATE_FALSIFICATION.
"""

from research.canonical_fixed_pnl_source_p3_3 import (
    FULL14,
    P1_MAXDD,
    P1_PF,
    P1_PNL,
    P1_TRADES,
    PREDECLARED_TOP3,
    REST11,
)
from research.mid_hold_state_separability_p4_0 import CHECKPOINTS_SEC
from small_paper.v1r_exit_v2_contract import FROZEN_GUARD

ANALYSIS_ID = "P4_1_MID_HOLD_NO_PROGRESS_GATE"
DOCUMENT_ID = "P4_1_MID_HOLD_GATE_ONE_SHOT_FALSIFICATION"
TASK_LABEL = "REUSED_HISTORY_PRECOMMITTED_CANDIDATE_FALSIFICATION"

CANDIDATE_ID = "MID_HOLD_NO_PROGRESS_V1"
EXIT_REASON = "MID_HOLD_NO_PROGRESS"

CHECKPOINTS_SEC = tuple(CHECKPOINTS_SEC)
GUARD_MONITOR_TO = float(FROZEN_GUARD.get("monitor_to") or 120.0)
DECISION_HORIZON_SEC = 600.0

VERDICT_OK = "P4_1_MID_HOLD_GATE_ONE_SHOT_COMPLETE"
VERDICT_BLOCKED = "P4_1_BLOCKED"

STATUS_INTEGRITY = "MATERIAL_INTEGRITY_ISSUE"
STATUS_DESTRUCTIVE = "MID_HOLD_NO_PROGRESS_WINNER_DESTRUCTIVE"
STATUS_NO_COVERAGE = "MID_HOLD_NO_PROGRESS_NO_USEFUL_COVERAGE"
STATUS_HARM = "MID_HOLD_NO_PROGRESS_PORTFOLIO_HARM"
STATUS_MIXED = "MID_HOLD_NO_PROGRESS_MIXED"
STATUS_NOT_FALSIFIED = "MID_HOLD_NO_PROGRESS_NOT_FALSIFIED"

MAX_WORKERS = 2
CACHE_VERSION = 1

FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
P1_TRADES = P1_TRADES
P1_PNL = P1_PNL
P1_PF = P1_PF
P1_MAXDD = P1_MAXDD
FROZEN_GUARD = FROZEN_GUARD
