"""FUTURES_REVERSAL_X_CASH_PARTICIPATION_DAY1_V1.

Cash participation at the frozen 9 BOTH_UP confirmations.
No new futures features. Day2 primary freeze unchanged.
"""
from __future__ import annotations

from research.futures_reversal_confirmed_entry_day1_v1 import (
    DAY2_PRIMARY,
    DAY2_PRIMARY_ID,
    ORIGINAL_FIVE,
    SELECTOR,
    TERCILE_N,
    UNIVERSE_N,
)

ANALYSIS_ID = "FUTURES_REVERSAL_X_CASH_PARTICIPATION_DAY1_V1"
PARENT_ID = "FUTURES_REVERSAL_CONFIRMED_ENTRY_DAY1_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
TRADING_DATE = "20260911"

CASH_LOOKBACK_SEC = 180
MIN_TRUE_N = 3

FROZEN_TRIGGERS = (
    "09:07:32",
    "09:21:46",
    "10:03:03",
    "10:17:35",
    "10:24:41",
    "10:32:39",
    "10:48:42",
    "10:53:05",
    "11:04:12",
)
BINDING_WINNER = "09:21:46"
BINDING_LOSER = "10:32:39"

DAY2_PRIMARY_UNCHANGED = True

CASE_A = "A"
CASE_B = "B"
CASE_C = "C"
CASE_D = "D"
VERDICT_A = "FUTURES_REVERSAL_WITH_CASH_PARTICIPATION_PLAUSIBLE_DAY1_V1"
VERDICT_B = "FUTURES_REVERSAL_CASH_PARTICIPATION_RELATIVE_ONLY_DAY1_V1"
VERDICT_C = "CASH_PARTICIPATION_DOES_NOT_RESOLVE_REVERSAL_QUALITY_DAY1_V1"
VERDICT_D = "CASH_PARTICIPATION_TOO_SPARSE_DAY1_V1"
NEXT_A = "KEEP_DAY2_PRIMARY_AND_FREEZE_CASH_PARTICIPATION_AS_SEPARATE_DIAGNOSTIC_V1"
NEXT_FAIL = "CURRENT_DAY1_INFORMATION_INSUFFICIENT_FOR_ENTRY"
NEXT_B = NEXT_FAIL
NEXT_C = NEXT_FAIL
NEXT_D = NEXT_FAIL

ENTRY = False
EXIT = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
DAY2_SUBSTITUTIONS_ALLOWED = False
NEW_FUTURES_FEATURES = False
CASH_CONFIRM_ONLY = True

assert SELECTOR == "OBSERVED_TRADE_N_180S"
assert CASH_LOOKBACK_SEC == 180
assert MIN_TRUE_N == 3
assert len(FROZEN_TRIGGERS) == 9
assert FROZEN_TRIGGERS[1] == BINDING_WINNER
assert FROZEN_TRIGGERS[5] == BINDING_LOSER
assert TERCILE_N == 16
assert UNIVERSE_N == 48
assert ORIGINAL_FIVE == ("09:20", "09:40", "10:20", "10:30", "10:40")
assert DAY2_PRIMARY_UNCHANGED is True
assert DAY2_PRIMARY["substitutions_allowed"] is False
assert DAY2_PRIMARY_ID == "FUTURES_X_STOCK_STATE_DAY2_CONFIRMATION_V1"
assert ENTRY is False and EXIT is False
assert NEW_FUTURES_FEATURES is False
assert CASH_CONFIRM_ONLY is True
