"""E1_X7 PFQ EXIT Gate Reconciliation V2 — repairable ⊆ denominator invariant."""

ANALYSIS_ID = "E1_X7_PFQ_EXIT_GATE_RECONCILIATION_V2"
SOURCE_EXIT_GATE_RUN = "e1x7_pfq_exit_gate_20260804_235025_A"
SOURCE_VERDICT = "E1_X7_PFQ_MULTIPLE_EXIT_BASELINES_REVIEW_REQUIRED"
SOURCE_BRIDGE_RUN = "e1x7_pfq_bridge_v2_20260804_232049_A"
CANDIDATE_ID = "PFQ_UPDATE_Q70"

PAIRS = (
    "PFQ_UPDATE_Q70|PFQ_X_PROGRESS_STRUCT",
    "PFQ_UPDATE_Q70|PFQ_X_PROTECT",
)

KNOWN_DENOM = {
    "PFQ_UPDATE_Q70|PFQ_X_PROGRESS_STRUCT": 62,
    "PFQ_UPDATE_Q70|PFQ_X_PROTECT": 46,
}

KNOWN = {
    "unique_episode_n": 92,
    "progress_trade_rows": 92,
    "protect_trade_rows": 92,
    "total_pair_trade_rows": 184,
}

MECH_SOFT = "SOFT_EXIT_PREMATURE"
MECH_GIVEBACK = "PLUS5_REACHED_BEFORE_EXIT_GIVEN_BACK_TO_NONPOSITIVE"
REF_PROFITABLE_SOFT = "PROFITABLE_SOFT_EXIT_OPPORTUNITY_COST"

GATE_MIN_REPAIRABLE_N = 20
GATE_MIN_REPAIRABLE_DAYS = 5
GATE_MIN_REPAIRABLE_FRACTION = 0.50
GATE_MIN_TOP_MECH_FRACTION = 0.50
