"""FLEX_MBO_CONNECTION_SPEC_RESOLUTION_V1. Protocol gaps only if official specs already local. No account. No strategy."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)

ANALYSIS_ID = "FLEX_MBO_CONNECTION_SPEC_RESOLUTION_V1"
PARENT_ID = "NEW_INFORMATION_ACQUISITION_FEASIBILITY_DESIGN_V1"
REQUIRED_PARENT_VERDICT = "FLEX_MBO_FEASIBILITY_BLOCKED_BY_PROTOCOL_GAPS_V1"
REQUIRED_PARENT_NEXT = "FLEX_MBO_CONNECTION_SPEC_RESOLUTION_V1"
REQUIRED_SELECTED_SOURCE = "EXCHANGE_NATIVE_ORDER_EVENT_FEED"
REQUIRED_POLICY_SHA256 = "51f493e48727b6fbff5359e79a44c358de19d41b41a7f309330d8b818590ea3b"
REQUIRED_FEASIBILITY_SPEC_SHA256 = "06d6299fad6048792c6e4bebc69f1e4f7aa402ce14d242f33b083eab86f298e8"

LEGACY_DEV_DAYS = DEVELOPMENT_DAYS
QUARANTINE_DAYS = ("20260903", "20260904")

CASE_A = "FLEX_MBO_PROTOCOL_REPLAY_SEMANTICS_RESOLVED_V1"
CASE_B = "FLEX_MBO_PROTOCOL_SEMANTICS_STILL_INCOMPLETE_V1"
CASE_C = "FLEX_MBO_CONNECTION_SPEC_ACCESS_REQUIRED_V1"
NEXT_A_LEGAL_OPEN = "FLEX_MBO_ACQUISITION_APPROVAL_AND_BUDGET_DECISION_V1"
NEXT_A_LEGAL_OPEN_IF_F12_F13_UNRESOLVED = "FLEX_MBO_PROVIDER_CONFIRMATION_PLAN_V1"
NEXT_B = "FLEX_MBO_PROVIDER_CONFIRMATION_PLAN_V1"
NEXT_C = "FLEX_MBO_AUTHORIZED_DOCUMENT_ACCESS_DECISION_V1"

PUBLIC_WEB_PROTOCOL_RESOLUTION_EXPECTED = False
NETWORK_LATENCY_ALPHA_ALLOWED = False
MICROTIMING_RESEARCH_ALLOWED = False
RESEARCH_METHOD_FROZEN = False
COLLECTOR_IMPLEMENTED = False
REPLAY_ENGINE_IMPLEMENTED = False
MARKET_DATA_PURCHASED = False
MARKET_DATA_DOWNLOADED = False
ACCOUNT_CREATED = False
PROVIDER_CONTACTED = False
CONTRACT_CHANGED = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

assert ANALYSIS_ID == "FLEX_MBO_CONNECTION_SPEC_RESOLUTION_V1"
assert REQUIRED_PARENT_VERDICT == "FLEX_MBO_FEASIBILITY_BLOCKED_BY_PROTOCOL_GAPS_V1"
assert REQUIRED_PARENT_NEXT == "FLEX_MBO_CONNECTION_SPEC_RESOLUTION_V1"
assert REQUIRED_SELECTED_SOURCE == "EXCHANGE_NATIVE_ORDER_EVENT_FEED"
assert REQUIRED_POLICY_SHA256 == "51f493e48727b6fbff5359e79a44c358de19d41b41a7f309330d8b818590ea3b"
assert REQUIRED_FEASIBILITY_SPEC_SHA256 == "06d6299fad6048792c6e4bebc69f1e4f7aa402ce14d242f33b083eab86f298e8"
assert PUBLIC_WEB_PROTOCOL_RESOLUTION_EXPECTED is False
assert ACCOUNT_CREATED is False
assert PROVIDER_CONTACTED is False
assert MARKET_DATA_PURCHASED is False
assert COLLECTOR_IMPLEMENTED is False
assert RESEARCH_METHOD_FROZEN is False
assert NETWORK_LATENCY_ALPHA_ALLOWED is False
assert MICROTIMING_RESEARCH_ALLOWED is False
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert QUARANTINE_DAYS == ("20260903", "20260904")
