"""WAIT5 execution-aware ENTRY rebase. Diagnostic only. No model. Runtime WAIT unchanged."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.multiobjective_feasibility import JOINT_FEASIBLE_MIN_RATE
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "WAIT5_EXECUTION_AWARE_ENTRY_REBASE_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
RATE_MIN = float(JOINT_FEASIBLE_MIN_RATE)
PARITY_ABS_TOL = 1e-10
DEV_WAIT_ID = "W5"
DEV_WAIT_SEC = 5.0
DOMINANCE_MIN_RATE = float(JOINT_FEASIBLE_MIN_RATE)
QUALITY_SPEARMAN_WEAK_MAX = 0.10

PRIOR_VERDICT_REQUIRED = "PASSIVE_WAIT5_PRECOMMIT_SUPPORTED"

PARITY_EXPECTED = {
    "ALL_CANDIDATE_N": 11684,
    "W5_WOULD_FILL_N": 852,
    "W5_ANY_RATE": 0.7317073170731707,
    "W5_MULTI_RATE": 0.5156794425087108,
    "W5_FILLABLE_0_COHORT_N": 77,
    "W5_FILLABLE_1_COHORT_N": 62,
    "W5_FILLABLE_2_COHORT_N": 32,
    "W5_FILLABLE_3PLUS_COHORT_N": 116,
    "W5_JOINT_SURVIVAL": 1.0,
    "PM_MULTI_RATE": 0.2517482517482518,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert float(RATE_MIN) == 0.50
assert float(DOMINANCE_MIN_RATE) == 0.50
assert abs(float(WAIT_SEC) - float(DEV_WAIT_SEC)) > 1e-12

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
WAIT_INTERPOLATION = False
REPRICING = False
LIMIT_CHANGED = False
FILL_RULE_CHANGED = False
OLD_JOINT_ADOPTED = False
ENTRY_RETRAIN_STARTED = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
PRICE_POLICY_STARTED = False
NEW_TARGET_CREATED = False
MARKETABLE_ASSUMED = False
TAKER_FILL_ADDED = False
POSITION_CAP_APPLIED = False
OCCUPANCY_APPLIED = False
REENTRY_APPLIED = False
W10_RESELECTED = False
