"""SUPPORT_RESISTANCE_FACE_VALID_FIRST_INTERACTION_REBUILD_V1. Causal swing S/R that looks like a trader drawing. No PnL."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "SUPPORT_RESISTANCE_FACE_VALID_FIRST_INTERACTION_REBUILD_V1"
ANALYSIS_ID = "SUPPORT_RESISTANCE_FACE_VALID_FIRST_INTERACTION_REBUILD_V1"
PARENT_ANALYSIS_ID = "SUPPORT_RESISTANCE_TEST_DESIGN_AUDIT_V1"
PARENT_VERDICT = "MULTIPLE_DESIGN_DEFICIENCIES"
RCA_DEFERRED = "REFERENCE_LEVEL_MECHANISM_RCA_V1"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"

ZONE_HALF_ATR = 0.15
LOOKBACK_DAYS = 60
CONFIRM_ATR = 0.75
ATR_N = 20
MIN_TOUCHES = 2
SAMPLE_N = 200
SAMPLE_SEED = 20260917
LUNCH_POLICY = "HOLD_THROUGH_LUNCH_RESUME_PM"
SESSION_FLAT = "15:20"

CASE_READY = "SUPPORT_RESISTANCE_FACE_VALID_REBUILD_READY_V1"
CASE_NOT_FACE = "SUPPORT_RESISTANCE_REBUILD_NOT_YET_FACE_VALID_V1"
CASE_GATE = "SUPPORT_RESISTANCE_REBUILD_STRUCTURAL_GATE_FAILED_V1"
CASE_BIND = "SUPPORT_RESISTANCE_REBUILD_BIND_FAILED_V1"

NEXT_MATCHED = "SUPPORT_RESISTANCE_FIRST_INTERACTION_MATCHED_CAUSAL_TEST_V1"
NEXT_STOP_GATE = "STOP_REBUILD_STRUCTURAL_GATE_FAILED_V1"
NEXT_REPAIR_FACE = "REPAIR_FACE_VALID_SWING_ZONE_DETECTOR_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_OPENED = False
NEW_PAID_DATA = False
PROMOTED = False
V27_BOLTED = False
RCA_EXECUTED = False
ZONE_WIDTH_SELECTED_BY_PNL = False
CONFIRM_ATR_SELECTED_BY_PNL = False
SALIENCE_SELECTED_BY_PNL = False
NO_PNL_PARAMETER_TUNING = True
X0_X1_USED_TO_SELECT_RULES = False
OLD_NO_INFO_REVIVED_AS_ECONOMIC_NULL = False

assert ANALYSIS_ID == "SUPPORT_RESISTANCE_FACE_VALID_FIRST_INTERACTION_REBUILD_V1"
assert PARENT_VERDICT == "MULTIPLE_DESIGN_DEFICIENCIES"
assert CONFIRM_ATR == 0.75
assert ZONE_HALF_ATR == 0.15
assert CONFIRM_ATR_SELECTED_BY_PNL is False
assert ZONE_WIDTH_SELECTED_BY_PNL is False
assert X0_X1_USED_TO_SELECT_RULES is False
assert NO_PNL_PARAMETER_TUNING is True
assert FROZEN_VALIDATION_OPENED is False
assert OLD_CONFIRMATION_OPENED is False
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert PROMOTED is False
assert OLD_NO_INFO_REVIVED_AS_ECONOMIC_NULL is False
