"""POST_OPEN_EXECUTION_TAX_DECOMPOSITION_V1. X1 vs canonical W5. No new ENTRY."""
from __future__ import annotations

from research.post_open_causal_upside_mechanism_discovery_v1 import (
    ANCHOR_HMS,
    BOARD_FRESHNESS_SEC,
    DEVELOPMENT_DAYS,
    FEATURE_IDS,
    PRIMARY_HORIZON_SEC,
    SESSION_FLATTEN_HM,
)
from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS

ANALYSIS_ID = "POST_OPEN_EXECUTION_TAX_DECOMPOSITION_V1"
PARENT_ID = "POST_OPEN_CAUSAL_UPSIDE_MECHANISM_DISCOVERY_V1"
REQUIRED_PARENT_VERDICT = "POST_OPEN_NO_STABLE_CAUSAL_UPSIDE_MECHANISM_IN_CURRENT_CAPTURE_V1"
REQUIRED_PARENT_NEXT = "EXISTING_CAPTURE_POST_OPEN_INFORMATION_CONTENT_LIMIT_V1"
KIND = "EXECUTION_TAX_DECOMPOSITION_ONLY"
CANDIDATE_STRATEGY_N = 0
SESSION = "AM"
CONTROL_ID = "X1_IMMEDIATE_ASK"
TREATMENT_ID = "CORRECTED_PASSIVE_FILL_W5"
W5_WAIT_SEC = 5.0
W5_PRECOMMIT_ID = "PASSIVE_WAIT5_PRECOMMIT_DEVELOPMENT_V1"

EXPECTED_ANCHOR_N = 6500
EXPECTED_EXECUTABLE_N = 4375
EXPECTED_PRIMARY_N = 4345
EXPECTED_X1_MEAN = -19.887523938008446
EXPECTED_X1_MEDIAN = -17.905102954341988
PARITY_ABS_TOL = 1e-9

W5_REF = {
    "W5_ANY_RATE": 0.7317073170731707,
    "W5_MULTI_RATE": 0.5156794425087108,
    "AM_W5_ANY": 0.8819444444444444,
    "AM_W5_MULTI": 0.7777777777777778,
}

CONDITIONAL_FEATURES = (
    "SPREAD_BPS",
    "BID_UPDATE_N_60S",
    "TRADING_VALUE_DELTA_180S",
    "TRADING_VALUE_DELTA_60S",
    "OBSERVED_TRADE_N_180S",
)

TREE_MAX_DEPTH = 2
TREE_MAX_LEAF_NODES = 4
TREE_MIN_LEAF_N = 100
LEAF_MIN_N = 100
LEAF_MIN_DAY_N = 8
LEAF_MIN_SYMBOL_N = 30
MIN_FILL_DAY_N = 8
MIN_FILL_SYMBOL_N = 50
LOBO_MIN_POS = 3
POS_P2_BLOCK_MIN = 3

CASE_IDENTITY = "POST_OPEN_EXECUTION_TAX_W5_IDENTITY_NOT_PROVEN_V1"
CASE_A = "POST_OPEN_UPSIDE_INFORMATION_RECOVERED_WITH_PASSIVE_EXECUTION_V1"
NEXT_A = "POST_OPEN_EXECUTION_ALIGNED_COMPLETE_STRATEGY_CONSTRUCTION_V1"
CASE_B = "POST_OPEN_EXECUTION_TAX_MATERIAL_BUT_ALPHA_INSUFFICIENT_V1"
NEXT_B = "EXISTING_CAPTURE_POST_OPEN_INFORMATION_CONTENT_LIMIT_CONFIRMED_V1"
CASE_C = "POST_OPEN_INFORMATION_LIMIT_CONFIRMED_AFTER_EXECUTION_DECOMPOSITION_V1"
NEXT_C = "NEW_INFORMATION_SOURCE_OR_STRATEGY_OBJECTIVE_REDESIGN_V1"
CASE_PARITY = "POST_OPEN_EXECUTION_TAX_PARENT_PARITY_FAIL_V1"

TRUE_OOS = False
CERTIFIED = False
MBO_WORK = False
FUTURES_WORK = False
SIZING = False

assert ANALYSIS_ID == "POST_OPEN_EXECUTION_TAX_DECOMPOSITION_V1"
assert REQUIRED_PARENT_VERDICT == "POST_OPEN_NO_STABLE_CAUSAL_UPSIDE_MECHANISM_IN_CURRENT_CAPTURE_V1"
assert REQUIRED_PARENT_NEXT == "EXISTING_CAPTURE_POST_OPEN_INFORMATION_CONTENT_LIMIT_V1"
assert int(CANDIDATE_STRATEGY_N) == 0
assert float(W5_WAIT_SEC) == 5.0
assert len(ANCHOR_HMS) == 13
assert len(FEATURE_IDS) == 30
assert len(CONDITIONAL_FEATURES) == 5
assert "ASK_UPDATE_N_60S" not in CONDITIONAL_FEATURES
assert TRUE_OOS is False
assert len(DEVELOPMENT_DAYS) == 10
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert len(FOLD_BLOCKS) == 5
assert BOARD_FRESHNESS_SEC
assert PRIMARY_HORIZON_SEC == 600.0
assert SESSION_FLATTEN_HM == (11, 29)
