"""WAIT5 session architecture precommit. Diagnostic only. No model. Runtime WAIT unchanged."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.multiobjective_feasibility import JOINT_FEASIBLE_MIN_RATE
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "WAIT5_SESSION_ARCHITECTURE_PRECOMMIT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
RATE_MIN = float(JOINT_FEASIBLE_MIN_RATE)
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
CURRENT_SCORE_ROLE = "FILLABILITY_ENRICHMENT_REFERENCE"
AM_NEXT_TASK = "AM_WAIT5_TWO_STAGE_TARGET_LEARNABILITY"
PM_NEXT_TASK = "PM_WAIT5_FILLABILITY_TARGET_LEARNABILITY"
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_VERDICT_REQUIRED = "WAIT5_SELECTION_CAPACITY_SESSION_ASYMMETRIC"

PARITY_EXPECTED = {
    "AM_COHORT_N": 144,
    "AM_ANY": 0.8819444444444444,
    "AM_MULTI": 0.7777777777777778,
    "AM_THREEPLUS": 0.7013888888888888,
    "AM_FILL5_N": 698,
    "PM_COHORT_N": 143,
    "PM_ANY": 0.5804195804195804,
    "PM_MULTI": 0.2517482517482518,
    "PM_THREEPLUS": 0.1048951048951049,
    "PM_FILL5_N": 154,
    "CURRENT_FILL5_ENRICHMENT": 3.3925667828106847,
    "AM_CURRENT_FILL5_ENRICHMENT": 3.5031439032155367,
    "PM_CURRENT_FILL5_ENRICHMENT": 3.8886416613689345,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert float(RATE_MIN) == 0.50
assert COMMON_AM_PM_MODEL_ALLOWED is False
assert COMMON_AM_PM_TARGET_ALLOWED is False
assert CURRENT_SCORE_ROLE == "FILLABILITY_ENRICHMENT_REFERENCE"

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
WAIT_INTERPOLATION = False
REPRICING = False
LIMIT_CHANGED = False
FILL_RULE_CHANGED = False
ENTRY_RETRAIN_STARTED = False
SESSION_INDICATOR_COMMON_MODEL = False
QUALITY_SCALAR_WEIGHT = False
JOINT_BINARY_TARGET = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
W10_RESELECTED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
PRICE_POLICY_STARTED = False
NEW_TARGET_CREATED = False
MARKETABLE_ASSUMED = False
TAKER_FILL_ADDED = False
POSITION_CAP_APPLIED = False
OCCUPANCY_APPLIED = False
REENTRY_APPLIED = False
PARETO_TARGET_ADOPTED = False
