"""SR_A2_BRACKETED_STRUCTURE_COMPLETE_STRATEGY_V1.

Post-hoc Development architecture. A2 only. C1 closed.
Eligibility: pre-known opposing S/R at A2 decision time. Not Confirmation.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE
from research.support_resistance_face_valid_first_interaction_rebuild_v1 import CONFIRM_ATR, ZONE_HALF_ATR

PROGRAM_ID = "SR_A2_BRACKETED_STRUCTURE_COMPLETE_STRATEGY_V1"
ANALYSIS_ID = "SR_A2_BRACKETED_STRUCTURE_COMPLETE_STRATEGY_V1"
STRATEGY_ID = "SR_A2_BRACKETED_COMPLETE_V1"
PARENT_ANALYSIS_ID = "SUPPORT_RESISTANCE_MECHANISM_TO_COMPLETE_STRATEGY_V1"
PARENT_VERDICT = "SR_PATH_SEPARATION_NOT_COMPLETE_STRATEGY_V1"

POST_HOC_DEVELOPMENT_ARCHITECTURE = True
C1_CLOSED = True
C1_REOPENED = False

EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_DETECTOR_SHA256 = "6e3060b71f8a4787b09d6b3c0f3ba9fa84c87712bf0f11b0165bfbfd1e0bf47e"
EXPECTED_STATE_MACHINE_SHA256 = "3c065f3757083fa6da792f9450e07504e902ea93d48391467a6bb7dca6e6a5b8"
EXPECTED_PRIMARY_FIRST_TEST_N = 2713

FROZEN_CONFIRM_ATR = 0.75
FROZEN_ZONE_HALF_ATR = 0.15
assert CONFIRM_ATR == FROZEN_CONFIRM_ATR
assert ZONE_HALF_ATR == FROZEN_ZONE_HALF_ATR

LUNCH_POLICY = "HOLD_THROUGH_LUNCH_RESUME_PM"
SESSION_FLAT = "15:20"
ENTRY_EXECUTION = "HISTORICAL_NEXT_BAR_OPEN_EXECUTION"
ELIGIBILITY_PRICE = "DECISION_BAR_CLOSE"
TARGET_FILL_CLASS = "HISTORICAL_STRUCTURAL_TARGET_TOUCH"
SHORT_LABEL = "HISTORICAL_SHORT_RESEARCH_ONLY"

CAP = 3
SHARES = 100
X1_STRESS_BPS = 8.0
TIE_SEED = "SR_A2_BRACKETED_SEEDED_HASH_ORDER_V1"
SMD_MATERIAL = 0.25

DEV_BLOCKS = ("D1", "D2", "D3", "D4")
GATE_BLOCKS = ("D2", "D3", "D4")

CASE_PASS_STRUCTURAL = "BRACKETED_STRUCTURAL_COMPLETE_CANDIDATE"
CASE_PASS_CONTEXT = "A2_WITH_OPPOSING_ZONE_CONTEXT_CANDIDATE"
CASE_FAIL = "SR_A2_BRACKETED_COMPLETE_STRATEGY_FAILED_V1"

NEXT_CONFIRM = "SUPPORT_RESISTANCE_SECONDARY_CONFIRMATION_NOT_PRISTINE_V1"
NEXT_STOP = "STOP_SUPPORT_RESISTANCE_STRATEGY_PATH_V1"

OLD_CONFIRMATION_OPENED = False
FROZEN_VALIDATION_OPENED = False
KABU50_APPLIED = False
DETECTOR_RETUNED = False
PNL_BASED_RULE_CHANGE = False
FEATURE_MINING = FEATURE_MINING_CLOSED
LIVE_DATE = LIVE_TRADING_DATE

STRATEGY_SPEC = {
    "post_hoc_development_architecture": True,
    "c1_closed": True,
    "eligibility_price": ELIGIBILITY_PRICE,
    "eligibility": "A2 confirmed AND pre-known opposing active S/R relative to decision-bar close",
    "entry": ENTRY_EXECUTION,
    "same_bar_entry": False,
    "target_frozen_before_entry": True,
    "target_not_replaced_after_entry": True,
    "exit": "thesis_invalidation | frozen opposing-zone nearest boundary | 15:20",
    "ambiguity": "INVALIDATION_WINS",
    "lunch": LUNCH_POLICY,
    "session_close": SESSION_FLAT,
    "cap": CAP,
    "shares": SHARES,
    "no_time_volume_sector_longonly_filters": True,
    "d1_d4_status": "ALL_DEVELOPMENT",
    "cost": "X0_GROSS and X1_8BPS_EXECUTION_STRESS",
}


__all__ = [
    "PROGRAM_ID",
    "STRATEGY_ID",
    "PARENT_VERDICT",
    "CASE_FAIL",
    "NEXT_STOP",
    "POST_HOC_DEVELOPMENT_ARCHITECTURE",
]
