"""P4-4: current exact Early Guard ON vs OFF-only ablation.

Research only. Full Dual Lane state-machine. No new Guard / no retune /
no Mid-Hold reopen / no Runtime change.
Label: REUSED_HISTORY_CURRENT_EXACT_COMPONENT_ABLATION.
"""

from research.canonical_fixed_pnl_source_p3_3 import (
    FULL14,
    P1_MAXDD,
    P1_PF,
    P1_PNL,
    P1_TRADES,
    PREDECLARED_TOP3,
    REST11,
)
from small_paper.v1r_exit_v2_contract import FROZEN_CONTINUATION, FROZEN_GUARD

ANALYSIS_ID = "P4_4_EARLY_GUARD_EXACT_ABLATION"
DOCUMENT_ID = "P4_4_CURRENT_EXACT_EARLY_GUARD_RECONCILIATION"
TASK_LABEL = "REUSED_HISTORY_CURRENT_EXACT_COMPONENT_ABLATION"

VARIANT_ID = "EARLY_GUARD_OFF_ONLY"
GUARD_EXIT_REASON = "IMBALANCE"
CANONICAL_GUARD_N = 89

HIST_SAVED_LOSS = 168100.0
HIST_FOREGONE_WINNER = 118900.0
HIST_RATIO = 1.413793

CLASS_SUPPORTED = "EARLY_GUARD_CURRENT_EXACT_SUPPORTED"
CLASS_MIXED = "EARLY_GUARD_CURRENT_EXACT_MIXED"
CLASS_HARMFUL = "EARLY_GUARD_CURRENT_EXACT_HARMFUL"
CLASS_DATA = "MATERIAL_INTEGRITY_ISSUE"

VERDICT_OK = "P4_4_EARLY_GUARD_EXACT_ABLATION_COMPLETE"
VERDICT_BLOCKED = "P4_4_BLOCKED"

MAX_WORKERS = 2
CACHE_VERSION = 1

FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
P1_TRADES = P1_TRADES
P1_PNL = P1_PNL
P1_PF = P1_PF
P1_MAXDD = P1_MAXDD
FROZEN_GUARD = FROZEN_GUARD
FROZEN_CONTINUATION = FROZEN_CONTINUATION
