"""FUTURES_MARKET_CONTEXT_ACQUISITION_V1. Isolated Core10+Dynamic38+2 futures. No strategy."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    STRESS_DAYS,
)

ANALYSIS_ID = "FUTURES_MARKET_CONTEXT_ACQUISITION_V1"
PARENT_ID = "POST_OPEN_CAUSAL_DOWNSIDE_MECHANISM_DISCOVERY_V1"
REQUIRED_PARENT_VERDICT = "CURRENT_CAPTURE_BIDIRECTIONAL_INFORMATION_LIMIT_CONFIRMED_V1"
REQUIRED_PARENT_NEXT = "NEW_CAUSAL_INFORMATION_ACQUISITION_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
ROLE = "NEW_INFO_DEV_CONSTRUCTION_ONLY"

CORE_N = 10
DYNAMIC_N = 38
FUTURES_N = 2
TOTAL_REGISTRATION_N = 50
STANDARD_DYNAMIC_N = 40
STANDARD_TOTAL_N = 50

FUTURE_CODES = ("NK225mini", "TOPIX")
DERIV_MONTH = 0
FUTURES_EXCHANGE = 2
STOCK_EXCHANGE = 1

WINDOW_START_HM = (7, 55)
WINDOW_END_HM = (11, 30)
NEW_INFO_FROM_DAY = "20260911"

FORBIDDEN_FUTURE_CODES = ("VI", "GROWTH", "DOW")

CASE_IMPL_FAIL = "NEW_CAUSAL_INFORMATION_ACQUISITION_IMPLEMENTATION_FAIL_V1"
CASE_CAPACITY = "NEW_CAUSAL_INFORMATION_KABU_CAPACITY_BLOCKED_V1"
CASE_FUTURES_UNSUPPORTED = "NEW_CAUSAL_INFORMATION_FUTURES_INPUT_NOT_SUPPORTED_V1"
CASE_FIRST_FULL = "NEW_CAUSAL_INFORMATION_FUTURES_CAPTURE_PROVEN_V1"
CASE_SET_READY = "NEW_CAUSAL_INFORMATION_FUTURES_CONSTRUCTION_SET_READY_V1"
CASE_MODE_READY = "NEW_CAUSAL_INFORMATION_FUTURES_ACQUISITION_MODE_READY_V1"
CASE_PREPARED = "NEW_INFO_FIRST_CAPTURE_PREPARED_V1"
CASE_LIVE_REG_FAIL = "NEW_CAUSAL_INFORMATION_LIVE_REGISTRATION_FAIL_V1"
CASE_FUTURES_RESOLVE_FAIL = "NEW_CAUSAL_INFORMATION_FUTURES_RESOLUTION_FAIL_V1"
CASE_TRANSPORT_FAIL = "NEW_CAUSAL_INFORMATION_FUTURES_TRANSPORT_FAIL_V1"
CASE_PARTIAL = "NEW_CAUSAL_INFORMATION_FUTURES_CAPTURE_PARTIAL_V1"
CASE_STARTED = "NEW_CAUSAL_INFORMATION_FUTURES_CAPTURE_STARTED_V1"
CASE_INVALID = "NEW_CAUSAL_INFORMATION_FUTURES_CAPTURE_INVALID_V1"
NEXT_WAIT_FIRST_DAY = "START_FIRST_NEW_INFO_CAPTURE_WINDOW_0755_1130_JST_V1"
NEXT_LIVE_COMMAND = "RUN_NEW_INFO_LIVE_CAPTURE_0755_1130_JST_V1"
NEXT_ACCUMULATE = "ACCUMULATE_FIRST_10_FULL_NEW_INFO_DAYS_V1"
NEXT_MECHANISM = "FUTURES_CONTEXT_CAUSAL_MECHANISM_DISCOVERY_V1"
PREPARE_OPERATOR_COMMAND = (
    "python kabu_native\\scripts\\run_futures_market_context_capture.py "
    "--prepare-only --trading-date 20260911"
)
LIVE_OPERATOR_COMMAND = (
    "python kabu_native\\scripts\\run_futures_market_context_capture.py "
    "--live --trading-date 20260911"
)

TRUE_OOS = False
CERTIFIED = False
V5_RESCUE = False

assert ANALYSIS_ID == "FUTURES_MARKET_CONTEXT_ACQUISITION_V1"
assert REQUIRED_PARENT_VERDICT == "CURRENT_CAPTURE_BIDIRECTIONAL_INFORMATION_LIMIT_CONFIRMED_V1"
assert int(CORE_N) + int(DYNAMIC_N) + int(FUTURES_N) == int(TOTAL_REGISTRATION_N) == 50
assert FUTURES_EXCHANGE == 2
assert STOCK_EXCHANGE == 1
assert DERIV_MONTH == 0
assert TRUE_OOS is False
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert NEW_INFO_FROM_DAY == "20260911"
