"""NEW_INFORMATION_ACQUISITION_FEASIBILITY_DESIGN_V1. Feasibility only. No purchase. No strategy. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)

ANALYSIS_ID = "NEW_INFORMATION_ACQUISITION_FEASIBILITY_DESIGN_V1"
PARENT_ID = "NEW_INFORMATION_SOURCE_POLICY_DECISION_V1"
REQUIRED_PARENT_VERDICT = "EXTERNAL_CAUSAL_INFORMATION_SOURCE_POLICY_SELECTED_V1"
REQUIRED_PARENT_NEXT = "NEW_INFORMATION_ACQUISITION_FEASIBILITY_DESIGN_V1"
REQUIRED_SELECTED_SOURCE = "EXCHANGE_NATIVE_ORDER_EVENT_FEED"
REQUIRED_POLICY_SHA256 = "51f493e48727b6fbff5359e79a44c358de19d41b41a7f309330d8b818590ea3b"

LEGACY_DEV_DAYS = DEVELOPMENT_DAYS
QUARANTINE_DAYS = ("20260903", "20260904")
MBO_ERA_START = "20241105"
MIN_REQUIRED_RESEARCH_DAYS = 30
NEW_DEV_MIN_VALID_DAYS = 20
NEW_DEV_MIN_CALENDAR_WEEKS = 4
TRUE_OOS_MIN_VALID_DAYS = 10

CASE_A = "FLEX_MBO_ACQUISITION_TECHNICALLY_FEASIBLE_V1"
CASE_B = "FLEX_MBO_FEASIBILITY_REQUIRES_PROVIDER_CONFIRMATION_V1"
CASE_C = "FLEX_MBO_FEASIBILITY_BLOCKED_BY_PROTOCOL_GAPS_V1"
CASE_D = "FLEX_MBO_ACQUISITION_NOT_FEASIBLE_V1"
NEXT_A = "FLEX_MBO_ACQUISITION_APPROVAL_AND_BUDGET_DECISION_V1"
NEXT_B = "FLEX_MBO_PROVIDER_CONFIRMATION_PLAN_V1"
NEXT_C = "FLEX_MBO_CONNECTION_SPEC_RESOLUTION_V1"
NEXT_D = "EXTERNAL_INFORMATION_SOURCE_POLICY_REASSESS_AFTER_FLEX_MBO_FAIL_V1"

MARKET_DATA_PURCHASED = False
HISTORICAL_DATA_DOWNLOADED = False
LIVE_FEED_STARTED = False
ACCOUNT_CREATED = False
SUBSCRIPTION_CHANGED = False
CONTRACT_SIGNED = False
API_KEY_CREATED = False
COLLECTOR_IMPLEMENTED = False
CAPTURE_SCHEMA_CHANGED = False
SOURCE_SEMANTIC_BOUNDARY_CHANGED = False
RESEARCH_METHOD_FROZEN = False
NETWORK_LATENCY_ALPHA_ALLOWED = False
MICROTIMING_RESEARCH_ALLOWED = False
LIVE_TECHNICAL_CALIBRATION_REQUIRED = True
EXPOSED_DAY_REUSE_WITH_NEW_SOURCE_ALLOWED = False
FUTURE_DATASET_DATES_ASSIGNED = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

assert ANALYSIS_ID == "NEW_INFORMATION_ACQUISITION_FEASIBILITY_DESIGN_V1"
assert REQUIRED_POLICY_SHA256 == "51f493e48727b6fbff5359e79a44c358de19d41b41a7f309330d8b818590ea3b"
assert REQUIRED_SELECTED_SOURCE == "EXCHANGE_NATIVE_ORDER_EVENT_FEED"
assert MARKET_DATA_PURCHASED is False
assert HISTORICAL_DATA_DOWNLOADED is False
assert COLLECTOR_IMPLEMENTED is False
assert RESEARCH_METHOD_FROZEN is False
assert NETWORK_LATENCY_ALPHA_ALLOWED is False
assert MICROTIMING_RESEARCH_ALLOWED is False
assert LIVE_TECHNICAL_CALIBRATION_REQUIRED is True
assert EXPOSED_DAY_REUSE_WITH_NEW_SOURCE_ALLOWED is False
assert SOURCE_SEMANTIC_BOUNDARY_CHANGED is False
assert int(MIN_REQUIRED_RESEARCH_DAYS) == 30
assert MBO_ERA_START == "20241105"
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert QUARANTINE_DAYS == ("20260903", "20260904")
