"""PROFITABLE_MOVE_MECHANISM_DISCOVERY_V1. Find repeatable profitable-move mechanisms from sealed DEV. Not a Full Strategy."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BOARD_FRESHNESS_SEC,
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.simple_tech_entry_family import (
    BOARD_ASK_BID_QTY_MAX_RATIO,
    EMA_LONG,
    EMA_SHORT,
    EMA_SLOPE_BARS,
    RCI_CROSS_LEVEL,
    VOLUME_MEDIAN_BARS,
    VOLUME_MULT,
    WARMUP_BARS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS, PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "PROFITABLE_MOVE_MECHANISM_DISCOVERY_V1"
PARENT_ANALYSIS_ID = "NEW_FULL_STRATEGY_ARCHITECTURE_INVENTORY_AND_FREEZE_V3"
REQUIRED_PARENT_VERDICT = "NEW_FULL_STRATEGY_NO_JUSTIFIED_NEW_ARCHITECTURE_V3"

SESSION = "AM"
SHARES_LABEL = 100
FIXED_HORIZONS = (3, 5, 10)
PRIMARY_DISCOVERY_HORIZON = 5
BOARD_FRESHNESS_SEC = float(BOARD_FRESHNESS_SEC)
EVENT_N_MIN = 40
EVENT_DAY_N_MIN = 8
POSITIVE_BLOCK_MIN = 4
Q_VALUE_H5_MAX = 0.05
PERM_ITERS = 10000
PERM_SEED = 20260807
TOP_MECHANISM_N = 3
FEATURE_LOOKAHEAD_N = 0
HORIZON_SEARCH = False
NEW_NUMERIC_THRESHOLD_SEARCH = False
STRATEGY_EXIT_USED_FOR_DISCOVERY = False
INFORMATION_FAMILY_INVENTORY_AS_PRIMARY_NEXT = False
FULL_STRATEGY_FROZEN = False
FULL_CAUSAL_PORTFOLIO_RUN = False
TRUE_OOS = False
CERTIFIED = False
SIZING = False
V4_CLOSED = True
V4_RCA_RUN = False
V4_RETUNE = False
PREVIOUS_V5_PROPOSAL_WITHDRAWN = True
ELIGIBLE_PROPOSAL_N = 0
FULL_STRATEGY_SPEC_SHA256_V5 = None

CASE_A = "PROFITABLE_MOVE_MECHANISM_FOUND_V1"
CASE_B = "ONLY_CLOSED_MECHANISMS_SHOW_EDGE_V1"
CASE_C = "NO_STABLE_PROFITABLE_MOVE_MECHANISM_FOUND_V1"
NEXT_A = "FULL_STRATEGY_FROM_DISCOVERED_MECHANISM_V1"
NEXT_B = "CLOSED_EDGE_TO_FULL_STRATEGY_DECISION_V1"
NEXT_C = "DISCOVERY_SEARCH_SPACE_REASSESSMENT_V1"
INVENTORY_NEXT_FORBIDDEN = "NEW_INFORMATION_FAMILY_INVENTORY_V1"

TEMPLATE_ORDER = ("A_SINGLE_STATE", "B_ONSET", "C_CROSS_FAMILY_PAIR", "D_ONE_STEP_SEQUENCE", "E_ONSET_WITH_CONTEXT")

assert ANALYSIS_ID == "PROFITABLE_MOVE_MECHANISM_DISCOVERY_V1"
assert REQUIRED_PARENT_VERDICT == "NEW_FULL_STRATEGY_NO_JUSTIFIED_NEW_ARCHITECTURE_V3"
assert INFORMATION_FAMILY_INVENTORY_AS_PRIMARY_NEXT is False
assert NEXT_C != INVENTORY_NEXT_FORBIDDEN
assert NEXT_A != PFQ_RECON_FORBIDDEN
assert tuple(FIXED_HORIZONS) == (3, 5, 10)
assert int(PRIMARY_DISCOVERY_HORIZON) == 5
assert HORIZON_SEARCH is False
assert NEW_NUMERIC_THRESHOLD_SEARCH is False
assert STRATEGY_EXIT_USED_FOR_DISCOVERY is False
assert FEATURE_LOOKAHEAD_N == 0
assert FULL_STRATEGY_FROZEN is False
assert FULL_CAUSAL_PORTFOLIO_RUN is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert V4_RCA_RUN is False
assert V4_RETUNE is False
assert abs(float(BOARD_FRESHNESS_SEC) - 5.0) < 1e-12
assert abs(float(VOLUME_MULT) - 1.5) < 1e-12
assert int(VOLUME_MEDIAN_BARS) == 5
assert int(WARMUP_BARS) == int(EMA_LONG) + int(EMA_SLOPE_BARS)
assert abs(float(RCI_CROSS_LEVEL) + 80.0) < 1e-12
assert abs(float(BOARD_ASK_BID_QTY_MAX_RATIO) - 2.0) < 1e-12
assert len(DEVELOPMENT_DAYS) == 10
assert MAX_RESEARCH_DATE == "20260807"
assert len(FOLD_BLOCKS) == 5
assert int(EVENT_N_MIN) == 40
assert int(EVENT_DAY_N_MIN) == 8
assert int(POSITIVE_BLOCK_MIN) == 4
assert abs(float(Q_VALUE_H5_MAX) - 0.05) < 1e-12
assert int(TOP_MECHANISM_N) == 3
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert EMA_SHORT == 9 and EMA_LONG == 21
