"""NEW_FULL_STRATEGY_ARCHITECTURE_REDESIGN_V1. Final pre-economics execution hardening."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "NEW_FULL_STRATEGY_ARCHITECTURE_REDESIGN_V1"
ARCHITECTURE_ID = "CSB_MA_ONSET_X1_Z_MA_LOSS"
PARENT_V1 = "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V1"
PARENT_V2 = "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V2"
PARENT_V1_SHA256 = "f45d8c53790adbd385b623224a9ceece5b91c53e0fe764b439458f454a657b15"

CASE_FROZEN = "NEW_FULL_STRATEGY_CAUSAL_SEMANTICS_FROZEN"
CASE_UNIMPLEMENTABLE = "NEW_FULL_STRATEGY_ARCHITECTURE_UNIMPLEMENTABLE"
NEXT_IF_FROZEN = "NEW_FULL_STRATEGY_IMPLEMENTATION_AND_DEV_EVAL_V1"
NEXT_AFTER_UNIMPLEMENTABLE = None

SESSION = "AM"
AM_START_HM = (9, 0)
AM_END_HM = (11, 30)
SESSION_FLATTEN_HM = (11, 29)
SESSION_FLATTEN_T_LABEL = "11:29:00 JST"

Q1_NEW_LOGIC_COMPLETION_DIRECT = True
Q2_BLOCKING_WITHOUT_THIS_RUN = True
Q3_OLD_RCA_AS_PURPOSE = False

TRUE_OOS = False
CERTIFIED = False
SIZING = False
NEW_REPLAY = False
NEW_ARCHITECTURE_ECONOMICS_RUN = False
NEW_ARCHITECTURE_PNL_READ_N = 0
ANOTHER_PRECOMMIT_AFTER_PASS = False

ALPHA_MECHANISM_CHANGED = False
ENTRY_ALPHA_CHANGED = False
TECHNICAL_EXIT_CHANGED = False
PORTFOLIO_CAP_CHANGED = False
BAR_FINALIZATION_SEMANTICS_CLARIFIED = True
OPERATIONAL_SESSION_RULE_CHANGED = True

assert ANALYSIS_ID == "NEW_FULL_STRATEGY_ARCHITECTURE_REDESIGN_V1"
assert Q1_NEW_LOGIC_COMPLETION_DIRECT is True
assert Q2_BLOCKING_WITHOUT_THIS_RUN is True
assert Q3_OLD_RCA_AS_PURPOSE is False
assert NEXT_IF_FROZEN != PFQ_RECON_FORBIDDEN
assert POSITION_CAP == 5
assert SHARES == 100
assert SESSION_FLATTEN_HM == (11, 29)
assert AM_END_HM == (11, 30)
assert ALPHA_MECHANISM_CHANGED is False
assert TECHNICAL_EXIT_CHANGED is False
assert OPERATIONAL_SESSION_RULE_CHANGED is True
assert ANOTHER_PRECOMMIT_AFTER_PASS is False
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert TRUE_OOS is False
assert CERTIFIED is False
assert NEW_ARCHITECTURE_ECONOMICS_RUN is False
assert NEW_ARCHITECTURE_PNL_READ_N == 0
