"""P3-0: Fixed Anchor mechanism audit (clock timing × cross-sectional selection).

Research only. No new strategy. No Dynamic retune. No Runtime change.
Does not modify V1RNativeEntryLive / DualLane / CLOCK_GRID / ENTRY / EXIT / Universe.
Label: REUSED_HISTORY_MECHANISM_DIAGNOSTIC — never OOS / prospective / robust.
"""

from research.dynamic_anchor_p2_3 import FULL14, PREDECLARED_TOP3

ANALYSIS_ID = "P3_0_FIXED_ANCHOR_MECHANISM_AUDIT"
DOCUMENT_ID = "P3_0_CLOCK_TIMING_X_CROSS_SECTION"
TASK_LABEL = "REUSED_HISTORY_MECHANISM_DIAGNOSTIC"
CONTAMINATION_LABEL = "REUSED_HISTORY_DIAGNOSTIC_ONLY"

P1_RESULT_NAME = "CURRENT_RUNTIME_REPLAY"
P1_TRADES = 267
P1_PNL = 2289100.0
P1_PF = 3.5711557901830844
P1_MAXDD = -210300.0
P1_TOP3_TRADES = 100
P1_TOP3_PNL = 1938050.0
P1_REST11_TRADES = 167
P1_REST11_PNL = 351050.0
P1_REST11_PF = 1.4335556378905767

OLD_DYNAMIC_STATUS = "REJECTED_AS_FIXED_REPLACEMENT"
TRAIL10_STATUS = "P2_4B_TRAIL10_HYPOTHESIS_NOT_SUPPORTED"

CLOCK_OFFSETS_SEC = (-300, -180, -60, 60, 180, 300)

CLOCK_NOT_UNIQUELY_SPECIAL = "CLOCK_NOT_UNIQUELY_SPECIAL"
CLOCK_EXACT_TIME_SUPPORTED = "CLOCK_EXACT_TIME_SUPPORTED"
CLOCK_TIMING_MIXED = "CLOCK_TIMING_MIXED"

SELECTION_SUPPORTED = "SELECTION_SUPPORTED"
SELECTION_NOT_SUPPORTED = "SELECTION_NOT_SUPPORTED"
SELECTION_MIXED = "SELECTION_MIXED"

MECH_EXACT_CLOCK = "EXACT_CLOCK_TIMING"
MECH_SELECTION = "CROSS_SECTIONAL_SELECTION"
MECH_BOTH = "CLOCK_AND_SELECTION"
MECH_TOP3 = "TOP3_DOMINATED"
MECH_MIXED = "MIXED"
MECH_NONE = "NO_CLEAR_MECHANISM"

VERDICT_COMPLETE = "P3_0_FIXED_ANCHOR_MECHANISM_AUDIT_COMPLETE"
VERDICT_INTEGRITY = "P3_0_MATERIAL_INTEGRITY_ISSUE"
VERDICT_BLOCKED = "P3_0_BLOCKED"

LOT_QTY = 100
MAX_WORKERS = 2

FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = tuple(d for d in FULL14 if d not in PREDECLARED_TOP3)
