"""AM ENTRY information reassessment. Frozen OOF. Diagnostic only. No new model."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import F2_UNION, FEATURE_SETS, NORMS
from research.wait5_session_target_learnability import POS_REP_DENOM, POS_REP_MIN
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_ENTRY_INFORMATION_REASSESSMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
FINAL_SELECTION_N = 3
SLOTS = 3
MAJORITY_RATE = 0.50
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False
CANONICAL_FEATURES = tuple(F2_UNION)
SPEARMAN_MIN_N = 3
DAY_CONSISTENT_MIN_N = 2

PRIOR_ANALYSIS_ID = "AM_CONSTRAINED_EXECUTION_AWARE_TARGET_ARCHITECTURE_REASSESSMENT_V1"
PRIOR_VERDICT = "AM_CURRENT_SIGNALS_CANNOT_IDENTIFY_JOINT_SET"

PARITY_EXPECTED = {
    "ANY_FU_GOOD_RATE": 0.8055555555555556,
    "ANY_FUD_GOOD_RATE": 0.5416666666666666,
    "FRONTIER_FU_GOOD_RATE": 0.2777777777777778,
    "FRONTIER_FUD_GOOD_RATE": 0.0763888888888889,
    "FUD_GOOD_FILL_PERCENTILE_MEDIAN": 0.9627659574468085,
    "FUD_GOOD_EXECU_PERCENTILE_MEDIAN": 0.9456675917360469,
    "PRED_FILL_EXECU_SPEARMAN_MEDIAN": 0.9579310740580437,
    "FILL_ONLY_ON_FRONTIER_RATE": 1.0,
    "DIRECT_ON_FRONTIER_RATE": 1.0,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(FINAL_SELECTION_N) == 3
assert int(SLOTS) == 3
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(POS_REP_MIN) == 6
assert int(POS_REP_DENOM) == 9
assert len(CANONICAL_FEATURES) == len(F2_UNION)

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
NEW_TARGET_CREATED = False
FEATURE_SEARCH = False
FEATURE_SEARCH_N = 0
NEW_FEATURE_N = 0
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
WEIGHT_SEARCH = False
STAGE1_ALLOWED = False
STAGE2_ALLOWED = False
SHORTLIST_SEARCH = False
P_FILL_TIMES_U_PRED = False
D_TRAINING_TARGET_ALLOWED = False
W10_ADOPTED = False
WAIT_SEARCH_N = 0
MODEL_REFIT_N = 0
SELECTION_REOPTIMIZATION_N = 0
ORACLE_SELECTION_USE_N = 0
POLICY_FROM_PARETO_N = 0
POLICY_FROM_ACTUAL_N = 0
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
ENTRY_RETRAIN_STARTED = False
W5_RUNTIME_ADOPTED = False
FROZEN_OOF_REPLAY_ONLY = True
PARETO_AS_STRATEGY = False
