"""E1_X6_TAER_FAILURE_SOURCE_ANALYSIS_V2 — diagnostic only; no TAER V2 / new family."""

ANALYSIS_ID = "E1_X6_TAER_FAILURE_SOURCE_ANALYSIS_V2"
CANONICAL_RUN = "e1x6_taer_integrity_20260804_004800"
CANONICAL_VERDICT = "E1_X6_NO_ROBUST_ENTRY_EXIT_PAIR"
