"""P3-1: decompose Fixed selection into execution vs directional edge.

Research only. No new strategy. No ENTRY / EXIT / Clock / Runtime change.
Uses P3-0R corrected harvest-time diagnostic as SoT.
Label: REUSED_HISTORY_MECHANISM_DIAGNOSTIC.
"""

from research.fixed_anchor_mechanism_audit_p3_0 import (
    CLOCK_EXACT_TIME_SUPPORTED,
    CLOCK_NOT_UNIQUELY_SPECIAL,
)
from research.fixed_selection_diagnostic_reconcile_p3_0r import (
    FULL14,
    PREDECLARED_TOP3,
    REST11,
)

ANALYSIS_ID = "P3_1_FIXED_SELECTION_EDGE_DECOMPOSITION"
DOCUMENT_ID = "P3_1_EXECUTION_VS_DIRECTIONAL"
TASK_LABEL = "REUSED_HISTORY_MECHANISM_DIAGNOSTIC"

CLOCK_FULL14 = CLOCK_EXACT_TIME_SUPPORTED
CLOCK_REST11 = CLOCK_NOT_UNIQUELY_SPECIAL

SOT_SELECTED_N = 1115
SOT_SELECTED_FILL_N = 286
SOT_SELECTED_FILL_RATE = 0.25650224215246636
SOT_NOT_SELECTED_N = 9943
SOT_NOT_SELECTED_FILL_N = 291
SOT_NOT_SELECTED_FILL_RATE = 0.02926682087901036

HORIZONS_SEC = (60, 180, 600)
FILL_BUCKETS_MS = (100, 250, 500, 1000)
WAIT_SEC = 1.0

EXEC_SUPPORTED = "EXECUTION_EDGE_SUPPORTED"
EXEC_MIXED = "EXECUTION_EDGE_MIXED"
EXEC_NOT = "EXECUTION_EDGE_NOT_SUPPORTED"

DIR_SUPPORTED = "DIRECTIONAL_EDGE_SUPPORTED"
DIR_MIXED = "DIRECTIONAL_EDGE_MIXED"
DIR_NOT = "DIRECTIONAL_EDGE_NOT_SUPPORTED"

EDGE_EXEC_DOM = "EXECUTION_DOMINANT"
EDGE_DIR_DOM = "DIRECTIONAL_DOMINANT"
EDGE_BOTH = "EXECUTION_AND_DIRECTIONAL"
EDGE_EXEC_DIR_MIXED = "EXECUTION_SUPPORTED_DIRECTIONAL_MIXED"
EDGE_DIR_EXEC_MIXED = "DIRECTIONAL_SUPPORTED_EXECUTION_MIXED"
EDGE_MIXED = "MIXED"
EDGE_NONE = "NO_SELECTION_EDGE"

VERDICT_OK = "P3_1_SELECTION_EDGE_DECOMPOSITION_COMPLETE"
VERDICT_ISSUE = "P3_1_MATERIAL_DIAGNOSTIC_ISSUE"
VERDICT_BLOCKED = "P3_1_BLOCKED"

MAX_WORKERS = 2
FULL14 = FULL14
PREDECLARED_TOP3 = PREDECLARED_TOP3
REST11 = REST11
