"""Sector-state to symbol transmission precommit. No symbol future-return betas."""
from __future__ import annotations

PROGRAM_ID = "CAUSAL_DRIVER_PB1_FOUNDATION"
PRECOMMIT_ID = "SECTOR_STATE_SYMBOL_TRANSMISSION_PRECOMMIT_V1"
ANALYSIS_ID = "SECTOR_STATE_SYMBOL_TRANSMISSION_PRECOMMIT_V1"

CASE_READY = "SECTOR_STATE_SYMBOL_TRANSMISSION_PRECOMMIT_READY_V1"
CASE_BLOCKED = "SECTOR_STATE_SYMBOL_TRANSMISSION_PRECOMMIT_BLOCKED_V1"
NEXT_RUN = "RUN_SECTOR_STATE_SYMBOL_TRANSMISSION_V1"
NEXT_RESOLVE = "RESOLVE_SECTOR_STATE_SYMBOL_TRANSMISSION_PRECOMMIT_BLOCKERS_V1"

PARENT_ANALYSIS_ID = "SECTOR_BREADTH_DISPERSION_NONOVERLAP_OFFSET_CORRECTION_V1"
PARENT_VERDICT = "SECTOR_BREADTH_DISPERSION_CAUSAL_LEAD_FOUND_V1"
PARENT_NEXT = "PRECOMMIT_SECTOR_STATE_SYMBOL_TRANSMISSION_V1"
PARENT_PRECOMMIT_ID = "SECTOR_BREADTH_DISPERSION_CAUSAL_DISCOVERY_PRECOMMIT_V1_3"
PARENT_PRECOMMIT_SHA256 = "83c2b92056941f5cae72d1123499c549e9e34ea3280d3ec4588e63a261509a80"

FAMILY_N = 270
GLOBAL_TARGET_N = 105
SECTOR3650_TARGET_N = 30
GLOBAL_HYPOTHESIS_N = 210
SECTOR_HYPOTHESIS_N = 60

DISCOVERY_MIN_VALID_DATES = 60
FV_MIN_INPUT_VALID_DATES = 20
COVERAGE_FLOOR_N = 5
COVERAGE_FRACTION = 0.10
GLOBAL_MIN_DISTINCT_SECTORS = 4
GLOBAL_MAX_SECTOR_SHARE = 0.40

BOOTSTRAP_N = 2000
DISCOVERY_BOOTSTRAP_SEED = 20240917
FV_BOOTSTRAP_SEED = 20260422
FDR_Q = 0.05
BH_FAMILY_M = 270
T6_ABS_RATIO = 0.50
F5_ABS_RATIO = 0.50

DRIVER_AGE_SEC = 60
TARGET_AGE_SEC = 120
PAST_CONTROL_MIN = 5
SECTOR_PEER_MIN_N = 2
SECTOR_PEER_MIN_FRAC = 0.80
