"""Precommit one directional-volume repair. No PnL and no range-break combination."""
from __future__ import annotations

from research.causal_driver_pb1.phase1.dates import assert_ingest_date_allowed

_ = assert_ingest_date_allowed

ANALYSIS_ID = "PRECOMMIT_SYMBOL_SETUP_DIRECTIONAL_VOLUME_CONFIRMATION_V1"
COMPLETE_STRATEGY_ID = "SYMBOL_SETUP_BASELINE_COMPLETE_STRATEGY_V1"
COMPLETE_STRATEGY_SHA256 = "25d8ef6944c4d82a15d57a3bb078e5503f733184ecb92ee5ad6ba95fe4f95f6d"
PRIMARY_DEFICIENCY = "SYMBOL_SETUP_EDGE_NOT_ESTABLISHED"
REPAIR_ID = "SYMBOL_SETUP_DIRECTIONAL_VOLUME_CONFIRMATION_V1"
RANGE_BREAK_REPAIR_ID = "SYMBOL_SETUP_PULLBACK_RANGE_BREAK_TRIGGER_V1"
RANGE_BREAK_STATUS = "NOT_SUPPORTED"
RCI_PASS_N = 457
VOLUME_PASS_N = 161
PRICE_ACTION_PASS_N = 121
PRIMARY_HORIZON_SEC = 180
SUPPORT_MIN_N = 30
FIELD_COVERAGE_MIN = 0.95
CLASSIFICATION_FRACTION_MIN = 0.50
PERIOD_GAP_MAX = 0.25
VERDICT_CLOSED = "FAIL_CLOSED"
VERDICT_UNRESOLVED = "SYMBOL_SETUP_DIRECTIONAL_VOLUME_DATA_CONTRACT_UNRESOLVED_V1"
VERDICT_INSUFFICIENT = "SYMBOL_SETUP_DIRECTIONAL_VOLUME_DATA_INSUFFICIENT_V1"
VERDICT_PARITY = "POPULATION_PARITY_FAIL"
VERDICT_READY = "SYMBOL_SETUP_DIRECTIONAL_VOLUME_PRECOMMIT_READY_V1"
NEXT_STOP_REPAIR = "STOP_DIRECTIONAL_VOLUME_REPAIR_V1"
NEXT_STOP = "STOP"
NEXT_RESEARCH = "RUN_SYMBOL_SETUP_DIRECTIONAL_VOLUME_MECHANISM_RESEARCH_V1"
