"""C1_MULTI_TIMEFRAME_PRECOMMIT_V1. Freeze 10 same-family MTF identities. No economics."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_ID, CANARY_SOURCE
from research.systematic_state_transition_library_precommit_v1 import (
    FOLD_BLOCKS,
    OR_FINAL_STATUS,
    PFQ_DOCUMENT_ID,
    PFQ_LINE,
    PFQ_RECON_FORBIDDEN,
    PFQ_VERDICT,
)

ANALYSIS_ID = "C1_MULTI_TIMEFRAME_PRECOMMIT_V1"
ARCHITECTURE_CLASS = "C1_MULTI_TIMEFRAME"
C4_CLASS = "C4_PORTFOLIO_CROWDING"

CASE_A = "C1_MULTI_TIMEFRAME_LIBRARY_FROZEN"
CASE_B = "C1_MULTI_TIMEFRAME_SPACE_ALREADY_EXHAUSTED"
CASE_E = "C1_MULTI_TIMEFRAME_PRECOMMIT_INTEGRITY_FAILED"

NEXT_IF_A = "C1_MULTI_TIMEFRAME_FULL_STRATEGY_V1"
NEXT_IF_B = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V1"

PRIOR_ANALYSIS_ID = "NEW_ARCHITECTURE_CLASS_RETHINK_V1"
PRIOR_VERDICT_REQUIRED = "NEW_ARCHITECTURE_CLASS_FOUND"
PRIOR_SELECTED_REQUIRED = "C1_MULTI_TIMEFRAME"

STATE_IDS = (
    "S_MA_TREND_UP",
    "S_BB_ABOVE_MID",
    "S_RCI_ABOVE_NEG80",
    "S_VOL_CONFIRM_1M",
    "S_CLOSE_ABOVE_VWAP",
)
HTF_IDS = ("HTF_3M", "HTF_5M")
HTF_WIDTH_SEC = {"HTF_3M": 180.0, "HTF_5M": 300.0}
RAW_CANDIDATE_IDS = (
    "MTF_3M__S_MA_TREND_UP",
    "MTF_5M__S_MA_TREND_UP",
    "MTF_3M__S_BB_ABOVE_MID",
    "MTF_5M__S_BB_ABOVE_MID",
    "MTF_3M__S_RCI_ABOVE_NEG80",
    "MTF_5M__S_RCI_ABOVE_NEG80",
    "MTF_3M__S_VOL_CONFIRM_1M",
    "MTF_5M__S_VOL_CONFIRM_1M",
    "MTF_3M__S_CLOSE_ABOVE_VWAP",
    "MTF_5M__S_CLOSE_ABOVE_VWAP",
)

BUCKET_ORIGIN_HM = (9, 0)
BUCKET_ORIGIN_LABEL = "09:00:00 JST"
SESSION = "AM"
MAX_RAW_CANDIDATE_N = 10

assert ANALYSIS_ID == "C1_MULTI_TIMEFRAME_PRECOMMIT_V1"
assert CASE_A != CASE_B != CASE_E
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert len(STATE_IDS) == 5
assert len(RAW_CANDIDATE_IDS) == 10
assert len(DEVELOPMENT_DAYS) == 10
assert len(BURNED_HOLDOUT_DAYS) == 8
assert len(STRESS_DAYS) == 4
assert MAX_RESEARCH_DATE == "20260807"
assert POSITION_CAP == 5
assert SHARES == 100
assert CANARY_ID == "RECOVERY_R2_X1_Z3"
assert CANARY_SOURCE
assert CANARY_EXPECTED
assert FOLD_BLOCKS
assert FORBIDDEN_INPUT_DAYS
assert OR_FINAL_STATUS
assert PFQ_DOCUMENT_ID and PFQ_VERDICT and PFQ_LINE
assert abs(HTF_WIDTH_SEC["HTF_3M"] - 180.0) < 1e-12
assert abs(HTF_WIDTH_SEC["HTF_5M"] - 300.0) < 1e-12
