"""AM WAIT5 Stage2 quality-objective reassessment. Frozen OOF replay only. No new model."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, NORMS
from research.wait5_session_target_learnability import POS_REP_DENOM, POS_REP_MIN
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_WAIT5_STAGE2_QUALITY_OBJECTIVE_REASSESSMENT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
MAX_WORKERS = 2
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_ANALYSIS_ID_REQUIRED = "AM_WAIT5_TWO_STAGE_PRECOMMITTED_DEVELOPMENT_V1"
PRIOR_VERDICT_REQUIRED = "AM_WAIT5_STAGE2_SINGLE_COMPONENT_ONLY"

STAGE1_SHORTLIST_N = 5
FINAL_SELECTION_N = 3
SLOTS = 3
SPEARMAN_MIN_N = 3
SAME_FILL_FREQUENT_MIN = 0.50
SAME_FILL_RARE_MAX = 0.20

PARITY_EXPECTED = {
    "FILL_ONLY_FILL_RATE": 0.4375,
    "TWO_STAGE_FILL_RATE": 0.4074074074074074,
    "DELTA_EXEC_U_VS_FILL_ONLY": -0.0004926072013832835,
    "DELTA_EXEC_D_VS_FILL_ONLY": 0.0004946688386588023,
    "TWO_STAGE_NE_FILL_ONLY_COHORT_RATE": 0.8819444444444444,
    "FILL_ONLY_COND_U": 0.010184098639284996,
    "TWO_STAGE_COND_U": 0.009385227050990586,
    "FILL_ONLY_COND_D": -0.009080470762772642,
    "TWO_STAGE_COND_D": -0.008971961696910573,
}

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(STAGE1_SHORTLIST_N) == 5
assert int(FINAL_SELECTION_N) == 3
assert int(SLOTS) == 3
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert int(POS_REP_MIN) == 6
assert int(POS_REP_DENOM) == 9
assert COMMON_AM_PM_MODEL_ALLOWED is False

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
BEST_REPRESENTATION_ADOPTED = False
HYPERPARAMETER_TUNING = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
SHORTLIST_SEARCH = False
WEIGHT_SEARCH = False
U_D_SCALARIZATION = False
PROBABILITY_THRESHOLD = False
FILLABILITY_CUTOFF_SEARCH = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
FINAL_MODEL_ADOPTED = False
FROZEN_OOF_REPLAY_ONLY = True
RETRAINING_NEW_FAMILY = False
