"""PB1 V4 Complete Strategy Economic Confirmation 1. Frozen strategy. OC economics once.

Does not mutate Frozen V4 or the frozen Complete Strategy package.
Does not open Frozen Validation economics or prospective.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.pb1_v4_complete_strategy_build_and_economic_validation import (
    CAP,
    COST_MODEL_ID,
    EXPECTED_MACHINE_SHA256,
    EXPECTED_SOURCE_INVENTORY_SHA256,
    FROZEN_ENTRY_IDENTITY,
    HISTORICAL_FILL_ID,
    LIVE_FILL_SOT_ID,
    OPS_EXIT_ID,
    SHARES,
    TECHNICAL_EXIT_ID,
)
from research.pb1_v4_complete_strategy_build_and_economic_validation.freeze import COMPLETE_STRATEGY_IDENTITY
from research.pb1_v4_frozen_old_confirmation_blind_validation import EVAL_FIRST, EVAL_LAST, FV_FIRST, FV_LAST, PROSPECTIVE_FROM

PROGRAM_ID = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_CONFIRMATION1"
ANALYSIS_ID = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_CONFIRMATION1_V1"
PRECOMMIT_ID = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_CONFIRMATION1_PRECOMMIT_V1"

EXPECTED_ENTRY_ID = "PB1_V4_CLARIFIED_MACHINE_CORRECTION_V4_FROZEN_V1"
EXPECTED_COMPLETE_STRATEGY_ID = "PB1_V4_COMPLETE_STRATEGY_FROZEN_V1"
EXPECTED_COMPLETE_STRATEGY_SHA256 = "556542319d22dff40cc1758b24d44d2ecb1985b8595927ca8f80618126961bf8"
EXPECTED_OC_E0 = 47
EXPECTED_OC_E1 = 103

assert FROZEN_ENTRY_IDENTITY == EXPECTED_ENTRY_ID
assert COMPLETE_STRATEGY_IDENTITY == EXPECTED_COMPLETE_STRATEGY_ID
assert CAP == 5
assert SHARES == 100
assert HISTORICAL_FILL_ID == "HISTORICAL_NEXT_BAR_OPEN_EXECUTION"
assert LIVE_FILL_SOT_ID == "X1_IMMEDIATE_ASK"
assert COST_MODEL_ID == "X1_8BPS_EXECUTION_STRESS"
assert TECHNICAL_EXIT_ID == "PB1_V4_THESIS_LOST_NEXT_OPEN"
assert OPS_EXIT_ID == "SESSION_FLAT_1520"
assert EVAL_FIRST == "20251127"
assert EVAL_LAST == "20260421"
assert EXPECTED_MACHINE_SHA256 == "8d9c79b644616146ad01100e27f34368460d4c032d955d0ced2aab171fbfb6cf"
assert EXPECTED_SOURCE_INVENTORY_SHA256 == "12299debc918a8b509c4105bc60448e0990c15748ded62ab72cbdf050886e4cf"

CASE_PASS = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_CONFIRMATION1_PASS_V1"
CASE_FAIL = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_CONFIRMATION1_FAIL_V1"
CASE_INVALID = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_CONFIRMATION1_INVALID_REPLAY"
CASE_HASH = "DO_NOT_OPEN_ECONOMIC_CONFIRMATION1"
NEXT_CONF2 = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_CONFIRMATION2_V1"
NEXT_DECOMP = "PB1_V4_COMPLETE_STRATEGY_ECONOMIC_FAILURE_DECOMPOSITION_V1"
NEXT_STOP = "STOP"

KNOWN_THESIS_LOST_REASONS = (
    "STALE_RANGE_RESOLUTION",
    "FAILED_BREAK_REACCEPTED",
    "REPEATED_OR_RECROSS",
    "DISPLACEMENT_UNWOUND",
    "ACCEPTED_STRUCTURAL_FAILURE",
)

FEATURE_MINING = FEATURE_MINING_CLOSED
_ = (FV_FIRST, FV_LAST, PROSPECTIVE_FROM, FEATURE_MINING)
