"""FUTURES_X_STOCK_STATE_INTERACTION_DAY1_V1.

Same futures state: does stock-specific state split later results?
Does that TOP-BOTTOM spread change with frozen futures context?

Not strategy. No futures-only retest. No breadth/ranking. 20260911 FULL only.
"""
from __future__ import annotations

from research.futures_context_day1_effect_check_v1 import (
    ANCHOR_HM,
    EARLY_HM,
    HORIZON_LABEL,
    HORIZONS_SEC,
    LATE_HM,
)

ANALYSIS_ID = "FUTURES_X_STOCK_STATE_INTERACTION_DAY1_V1"
PARENT_ID = "FUTURES_MICROSTRUCTURE_PRESSURE_DAY1_V1"
KIND = "NEW_INFO_DEV_CONSTRUCTION_ONLY"
TRADING_DATE = "20260911"

SELECTORS = (
    "SPREAD_BPS",
    "OBSERVED_TRADE_N_180S",
    "TRADING_VALUE_DELTA_180S",
    "BID_UPDATE_N_60S",
    "UNDER_BUY_QTY",
    "OVER_SELL_QTY",
)

CONTEXT_FAMILIES = (
    "NK_RET_180S",
    "AGREEMENT_180S",
    "NK_VS_CASH_ALIGN_180S",
)

NK_BUCKETS = ("UP", "DOWN")
AGREEMENT_BUCKETS = ("BOTH_UP", "MIXED", "BOTH_DOWN")
ALIGN_BUCKETS = ("ALIGNED", "DISAGREED")

CONTEXT_SPECS = (
    ("NK_RET_180S", NK_BUCKETS),
    ("AGREEMENT_180S", AGREEMENT_BUCKETS),
    ("NK_VS_CASH_ALIGN_180S", ALIGN_BUCKETS),
)

TERCILE_N = 16
UNIVERSE_N = 48
MATERIAL_BPS = 5.0
MIN_CONTEXT_CLOCK_N = 3
LOOKBACK_RET_SEC = 180
OTU_WINDOW_SEC = 180
BID_UPD_WINDOW_SEC = 60

CASE_A = "A"
CASE_B = "B"
CASE_C = "C"
VERDICT_A = "FUTURES_X_STOCK_STATE_EXECUTABLE_CANDIDATE_DAY1_V1"
VERDICT_B = "FUTURES_X_STOCK_STATE_RELATIVE_EFFECT_ONLY_DAY1_V1"
VERDICT_C = "FUTURES_X_STOCK_STATE_NO_USEFUL_INTERACTION_DAY1_V1"
NEXT_A = "FREEZE_EXACT_INTERACTION_FOR_DAY2_CONFIRMATION_V1"
NEXT_B = "CONFIRM_EXACT_INTERACTION_ON_DAY2_V1"
NEXT_C = "DO_NOT_USE_SIMPLE_FUTURES_CONTEXT_FOR_STOCK_SELECTION_V1"

ENTRY = False
EXIT = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
TRUE_OOS = False
CERTIFIED = False

FROZEN_COMPARISON_N = (
    len(SELECTORS)
    * sum(len(buckets) for _name, buckets in CONTEXT_SPECS)
    * len(HORIZONS_SEC)
)

assert SELECTORS == (
    "SPREAD_BPS",
    "OBSERVED_TRADE_N_180S",
    "TRADING_VALUE_DELTA_180S",
    "BID_UPDATE_N_60S",
    "UNDER_BUY_QTY",
    "OVER_SELL_QTY",
)
assert len(SELECTORS) == 6
assert TERCILE_N == 16
assert UNIVERSE_N == 48
assert MATERIAL_BPS == 5.0
assert LOOKBACK_RET_SEC == 180
assert len(ANCHOR_HM) == 13
assert ANCHOR_HM[0] == (9, 10)
assert ANCHOR_HM[-1] == (11, 10)
assert len(EARLY_HM) == 6
assert len(LATE_HM) == 7
assert ENTRY is False and EXIT is False
assert RUNTIME_CHANGED is False and PAPER_CHANGED is False
assert FROZEN_COMPARISON_N == 6 * 7 * 4
assert "AGREEMENT" not in CONTEXT_FAMILIES  # 180s family only; not Day1 60s AGREEMENT
assert HORIZONS_SEC == (60, 180, 300, 600)
assert HORIZON_LABEL[600] == "10m"
