"""GENERALIZATION_FAILURE_RCA_V1. Existing-artifact RCA. No new replay/filter."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "GENERALIZATION_FAILURE_RCA_V1"
REBASE_ANALYSIS_ID = "RESEARCH_OBJECTIVE_REBASE_V1"
REBASE_VERDICT_REQUIRED = "RESEARCH_OBJECTIVE_REBASED_TO_GENERALIZATION_RCA"
REBASE_DEFICIENCY_REQUIRED = "AGGREGATE_EDGE_GENERALIZATION_FAILURE"
REBASE_NEXT_REQUIRED = "GENERALIZATION_FAILURE_RCA_V1"

CASE_A = "GENERALIZATION_FAILURE_MIXED_MECHANISMS"
CASE_B = "GENERALIZATION_FAILURE_SYMBOL_MODE_SUPPORTED"
CASE_C = "GENERALIZATION_FAILURE_DAY_MODE_SUPPORTED"
CASE_D = "GENERALIZATION_FAILURE_MIXED_CONCENTRATION"
CASE_E = "GENERALIZATION_FAILURE_SELECTION_SURFACE_SUPPORTED"
CASE_F = "GENERALIZATION_FAILURE_RCA_INCONCLUSIVE"
CASE_INTEGRITY = "GENERALIZATION_FAILURE_RCA_INTEGRITY_FAILED"

NEXT_IF_A = "GENERALIZATION_FAILURE_COMPONENT_RCA_V1"
NEXT_IF_B = "CROSS_SYMBOL_TRANSFER_MECHANISM_RCA_V1"
NEXT_IF_C = "DAY_STATE_MECHANISM_RCA_V1"
NEXT_IF_D = "GENERALIZATION_FAILURE_COMPONENT_RCA_V1"
NEXT_IF_E = "SELECTION_SURFACE_MECHANISM_RCA_V1"
NEXT_IF_F = "GENERALIZATION_FAILURE_EVIDENCE_GAP_V1"

ST_WINNER_ID = "ST_HANDOFF_NEXT__S_CLOSE_ABOVE_VWAP__S_RCI_ABOVE_NEG80"
ST_BASE_PNL = 220580.0
ST_BASE_PF = 2.7365769170209417
ST_CAUSAL_PNL = 77580.0
ST_CAUSAL_PF = 1.61076995748701
ST_TRAIN_TOP3_N = 2
ST_FOLD_TEST_PNL = -67720.0

EXPECTED_ST_G1G2_N = 7
EXPECTED_C1_G1G2_N = 4
EXPECTED_RECOVERY_G1G2_N = 2
PRIMARY_E1_STRATEGY_N = 13

G2_MIN_PF = 1.10

TRUE_OOS = False
CERTIFIED = False
SIZING = False
NEW_REPLAY = False
NEW_FULL_CAUSAL_RUN = False
NEW_PNL_SIMULATION = False
NEW_FOLD_RUN = False
NEW_ENTRY = False
NEW_EXIT = False
NEW_THRESHOLD = False
NEW_CANDIDATE = False
RAW_CAPTURE_READ_N = 0
E4_PRIMARY_VOTE = False
L3_PRIMARY_VOTE = False
E4_CAN_CHANGE_CASE = False
D3_DECISION_ELIGIBLE_DEFAULT = False

assert ANALYSIS_ID == "GENERALIZATION_FAILURE_RCA_V1"
assert PRIMARY_E1_STRATEGY_N == EXPECTED_ST_G1G2_N + EXPECTED_C1_G1G2_N + EXPECTED_RECOVERY_G1G2_N == 13
assert E4_PRIMARY_VOTE is False
assert L3_PRIMARY_VOTE is False
assert NEW_REPLAY is False
assert RAW_CAPTURE_READ_N == 0
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
