"""SECTOR_SYMBOL_DRIVER_RESPONSE_MAPPING_V1. Map drivers to sectors/stocks. No global strategy. No purchase."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "COMPLETE_CAUSAL_STRATEGY_RESEARCH_V1"
ANALYSIS_ID = "SECTOR_SYMBOL_DRIVER_RESPONSE_MAPPING_V1"
PARENT_ANALYSIS_ID = "IDENTIFY_MINIMUM_MISSING_EXTERNAL_CAUSAL_INFORMATION_V1"
PARENT_VERDICT = "HISTORICAL_FUTURES_SOURCE_NOT_AVAILABLE_V1"
KIND = "DRIVER_SECTOR_STOCK_RESPONSE_MAP"
SEMANTICS = "BAR_START"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_HM1_ANCHOR_SHA256 = "2b26609cce4f14f50c25a77727e2c77fc037261ea74965fa7e195a0c8cfb9e23"
HM1_ID = "HM1_CONTROLLED_PULLBACK_RECLAIM"
PROXY_NK = "1321"
PROXY_TOPIX = "1306"
PRIMARY_HORIZON_MIN = 5
FWD_HORIZONS = (1, 3, 5, 10, 15)
CLUSTER_K = 5
MIN_CLOCK_N = 200
MIN_DAY_N = 40
MIN_SECTOR_N_AT_CLOCK = 3

CASE_MAP = "SECTOR_SYMBOL_DRIVER_MAP_FOUND_V1"
CASE_SECTOR = "SECTOR_DRIVER_MAP_FOUND_STOCK_SPECIFICITY_WEAK_V1"
CASE_FUTURES = "TRUE_FUTURES_REQUIRED_FOR_KEY_DRIVER_GROUPS_V1"
CASE_INSUFFICIENT = "CURRENT_DRIVER_SET_INSUFFICIENT_V1"
CASE_BIND = "DRIVER_MAP_BIND_FAILED_V1"

NEXT_PLAYBOOKS = "BUILD_DRIVER_SPECIFIC_PLAYBOOKS_V1"
NEXT_SECTOR_PB = "BUILD_SECTOR_LEVEL_PLAYBOOKS_V1"
NEXT_FUT_GROUP = "ACCUMULATE_PROSPECTIVE_TRUE_FUTURES_BY_RESPONSE_GROUP_V1"
NEXT_EXPAND = "EXPAND_CAUSAL_DRIVER_CATALOG_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"
NEXT_PROSPECTIVE_SUBTRACK = "PROXY_PLUS_PROSPECTIVE_FUTURES_BRIDGE_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_USED_TO_DESIGN = False
HM1_TUNED = False
PURCHASE_REQUESTED = False
YFINANCE_USED = False
ENTRY_RULES_OPTIMIZED = False

assert ANALYSIS_ID == "SECTOR_SYMBOL_DRIVER_RESPONSE_MAPPING_V1"
assert PARENT_VERDICT == "HISTORICAL_FUTURES_SOURCE_NOT_AVAILABLE_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert KABU_50_APPLIED is False
assert PURCHASE_REQUESTED is False
assert PRIMARY_HORIZON_MIN == 5
assert CLUSTER_K == 5
assert ENTRY_RULES_OPTIMIZED is False
