"""SUPPORT_RESISTANCE_MATCHED_SEPARATION_NOT_A_STRATEGY_V1. Transportability and executable timing. Not a strategy."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE
from research.support_resistance_face_valid_first_interaction_rebuild_v1 import CONFIRM_ATR, ZONE_HALF_ATR

PROGRAM_ID = "SUPPORT_RESISTANCE_MATCHED_SEPARATION_NOT_A_STRATEGY_V1"
ANALYSIS_ID = "SUPPORT_RESISTANCE_MATCHED_SEPARATION_NOT_A_STRATEGY_V1"
PARENT_ANALYSIS_ID = "SUPPORT_RESISTANCE_FIRST_INTERACTION_MATCHED_CAUSAL_TEST_V1"
PARENT_VERDICT = "FACE_VALID_SR_MATCHED_PATH_SEPARATION_FOUND_V1"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_DETECTOR_SHA256 = "6e3060b71f8a4787b09d6b3c0f3ba9fa84c87712bf0f11b0165bfbfd1e0bf47e"
EXPECTED_STATE_MACHINE_SHA256 = "3c065f3757083fa6da792f9450e07504e902ea93d48391467a6bb7dca6e6a5b8"
EXPECTED_PRIMARY_FIRST_TEST_N = 2713

FROZEN_CONFIRM_ATR = 0.75
FROZEN_ZONE_HALF_ATR = 0.15
LUNCH_POLICY = "HOLD_THROUGH_LUNCH_RESUME_PM"
SESSION_FLAT = "15:20"
EVAL_BLOCKS = ("D2", "D3", "D4")
BOOT_N = 400
BOOT_SEED = 20260917
MIN_PAIR_N = 80
MIN_DAY_N = 25
MIN_SYMBOL_N = 10
PRIMARY_METRIC = "p20_before_m20"
SMD_MATERIAL = 0.25
P20_MATCH_GAP_MATERIAL = 0.05
PLACEBO_RATIO_MIN = 2.0
LOGISTIC_C = 1.0
PROPENSITY_MAX_CONTROLS = 60

CONTINUE_MECHANISMS = ("A", "C")
DIAGNOSTIC_ONLY = ("B", "D")

CASE_BOTH = "SR_A_AND_C_EXECUTABLE_MECHANISMS_SUPPORTED_V1"
CASE_A_ONLY = "SR_FIRST_TOUCH_ONLY_EXECUTABLE_MECHANISM_SUPPORTED_V1"
CASE_C_ONLY = "SR_RETEST_HOLD_ONLY_EXECUTABLE_MECHANISM_SUPPORTED_V1"
CASE_NOT_TRANSPORT = "SR_MATCHED_SEPARATION_NOT_TRANSPORTABLE_V1"
CASE_CONSUMED = "SR_SEPARATION_CONSUMED_BEFORE_EXECUTABLE_ENTRY_V1"
CASE_INFERENCE = "SR_INFERENCE_NOT_ROBUST_V1"
CASE_BIND = "SR_MATCHED_SEPARATION_BIND_FAILED_V1"
CASE_HASH = "SR_MATCHED_SEPARATION_DETECTOR_HASH_FAILED_V1"

NEXT_COMPLETE = "SUPPORT_RESISTANCE_MECHANISM_TO_COMPLETE_STRATEGY_V1"
NEXT_STOP = "STOP_SUPPORT_RESISTANCE_STRATEGY_PATH_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"
NEXT_HASH = "REPAIR_FROZEN_DETECTOR_HASH_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_OPENED = False
NEW_PAID_DATA = False
PROMOTED = False
V27_BOLTED = False
RCA_EXECUTED = False
NO_PNL_PARAMETER_TUNING = True
X0_X1_USED_TO_SELECT_RULES = False
DETECTOR_RETUNED = False
STRATEGY_SELECTED = False
MATCHABILITY_USED_AS_ENTRY_FILTER = False
A_VS_C_SELECTED_BY_EFFECT_SIZE = False
EXIT_OPTIMIZED = False
A1_CLASSIFICATION = "HISTORICAL_PASSIVE_EXECUTION_APPROXIMATION"

assert CONFIRM_ATR == FROZEN_CONFIRM_ATR == 0.75
assert ZONE_HALF_ATR == FROZEN_ZONE_HALF_ATR == 0.15
assert DETECTOR_RETUNED is False
assert STRATEGY_SELECTED is False
assert PARENT_VERDICT == "FACE_VALID_SR_MATCHED_PATH_SEPARATION_FOUND_V1"
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert OLD_CONFIRMATION_OPENED is False
assert MATCHABILITY_USED_AS_ENTRY_FILTER is False
assert A_VS_C_SELECTED_BY_EFFECT_SIZE is False
assert EXIT_OPTIMIZED is False
