"""Diagnose K=1 slope-loss noise. The frozen exit is not changed."""
from __future__ import annotations

from research.causal_driver_pb1.phase1.dates import assert_ingest_date_allowed

_ = assert_ingest_date_allowed

ANALYSIS_ID = "SYMBOL_SETUP_THESIS_EXIT_NOISE_RCA_V1"
COMPLETE_STRATEGY_ID = "SYMBOL_SETUP_BASELINE_COMPLETE_STRATEGY_V1"
COMPLETE_STRATEGY_SHA256 = "25d8ef6944c4d82a15d57a3bb078e5503f733184ecb92ee5ad6ba95fe4f95f6d"
EXIT_ID = "SYMBOL_SETUP_V1_LITERAL_MA_THESIS_LOSS_EXIT"
EXIT_SHA256 = "5962da204396b9f578dfa19becbbd39f88c30c71a8b768c4b1a1c7d232115e1b"
TECHNICAL_N = 121
BOARD_PASS_N = 44
FILL_N = 7
PRIMARY_DEFICIENCY = "SYMBOL_SETUP_EDGE_NOT_ESTABLISHED"
VERDICT_PARITY = "EXIT_NOISE_RCA_POPULATION_PARITY_FAIL"
VERDICT_CLOSED = "FAIL_CLOSED"
VERDICT_WARRANT = "SYMBOL_SETUP_EXIT_SLOPE_LOSS_PERSISTENCE_MECHANISM_WARRANTED_V1"
VERDICT_K1 = "SYMBOL_SETUP_EXIT_K1_NOISE_HYPOTHESIS_NOT_SUPPORTED_V1"
VERDICT_INSUFFICIENT = "SYMBOL_SETUP_EXIT_NOISE_EVIDENCE_INSUFFICIENT_V1"
NEXT_WARRANT = "PRECOMMIT_SYMBOL_SETUP_EXIT_PERSISTENCE_MECHANISM_V1"
NEXT_K1 = "KEEP_SYMBOL_SETUP_LITERAL_K1_EXIT_V1"
NEXT_INSUFFICIENT = "PRESERVE_EXIT_AND_COLLECT_MORE_CAUSAL_EVIDENCE_V1"
NEXT_STOP = "STOP"
CLOCKS = (60, 180, 300)
