"""PB1_PLAYBOOK_REDESIGN_V3.

Minimum coherent opening-range continuation redesign from trigger RCA + structural RCA.
NEW candidate machine. Do not mutate V2.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.pb1_opening_range_continuation_face_valid_v2 import (
    BREAK_BEYOND_ATR_FRAC,
    BREAK_BEYOND_OR_FRAC,
    BREAK_CLOSE_LOC,
    LAST_BREAK,
    LAST_TRIGGER,
    LEAVE_EXT_OR_FRAC,
    MIN_AWAY_BARS,
    OR_KNOWN_FROM,
    RETEST_FRESHNESS_MIN,
)
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE
from research.support_resistance_face_valid_first_interaction_rebuild_v1 import CONFIRM_ATR, ZONE_HALF_ATR

PROGRAM_ID = "PB1_PLAYBOOK_REDESIGN_V3"
ANALYSIS_ID = "PB1_PLAYBOOK_REDESIGN_V3"
PARENT_TRIGGER_RCA = "PB1_CAUSAL_PATH_FAILURE_RCA_V1"
PARENT_TRIGGER_VERDICT = "PB1_TRIGGER_SEMANTICS_MIXED_V1"
PARENT_STRUCTURE_RCA = "PB1_STRUCTURE_AND_SYMBOL_CONTEXT_RCA_V1"
PARENT_STRUCTURE_VERDICT = "PB1_STRUCTURE_AND_SYMBOL_CONTEXT_MAPPED_V1"
PARENT_V2_SHA = "3ebe0220fd9cb1e5749e39833fa1bab0146759cce5dc9daaacf0e3b3d3daf3fd"
EXPECTED_PARENT_SETUP_N = 465

EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
EXPECTED_DETECTOR_SHA256 = "6e3060b71f8a4787b09d6b3c0f3ba9fa84c87712bf0f11b0165bfbfd1e0bf47e"
EXPECTED_STATE_MACHINE_SHA256 = "3c065f3757083fa6da792f9450e07504e902ea93d48391467a6bb7dca6e6a5b8"

FROZEN_CONFIRM_ATR = 0.75
FROZEN_ZONE_HALF_ATR = 0.15
assert CONFIRM_ATR == FROZEN_CONFIRM_ATR
assert ZONE_HALF_ATR == FROZEN_ZONE_HALF_ATR

# Identical V2 constants (not retuned).
assert BREAK_BEYOND_OR_FRAC == 0.08
assert BREAK_BEYOND_ATR_FRAC == 0.05
assert BREAK_CLOSE_LOC == 0.55
assert MIN_AWAY_BARS == 2
assert LEAVE_EXT_OR_FRAC == 0.15
assert RETEST_FRESHNESS_MIN == 30
assert LAST_BREAK == "10:00"
assert LAST_TRIGGER == "11:20"
assert OR_KNOWN_FROM == "09:15"

# V3 semantic constants. Not searched.
STRUCTURAL_ROUTE_R_MULT = 1.0
ACCEPTANCE_FAIL_CLOSES = 2
PRIMARY_TRIGGER = "RECLAIM_RETEST_MICRO_HIGH"
ARCHIVED_TRIGGER = "FAILED_PUSH_THEN_CLOSE_BACK"

SAMPLE_N = 96
SAMPLE_SEED = "PB1_PLAYBOOK_REDESIGN_V3:FACE_VERIFY"

GATE_CLEAR_MIN = 2.0 / 3.0
GATE_NOT_MAX = 0.15
GATE_BLOCKED_LEAK_MAX = 0.15
GATE_FAILED_PUSH_LEAK = 0
GATE_RISK_INVALID = 0

CASE_FACE_VALID = "PB1_V3_FACE_VALID_READY_V1"
CASE_NEEDS_REBUILD = "PB1_V3_SEMANTICS_NEEDS_REBUILD_V1"
CASE_BIND = "PB1_V3_BIND_FAILED_V1"
NEXT_PATH_TEST = "PB1_V3_CAUSAL_PATH_TEST_V1"
NEXT_FIX = "FIX_PB1_V3_FACE_VALIDITY_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

OLD_CONFIRMATION_OPENED = False
FROZEN_VALIDATION_OPENED = False
KABU50_APPLIED = False
PNL_OPTIMIZATION = False
THRESHOLD_OPTIMIZED = False
MARKET_REGIME_GATE = False
SYMBOL_ARCHETYPE_GATE = False
CLEAN_FLIP_WINNER_RULE = False
RETEST_5MIN_GATE = False
EXTENSION_BPS_OPTIMIZED = False
ONE_R_SEARCHED = False
FAILED_PUSH_REMOVED_FOR_RETURN = False
FEATURE_MINING = FEATURE_MINING_CLOSED
LIVE_DATE = LIVE_TRADING_DATE
