"""Five-second breakout acceptance. The parent impulse signal is unchanged."""

ANALYSIS_ID = "EVENT_TIME_IMPULSE_BREAKOUT_ACCEPTANCE_ENTRY_V1"
PARENT_ANALYSIS_ID = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_DISCOVERY_V1"
PARENT_VERDICT = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_MECHANISM_SUPPORTED_V1"
FAILED_EXECUTION_VERDICT = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_EXECUTABLE_ENTRY_NOT_SUPPORTED_V1"
FAILED_EXECUTION_ID = "EVENT_TIME_IMPULSE_PASSIVE_BID_W5_V1"
REQUIRED_SIGNAL_SHA256 = "06345e9f7ddd2fcdf21a7beac49241495d3a4b6607715c879cf2ef0a307b4f68"
ENTRY_EXECUTION_ID = "BREAKOUT_ACCEPTANCE_5S_IMMEDIATE_ASK_V1"
ENTRY_ID = "EVENT_TIME_VOLUME_CONFIRMED_IMPULSE_ACCEPTED_ENTRY_V1"

ACCEPTANCE_SEC = 5.0
HORIZONS = (30, 60, 180, 300)
PRIMARY_HORIZON = 180
MIN_ACCEPTED_N = 100
ESSENTIALLY_ALL_SHARE = 0.80
PARENT_FULL_N = 11930

VERDICT_SUPPORTED = "EVENT_TIME_BREAKOUT_ACCEPTANCE_EXECUTABLE_ENTRY_SUPPORTED_V1"
VERDICT_NOT = "EVENT_TIME_BREAKOUT_ACCEPTANCE_EXECUTABLE_ENTRY_NOT_SUPPORTED_V1"
VERDICT_SUPPORT = "EVENT_TIME_BREAKOUT_ACCEPTANCE_INSUFFICIENT_SUPPORT_V1"
VERDICT_MISMATCH = "ENTRY_SIGNAL_IDENTITY_MISMATCH"
NEXT_EXIT = "RESEARCH_EVENT_TIME_IMPULSE_ACCEPTED_ENTRY_EXIT_V1"
NEXT_STOP_FAMILY = "STOP_EVENT_TIME_STOCK_MICROSTRUCTURE_ENTRY_DISCOVERY_V1"
NEXT_STOP = "STOP"
INFORMATION_NOT_CAPTURABLE = "EVENT_TIME_STOCK_MICROSTRUCTURE_EDGE_NOT_EXECUTABLY_CAPTURABLE_V1"
