"""AM WAIT5 two-stage Stage1→Stage2 interface precommit. No training. No performance."""
from __future__ import annotations

from research.direct_joint_objective import ELIGIBLE_DAYS
from research.entry_objective_redesign_c3 import FEATURE_SETS, MIN_COHORT_N, NORMS
from small_paper.v1r_primary_runtime import WAIT_SEC

ANALYSIS_ID = "AM_WAIT5_TWO_STAGE_INTERFACE_PRECOMMIT_V1"
C14_ID = "V1R_EXIT_V2_PAPER_PRIMARY_CANDIDATE_V26G14_14"
TRUE_OOS = False
NEW_FORWARD_N = 0
PARITY_ABS_TOL = 1e-10
DEV_WAIT_SEC = 5.0
SESSION = "AM"
REPRESENTATION_N = 9
COMMON_AM_PM_MODEL_ALLOWED = False
COMMON_AM_PM_TARGET_ALLOWED = False

PRIOR_ANALYSIS_ID_REQUIRED = "AM_WAIT5_TWO_STAGE_OBJECTIVE_PRECOMMIT_V1"
PRIOR_VERDICT_REQUIRED = "AM_WAIT5_TWO_STAGE_OBJECTIVE_PRECOMMITTED"
NEXT_RESEARCH = "AM_WAIT5_TWO_STAGE_PRECOMMITTED_DEVELOPMENT"

STAGE1_TARGET = "Y_FILL5_AM"
STAGE1_SCORE = "P_FILL5"
STAGE2_U_TARGET = "U_FILL"
STAGE2_D_TARGET = "D_FILL"
QUALITY_COMBINATION = "MIN_PERCENTILE_RANK"

STAGE1_SHORTLIST_N = 5
FINAL_SELECTION_N = 3
STAGE1_SHORTLIST_RULE = "P_FILL5_TOP5"
STAGE2_SELECTION_RULE = "MIN_PERCENTILE_RANK_TOP3"

ALLOWED_DEVELOPMENT_ARMS = ("CONTROL", "FILL_ONLY", "TWO_STAGE")
CONTROL_ARM = "CURRENT Top3"
FILL_ONLY_ARM = "P_FILL5 Top3"
TWO_STAGE_ARM = "P_FILL5 Top5 shortlist → Joint Quality Top3"

U_D_WEIGHT_SEARCH_ALLOWED = False
SHORTLIST_SEARCH_ALLOWED = False
PROBABILITY_THRESHOLD_ALLOWED = False
BEST_REPRESENTATION_ADOPTED = False
FILL_ONLY_AND_TWO_STAGE_DISTINCT_BY_CONSTRUCTION = True

assert abs(float(WAIT_SEC) - 1.0) < 1e-12
assert float(DEV_WAIT_SEC) == 5.0
assert SESSION == "AM"
assert int(STAGE1_SHORTLIST_N) == 5
assert int(FINAL_SELECTION_N) == 3
assert int(STAGE1_SHORTLIST_N) > int(FINAL_SELECTION_N)
assert int(MIN_COHORT_N) >= int(STAGE1_SHORTLIST_N)
assert len(FEATURE_SETS) * len(NORMS) == int(REPRESENTATION_N)
assert SHORTLIST_SEARCH_ALLOWED is False
assert PROBABILITY_THRESHOLD_ALLOWED is False
assert U_D_WEIGHT_SEARCH_ALLOWED is False
assert FILL_ONLY_AND_TWO_STAGE_DISTINCT_BY_CONSTRUCTION is True

RUNTIME_CHANGED = False
C14_CHANGED = False
PAPER_OPERATED = False
OPVAL_OPERATED = False
C4_STARTED = False
EXACT_RAN = False
NEW_MODEL_CREATED = False
FEATURE_SEARCH = False
PNL_USED = False
WAIT_POLICY_ADOPTED = False
ENTRY_RETRAIN_STARTED = False
SESSION_INDICATOR_COMMON_MODEL = False
QUALITY_SCALAR_WEIGHT = False
JOINT_BINARY_TARGET = False
TOPK_SEARCH = False
THRESHOLD_SEARCH = False
PARETO_TARGET_ADOPTED = False
PARETO_KNEE_SEARCH = False
WEIGHT_SEARCH = False
U_ONLY_STRATEGY_ALLOWED = False
D_ONLY_STRATEGY_ALLOWED = False
WEIGHTED_UD_STRATEGY_ALLOWED = False
P_FILL5_TIMES_QUALITY_ALLOWED = False
RUNTIME_CANDIDATE_CREATED = False
STRATEGY_CREATED = False
DEVELOPMENT_RUN_STARTED = False
PERFORMANCE_EVAL_STARTED = False
