"""RESEARCH_OBJECTIVE_REBASE_V1. Existing-artifact synthesis. No new replay."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "RESEARCH_OBJECTIVE_REBASE_V1"

CASE_A = "RESEARCH_OBJECTIVE_REBASED_TO_INFORMATION_GAP"
CASE_B = "RESEARCH_OBJECTIVE_REBASED_TO_GENERALIZATION_RCA"
CASE_C = "RESEARCH_OBJECTIVE_REBASED_TO_VALUE_CAPTURE_RCA"
CASE_D = "RESEARCH_OBJECTIVE_REBASE_INCONCLUSIVE"
CASE_E = "RESEARCH_OBJECTIVE_REBASE_INTEGRITY_FAILED"

NEXT_IF_A = "NEW_INFORMATION_FAMILY_INVENTORY_V1"
NEXT_IF_B = "GENERALIZATION_FAILURE_RCA_V1"
NEXT_IF_C = "TRADE_PATH_VALUE_CAPTURE_RCA_V1"
NEXT_IF_D = "RESEARCH_OBJECTIVE_REBASE_EVIDENCE_GAP_V1"
NEXT_IF_E = "Fix integrity only. No new strategy."

LINEAGE_IDS = (
    "L1_TECHNICAL_PRICE_STATE",
    "L2_RECOVERY_RECLAIM_PATH",
    "L3_ACTIVITY_ONSET",
)
OVERLAY_ID = "O1_PORTFOLIO_CROWDING_OVERLAY"
INDEPENDENT_INFORMATION_LINEAGE_N = 3

CLASS_IDS = (
    "C1_MULTI_TIMEFRAME",
    "C2_EPISODE_AGE",
    "C3_FAILURE_ROUTING",
    "C4_PORTFOLIO_CROWDING",
)

C4_ANALYSIS_ID = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2"
C4_VERDICT_REQUIRED = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_NO_ROBUST_CANDIDATE"
C4_NEXT_REQUIRED = "RESEARCH_OBJECTIVE_REBASE_V1"
C4_PRIMARY_CLOSE_REASON = "ABSOLUTE_ECONOMIC_PASS_ZERO"

TRUE_OOS = False
CERTIFIED = False
SIZING = False
STRESS_OPENED_THIS_RUN = False
NEW_REPLAY = False
NEW_CANDIDATE = False
NEW_ENTRY = False
NEW_EXIT = False
NEW_THRESHOLD = False
NEW_PNL_SIMULATION = False
NEW_FULL_CAUSAL_RUN = False
NEW_FOLD_RUN = False
C5_CREATED = False
CANDIDATE_COUNT_WEIGHTED_VOTE = False
ANY_CANDIDATE_FAMILY_VOTE = False

assert ANALYSIS_ID == "RESEARCH_OBJECTIVE_REBASE_V1"
assert len(LINEAGE_IDS) == INDEPENDENT_INFORMATION_LINEAGE_N == 3
assert OVERLAY_ID not in LINEAGE_IDS
assert C5_CREATED is False
assert NEW_REPLAY is False
assert CANDIDATE_COUNT_WEIGHTED_VOTE is False
assert ANY_CANDIDATE_FAMILY_VOTE is False
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
assert C4_PRIMARY_CLOSE_REASON != "I2_ZERO"
