"""RESEARCH_PAUSE_AND_DATA_REQUIREMENTS_REDESIGN_V1. Pause protocol. No strategy. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)

ANALYSIS_ID = "RESEARCH_PAUSE_AND_DATA_REQUIREMENTS_REDESIGN_V1"
PARENT_ID = "EXISTING_DATA_STRATEGY_RESEARCH_STOP_REASSESSMENT_V1"
REQUIRED_PARENT_VERDICT = "EXISTING_SEALED_DEV_STRATEGY_RESEARCH_JUSTIFIABLY_EXHAUSTED_V1"
REQUIRED_PARENT_NEXT = "RESEARCH_PAUSE_AND_DATA_REQUIREMENTS_REDESIGN_V1"
REQUIRED_CLOSED_ARCHITECTURE_N = 23
REQUIRED_ELIGIBLE_METHOD_N = 0
REQUIRED_METHOD_SPEC_SHA256 = "f5e1a63c1e483f4f386492b83be745c1c2017b95888bd79ba84d27621dc4a9fb"

LEGACY_DEV_DAYS = DEVELOPMENT_DAYS
QUARANTINE_DAYS = ("20260903", "20260904")

NEW_DEV_MIN_VALID_DAYS = 20
NEW_DEV_MIN_CALENDAR_WEEKS = 4
INTERNAL_FOLD_N = 5
TRUE_OOS_MIN_VALID_DAYS = 10

NEW_STRATEGY_CREATED = False
NEW_ENTRY_CREATED = False
NEW_EXIT_CREATED = False
NEW_MODEL_CREATED = False
NEW_THRESHOLD_CREATED = False
NEW_CANDIDATE_LIBRARY_CREATED = False
NEW_ECONOMIC_RUN = False
NEW_OUTCOME_COMPUTE = False
NEW_EXTERNAL_DATA_ACQUIRED = False
ENTRY_ONLY_METHOD_REVIVAL = False
FRESH_DATA_ONLY_RESTART_ALLOWED = False
FUTURE_DATASET_DATES_ASSIGNED = False
FUTURE_USE_REQUIRES_EXPLICIT_POLICY_CHANGE = True
BURNED_DATA_RECLASSIFIED_AS_TRUE_OOS = False
BURNED_DATA_RECLASSIFIED_AS_NEW_DEV = False
QUARANTINE_CHANGED = False
PROSPECTIVE_DATA_CONSUMED = False
PAPER_20260907_READ = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

CASE_A = "RESEARCH_RESET_NEW_INFORMATION_ACQUISITION_REQUIRED_V1"
CASE_B = "RESEARCH_PAUSED_EXTERNAL_INFORMATION_DECISION_REQUIRED_V1"
CASE_C = "RESEARCH_PAUSED_FRESH_DATA_RESET_REQUIRED_V1"
CASE_D = "STRATEGY_RESEARCH_PAUSED_NO_JUSTIFIED_RESTART_PATH_V1"
NEXT_A = "NEW_INFORMATION_ACQUISITION_FEASIBILITY_DESIGN_V1"
NEXT_B = "NEW_INFORMATION_SOURCE_POLICY_DECISION_V1"
NEXT_C = "WAIT_FOR_EXPLICIT_FUTURE_DATA_POLICY_CHANGE"
NEXT_D = "MAINTAIN_PAPER_OBSERVATION_ONLY"

assert ANALYSIS_ID == "RESEARCH_PAUSE_AND_DATA_REQUIREMENTS_REDESIGN_V1"
assert REQUIRED_PARENT_VERDICT == "EXISTING_SEALED_DEV_STRATEGY_RESEARCH_JUSTIFIABLY_EXHAUSTED_V1"
assert NEW_ECONOMIC_RUN is False
assert NEW_STRATEGY_CREATED is False
assert ENTRY_ONLY_METHOD_REVIVAL is False
assert FRESH_DATA_ONLY_RESTART_ALLOWED is False
assert FUTURE_DATASET_DATES_ASSIGNED is False
assert FUTURE_USE_REQUIRES_EXPLICIT_POLICY_CHANGE is True
assert int(NEW_DEV_MIN_VALID_DAYS) == 20
assert int(NEW_DEV_MIN_CALENDAR_WEEKS) == 4
assert int(INTERNAL_FOLD_N) == 5
assert int(TRUE_OOS_MIN_VALID_DAYS) == 10
assert MAX_RESEARCH_DATE == "20260807"
assert len(LEGACY_DEV_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert QUARANTINE_DAYS == ("20260903", "20260904")
