"""V1R EXIT V2 — Asymmetric Sequential EXIT State Machine research."""

ANALYSIS_ID = "V1R_EXIT_V2_ASYMMETRIC"
DOCUMENT_ID = "V1R_EXIT_V2_ASYMMETRIC"
FORBIDDEN_FROM = "20260810"
BASELINE_ID = "FIXED600"
