"""PB1_V4_IMPLEMENTATION_INTEGRITY_AND_SPEC_PARITY_AUDIT_V1.

Diagnosis only. Do not mutate V4. No new thresholds. No prospective face. No PnL.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.pb1_v4_machine_implementation import PARENT_V32_SHA
from research.pb1_v4_machine_implementation.definitions import machine_sha256 as v4_machine_sha256
from research.pb1_v4_opening_drive_location_reaccel_spec import CASE_READY as PARENT_SPEC_VERDICT
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "PB1_V4_IMPLEMENTATION_INTEGRITY_AND_SPEC_PARITY_AUDIT"
ANALYSIS_ID = "PB1_V4_IMPLEMENTATION_INTEGRITY_AND_SPEC_PARITY_AUDIT_V1"
PARENT_V4_PROGRAM = "PB1_V4_MACHINE_IMPLEMENTATION"
FROZEN_V4_SHA = "fa0451bb3d89fe830544f167ab1375f2e569d1ffaf358cced6f092d4039fd3ee"
assert PARENT_SPEC_VERDICT == "PB1_V4_SEMANTIC_SPEC_READY_V1"
assert PARENT_V32_SHA == "56edb2c2576805e46193528824fb61faebb5ae7c85be0201f0331e90f9a67f43"
assert v4_machine_sha256() == FROZEN_V4_SHA

CASE_PARITY = "PB1_V4_IMPLEMENTATION_PARITY_CONFIRMED_V1"
CASE_MISMATCH = "PB1_V4_IMPLEMENTATION_SPEC_MISMATCH_V1"
CASE_LEAKAGE = "PB1_V4_LEGACY_RULE_LEAKAGE_CONFIRMED_V1"
CASE_BIND = "PB1_V4_INTEGRITY_AUDIT_BIND_FAILED_V1"
NEXT_FACE = "PB1_V4_PROSPECTIVE_FACE_VALIDATION"
NEXT_CORRECT = "PB1_V4_IMPLEMENTATION_CORRECTION_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

OLD_CONFIRMATION_OPENED = False
FROZEN_VALIDATION_OPENED = False
KABU50_APPLIED = False
PNL_OPTIMIZATION = False
THRESHOLD_OPTIMIZED = False
V4_RULE_CHANGED = False
FEATURE_MINING = FEATURE_MINING_CLOSED
LIVE_DATE = LIVE_TRADING_DATE
_ = v4_machine_sha256
