"""NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V2. Causal hardening addendum. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V2"
PARENT_ANALYSIS_ID = "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V1"
PARENT_ARCHITECTURE_ID = "CSB_MA_ONSET_X1_Z_MA_LOSS"
PARENT_SPEC_SHA256 = "f45d8c53790adbd385b623224a9ceece5b91c53e0fe764b439458f454a657b15"

CASE_FROZEN = "NEW_FULL_STRATEGY_CAUSAL_SEMANTICS_FROZEN"
CASE_UNRESOLVED = "NEW_FULL_STRATEGY_CAUSAL_SEMANTICS_UNRESOLVED"
STOP_UNIVERSE = "CSB_CAUSAL_UNIVERSE_UNRESOLVED"
STOP_FILL_TIE = "CSB_CAUSAL_FILL_TIE_UNRESOLVED"
STOP_X1 = "CSB_X1_PENDING_SEMANTICS_UNRESOLVED"
STOP_SESSION_CLOSE = "CSB_SESSION_CLOSE_SEMANTICS_UNRESOLVED"
NEXT_IF_FROZEN = "NEW_FULL_STRATEGY_IMPLEMENTATION_AND_DEV_EVAL_V1"
NEXT_IF_UNRESOLVED = "NEW_FULL_STRATEGY_ARCHITECTURE_REDESIGN_V1"

SESSION = "AM"
AM_START_HM = (9, 0)
AM_END_HM = (11, 30)

Q1_NEW_LOGIC_COMPLETION_DIRECT = True
Q2_BLOCKING_WITHOUT_THIS_RUN = True
Q3_OLD_RCA_AS_PURPOSE = False

TRUE_OOS = False
CERTIFIED = False
SIZING = False
NEW_REPLAY = False
NEW_ARCHITECTURE_ECONOMICS_RUN = False
NEW_ARCHITECTURE_PNL_READ_N = 0
RAW_CAPTURE_READ_N = 0
VWAP_ENTRY_USED = False
VWAP_EXIT_USED = False
VWAP_FILTER_USED = False
BOARD_PRIMARY_ALPHA = False
CORE_ARCHITECTURE_CHANGED = False
NEW_ALPHA_PRIMITIVE = False
NEW_THRESHOLD = False
ARBITRARY_BREADTH_DELAY_ADDED = False

assert ANALYSIS_ID == "NEW_FULL_STRATEGY_ARCHITECTURE_PRECOMMIT_V2"
assert Q1_NEW_LOGIC_COMPLETION_DIRECT is True
assert Q2_BLOCKING_WITHOUT_THIS_RUN is True
assert Q3_OLD_RCA_AS_PURPOSE is False
assert NEXT_IF_UNRESOLVED != PFQ_RECON_FORBIDDEN
assert NEXT_IF_FROZEN != PFQ_RECON_FORBIDDEN
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert CORE_ARCHITECTURE_CHANGED is False
assert NEW_THRESHOLD is False
assert ARBITRARY_BREADTH_DELAY_ADDED is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert NEW_ARCHITECTURE_ECONOMICS_RUN is False
assert NEW_ARCHITECTURE_PNL_READ_N == 0
