"""BUILD_ALIGNED_HISTORICAL_PANEL_V1. Causal panel only. No strategy. No PnL. Universe immutable."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.fixed_daytrade_universe_v1 import LAST_COMPLETE_TSE_SESSION, UNIVERSE_ID
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

ANALYSIS_ID = "BUILD_ALIGNED_HISTORICAL_PANEL_V1"
PARENT_VERDICT = "FIXED_DAYTRADE_UNIVERSE_FROZEN_V1"
KIND = "ALIGNED_PANEL_ONLY"
REQUIRED_UNIVERSE_ID = UNIVERSE_ID
PROBE_DATE = LAST_COMPLETE_TSE_SESSION  # 20260911; never 20260914
FORBIDDEN_DATA_FROM = "20260914"
CANONICAL_TZ = "Asia/Tokyo"

CASE_READY = "ALIGNED_HISTORICAL_PANEL_READY_V1"
CASE_PARTIAL = "ALIGNED_HISTORICAL_PANEL_CORE_READY_EXTERNAL_PARTIAL_V1"
CASE_EXT_BLOCK = "ALIGNED_HISTORICAL_PANEL_EXTERNAL_CONTEXT_BLOCKED_V1"
CASE_TIME_BLOCK = "ALIGNED_HISTORICAL_PANEL_TIME_SEMANTICS_BLOCKED_V1"
CASE_ADDON = "JQUANTS_MINUTE_ADDON_REQUIRED_V1"
CASE_UNIVERSE = "FROZEN_UNIVERSE_MANIFEST_INVALID_V1"
CASE_SCHEMA = "EQUITY_MINUTE_SCHEMA_MISMATCH_V1"
CASE_FETCH = "EQUITY_MINUTE_FETCH_FAILED_V1"

NEXT_CAUSE = "CAUSE_FIRST_MECHANISM_DISCOVERY_V1"
NEXT_ADDON = "ACQUIRE_JQUANTS_MINUTE_ADDON_THEN_RETRY_PANEL_V1"
NEXT_TIME = "PROVE_EQUITY_MINUTE_TIME_SEMANTICS_THEN_RETRY_PANEL_V1"
NEXT_EXT = "ACQUIRE_CORE_EXTERNAL_CONTEXT_THEN_RETRY_PANEL_V1"
NEXT_UNIVERSE = "REPAIR_FROZEN_UNIVERSE_MANIFEST_THEN_RETRY_PANEL_V1"

STRATEGY_SEARCH_STARTED = False
ENTRY = False
EXIT = False
PNL_USED = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
LIVE_20260914_CHANGED = False
UNIVERSE_CHANGED = False
SAME_BAR_CLOSE_ENTRY = False
SYNTHETIC_MISSING_FILL = False
FUTURES_AUTOSPLICE = False
RANDOM_SPLIT = False

ENDPOINT_MINUTE = "/v2/equities/bars/minute"
ENDPOINT_TICK_BULK = "/equities/trades"
ENDPOINT_BULK_LIST = "/v2/bulk/list"
ENDPOINT_BULK_GET = "/v2/bulk/get"
ENDPOINT_INDICES_DAILY = "/v2/indices/bars/daily"
ENDPOINT_TOPIX_DAILY = "/v2/indices/bars/daily/topix"
ENDPOINT_FUTURES_DAILY = "/v2/derivatives/bars/daily/futures"

MINUTE_REQUIRED_RAW = ("Date", "Time", "Code", "O", "H", "L", "C", "Vo")
MINUTE_OPTIONAL_RAW = ("Va",)
PROBE_SYMBOL = "7203"
PROBE_TICK_SYMBOLS = ("1605", "7203")

assert ANALYSIS_ID == "BUILD_ALIGNED_HISTORICAL_PANEL_V1"
assert PARENT_VERDICT == "FIXED_DAYTRADE_UNIVERSE_FROZEN_V1"
assert PROBE_DATE == "20260911"
assert PROBE_DATE < FORBIDDEN_DATA_FROM
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert STRATEGY_SEARCH_STARTED is False
assert SAME_BAR_CLOSE_ENTRY is False
assert SYNTHETIC_MISSING_FILL is False
assert FUTURES_AUTOSPLICE is False
assert UNIVERSE_CHANGED is False
