"""HIGHER_MAGNITUDE_STATE_DISCOVERY_V1. Episodes + ranking. CS1–CS3 stay not promoted."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

PROGRAM_ID = "COMPLETE_CAUSAL_STRATEGY_RESEARCH_V1"
ANALYSIS_ID = "HIGHER_MAGNITUDE_STATE_DISCOVERY_V1"
PARENT_ANALYSIS_ID = "CAUSAL_PATH_TO_COMPLETE_STRATEGY_V1"
PARENT_VERDICT = "CAUSAL_STRUCTURE_FOUND_EDGE_INSUFFICIENT_V1"
KIND = "EPISODE_SEQUENCE_RANKING_MAGNITUDE"
SEMANTICS = "BAR_START"
EXPECTED_SPLIT_SHA256 = "2c9bd8f4ce7c86116833b54e1d41e4cbc4b59c3e504b769140fea435d375b3b4"
EXPECTED_BLOCK_SHA256 = "e7a16d860f73acc592c94ac7a717820f0dcea263fd60ab39b0cf7af980912718"
X1_TAX_BPS = 8.0
MAX_CANDIDATES = 2
EPISODE_GAP_MIN = 15
OCCUPANCY = 3
RANK_DIAGNOSTIC_K = (1, 3)
PRIOR_GROSS_BPS_CEILING = 6.0
MATERIAL_GROSS_BPS = 10.0
REJECTED_CS = (
    "CS1_TREND_PULLBACK_RECLAIM",
    "CS2_BREAKOUT_EXPANSION",
    "CS3_EMA_IMPROVE",
)

CASE_FOUND = "HIGH_MAGNITUDE_COMPLETE_STRATEGY_CANDIDATE_FOUND_V1"
CASE_RANKED = "CROSS_SECTIONAL_OPPORTUNITY_SELECTION_FOUND_V1"
CASE_LIMIT = "STOCK_PANEL_MAGNITUDE_LIMIT_CONFIRMED_V1"
CASE_BIND = "HIGHER_MAGNITUDE_BIND_FAILED_V1"

NEXT_SECONDARY = "SECONDARY_CONFIRMATION_AND_FREEZE_REVIEW_V1"
NEXT_FREEZE_RANKED = "FREEZE_RANKED_COMPLETE_STRATEGY_V1"
NEXT_EXTERNAL = "IDENTIFY_MINIMUM_MISSING_EXTERNAL_CAUSAL_INFORMATION_V1"
NEXT_BIND = "REPAIR_PRIOR_BIND_THEN_RETRY_V1"

KABU_50_APPLIED = False
FROZEN_VALIDATION_OPENED = False
OLD_CONFIRMATION_USED_TO_DESIGN = False
SAME_BAR_CLOSE_ENTRY = False
HISTORICAL_BID_ASK_INFERRED = False
FUTURE_AS_DECISION_FEATURE = False
CS1_CS3_RESCUED = False
EPISODE_LENGTH_GRID_SEARCHED = False

assert ANALYSIS_ID == "HIGHER_MAGNITUDE_STATE_DISCOVERY_V1"
assert PARENT_VERDICT == "CAUSAL_STRUCTURE_FOUND_EDGE_INSUFFICIENT_V1"
assert EPISODE_GAP_MIN == 15
assert MAX_CANDIDATES == 2
assert RANK_DIAGNOSTIC_K == (1, 3)
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert FROZEN_VALIDATION_OPENED is False
assert CS1_CS3_RESCUED is False
assert EPISODE_LENGTH_GRID_SEARCHED is False
assert KABU_50_APPLIED is False
