"""NEW_FULL_STRATEGY_ARCHITECTURE_CONSTRUCTION_V2. Freeze HTF resistance-episode Full Strategy. No PnL."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "NEW_FULL_STRATEGY_ARCHITECTURE_CONSTRUCTION_V2"
ARCHITECTURE_ID = "HTF5_MA_RESISTANCE_EPISODE_VOL_X1_Z_SUPPORT_FAIL"
SPEC_VERSION = "V4"

CSB_EVAL_ID = "NEW_FULL_STRATEGY_IMPLEMENTATION_AND_DEV_EVAL_V1"
CSB_REQUIRED_VERDICT = "NEW_FULL_STRATEGY_DEV_EVAL_FAIL_GATES"
PINNED_V3_SHA256 = "6fc34ea5c0b973c7a4b575ac4b4d2290b45a9c23d1988280c11eb681c084f3c2"

CASE_FROZEN = "NEW_FULL_STRATEGY_ARCHITECTURE_V2_FROZEN"
CASE_DUPLICATE = "NEW_ARCHITECTURE_V2_DUPLICATE_CLOSED_LINEAGE"
CASE_STRUCTURAL = "NEW_ARCHITECTURE_V2_STRUCTURAL_COVERAGE_IMPOSSIBLE"
NEXT_IF_FROZEN = "NEW_FULL_STRATEGY_V2_IMPLEMENTATION_AND_DEV_EVAL_V1"

SESSION = "AM"
AM_START_HM = (9, 0)
AM_END_HM = (11, 30)
SESSION_FLATTEN_HM = (11, 29)
SESSION_FLATTEN_T_LABEL = "11:29:00 JST"
HTF_WIDTH_SEC = 300.0
HTF_ORIGIN_HM = (9, 0)
EMA_LEVEL_PERIOD = 21

LEVEL_AVAILABLE_DAY_MIN = int(MIN_TRADING_DAYS_WITH_FILL)

CSB_RCA_RUN = False
CSB_RETUNE = False
OLD_ST_RCA_CONTINUED = False
ANOTHER_PRECOMMIT_RUN = False
HTF_TREND_BOOLEAN_USED = False
VOLUME_THRESHOLD_SEARCH = False
BOARD_PRIMARY_ALPHA = False
VWAP_ENTRY_USED = False
VWAP_EXIT_USED = False
VWAP_FILTER_USED = False
RCI_USED = False
BB_USED = False
DAILY_MA_ADDED = False
NEW_CANDIDATE_PNL_READ_N = 0
NEW_CANDIDATE_ECONOMICS_RUN = False
TRUE_OOS = False
CERTIFIED = False
SIZING = False

Q1_NEW_LOGIC_COMPLETION_DIRECT = True
Q2_BLOCKING_WITHOUT_THIS_RUN = True
Q3_OLD_RCA_AS_PURPOSE = False

assert ANALYSIS_ID == "NEW_FULL_STRATEGY_ARCHITECTURE_CONSTRUCTION_V2"
assert ARCHITECTURE_ID == "HTF5_MA_RESISTANCE_EPISODE_VOL_X1_Z_SUPPORT_FAIL"
assert CSB_RCA_RUN is False
assert CSB_RETUNE is False
assert OLD_ST_RCA_CONTINUED is False
assert ANOTHER_PRECOMMIT_RUN is False
assert HTF_TREND_BOOLEAN_USED is False
assert VOLUME_THRESHOLD_SEARCH is False
assert BOARD_PRIMARY_ALPHA is False
assert NEW_CANDIDATE_PNL_READ_N == 0
assert NEW_CANDIDATE_ECONOMICS_RUN is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert POSITION_CAP == 5
assert SHARES == 100
assert LEVEL_AVAILABLE_DAY_MIN == 8
assert abs(HTF_WIDTH_SEC - 300.0) < 1e-12
assert EMA_LEVEL_PERIOD == 21
assert SESSION_FLATTEN_HM == (11, 29)
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert NEXT_IF_FROZEN != PFQ_RECON_FORBIDDEN
assert Q3_OLD_RCA_AS_PURPOSE is False
assert DAILY_MA_ADDED is False
