"""E1_X7 PFQ Realizability Bridge Audit V2 — frozen PFQ conditions; design period only."""

ANALYSIS_ID = "E1_X7_PFQ_REALIZABILITY_BRIDGE_AUDIT_V2"
SOURCE_RUN = "e1x7_pfq_20260804_080510"

# Frozen thresholds (do not recompute)
FROZEN_THRESHOLDS = {
    "price_update_count_10s_q70": 8.0,
    "uptick_volume_ratio_30s_q30": 0.7991666666666666,
}

KNOWN_COUNTS = {
    "ALL_PULLBACK": 303,
    "PFQ_UPDATE_Q70": 92,
    "PFQ_FLOW_Q30": 85,
    "PFQ_JOINT": 41,
}

FROZEN_PAIRS = [
    ("PFQ_UPDATE_Q70", "PFQ_X_PROGRESS_STRUCT"),
    ("PFQ_UPDATE_Q70", "PFQ_X_PROTECT"),
    ("PFQ_FLOW_Q30", "PFQ_X_PROGRESS_STRUCT"),
    ("PFQ_FLOW_Q30", "PFQ_X_PROTECT"),
]

HARD_EXITS = {
    "RECLAIM_LEVEL_BREAK",
    "PULLBACK_LOW_BREAK",
    "HARD_STOP",
    "MAX_HOLD",
    "SESSION_END",
}
SOFT_EXITS = {
    "NO_PROGRESS_UPDATE_DEAD",
    "MFE_GIVEBACK",
    "UPDATE_DETERIORATION",
}

BOOTSTRAP_REPS = 1000
BOOTSTRAP_SEED = 20260804
FRESHNESS_MAX_SEC = 30.0
MAX_HOLD_SEC = 300.0
COST_BPS = 5.0

# Single failure classification priority (first match wins)
FAILURE_PRIORITY = [
    "NO_EXECUTABLE_OPPORTUNITY",
    "ENTRY_PATH_FAILURE_MINUS10_FIRST",
    "ENTRY_PATH_FAILURE_MINUS15_FIRST",
    "HARD_INVALIDATION_BEFORE_PLUS5",
    "SOFT_EXIT_PREMATURE",
    "PLUS5_REACHED_BEFORE_EXIT_CAPTURED_POSITIVE",
    "PLUS5_REACHED_BEFORE_EXIT_GIVEN_BACK_TO_NONPOSITIVE",
    "PLUS10_REACHED_BEFORE_EXIT_CAPTURED_LT_PLUS5",
    "MAX_HOLD_CENSORED",
    "SESSION_END_CENSORED",
    "OTHER",
]
