"""EXISTING_ARCHITECTURE_EXHAUSTION_REVIEW_V1. Artifact inventory only. No new economics."""
from __future__ import annotations

ANALYSIS_ID = "EXISTING_ARCHITECTURE_EXHAUSTION_REVIEW_V1"

STATUS_ENUM = (
    "CLOSED_ROBUST_FAILURE",
    "CLOSED_ECONOMIC_FAILURE",
    "CLOSED_INTEGRITY_FAILURE",
    "CLOSED_DUPLICATE",
    "ALREADY_EXECUTED_FULL_STRATEGY",
    "NOT_FULL_STRATEGY",
    "PREEXISTING_UNTESTED_FULL_CAUSAL",
    "PREEXISTING_PARTIALLY_TESTED",
    "NEW_DERIVATIVE_NOT_PREEXISTING",
    "INSUFFICIENT_ARTIFACT_TO_CLASSIFY",
)

REMAINING_STATUSES = (
    "PREEXISTING_UNTESTED_FULL_CAUSAL",
    "PREEXISTING_PARTIALLY_TESTED",
)

CLOSED_STATUSES = (
    "CLOSED_ROBUST_FAILURE",
    "CLOSED_ECONOMIC_FAILURE",
    "CLOSED_INTEGRITY_FAILURE",
    "CLOSED_DUPLICATE",
)

CASE_A = "EXISTING_ARCHITECTURE_REMAINING_FOUND"
CASE_B = "EXISTING_ARCHITECTURE_EXHAUSTED"
CASE_C = "ARCHITECTURE_INVENTORY_INCOMPLETE"

NEXT_OR_RECONCILE = "OR_OVERLAY_CAUSAL_CONTRIBUTION_RECONCILIATION_V1"
NEXT_STATE_SPACE = "SYSTEMATIC_STATE_SPACE_DISCOVERY_PRECOMMIT_V1"

STRESS_DAYS = ("20260828", "20260831", "20260901", "20260902")
FORBIDDEN_FUTURE_PREFIX = "20260903"

assert ANALYSIS_ID == "EXISTING_ARCHITECTURE_EXHAUSTION_REVIEW_V1"
assert CASE_A and CASE_B and CASE_C
assert NEXT_OR_RECONCILE != "OPEN_STRENGTH_LEADER_FULL_STRATEGY_V1"
