"""Frozen architecture inventory from existing source/spec/report artifacts only."""
from __future__ import annotations

from typing import Any

from research.existing_architecture_exhaustion_review_v1 import STATUS_ENUM

ROW_FIELDS = (
    "ARCHITECTURE_ID",
    "FIRST_KNOWN_DATE",
    "SOURCE_PATH",
    "ENTRY_ARCHITECTURE",
    "EXECUTION_ARCHITECTURE",
    "EXIT_ARCHITECTURE",
    "PORTFOLIO_CONTRACT",
    "ORIGINAL_CAP",
    "DATA_SCOPE",
    "ACTUAL_PAPER_RUN",
    "REPLAY_RUN",
    "FULL_CAUSAL_RUN",
    "REALISTIC_EXECUTION_PROVEN",
    "QUEUE_ASSUMPTION",
    "ROBUSTNESS_TESTED",
    "CONCENTRATION_TESTED",
    "FINAL_VERDICT",
    "CURRENT_STATUS",
    "WHY_CLOSED_OR_OPEN",
    "EXACT_DUPLICATE_OF",
    "STRESS_INFORMED",
    "FUTURE_USED",
    "PREEXISTING",
    "EXACT_SOURCE_RECOVERABLE",
    "IS_DUPLICATE",
    "ALREADY_ROBUST_FAILED",
    "INTEGRITY_INVALIDATED",
    "ALREADY_FULL_CAUSAL_EVALUATED",
    "CAUSAL_DATA_REPRODUCIBLE",
    "FUTURE_REQUIRED",
    "RECONSTRUCTION_RANK",
    "HISTORICAL_COVERAGE_PROVEN",
    "EVIDENCE_PATHS",
)


def _r(**kwargs: Any) -> dict[str, Any]:
    row = {k: kwargs[k] for k in ROW_FIELDS}
    status = str(row["CURRENT_STATUS"])
    if status not in STATUS_ENUM:
        raise ValueError(f"illegal CURRENT_STATUS {status}")
    return row


def architecture_inventory() -> list[dict[str, Any]]:
    return [
        _r(
            ARCHITECTURE_ID="PRODUCTION_PBV2_MAINLINE",
            FIRST_KNOWN_DATE="20260529",
            SOURCE_PATH="src/small_paper/pilot_runner.py",
            ENTRY_ARCHITECTURE="Stage2 PBv2 continuation-quality mainline (entry_score_v2 / quality gates)",
            EXECUTION_ARCHITECTURE="Runtime/paper live fill path (not research Ask1 occupancy harvest)",
            EXIT_ARCHITECTURE="combined_structural_exit_v1_trailing_mfe_shadow (production YAML)",
            PORTFOLIO_CONTRACT="Split CAP with OR overlay: PBv2 pool cap_pbv2=4, same-symbol no overlap",
            ORIGINAL_CAP="cap_pbv2=4 (total 5 with OR)",
            DATA_SCOPE="Paper journals 20260529–20260714 cited in Phase551/Phase687W27",
            ACTUAL_PAPER_RUN=True,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="phase551_current_runtime_full_period_replay_done; production mainline still active",
            CURRENT_STATUS="ALREADY_EXECUTED_FULL_STRATEGY",
            WHY_CLOSED_OR_OPEN="Exact PBv2 Full Strategy is production Runtime/paper occupancy, not an untested research architecture.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/reports/phase551_report.json; configs/small_paper_pilot_q070_cap3_entry_price_risk_guard_trailing_mfe_shadow.yaml",
        ),
        _r(
            ARCHITECTURE_ID="PRODUCTION_OR_OPEN_STRENGTH_OVERLAY",
            FIRST_KNOWN_DATE="20260625",
            SOURCE_PATH="src/small_paper/or_overlay_entry.py",
            ENTRY_ARCHITECTURE="PBv2-reject fallback overlay: O_R003 CurrentPrice near causal HighPrice within DAY_HIGH_NEAR_PCT=0.25 and update_count<=8; reason OS9 (mins<=90 AND rank<=10 AND vwap>0) or day_leader (mins<=90 AND rank<=10)",
            EXECUTION_ARCHITECTURE="Same Runtime/paper fill as PBv2 after overlay accept; skipped if PBv2 already accepted or same-symbol open",
            EXIT_ARCHITECTURE="Shared production structural_exit_policy with PBv2 (no dedicated OR EXIT)",
            PORTFOLIO_CONTRACT="pilot_runner._maybe_try_or_overlay_entry only if pbv2_decision.accept is false; split pools cap_pbv2=4 cap_or=1",
            ORIGINAL_CAP="cap_or=1",
            DATA_SCOPE="Phase534 theory 20260529–20260624; Phase687W27 paper 20260615–20260714; OR-era 9 days with or_accepts=73",
            ACTUAL_PAPER_RUN=True,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=False,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="Production overlay exists; isolated OR-sleeve Full Causal occupancy contribution NOT found",
            CURRENT_STATUS="PREEXISTING_PARTIALLY_TESTED",
            WHY_CLOSED_OR_OPEN="Runtime/paper overlay is preexisting, but combined PBv2+OR journals (W27) are not isolated OR-sleeve Full Causal. Not a standalone strategy.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=False,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="src/small_paper/or_overlay_entry.py; src/small_paper/or_overlay_cap.py; src/small_paper/pilot_runner.py:_maybe_try_or_overlay_entry; src/research/phase534_or_open_strength_theory.py; docs/operations/phase538_or_overlay_runtime_adoption.md; results/reports/phase687w27_pm_or_slot_policy_comparison/phase687w27_results.json; results/reports/phase551_report.json",
        ),
        _r(
            ARCHITECTURE_ID="OPEN_STRENGTH_STANDALONE",
            FIRST_KNOWN_DATE="NONE",
            SOURCE_PATH="NONE (proposed OPEN_STRENGTH_LEADER_FULL_STRATEGY_V1 is not in Runtime)",
            ENTRY_ARCHITECTURE="Would drop PBv2-reject requirement and reuse O_R003/OS9 primitives as standalone ENTRY",
            EXECUTION_ARCHITECTURE="Not defined in production",
            EXIT_ARCHITECTURE="Proposed new ZV/Z3/ZH is not production OR EXIT",
            PORTFOLIO_CONTRACT="Proposed CAP 1→5 is not production cap_or=1 overlay",
            ORIGINAL_CAP="proposed 5 (not production)",
            DATA_SCOPE="NONE",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=False,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=False,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="NEW_DERIVATIVE_NOT_PREEXISTING",
            CURRENT_STATUS="NEW_DERIVATIVE_NOT_PREEXISTING",
            WHY_CLOSED_OR_OPEN="Old O_R003 primitive + standalone CAP5 + new EXIT is not preexisting Production OR.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=False,
            EXACT_SOURCE_RECOVERABLE=False,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=False,
            CAUSAL_DATA_REPRODUCIBLE=False,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=9,
            HISTORICAL_COVERAGE_PROVEN=False,
            EVIDENCE_PATHS="src/small_paper/pilot_runner.py:_maybe_try_or_overlay_entry (overlay-only path)",
        ),
        _r(
            ARCHITECTURE_ID="E1_X6_SCORE_JOINT",
            FIRST_KNOWN_DATE="20260801",
            SOURCE_PATH="kabu_native/docs/e1_x6_validation_plan.md",
            ENTRY_ARCHITECTURE="Score / score-derived X6 joint ENTRY (Stage1 200 + Stage2 196)",
            EXECUTION_ARCHITECTURE="X6 joint research occupancy (not production Runtime)",
            EXIT_ARCHITECTURE="X5 frozen / tighter-stop / wider-target families in joint registry",
            PORTFOLIO_CONTRACT="Joint strategy research, CAP200 registry, 9-day 20260721–20260731",
            ORIGINAL_CAP="joint_cap=200 (candidate registry, not production CAP5)",
            DATA_SCOPE="20260721–20260731",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="E1_X6_NO_ROBUST_JOINT_STRATEGY",
            CURRENT_STATUS="CLOSED_ROBUST_FAILURE",
            WHY_CLOSED_OR_OPEN="Score-based 396-strategy joint gates failed. Plan V3 says this verdict is historical and must not be reopened as a candidate.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=2,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/e1_x6_redesign_20260721_20260731/joint_validation_e1x6_joint_20260802_105444_48d0ed8e.json",
        ),
        _r(
            ARCHITECTURE_ID="E1_X6R3_CONT_PULL_BREAK",
            FIRST_KNOWN_DATE="20260802",
            SOURCE_PATH="kabu_native/docs/e1_x6_plan_v3_raw_feature_redesign.md",
            ENTRY_ARCHITECTURE="IDLE→SETUP→CONFIRM→TRIGGER→OPEN; CONT / PULL / BREAK; STANDARD/STRICT confirm; market regimes TREND_UP/RANGE_LOW_VOL/EXPANSION_UP/RISK_OFF_UNSTABLE/NEUTRAL",
            EXECUTION_ARCHITECTURE="Ask buy / bid sell, 5bps, 100 shares, CAP5, 5s grid as-of",
            EXIT_ARCHITECTURE="EXIT_A_STRUCTURAL vs EXIT_B_STRUCTURAL_TRAIL; registry X6R3_<CONT|PULL|BREAK>_<STANDARD|STRICT>_<REG_*>_<EXIT_A|EXIT_B>",
            PORTFOLIO_CONTRACT="Max 24 registry candidates; 9-day equal-weight; Rolling-origin / RefitLODO",
            ORIGINAL_CAP="5",
            DATA_SCOPE="20260721–20260731 AM/PM (X6R3 Phase B store)",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="E1_X6_RAW_REDESIGN_PHASE_B_NO_ROBUST_CANDIDATE",
            CURRENT_STATUS="CLOSED_ROBUST_FAILURE",
            WHY_CLOSED_OR_OPEN="All 24 X6R3 candidates failed qualification (selected=None). CONT/PULL/BREAK + regimes already closed. Do not re-candidate.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="C:/Users/yhach/e1x6_research_store/raw_feature_redesign/e1x6r3b_20260803_051047_53886aa0/published/report.json",
        ),
        _r(
            ARCHITECTURE_ID="E1_X6_FCRR",
            FIRST_KNOWN_DATE="20260803",
            SOURCE_PATH="docs/research/e1_x6_fcrr_implementation_spec.md",
            ENTRY_ARCHITECTURE="FCRR sequential SELLING_EXHAUSTED-mandatory state machine F1/F2 R10/R20/R30",
            EXECUTION_ARCHITECTURE="FCRR research occupancy; economics_opened=false on Phase B revision",
            EXIT_ARCHITECTURE="Joint EXIT planned; never reached because ENTRY unreachable",
            PORTFOLIO_CONTRACT="Frozen E1_X5 comparison CAP/EXIT; sequential family",
            ORIGINAL_CAP="5 (spec vs Frozen E1_X5)",
            DATA_SCOPE="20260721–20260731 fitted_on_build_days 20260721–24",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="FCRR_SEQUENTIAL_ENTRY_FAMILY_UNREACHABLE",
            CURRENT_STATUS="CLOSED_ROBUST_FAILURE",
            WHY_CLOSED_OR_OPEN="All sequential FCRR profiles ENTRY_UNREACHABLE. Freeze says not edge negation, but family is not executable and successor TAER also closed. Do not reopen FCRR.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=False,
            EVIDENCE_PATHS="results/research/e1_x6_fcrr_phase_b_entry_revision/report.json; C:/Users/yhach/e1x6_research_store/fcrr/FREEZE_PHASE_B_STATUS.json",
        ),
        _r(
            ARCHITECTURE_ID="E1_X6_TAER",
            FIRST_KNOWN_DATE="20260803",
            SOURCE_PATH="src/research/e1_x6_taer/run_study.py",
            ENTRY_ARCHITECTURE="Trigger-anchored entry: actual cross first, then lookback setup/exhaustion (TAER_P0–P3)",
            EXECUTION_ARCHITECTURE="TAER joint occupancy on 20260721–20260731",
            EXIT_ARCHITECTURE="TAER retention R0/R10/R20 joint EXIT pairs",
            PORTFOLIO_CONTRACT="Adoptable profiles P1–P3; P0 diagnostic-only",
            ORIGINAL_CAP="research joint (Frozen E1_X5 comparison)",
            DATA_SCOPE="20260721–20260731",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="E1_X6_NO_ROBUST_ENTRY_EXIT_PAIR",
            CURRENT_STATUS="CLOSED_ROBUST_FAILURE",
            WHY_CLOSED_OR_OPEN="Integrity rerun after invalid joint economics: no robust ENTRY×EXIT pair. Do not reopen TAER trigger-anchored family.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="C:/Users/yhach/e1x6_research_store/taer/e1x6_taer_integrity_20260804_004800/report.json",
        ),
        _r(
            ARCHITECTURE_ID="E1_X7_PFQ",
            FIRST_KNOWN_DATE="20260804",
            SOURCE_PATH="C:/Users/yhach/e1x6_research_store/e1_x7_pfq/e1x7_pfq_20260804_080510/report.json",
            ENTRY_ARCHITECTURE="PFQ_UPDATE_Q70 (price_update_count_10s>=8) and/or PFQ_FLOW_Q30 (uptick_volume_ratio_30s<=0.7991666666666666); joint support n=41 insufficient",
            EXECUTION_ARCHITECTURE="Event-time same-symbol bids after entry; 1s grid max hold 300s",
            EXIT_ARCHITECTURE="Hard: HARD_STOP/MAX_HOLD/PULLBACK_LOW_BREAK/RECLAIM_LEVEL_BREAK/SESSION_END; Soft: MFE_GIVEBACK/NO_PROGRESS_UPDATE_DEAD/UPDATE_DETERIORATION",
            PORTFOLIO_CONTRACT="Independent ENTRY×EXIT joint study; exploratory design diagnostic only; prospective blocked",
            ORIGINAL_CAP="research PFQ (not production split CAP)",
            DATA_SCOPE="20260721–20260731",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=False,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="E1_X7_DESIGN_PERIOD_COMPLETE_PENDING_PROSPECTIVE; bridge E1_X7_PFQ_ENTRY_SUPPORTED_EXIT_CAPTURE_LIMITATION",
            CURRENT_STATUS="PREEXISTING_PARTIALLY_TESTED",
            WHY_CLOSED_OR_OPEN="Preexisting PFQ Full Strategy identity exists, but period_status=EXPLORATORY_DESIGN_ONLY and isolated Full Causal occupancy of this research unit was not run. Not selected by Runtime-history priority.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=False,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=2,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="C:/Users/yhach/e1x6_research_store/e1_x7_pfq/e1x7_pfq_20260804_080510/report.json; C:/Users/yhach/e1x6_research_store/e1_x7_pfq_bridge_v2/e1x7_pfq_bridge_v2_20260804_233025_B/report_raw.json",
        ),
        _r(
            ARCHITECTURE_ID="RPFE",
            FIRST_KNOWN_DATE="20260724",
            SOURCE_PATH="results/research/realistic_price_flow_entry/20260724_010347/report.json",
            ENTRY_ARCHITECTURE="Realistic Price-Flow ENTRY temporal state machine (real micro-high / range-high cross)",
            EXECUTION_ARCHITECTURE="Offline RPFE harvest; RPFE_OFFLINE_ONLY",
            EXIT_ARCHITECTURE="Early-stop label fixed; not production EXIT",
            PORTFOLIO_CONTRACT="Offline comparison vs PBv2; no production change",
            ORIGINAL_CAP="research vs PBv2 CAP5",
            DATA_SCOPE="RPFE 20260724 reports; later E1_X15 incremental 20260721–31",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="RPFE_TEMPORAL_NO_EDGE / RPFE_OFFLINE_ONLY; E1_X15 selected_candidate=null",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="Full evidence: temporal no edge. Do not revive under a new name.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/realistic_price_flow_entry/20260724_010347/report.json; results/research/e1_x15_rpfe_incremental_entry/report.json",
        ),
        _r(
            ARCHITECTURE_ID="VCIE",
            FIRST_KNOWN_DATE="20260724",
            SOURCE_PATH="results/research/volume_confirmed_impulse_entry/20260724_210951/report.json",
            ENTRY_ARCHITECTURE="Volume-Confirmed Impulse ENTRY (true volume impulse / breakout-hold / trade-side inferred)",
            EXECUTION_ARCHITECTURE="Offline VCIE; VCIE_OFFLINE_ONLY",
            EXIT_ARCHITECTURE="Not production",
            PORTFOLIO_CONTRACT="Offline; no production change",
            ORIGINAL_CAP="research",
            DATA_SCOPE="VCIE 20260724; quote semantic audit 20260725",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="VCIE_OFFLINE_ONLY / VCIE_CAPTURE_NO_EDGE; lineage QUOTE_SEMANTIC_GLOBAL_AFFECTED",
            CURRENT_STATUS="CLOSED_INTEGRITY_FAILURE",
            WHY_CLOSED_OR_OPEN="Quote semantic inversion invalidates VCIE/price-flow quote-inferred lineage. Also capture no edge. Do not rename-revive.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=True,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/volume_confirmed_impulse_entry/20260724_210951/report.json; results/research/global_quote_semantic_audit/20260725_065034/report.json",
        ),
        _r(
            ARCHITECTURE_ID="SIMPLE_TECH_ENTRY_FAMILY",
            FIRST_KNOWN_DATE="20260810",
            SOURCE_PATH="results/research/simple_tech_redesign/strategy_level_entry_rebase_v1/report.json",
            ENTRY_ARCHITECTURE="T3 pullback/RCI/board/volume family: V1/V4/V6/V8/V9/V10 eligible ENTRY IDs (17)",
            EXECUTION_ARCHITECTURE="E4_THEN_ASK_CROSS_W5",
            EXIT_ARCHITECTURE="SESSION_CLOSE_ONLY control during rebase; technical EXIT family exhausted separately",
            PORTFOLIO_CONTRACT="AM, CAP5, 100 shares, development through 20260827 listed in rebase spec",
            ORIGINAL_CAP="5",
            DATA_SCOPE="rebase development_days 20260722–20260827; family closed CASE C",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="SIMPLE_TECH_ENTRY_FAMILY_ABSOLUTE_EDGE_EXHAUSTED",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="T3/RCI/Board/Dynamic Anchor/old volume retune closed. Do not reopen as OPEN.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/simple_tech_redesign/strategy_level_entry_rebase_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="SIMPLE_TECH_V25_V29_EXIT_RCA",
            FIRST_KNOWN_DATE="20260820",
            SOURCE_PATH="results/research/simple_tech_redesign/branch_u_full_causal_portfolio_replay/report.json",
            ENTRY_ARCHITECTURE="Not a new ENTRY; EXIT RCA on existing Simple-Tech signals",
            EXECUTION_ARCHITECTURE="V27 fill identity",
            EXIT_ARCHITECTURE="V25/V26 coverage; V27 sequence; V28 persistence; V29 terminal-failure RCA",
            PORTFOLIO_CONTRACT="EXIT diagnostic, not a standalone Full Strategy identity",
            ORIGINAL_CAP="5 (parent Simple-Tech)",
            DATA_SCOPE="Frozen V26–V29 verdicts inside Branch U replay report",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="V26 coverage/exit-separation failed; V28 winner harm; V29 mixed; technical EXIT development exhausted",
            CURRENT_STATUS="NOT_FULL_STRATEGY",
            WHY_CLOSED_OR_OPEN="EXIT RCA family, not a Full Strategy unit. CURRENT_SIMPLE_TECH_TECHNICAL_EXIT_DEVELOPMENT_EXHAUSTED. Do not reopen as OPEN.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/simple_tech_redesign/branch_u_full_causal_portfolio_replay/report.json",
        ),
        _r(
            ARCHITECTURE_ID="SIMPLE_TECH_BRANCH_U",
            FIRST_KNOWN_DATE="20260826",
            SOURCE_PATH="results/research/simple_tech_redesign/branch_u_full_causal_portfolio_replay/report.json",
            ENTRY_ARCHITECTURE="Simple-Tech Branch U (BB-lower-break EXIT overlay on existing ENTRY)",
            EXECUTION_ARCHITECTURE="V27 fill identity parity",
            EXIT_ARCHITECTURE="U_BB_LOWER_BREAK + session close",
            PORTFOLIO_CONTRACT="CAP-aware causal portfolio replay; holdout later terminated inconclusive then family exhausted",
            ORIGINAL_CAP="5",
            DATA_SCOPE="Branch U causal replay; HOLDOUT_STATUS_FROZEN=SIMPLE_TECH_BRANCH_U_HOLDOUT_TERMINATED_INCONCLUSIVE",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="SIMPLE_TECH_BRANCH_U_CAUSAL_PORTFOLIO_SUPPORTED then family ABSOLUTE_EDGE_EXHAUSTED / holdout inconclusive",
            CURRENT_STATUS="CLOSED_ROBUST_FAILURE",
            WHY_CLOSED_OR_OPEN="Later strategy-level rebase closed the Simple-Tech family. Branch U must not be reopened as OPEN.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/simple_tech_redesign/branch_u_full_causal_portfolio_replay/report.json; results/research/simple_tech_redesign/strategy_level_entry_rebase_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="SIMPLE_TECH_BRANCH_P",
            FIRST_KNOWN_DATE="20260826",
            SOURCE_PATH="results/research/simple_tech_redesign/branch_p_vwap_close_exit_v1/report.json",
            ENTRY_ARCHITECTURE="Simple-Tech parent ENTRY; Branch P is EXIT overlay",
            EXECUTION_ARCHITECTURE="Simple-Tech fill path",
            EXIT_ARCHITECTURE="P_VWAP close EXIT and P_BB structure EXIT",
            PORTFOLIO_CONTRACT="Technical EXIT overlay; later EXIT development exhausted",
            ORIGINAL_CAP="5",
            DATA_SCOPE="Branch P VWAP/BB reports under simple_tech_redesign",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="SIMPLE_TECH_BRANCH_P_VWAP_NOT_SUPPORTED; SIMPLE_TECH_BRANCH_P_BB_NOT_SUPPORTED",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="Both Branch P EXIT mechanisms not supported. Do not reopen.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/simple_tech_redesign/branch_p_vwap_close_exit_v1/report.json; results/research/simple_tech_redesign/branch_p_bb_structure_exit_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="SIMPLE_FULL_STRATEGY_75_GRID",
            FIRST_KNOWN_DATE="20260807",
            SOURCE_PATH="results/research/simple_full_strategy_discovery_v1/report.json",
            ENTRY_ARCHITECTURE="Simple-Full 75-grid ENTRY×EXEC×EXIT discovery (includes E4 cell)",
            EXECUTION_ARCHITECTURE="X1/X2 family Ask occupancy",
            EXIT_ARCHITECTURE="Z-family Technical EXITs including Z3",
            PORTFOLIO_CONTRACT="CAP=5, 100 shares, DEV 10d occupancy Full Causal",
            ORIGINAL_CAP="5",
            DATA_SCOPE="DEVELOPMENT 20260722–20260807",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="SIMPLE_FULL_STRATEGY_NO_ROBUST_CANDIDATE",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="75-grid Full Causal CASE B. No robust candidate. Do not rerun grid.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/simple_full_strategy_discovery_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="DYNAMIC_ANCHOR_TRAIL10",
            FIRST_KNOWN_DATE="20260804",
            SOURCE_PATH="results/research/dynamic_anchor_pnl_test_p2_2/report.json",
            ENTRY_ARCHITECTURE="Dynamic Anchor T1/C1 confirmation lineage",
            EXECUTION_ARCHITECTURE="P2-1 event validation then P2-2 reused-history PnL",
            EXIT_ARCHITECTURE="Trailing-10 overlay (P2-4A precommit; P2-2 worse on reused history)",
            PORTFOLIO_CONTRACT="Reused-history vs current; not production adoption",
            ORIGINAL_CAP="parent CAP",
            DATA_SCOPE="P2-2 reused history PnL test",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="P2_2_DYNAMIC_WORSE_ON_REUSED_HISTORY",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="Dynamic Anchor worse than current on reused history. Listed excluded on Simple-Tech rebase. Do not reopen.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/dynamic_anchor_pnl_test_p2_2/report.json",
        ),
        _r(
            ARCHITECTURE_ID="AM_C0",
            FIRST_KNOWN_DATE="20260820",
            SOURCE_PATH="results/research/am_entry_research_final_decision/report.json",
            ENTRY_ARCHITECTURE="C0_B0_PRIMARY_B1_CONFIRM AM ENTRY prospective challenger",
            EXECUTION_ARCHITECTURE="DEV_WAIT_SEC=5 overlay vs current AM",
            EXIT_ARCHITECTURE="AM C0 indicator EXIT overlay (frozen prospective spec)",
            PORTFOLIO_CONTRACT="Paired overlay vs current; RUNTIME_ADOPTION_ALLOWED=false; frozen for future OOS only then Stress integrity failed",
            ORIGINAL_CAP="overlay vs current CAP",
            DATA_SCOPE="AM development 18d search closed; Stress 20260828–20260902 integrity failed",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="AM_ENTRY_DEVELOPMENT_CLOSED_C0_PROSPECTIVE_CHALLENGER_FROZEN then AM_C0_STRESS_INTEGRITY_FAILED",
            CURRENT_STATUS="CLOSED_INTEGRITY_FAILURE",
            WHY_CLOSED_OR_OPEN="Development closed as frozen prospective challenger (not adopted). Reused-history Stress CASE E integrity failed. Do not reopen C0.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=True,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=True,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/am_entry_research_final_decision/report.json; results/research/am_c0_reused_history_stress_20260828_20260902_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="V1R_P1",
            FIRST_KNOWN_DATE="20260722",
            SOURCE_PATH="src/small_paper/v1r_native_entry_live.py",
            ENTRY_ARCHITECTURE="V1R frozen P1 native ENTRY",
            EXECUTION_ARCHITECTURE="v1r_live_dual_lane / native live path",
            EXIT_ARCHITECTURE="V1R P1 frozen EXIT",
            PORTFOLIO_CONTRACT="Frozen P1 strategy extension attempted through 20260902",
            ORIGINAL_CAP="V1R P1 production/paper contract",
            DATA_SCOPE="P1_FULL14_DAYS 20260722–20260820; extension through 20260902 integrity failed",
            ACTUAL_PAPER_RUN=True,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=False,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="V1R_FROZEN_REPLAY_INTEGRITY_FAILED; V1R_P1_IMPLEMENTATION_RECOVERY_EXHAUSTED",
            CURRENT_STATUS="CLOSED_INTEGRITY_FAILURE",
            WHY_CLOSED_OR_OPEN="P1 source unrecoverable / BYTE_IDENTICAL=false. Implementation recovery exhausted. Do not return to P1 source recovery.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=True,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=False,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=True,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=False,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=9,
            HISTORICAL_COVERAGE_PROVEN=False,
            EVIDENCE_PATHS="results/research/v1r_p1_source_forensic_recovery_v1/report.json; results/research/v1r_frozen_p1_strategy_extension_through_20260902_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="BREAKOUT_CONTINUATION",
            FIRST_KNOWN_DATE="20260807",
            SOURCE_PATH="results/research/new_entry_breakout_continuation_v1/report.json",
            ENTRY_ARCHITECTURE="P1 5-bar high first-cross AND P2 volume>prior-10 median AND P3 Close>session VWAP",
            EXECUTION_ARCHITECTURE="Ask occupancy Full Causal",
            EXIT_ARCHITECTURE="Technical EXIT family used in that Full Strategy run",
            PORTFOLIO_CONTRACT="CAP=5 occupancy; DEV then locked Holdout",
            ORIGINAL_CAP="5",
            DATA_SCOPE="DEV 10d then burned Holdout 8d",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="NEW_ENTRY_BREAKOUT_CONTINUATION_DEV_FAILED; BREAKOUT_CONTINUATION_HOLDOUT_ALPHA_FAILED; BREAKOUT_PERMANENTLY_CLOSED",
            CURRENT_STATUS="CLOSED_ROBUST_FAILURE",
            WHY_CLOSED_OR_OPEN="Holdout CASE C permanently closed Breakout. Do not retune.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/new_entry_breakout_continuation_v1/report.json; results/research/breakout_continuation_locked_holdout_alpha_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="VWAP_REJECTION_RECLAIM",
            FIRST_KNOWN_DATE="20260807",
            SOURCE_PATH="results/research/new_entry_vwap_rejection_reclaim_v1/report.json",
            ENTRY_ARCHITECTURE="VWAP rejection then reclaim chase family (not Low<VWAP / Close>Open FDR)",
            EXECUTION_ARCHITECTURE="Ask occupancy Full Causal",
            EXIT_ARCHITECTURE="Technical EXIT family in that Full Strategy run",
            PORTFOLIO_CONTRACT="CAP=5 DEV-only; Holdout never opened",
            ORIGINAL_CAP="5",
            DATA_SCOPE="DEVELOPMENT 20260722–20260807",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="NEW_ENTRY_VWAP_RECLAIM_DEV_FAILED",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="DEV CASE B. Holdout never opened. Do not retune VWAP reclaim.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/new_entry_vwap_rejection_reclaim_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="FAILED_BREAKDOWN_RECLAIM",
            FIRST_KNOWN_DATE="20260807",
            SOURCE_PATH="results/research/new_entry_failed_breakdown_reclaim_v1/report.json",
            ENTRY_ARCHITECTURE="Failed breakdown reclaim (distinct from VWAP chase and Breakout)",
            EXECUTION_ARCHITECTURE="Ask occupancy Full Causal",
            EXIT_ARCHITECTURE="Technical EXIT family in that Full Strategy run",
            PORTFOLIO_CONTRACT="CAP=5 DEV-only",
            ORIGINAL_CAP="5",
            DATA_SCOPE="DEVELOPMENT 20260722–20260807",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="FAILED_BREAKDOWN_RECLAIM_DEV_ALPHA_FAILED",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="DEV CASE C family closed. Do not retune FDR.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/new_entry_failed_breakdown_reclaim_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="E4_X2_Z3",
            FIRST_KNOWN_DATE="20260807",
            SOURCE_PATH="results/research/e4_x2_z3_causal_concentration_recheck_v1/report.json",
            ENTRY_ARCHITECTURE="E4 Simple-Full ENTRY cell",
            EXECUTION_ARCHITECTURE="X2",
            EXIT_ARCHITECTURE="Z3",
            PORTFOLIO_CONTRACT="CAP=5 Full Causal; causal EX-TOP1 exclude 285A before signal",
            ORIGINAL_CAP="5",
            DATA_SCOPE="DEV 10d; causal recheck confirmed true symbol dependence",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="E4_X2_Z3_TRUE_SYMBOL_DEPENDENCE_CONFIRMED",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="TRUE_SYMBOL_DEPENDENCE. Prior DROP_TOP was CLASS A posthoc. Closed. Do not rerun E4.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/e4_x2_z3_causal_concentration_recheck_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="RECOVERY_SEQUENCE",
            FIRST_KNOWN_DATE="20260905",
            SOURCE_PATH="results/research/recovery_sequence_full_strategy_architecture_v1/report.json",
            ENTRY_ARCHITECTURE="Recovery Sequence R1–R3 ENTRY state machine",
            EXECUTION_ARCHITECTURE="Ask occupancy Full Causal",
            EXIT_ARCHITECTURE="Paired Technical EXITs in the 6-candidate grid",
            PORTFOLIO_CONTRACT="CAP=5; 6 candidates; causal EX-TOP1",
            ORIGINAL_CAP="5",
            DATA_SCOPE="DEVELOPMENT 20260722–20260807",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="RECOVERY_SEQUENCE_FULL_STRATEGY_NO_ROBUST_CANDIDATE",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="6/6 coverage; 0 economic PASS; all CAUSAL_EX_TOP1_PNL negative. Do not add R4.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/recovery_sequence_full_strategy_architecture_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="PARTICIPATION_ONSET",
            FIRST_KNOWN_DATE="20260906",
            SOURCE_PATH="results/research/participation_onset_full_strategy_v1/report.json",
            ENTRY_ARCHITECTURE="P1 T1 volume_percentile_60s FALSE→TRUE onset; threshold frozen 0.6486486486486487; no above-VWAP filter",
            EXECUTION_ARCHITECTURE="X1 first fresh Ask1 at/after t0",
            EXIT_ARCHITECTURE="Exactly 3: Z3 / ZP / ZH",
            PORTFOLIO_CONTRACT="CAP=5, 100 shares, DEV occupancy Full Causal",
            ORIGINAL_CAP="5",
            DATA_SCOPE="DEVELOPMENT 20260722–20260807",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=True,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="PARTICIPATION_ONSET_FULL_STRATEGY_NO_ROBUST_CANDIDATE",
            CURRENT_STATUS="CLOSED_ECONOMIC_FAILURE",
            WHY_CLOSED_OR_OPEN="3/3 economic fail. Do not retune T1. Do not add VWAP filter. Do not add 4th EXIT.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=0,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/participation_onset_full_strategy_v1/report.json",
        ),
        _r(
            ARCHITECTURE_ID="E1_X14_BOARD_INDEPENDENT_SIGNAL",
            FIRST_KNOWN_DATE="20260805",
            SOURCE_PATH="results/research/e1_x15_rpfe_incremental_entry/report.json",
            ENTRY_ARCHITECTURE="Board-independent feature/signal audit (T1 volume_percentile_60s among components)",
            EXECUTION_ARCHITECTURE="Feature audit / holdout mixed components — not occupancy Full Strategy",
            EXIT_ARCHITECTURE="None as Full Strategy unit",
            PORTFOLIO_CONTRACT="NOT_FULL_STRATEGY",
            ORIGINAL_CAP="n/a",
            DATA_SCOPE="E1_X14 holdout mixed component candidates; days already used in feature selection",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="E1_X14_HOLDOUT_MIXED_COMPONENT_CANDIDATES_FOUND",
            CURRENT_STATUS="NOT_FULL_STRATEGY",
            WHY_CLOSED_OR_OPEN="Feature/signal audit, not ENTRY+EXEC+EXIT+CAP Full Strategy identity.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=2,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/e1_x15_rpfe_incremental_entry/report.json (source_verdict E1_X14_HOLDOUT_MIXED_COMPONENT_CANDIDATES_FOUND)",
        ),
        _r(
            ARCHITECTURE_ID="E1_X15_RPFE_INCREMENTAL",
            FIRST_KNOWN_DATE="20260805",
            SOURCE_PATH="results/research/e1_x15_rpfe_incremental_entry/report.json",
            ENTRY_ARCHITECTURE="C0–C* incremental gates on distance_from_vwap_bps / rebound_from_recent_low_bps / volume_percentile_60s",
            EXECUTION_ARCHITECTURE="RPFE episode incremental study (exploratory combination)",
            EXIT_ARCHITECTURE="Forward-return / MFE-MAE diagnostic, not frozen Full Strategy EXIT",
            PORTFOLIO_CONTRACT="INTERNAL_EXPLORATORY_COMBINATION_STUDY; selected_candidate=null",
            ORIGINAL_CAP="n/a",
            DATA_SCOPE="20260721–20260731 already used in feature selection",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=True,
            FULL_CAUSAL_RUN=True,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=True,
            CONCENTRATION_TESTED=True,
            FINAL_VERDICT="E1_X15_INCREMENTAL_CANDIDATE_MIXED selected_candidate=null",
            CURRENT_STATUS="CLOSED_DUPLICATE",
            WHY_CLOSED_OR_OPEN="RPFE-lineage incremental combination; selected none. Not a distinct remaining architecture.",
            EXACT_DUPLICATE_OF="RPFE",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=True,
            EXACT_SOURCE_RECOVERABLE=True,
            IS_DUPLICATE=True,
            ALREADY_ROBUST_FAILED=True,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=True,
            CAUSAL_DATA_REPRODUCIBLE=True,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=1,
            HISTORICAL_COVERAGE_PROVEN=True,
            EVIDENCE_PATHS="results/research/e1_x15_rpfe_incremental_entry/report.json",
        ),
        _r(
            ARCHITECTURE_ID="TAER_PULLBACK_NEW_FAMILY_HYPOTHESIS",
            FIRST_KNOWN_DATE="20260804",
            SOURCE_PATH="C:/Users/yhach/e1x6_research_store/taer/e1x6_taer_fsa_v4_20260804_071044/report.json",
            ENTRY_ARCHITECTURE="FSA V4 pullback new-family hypothesis (not a frozen Full Strategy spec)",
            EXECUTION_ARCHITECTURE="None frozen",
            EXIT_ARCHITECTURE="None frozen",
            PORTFOLIO_CONTRACT="Hypothesis support only; TAER V1 closeout unchanged",
            ORIGINAL_CAP="n/a",
            DATA_SCOPE="TAER FSA V4 on 20260721–20260731 clusters",
            ACTUAL_PAPER_RUN=False,
            REPLAY_RUN=False,
            FULL_CAUSAL_RUN=False,
            REALISTIC_EXECUTION_PROVEN=False,
            QUEUE_ASSUMPTION=False,
            ROBUSTNESS_TESTED=False,
            CONCENTRATION_TESTED=False,
            FINAL_VERDICT="TAER_PULLBACK_NEW_FAMILY_HYPOTHESIS_SUPPORTED|TAER_RANGE_STABLE_FEATURES_MODEL_SUPPORT_INSUFFICIENT",
            CURRENT_STATUS="NEW_DERIVATIVE_NOT_PREEXISTING",
            WHY_CLOSED_OR_OPEN="A new family hypothesis after TAER closeout is not a preexisting Full Strategy architecture. Handmade follow-on forbidden by this gate.",
            EXACT_DUPLICATE_OF="",
            STRESS_INFORMED=False,
            FUTURE_USED=False,
            PREEXISTING=False,
            EXACT_SOURCE_RECOVERABLE=False,
            IS_DUPLICATE=False,
            ALREADY_ROBUST_FAILED=False,
            INTEGRITY_INVALIDATED=False,
            ALREADY_FULL_CAUSAL_EVALUATED=False,
            CAUSAL_DATA_REPRODUCIBLE=False,
            FUTURE_REQUIRED=False,
            RECONSTRUCTION_RANK=9,
            HISTORICAL_COVERAGE_PROVEN=False,
            EVIDENCE_PATHS="C:/Users/yhach/e1x6_research_store/taer/e1x6_taer_fsa_v4_20260804_071044/report.json",
        ),
    ]


def open_strength_audit() -> dict[str, Any]:
    return {
        "A_OR_ENTRY_PREDICATE": (
            "O_R003: CurrentPrice near causal board HighPrice within DAY_HIGH_NEAR_PCT=0.25 "
            "AND update_count<=8. Then reason: OS9_open_strength_proxy "
            "(minutes_from_open<=90 AND day_return rank<=10 AND vwap_distance>0) "
            "OR day_leader (minutes_from_open<=90 AND rank<=10)."
        ),
        "B_OR_OVERLAY_ROLE": (
            "PBv2 rejection fallback overlay. _maybe_try_or_overlay_entry returns pbv2_decision "
            "unchanged if pbv2_decision.accept is true, or if same-symbol already open."
        ),
        "C_OR_CAP": "cap_pbv2=4, cap_or=1, total 5; independent pools; REJECT_OR_CAP_FULL",
        "D_OR_EXIT_POLICY": (
            "No dedicated OR EXIT. Shared production structural_exit_policy "
            "(combined_structural_exit_v1_trailing_mfe_shadow on production YAML)."
        ),
        "E_OR_OBSERVED_EVIDENCE": (
            "Phase687W27 all_paper A_CURRENT: accepted=1323 PnL=-252470 PF=0.8796 or_count=73 pbv2_count=1250. "
            "OR-era A_CURRENT: accepted=497 PnL=-96270 PF=0.9023 or_accepts=73 pbv2_count=424. "
            "Method: CAP-aware portfolio replay on Paper journals, not Capture event Full Causal occupancy."
        ),
        "F_OR_SLEEVE_ISOLATED_ECONOMICS": (
            "No artifact found that isolates OR-sleeve occupancy contribution vs PBv2-only under "
            "exact Production 4+1 split and overlay-only-on-PBv2-reject. Phase551 or_trades=0 / or_pnl=0 "
            "on 20260529–20260625 (OR-empty window). Combined-book W27 PnL is not OR_SLEEVE_CAUSAL_EDGE."
        ),
        "OR_SLEEVE_ISOLATED_FULL_CAUSAL_ALREADY_RUN": False,
        "CLASSIC_OPENING_RANGE_BREAKOUT": False,
        "STANDALONE_OPEN_STRENGTH_PREEXISTING": False,
        "PRODUCTION_OR_ROLE": "PBv2 reject fallback overlay (not standalone strategy)",
    }


def x6r3_audit() -> dict[str, Any]:
    return {
        "SCORE_JOINT_VERDICT": "E1_X6_NO_ROBUST_JOINT_STRATEGY",
        "SCORE_JOINT_SCOPE": "existing score / score-derived 396 strategies; historical; not X6R3 raw redesign conclusion",
        "X6R3_PHASE_B_VERDICT": "E1_X6_RAW_REDESIGN_PHASE_B_NO_ROBUST_CANDIDATE",
        "X6R3_SELECTED": None,
        "X6R3_QUALIFIED": [],
        "X6R3_CONT_PULL_BREAK_CLOSED": True,
        "X6R3_FULL_STRATEGY_RUN": True,
        "X6R3_COVERAGE_INTEGRITY_CLOSURE": "integrity ok / A/B match / protected manifest match in Phase B report.md",
        "X6R3_ECONOMICS_CLOSURE": "all 24 candidates qualified=False; BREAK mostly n=0; CONT negative or thin; PULL thin/zero",
        "FCRR_VERDICT": "FCRR_SEQUENTIAL_ENTRY_FAMILY_UNREACHABLE",
        "FCRR_NOTE": "ENTRY_UNREACHABLE on sequential profiles; economics_opened=false; successor was TAER",
        "TAER_VERDICT": "E1_X6_NO_ROBUST_ENTRY_EXIT_PAIR",
        "REOPEN_X6R3": False,
        "EVIDENCE_PATHS": [
            "results/research/e1_x6_redesign_20260721_20260731/joint_validation_e1x6_joint_20260802_105444_48d0ed8e.json",
            "C:/Users/yhach/e1x6_research_store/raw_feature_redesign/e1x6r3b_20260803_051047_53886aa0/published/report.json",
            "results/research/e1_x6_fcrr_phase_b_entry_revision/report.json",
            "C:/Users/yhach/e1x6_research_store/taer/e1x6_taer_integrity_20260804_004800/report.json",
        ],
    }
