"""OPENING_LOGIC_INPUT_CAPABILITY_AUDIT_V1. Requirements input only. No economics. No MBO."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    STRESS_DAYS,
)

ANALYSIS_ID = "OPENING_LOGIC_INPUT_CAPABILITY_AUDIT_V1"
PARENT_ID = "EXISTING_DATA_ENTRY_ALIGNED_FULL_CAUSAL_LOGIC_COMPLETION_V1"
REQUIRED_PARENT_VERDICT = "ENTRY_ALIGNED_STATE_TRANSITION_ECONOMIC_FAIL_V1"
PARENT_ARCHITECTURE_CLOSED = True

LEGACY_DEV_DAYS = DEVELOPMENT_DAYS
QUARANTINE_DAYS = ("20260903", "20260904")

CASE_A = "OPENING_LOGIC_INPUTS_SUFFICIENT_FOR_REQUIREMENTS_V1"
CASE_B = "OPENING_LOGIC_SYMBOL_INPUTS_AVAILABLE_NO_MARKET_CONTEXT_V1"
CASE_C = "OPENING_LOGIC_PREOPEN_INPUT_NOT_SUPPORTED_V1"
NEXT_AB = "OPENING_LOGIC_REQUIREMENTS_FREEZE_V1"
NEXT_C = "OPENING_LOGIC_EXISTING_DATA_ARCHITECTURE_REDIRECT_V1"

MBO_WORK_THIS_RUN = False
EXTERNAL_ACQUISITION = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False
STRATEGY_CREATED = False
PNL_COMPUTED = False
OUTCOME_INFORMATION_COMPUTED = False
THRESHOLD_SELECTED = False

assert ANALYSIS_ID == "OPENING_LOGIC_INPUT_CAPABILITY_AUDIT_V1"
assert REQUIRED_PARENT_VERDICT == "ENTRY_ALIGNED_STATE_TRANSITION_ECONOMIC_FAIL_V1"
assert tuple(LEGACY_DEV_DAYS) == (
    "20260722",
    "20260728",
    "20260729",
    "20260730",
    "20260731",
    "20260803",
    "20260804",
    "20260805",
    "20260806",
    "20260807",
)
assert MAX_RESEARCH_DATE == "20260807"
assert MBO_WORK_THIS_RUN is False
assert EXTERNAL_ACQUISITION is False
assert SIZING is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert STRATEGY_CREATED is False
assert PNL_COMPUTED is False
assert OUTCOME_INFORMATION_COMPUTED is False
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert QUARANTINE_DAYS == ("20260903", "20260904")
