"""E4_X2_Z3 causal concentration recheck. Posthoc DROP_TOP vs Full Causal EX-TOP1. LODO restored. Stress sealed."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    CANDIDATE_N,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    LODO_TOP3_MIN,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
    WAIT_SEC,
)

ANALYSIS_ID = "E4_X2_Z3_CAUSAL_CONCENTRATION_RECHECK_V1"
FOCUS_CANDIDATE = "E4_X2_Z3"
PRIOR_ANALYSIS_ID = "SIMPLE_FULL_STRATEGY_DISCOVERY_V1"
PRIOR_VERDICT = "SIMPLE_FULL_STRATEGY_NO_ROBUST_CANDIDATE"
PRIOR_ECONOMIC_PASS_N = 0
PROSPECTIVE_HARVEST_SUSPENDED = True
TRUE_OOS = False
CERTIFIED = False
STRESS_OPENED_THIS_RUN = False
SIZING = False
RETUNE = False

EXPECTED_BASE = {
    "signal_n": 1784,
    "fill_n": 295,
    "TRADE_N": 295,
    "trades_per_day": 29.5,
    "TOTAL_PNL": 820060.0,
    "PF": 1.8901214601,
    "MAXDD": -162200.0,
    "positive_day_n": 6,
    "negative_day_n": 4,
    "EX_BEST_DAY_PNL": 426650.0,
    "DROP_TOP_SYMBOL_PNL": -387940.0,
    "direct_exit_effect": 145600.0,
    "slot_release_effect": 275200.0,
}

DROP_TOP_METHOD_A = "POSTHOC_LEDGER_SUBTRACTION"
DROP_TOP_METHOD_B = "CAUSAL_UNIVERSE_EXCLUSION_RERUN"

CASE_E = "E4_X2_Z3_RECHECK_INTEGRITY_FAILED"
CASE_TRUE_DEP = "E4_X2_Z3_TRUE_SYMBOL_DEPENDENCE_CONFIRMED"
CASE_A = "E4_X2_Z3_CORRECTED_FULL_STRATEGY_DEV_SUPPORTED"
CASE_C = "SIMPLE_FULL_STRATEGY_CORRECTED_SELECTION_CHANGED"
CASE_D = "SIMPLE_FULL_STRATEGY_CORRECTED_SELECTION_UNSTABLE"
CASE_B = "SIMPLE_FULL_STRATEGY_NO_ROBUST_CANDIDATE"

assert ANALYSIS_ID == "E4_X2_Z3_CAUSAL_CONCENTRATION_RECHECK_V1"
assert FOCUS_CANDIDATE == "E4_X2_Z3"
assert POSITION_CAP == 5
assert SHARES == 100
assert WAIT_SEC == 5.0
assert MAX_RESEARCH_DATE == "20260807"
assert STRESS_OPENED_THIS_RUN is False
assert SIZING is False
assert RETUNE is False
assert CANDIDATE_N == 75
assert LODO_TOP3_MIN == 6
assert MIN_PF == 1.10
assert len(DEVELOPMENT_DAYS) == 10
assert len(BURNED_HOLDOUT_DAYS) == 8
assert STRESS_DAYS == ("20260828", "20260831", "20260901", "20260902")
assert FORBIDDEN_INPUT_DAYS
