"""FREEZE_FIXED_DAYTRADE_UNIVERSE_V1. Quantitative freeze only. No strategy. No PnL."""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.fixed_universe_historical_foundation_v1 import (
    RECOMMENDED_STOCK_N,
    TARGET_UNIVERSE_MAX,
    TARGET_UNIVERSE_MIN,
)
from research.run_20260914_day2_futures_plus_first_live_breadth_v1 import TRADING_DATE as LIVE_TRADING_DATE

ANALYSIS_ID = "ACQUIRE_OFFICIAL_DAILY_60D_THEN_RETRY_FREEZE_V1"
PARENT_FREEZE_ID = "FREEZE_FIXED_DAYTRADE_UNIVERSE_V1"
PARENT_ID = "FIXED_UNIVERSE_HISTORICAL_RESEARCH_FOUNDATION_V1"
REQUIRED_PARENT_VERDICT = "HISTORICAL_FOUNDATION_PARTIAL_EXTERNAL_CONTEXT_V1"
KIND = "UNIVERSE_FREEZE_ONLY"
UNIVERSE_ID = "FIXED_DAYTRADE_UNIVERSE_V1"
SELECTION_METHODOLOGY_VERSION = "FIXED_DAYTRADE_UNIVERSE_SELECTION_V1"
PHASE = 1
EMPTY_UNFROZEN_SHA = "79bf6f5e7175a44c4e47d330d33e8285caecffae5c64937c211d0b409612ef94"

TARGET_N = int(RECOMMENDED_STOCK_N)
BAND_MIN = int(TARGET_UNIVERSE_MIN)
BAND_MAX = int(TARGET_UNIVERSE_MAX)
TRAIL_SESSIONS = 60
FREEZE_ASOF_JST = "20260913"
LAST_COMPLETE_TSE_SESSION = "20260911"
FORBIDDEN_DATA_FROM = "20260914"
PANEL_CONDITIONED_AS_OF = "202609"

CASE_FROZEN = "FIXED_DAYTRADE_UNIVERSE_FROZEN_V1"
CASE_WAITING = "FIXED_UNIVERSE_FREEZE_WAITING_FOR_DAILY_SOURCE_V1"
CASE_INSUFFICIENT = "FIXED_UNIVERSE_COVERAGE_INSUFFICIENT_V1"
CASE_KEY_REQUIRED = "JQUANTS_API_KEY_REQUIRED_FOR_UNIVERSE_FREEZE_V1"
CASE_CALENDAR_MISMATCH = "CALENDAR_WINDOW_MISMATCH_V1"
CASE_NO_VA = "TRADING_VALUE_FIELD_NOT_AVAILABLE_V1"
CASE_SCHEMA = "JQUANTS_DAILY_SCHEMA_MISMATCH_V1"
CASE_FETCH = "JQUANTS_DAILY_FETCH_FAILED_V1"
NEXT_PANEL = "BUILD_ALIGNED_HISTORICAL_PANEL_V1"
NEXT_RETRY = "ACQUIRE_OFFICIAL_DAILY_60D_THEN_RETRY_FREEZE_V1"
NEXT_SET_KEY = "SET_JQUANTS_API_KEY_THEN_RETRY_FREEZE_V1"
NEXT_REDESIGN = "REDESIGN_FIXED_UNIVERSE_COVERAGE_V1"
EXPECTED_WINDOW_FIRST = "20260618"
EXPECTED_WINDOW_LAST = "20260911"
EXPECTED_WINDOW_N = 60
JQUANTS_BASE = "https://api.jquants.com"
ENDPOINT_DAILY = "/v2/equities/bars/daily"
ENDPOINT_MASTER = "/v2/equities/master"
ENDPOINT_CALENDAR = "/v2/markets/calendar"

STRATEGY_SEARCH_STARTED = False
PANEL_BUILT = False
ENTRY = False
EXIT = False
LIVE_20260914_CHANGED = False
RUNTIME_CHANGED = False
PAPER_CHANGED = False
OUTCOME_USED = False
FUTURE_RETURN_USED = False
PAPER_RESULT_USED = False
THRESHOLD_OPTIMIZATION = False
YFINANCE_ALLOWED = False

REVIEW_CADENCE = ("quarterly", "semiannual")
MID_REMOVAL_ALLOWED = (
    "delisting",
    "structural_liquidity_collapse",
    "long_suspension",
    "corporate_reorganization",
    "persistent_operational_incompatibility",
)
MID_REMOVAL_FORBIDDEN = (
    "research_loss",
    "negative_paper_pnl",
    "low_strategy_score",
    "poor_backtest_result",
)

# Precommitted operability / liquidity floors. Not fitted to the candidate 45.
MIN_ACTIVE_SESSION_N = 55
MIN_SESSION_COVERAGE = 55.0 / 60.0
MIN_MEDIAN_VA_JPY = 1_000_000_000.0
MIN_P20_VA_JPY = 200_000_000.0
ROBUSTNESS_HALF_RATIO_FLOOR = 0.25
PAPER_LOT_QTY = 100
MARGIN_LEVERAGE = 2.0
MAX_POSITION_RATIO = 0.1
PAPER_MIN_ENTRY_PRICE = 50.0
PAPER_ACCOUNTING = "yen_100"
DEFAULT_PAPER_EQUITY_YEN = 1_000_000.0

assert ANALYSIS_ID == "ACQUIRE_OFFICIAL_DAILY_60D_THEN_RETRY_FREEZE_V1"
assert UNIVERSE_ID == "FIXED_DAYTRADE_UNIVERSE_V1"
assert EMPTY_UNFROZEN_SHA == "79bf6f5e7175a44c4e47d330d33e8285caecffae5c64937c211d0b409612ef94"
assert SELECTION_METHODOLOGY_VERSION == "FIXED_DAYTRADE_UNIVERSE_SELECTION_V1"
assert CASE_KEY_REQUIRED.startswith("JQUANTS_API_KEY_REQUIRED")
assert EXPECTED_WINDOW_N == 60
assert EXPECTED_WINDOW_LAST == LAST_COMPLETE_TSE_SESSION
assert REQUIRED_PARENT_VERDICT == "HISTORICAL_FOUNDATION_PARTIAL_EXTERNAL_CONTEXT_V1"
assert LAST_COMPLETE_TSE_SESSION < FORBIDDEN_DATA_FROM
assert FREEZE_ASOF_JST < FORBIDDEN_DATA_FROM
assert LIVE_TRADING_DATE == "20260914"
assert FEATURE_MINING_CLOSED is True
assert STRATEGY_SEARCH_STARTED is False
assert PANEL_BUILT is False
assert OUTCOME_USED is False
assert YFINANCE_ALLOWED is False
assert LIVE_20260914_CHANGED is False
assert THRESHOLD_OPTIMIZATION is False
assert BAND_MIN <= TARGET_N <= BAND_MAX
assert int(TRAIL_SESSIONS) == 60
assert int(PAPER_LOT_QTY) == 100
