"""POST_OPEN_AGGREGATE_ORDER_PRESSURE_ACCEPTANCE_FULL_STRATEGY_V1. LEGACY_DEV only."""
from __future__ import annotations

from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_OPTIONAL

ANALYSIS_ID = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_ACCEPTANCE_FULL_STRATEGY_V1"
PARENT_ID = "INTRADAY_SPECIAL_QUOTE_RESOLUTION_FULL_STRATEGY_V1"
REQUIRED_PARENT_VERDICT = "INTRADAY_SPECIAL_QUOTE_RESOLUTION_COVERAGE_FAIL_V1"
REQUIRED_PARENT_NEXT = "NEXT_NON_OPENING_POST_OPEN_ARCHITECTURE_V2"
OPENING_LINE_STATUS = "CLOSED"
ISQ_LINE_STATUS = "CLOSED"

CANARY_ROW_ID = "R2_X1_Z3"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
EXEC_EVAL_ID = "X1"
SHARES_N = 100
SESSION = "AM"
SESSION_FLATTEN_HM = (11, 29)
PORTFOLIO_WAIT_SEC = 0.05
BOARD_FRESHNESS_SEC = 5.0
POSITION_CAP_N = 5
CANDIDATE_N = 1
STRATEGY_ID = "AOP_DUAL_BUY_PRESSURE_X1_Z_ANCHOR_LOSS_V1"
EXIT_ID = "Z_AOP_PRESSURE_ANCHOR_LOSS"
PRESSURE_FIELDS = (
    "MarketOrderBuyQty",
    "MarketOrderSellQty",
    "UnderBuyQty",
    "OverSellQty",
)

CASE_PASS = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_ROBUST_DEV_CANDIDATE_FOUND_V1"
CASE_INPUT = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_INPUT_NOT_SUPPORTED_V1"
CASE_DUP = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_MATERIAL_DUPLICATE_V1"
CASE_INTEGRITY = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_INTEGRITY_FAIL_V1"
CASE_COVERAGE = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_COVERAGE_FAIL_V1"
CASE_ECON = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_ECONOMIC_FAIL_V1"
CASE_ROBUST = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_ROBUSTNESS_FAIL_V1"
CASE_PARITY = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_ENGINE_PARITY_FAIL_V1"
CASE_TESTS = "POST_OPEN_AGGREGATE_ORDER_PRESSURE_IMPLEMENTATION_SEMANTICS_FAIL_V1"
NEXT_PASS = "FROZEN_LOGIC_EXISTING_DATA_CONFIRMATION_V1"
NEXT_V3 = "NEXT_NON_OPENING_POST_OPEN_ARCHITECTURE_V3"
NEXT_FIX = "FIX_IMPLEMENTATION_ONLY"

MBO_WORK = False
FUTURES_WORK = False
SIZING = False
TRUE_OOS = False
CERTIFIED = False

assert ANALYSIS_ID == "POST_OPEN_AGGREGATE_ORDER_PRESSURE_ACCEPTANCE_FULL_STRATEGY_V1"
assert REQUIRED_PARENT_VERDICT == "INTRADAY_SPECIAL_QUOTE_RESOLUTION_COVERAGE_FAIL_V1"
assert STRATEGY_ID == "AOP_DUAL_BUY_PRESSURE_X1_Z_ANCHOR_LOSS_V1"
assert int(CANDIDATE_N) == 1
assert int(POSITION_CAP) == 5
assert int(SHARES_N) == 100
assert tuple(SESSION_FLATTEN_HM) == (11, 29)
assert CANARY_EXPECTED["signal_n"] == 490
assert MBO_WORK is False
assert SIZING is False
assert TRUE_OOS is False
assert MAX_RESEARCH_DATE == "20260807"
assert BURNED_HOLDOUT_DAYS and STRESS_DAYS and FORBIDDEN_INPUT_DAYS
assert CANARY_OPTIONAL
assert float(MIN_PF) == 1.10
assert int(MIN_TOTAL_TRADES) == 40
assert int(MIN_TRADING_DAYS_WITH_FILL) == 8
assert float(MIN_TRADES_PER_DAY) == 4.0
assert PRESSURE_FIELDS
