"""PB1 V4 prospective semantic validation. Frozen V4. Research only.

Does not mutate V4. Does not use PnL. Does not place orders.
"""
from __future__ import annotations

from research.current_day1_information_close_v1 import FEATURE_MINING_CLOSED
from research.pb1_v4_clarified_machine_correction_v4.definitions import machine_sha256 as v4_machine_sha256
from research.pb1_v4_clarified_machine_correction_v4.spec import source_sha256 as v4_source_sha256
from research.pb1_v4_clarified_machine_correction_v4_freeze_and_prospective_prep import (
    EXPECTED_SPEC_SHA,
    EXPECTED_V4_MACHINE_SHA256,
    EXPECTED_V4_SOURCE_SHA256,
    FROZEN_IDENTITY,
)
from research.pb1_v4_prospective_semantic_validation_preflight import (
    EXPECTED_MACHINE_SHA256,
    EXPECTED_SOURCE_INVENTORY_SHA256,
    FIRST_ELIGIBLE_JP_CASH_SESSION,
)
from research.pb1_v4_semantic_spec_clarification.spec import spec_sha256

PROGRAM_ID = "PB1_V4_PROSPECTIVE_SEMANTIC_VALIDATION"
ANALYSIS_ID = "PB1_V4_PROSPECTIVE_SEMANTIC_VALIDATION_V1"
FROZEN_IDENTITY_V4 = FROZEN_IDENTITY
EXPECTED_PRECOMMIT_SHA256 = "bbd6b733a66f9ba14be1105c7212d18b2baccb58c9579ec1a3137b8495d57ace"
SESSION0 = FIRST_ELIGIBLE_JP_CASH_SESSION
MIN_ACTIVE_SYMBOLS = 80
LOOKBACK_SESSIONS = 80
WHY_STOP = 21
SESSION_STOP = 40

assert spec_sha256() == EXPECTED_SPEC_SHA
assert v4_machine_sha256() == EXPECTED_V4_MACHINE_SHA256 == EXPECTED_MACHINE_SHA256
assert v4_source_sha256() == EXPECTED_V4_SOURCE_SHA256
assert EXPECTED_SOURCE_INVENTORY_SHA256 == "12299debc918a8b509c4105bc60448e0990c15748ded62ab72cbdf050886e4cf"
assert FROZEN_IDENTITY_V4 == "PB1_V4_CLARIFIED_MACHINE_CORRECTION_V4_FROZEN_V1"

CASE_STARTED = "PB1_V4_PROSPECTIVE_SEMANTIC_VALIDATION_STARTED_V1"
CASE_NOT_YET = "PB1_V4_PROSPECTIVE_PRESTART_NOT_YET_OCCURRED_V1"
CASE_WAITING = "PB1_V4_PROSPECTIVE_WAITING_FOR_AM_WINDOW_V1"
CASE_INELIGIBLE = "PB1_V4_PROSPECTIVE_SEMANTIC_VALIDATION_INELIGIBLE_SESSION_V1"
CASE_HASH = "DO_NOT_START_PROSPECTIVE"
CASE_BIND = "PB1_V4_PROSPECTIVE_SEMANTIC_VALIDATION_BIND_FAILED_V1"
NEXT_CONTINUE = "CONTINUE_FROZEN_PROSPECTIVE_BATCH"
NEXT_RETRY_AFTER_AM = "RETRY_START_PB1_V4_PROSPECTIVE_AFTER_20260924_AM_WINDOW"
NEXT_STOP = "STOP"

FEATURE_MINING = FEATURE_MINING_CLOSED
_ = FEATURE_MINING
