"""Prior driver-family exhaustion inventory. Status from published verdicts + data readiness. No PnL ranking."""
from __future__ import annotations

from typing import Any


def driver_inventory() -> list[dict[str, Any]]:
    return [
        {
            "driver_family": "USDJPY",
            "mechanism": "USDJPY causal return -> Japan market/sector future return",
            "source": "Dukascopy/Jetta 1m Bid/Ask mid",
            "resolution": "1m",
            "period": "DEV 20240917-20251126; C1 not opened",
            "target": "MKT105_EQW + 11 TSE33 EQW",
            "causal_timing": "FX available_at <= T; stock outcome after T",
            "sample": "288 tests; DEV_candidate_n=0; n≈10402 MKT clocks",
            "verdict": "USDJPY_STANDALONE_CAUSAL_LEAD_NOT_FOUND_V1",
            "status": "EXHAUSTED",
            "note": "Current architecture STOPPED. Old USDJPY_SECTOR_SPECIFIC_DRIVER_FOUND_V1 not reused. D3-near-misses are not candidates.",
        },
        {
            "driver_family": "NK225_MINI_TOPIX_FUTURES",
            "mechanism": "Index futures lead cash equity response",
            "source": "Kabu PUSH live; J-Quants DataCube not local; ETF 1321/1306 proxy forbidden",
            "resolution": "PUSH event / 1m product exists commercially",
            "period": "live capture ~20260911+ only; no Dev/C1 history",
            "target": "not tested as Causal Driver Phase2 family",
            "causal_timing": "live received_at; historical available_at unproven",
            "sample": "thin live days",
            "verdict": "HISTORICAL_FUTURES_SOURCE_NOT_AVAILABLE_V1",
            "status": "DATA_UNAVAILABLE",
            "note": "CURRENT_DRIVER_SET_INSUFFICIENT_V1 for ETF proxies. Do not start alpha on ~10 live days.",
        },
        {
            "driver_family": "MARKET_INDEX_BREADTH",
            "mechanism": "market breadth / leadership as driver of later stock return",
            "source": "105 1m can build cross-section; live breadth JSONL thin",
            "resolution": "1m stock-derived or few-day capture",
            "period": "stock-derived Dev+C1 possible; official index futures not",
            "target": "individual / sector with leave-target-out",
            "causal_timing": "other-name info <= T",
            "sample": "prior ETF-proxy mapping insufficient",
            "verdict": "CURRENT_DRIVER_SET_INSUFFICIENT_V1",
            "status": "PARTIAL",
            "note": "True index futures missing. Stock-cross-section breadth is a distinct family (see sector breadth).",
        },
        {
            "driver_family": "SECTOR_BREADTH_DISPERSION",
            "mechanism": "sector breadth/dispersion/acceleration -> target future response, target excluded",
            "source": "J-Quants equity 1m 105",
            "resolution": "1m",
            "period": "DEV+C1 on disk",
            "target": "symbol/sector leave-target-out",
            "causal_timing": "aggregate of others available_at <= T",
            "sample": "untested as Causal Driver family",
            "verdict": None,
            "status": "UNTESTED",
            "note": "Data ready. Lower priority: overlaps market-state / same-session technical context.",
        },
        {
            "driver_family": "CROSS_SECTIONAL_LEADER_LAGGARD",
            "mechanism": "other stock / peer / leader shock -> target future response; LEAVE_TARGET_OUT",
            "source": "J-Quants equity 1m 105",
            "resolution": "1m",
            "period": "DEV+C1 on disk",
            "target": "105 observation universe; runtime small frozen leader set",
            "causal_timing": "leader available_at <= T; target future starts after T",
            "sample": "prior peer playbook existed under SR context",
            "verdict": "PEER_PROPAGATION_REAL_BUT_EDGE_CONSUMED_V1 (old playbook; not this family)",
            "status": "UNTESTED",
            "note": (
                "Distinct from PB1 target-self opening structure. Prior peer result is not used to rank this family. "
                "Register as CROSS_SECTIONAL_DRIVER. Do not embed in PB1."
            ),
        },
        {
            "driver_family": "PEER_PROPAGATION_SR_CONTEXT",
            "mechanism": "sector-peer lead inside native SR/path context",
            "source": "native 1m 105",
            "resolution": "1m",
            "period": "historical discovery blocks",
            "target": "peer of target; playbook path",
            "causal_timing": "peer lead vs simultaneous",
            "sample": "P1/P2/P3 frozen then RCA",
            "verdict": "PEER_PROPAGATION_MECHANISM_FOUND_V1 then PEER_PROPAGATION_REAL_BUT_EDGE_CONSUMED_V1",
            "status": "EXHAUSTED",
            "note": "Do not revive as PB1 feature expansion or the same playbook under a new name.",
        },
        {
            "driver_family": "SPECIAL_QUOTE",
            "mechanism": "special-quote resolution direction",
            "source": "board / special quote fields",
            "resolution": "event",
            "period": "legacy full-strategy window",
            "target": "same-stock post-open",
            "causal_timing": "quote event",
            "sample": "coverage fail",
            "verdict": "INTRADAY_SPECIAL_QUOTE_RESOLUTION_COVERAGE_FAIL_V1",
            "status": "DATA_INSUFFICIENT",
            "note": "Low priority. Board fields often zero/unavailable.",
        },
        {
            "driver_family": "ORDER_PRESSURE",
            "mechanism": "aggregate order-pressure after open",
            "source": "MarketOrderBuyQty / UnderBuyQty etc.",
            "resolution": "board snapshot",
            "period": "legacy",
            "target": "same-stock",
            "causal_timing": "board at T",
            "sample": "input not supported",
            "verdict": "POST_OPEN_AGGREGATE_ORDER_PRESSURE_INPUT_NOT_SUPPORTED_V1",
            "status": "DATA_UNAVAILABLE",
            "note": "Do not return to zero/unavailable board fields.",
        },
        {
            "driver_family": "CALCPRICE",
            "mechanism": "CalcPrice vs current / prior close as driver",
            "source": "board CalcPrice",
            "resolution": "snapshot",
            "period": "legacy prior-close line",
            "target": "same-stock",
            "causal_timing": "board",
            "sample": "used as diagnostic in recapture line",
            "verdict": "PRIOR_CLOSE_RECAPTURE_NO_STABLE_SUCCESS_MECHANISM_V1",
            "status": "EXHAUSTED",
            "note": "Same-stock technical / board. Not an independent external driver.",
        },
        {
            "driver_family": "NATIVE_PRICE_STATUS",
            "mechanism": "same-stock 1m path / VWAP / SR / direction stacks",
            "source": "J-Quants 1m OHLC",
            "resolution": "1m",
            "period": "full historical research stack",
            "target": "same symbol",
            "causal_timing": "own past price <= T",
            "sample": "many packages",
            "verdict": "multiple STOPPED (R11 invalidated; native stacks stopped; PB1 INSUFFICIENT)",
            "status": "EXHAUSTED",
            "note": "Forbidden as next Causal Driver. Target-self past-price reprocessing.",
        },
        {
            "driver_family": "PRIOR_CLOSE_RECAPTURE",
            "mechanism": "reclaim prior close after open",
            "source": "daily prior close + 1m",
            "resolution": "1m vs prior close",
            "period": "legacy + sustained RCA",
            "target": "same-stock",
            "causal_timing": "own price vs prior close",
            "sample": "coverage fail then no stable success mechanism",
            "verdict": "PRIOR_CLOSE_RECAPTURE_NO_STABLE_SUCCESS_MECHANISM_V1",
            "status": "EXHAUSTED",
            "note": "Same-stock post-open.",
        },
        {
            "driver_family": "SAME_STOCK_POST_OPEN_TECHNICAL",
            "mechanism": "SMA / MTF / opening-range / PB1 internals",
            "source": "1m own price + PB1 V4",
            "resolution": "1m/5m",
            "period": "PB1 V1-V4 and native playbooks",
            "target": "same-stock",
            "causal_timing": "own structure",
            "sample": "Complete Strategy Conf1 FAIL; entry architecture INSUFFICIENT",
            "verdict": "PB1_ENTRY_ARCHITECTURE_INFORMATION_INSUFFICIENT_V1",
            "status": "EXHAUSTED",
            "note": "Do not expand PB1 features. V4 frozen.",
        },
        {
            "driver_family": "TRUE_CME_NQ_ES",
            "mechanism": "US index futures -> JP tech/export response",
            "source": "Databento GLBX not local; no API key pull",
            "resolution": "1m",
            "period": "Dev window not on disk",
            "target": "electrical/tech names historically as proxies",
            "causal_timing": "US session / Japan morning overlap",
            "sample": "cost/coverage audit only",
            "verdict": "TRUE_CME_NQ_ES_SOURCE_BLOCKED_V1",
            "status": "DATA_UNAVAILABLE",
            "note": "Do not purchase in this task. Oil follow-on package was not run.",
        },
        {
            "driver_family": "KOREA_SEMICONDUCTOR",
            "mechanism": "KRX semi leaders -> JP electrical",
            "source": "KRX not entitled",
            "resolution": "intraday unavailable",
            "period": "n/a",
            "target": "JP semi/electrical",
            "causal_timing": "Korea session",
            "sample": "source audit",
            "verdict": "KOREA_INTRADAY_SOURCE_NOT_AVAILABLE_V1",
            "status": "DATA_UNAVAILABLE",
            "note": None,
        },
        {
            "driver_family": "HKG_CHINA_A50",
            "mechanism": "HK / A50 -> JP China-sensitive names",
            "source": "prior catalog; not a Dev+C1 1m panel here",
            "resolution": "mixed",
            "period": "discovery catalog",
            "target": "China-sensitive JP",
            "causal_timing": "simultaneous not lead",
            "sample": "response mapping",
            "verdict": "HKG_CHINA_A50_SIMULTANEOUS_ONLY_V1",
            "status": "EXHAUSTED",
            "note": "Closed as no usable causal lead.",
        },
        {
            "driver_family": "OTHER_FX_RATES_COMMODITY",
            "mechanism": "non-USDJPY FX / JGB / oil",
            "source": "ambiguous or unpaid",
            "resolution": "unknown locally",
            "period": "n/a",
            "target": "unspecified",
            "causal_timing": "unproven",
            "sample": "catalog only",
            "verdict": None,
            "status": "DATA_UNAVAILABLE",
            "note": "Do not select a family whose source is ambiguous.",
        },
    ]
