"""C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2. Uniform 40-pair Full Causal. No Z3 metric reuse."""
from __future__ import annotations

from research.c1_multi_timeframe_entry_exit_pair_precommit_v1.spec import pair_id
from research.c1_multi_timeframe_entry_exit_pair_precommit_v2.equivalence import build_final_pairs
from research.c1_multi_timeframe_full_strategy_v1 import (
    BOARD_FRESHNESS_SEC,
    C1_BROADENS_ENTRY_POPULATION_CLAIM,
    CANARY_EXPECTED,
    CANARY_ID,
    CANARY_SOURCE,
    FOLD_TRAIN_FILL_DAYS_MIN,
    FOLD_TRAIN_TRADE_N_MIN,
    FOLD_TRAIN_TRADES_PER_DAY_MIN,
    GLOBAL_VWAP_ENTRY_GATE,
    MIN_QTY,
    MIN_PF,
    MIN_TOTAL_TRADES,
    MIN_TRADES_PER_DAY,
    MIN_TRADING_DAYS_WITH_FILL,
    NON_VWAP_CANDIDATE_IDS,
    PORTFOLIO_WAIT_SEC,
    VWAP_CANDIDATE_IDS,
)
from research.c1_multi_timeframe_precommit_v1 import RAW_CANDIDATE_IDS
from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS, PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2"
PRECOMMIT_ANALYSIS_ID = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_PAIR_PRECOMMIT_V2"
PRECOMMIT_VERDICT_REQUIRED = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_LIBRARY_V2_FROZEN"
PRECOMMIT_NEXT_REQUIRED = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2"
DEV_CLASSIFICATION = "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
PRIOR_Z3_ONLY_ANALYSIS_ID = "C1_MULTI_TIMEFRAME_FULL_STRATEGY_V1"
PRIOR_Z3_ONLY_VERDICT = "C1_MULTI_TIMEFRAME_NO_ROBUST_CANDIDATE"

CASE_A = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_CANDIDATE_FOUND"
CASE_B = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_NO_ROBUST_CANDIDATE"
CASE_C = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_SELECTION_UNSTABLE"
CASE_E = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2_INTEGRITY_FAILED"
CASE_CANARY = "C1_MULTI_TIMEFRAME_ENTRY_EXIT_ENGINE_PARITY_FAILED"

NEXT_IF_A = "C1_MULTI_TIMEFRAME_REUSED_HISTORY_STRESS_V1"
NEXT_IF_B = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V1"
NEXT_IF_C = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V1"

KEPT_EXIT_IDS = (
    "Z1_VWAP_LOSS",
    "Z2_STRUCTURE_LOSS",
    "Z3_TWO_BAR_WEAKNESS",
    "Z5_HYBRID_SIMPLE",
)
DROPPED_EXIT_IDS = ("Z4_TRAILING_STRUCTURE",)
EXIT_FIRE_KEY = {
    "Z1_VWAP_LOSS": "Z1",
    "Z2_STRUCTURE_LOSS": "Z2",
    "Z3_TWO_BAR_WEAKNESS": "Z3",
    "Z5_HYBRID_SIMPLE": "Z5",
}
EXECUTION_ID = "X1_IMMEDIATE_ASK"

REQUIRED_V2_HASHES = {
    "ENTRY_LIBRARY_SHA256": "bd01a82a923866facb914e5d2d86ec1ab223e5e5a5ea9eb70e260cb7da3f822f",
    "EXECUTION_SHA256": "6effcef3845b014ef868fa64ad224f3ddc072d64dc83351d97646cc1c54ced5b",
    "PORTFOLIO_SHA256": "e766a3f4b39c91e81c11c63e59c28a15c10965df01ddd220a5fb39430282cdf8",
    "FOLD_ASSIGNMENT_SHA256": "65a750dffffc08dd829fbbfca59047bb004bab66a5ed408b5f02cc8fea159936",
    "GATES_SHA256": "50806c90dda69b551633015ea2066df8bc9765ca1df27bfe6c88a00c96913f4d",
    "CANARY_SPEC_SHA256": "b2c4a7efbae484e579c597b5f99a9e4b5a6487378ae9d7f6a73d18010da121bd",
    "EXIT_FILE_SHA256": "1a2798c6bcee0885615751a7ced6f479973620822787202fba054c9d2b5b538e",
    "EQUIVALENCE_SHA256": "a19eaf5814f7a39ba32b4b3cc3858355f1f491910ae491864deda40c36501d4b",
    "FINAL_EXIT_SHA256": "11c43eecb5cc1d9860609301aef1c2773b0eed68d544503e7b46aac8477100b1",
    "FINAL_PAIR_SHA256": "cca87d9c23ad2f429a1080e45e6f0cb02d60b934330ac748ee84f2f9aa9471de",
}

FROZEN_PAIRS = tuple(r["CANDIDATE_ID"] for r in build_final_pairs(list(KEPT_EXIT_IDS)))

SESSION = "AM"
PROSPECTIVE_HARVEST_SUSPENDED = True
TRUE_OOS = False
CERTIFIED = False
STRESS_OPENED_THIS_RUN = False
SIZING = False
RETUNE = False
SELECTED_STRATEGY_SYMBOL_FILTER = False
TOP_SYMBOL_EXCLUSION_PROPAGATED_TO_STRATEGY = False
Z3_SLICE_PREVIOUSLY_OBSERVED = True
Z3_PREVIOUSLY_OBSERVED_PAIR_N = 10
Z3_PREVIOUSLY_OBSERVED_PAIR_N_INT = 10

assert ANALYSIS_ID == "C1_MULTI_TIMEFRAME_ENTRY_EXIT_FULL_STRATEGY_V2"
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert NEXT_IF_B != PFQ_RECON_FORBIDDEN
assert CANARY_ID == "RECOVERY_R2_X1_Z3"
assert len(KEPT_EXIT_IDS) == 4
assert "Z4_TRAILING_STRUCTURE" not in KEPT_EXIT_IDS
assert len(FROZEN_PAIRS) == 40
assert all(EXECUTION_ID in p for p in FROZEN_PAIRS)
assert all("Z4_TRAILING_STRUCTURE" not in p for p in FROZEN_PAIRS)
assert all(pair_id(e, z) in FROZEN_PAIRS for e in RAW_CANDIDATE_IDS for z in KEPT_EXIT_IDS)
assert DEV_CLASSIFICATION == "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert GLOBAL_VWAP_ENTRY_GATE is False
assert C1_BROADENS_ENTRY_POPULATION_CLAIM is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert STRESS_OPENED_THIS_RUN is False
assert SIZING is False
assert FOLD_BLOCKS
assert DEVELOPMENT_DAYS
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
assert CANARY_EXPECTED
assert CANARY_SOURCE
assert VWAP_CANDIDATE_IDS
assert NON_VWAP_CANDIDATE_IDS
assert BOARD_FRESHNESS_SEC
assert MIN_QTY
assert PORTFOLIO_WAIT_SEC
assert MIN_TOTAL_TRADES == 40
assert MIN_TRADING_DAYS_WITH_FILL == 8
assert MIN_TRADES_PER_DAY == 4.0
assert MIN_PF == 1.10
assert FOLD_TRAIN_TRADE_N_MIN == 32
assert FOLD_TRAIN_FILL_DAYS_MIN == 7
assert FOLD_TRAIN_TRADES_PER_DAY_MIN == 4.0
assert Z3_SLICE_PREVIOUSLY_OBSERVED is True
assert Z3_PREVIOUSLY_OBSERVED_PAIR_N == 10
assert SELECTED_STRATEGY_SYMBOL_FILTER is False
assert TOP_SYMBOL_EXCLUSION_PROPAGATED_TO_STRATEGY is False
assert EXIT_FIRE_KEY["Z5_HYBRID_SIMPLE"] == "Z5"
assert DROPPED_EXIT_IDS == ("Z4_TRAILING_STRUCTURE",)
assert Z3_PREVIOUSLY_OBSERVED_PAIR_N_INT == 10
assert SESSION == "AM"
assert PROSPECTIVE_HARVEST_SUSPENDED is True
assert RETUNE is False
assert len(REQUIRED_V2_HASHES) == 10
