"""Research the precommitted prior-3-bar range break. No complete-strategy PnL."""
from __future__ import annotations

from research.causal_driver_pb1.phase1.dates import assert_ingest_date_allowed

_ = assert_ingest_date_allowed

ANALYSIS_ID = "RUN_SYMBOL_SETUP_PULLBACK_RANGE_BREAK_MECHANISM_RESEARCH_V1"
REPAIR_ID = "SYMBOL_SETUP_PULLBACK_RANGE_BREAK_TRIGGER_V1"
REPAIR_SPEC_SHA256 = "2571a28177d8b1dd71278e92a4195f76a82e674aa70a7f70cf45f8edcae8c113"
COMPLETE_STRATEGY_ID = "SYMBOL_SETUP_BASELINE_COMPLETE_STRATEGY_V1"
COMPLETE_STRATEGY_SHA256 = "25d8ef6944c4d82a15d57a3bb078e5503f733184ecb92ee5ad6ba95fe4f95f6d"
PRIMARY_DEFICIENCY = "SYMBOL_SETUP_EDGE_NOT_ESTABLISHED"
VOLUME_PASS_N = 161
BASELINE_SIGNAL_N = 121
BASELINE_BOARD_N = 44
PRIMARY_HORIZON_SEC = 180
SUPPORT_MIN_N = 30
HORIZONS = (30, 60, 180, 300)
FROZEN_BASELINE_180 = {
    "raw_mid_median": 0.0,
    "bid_anchor_median": 0.0,
    "ask_to_bid_median": -18.39587932303164,
}
VERDICT_CLOSED = "FAIL_CLOSED"
VERDICT_PARITY = "SYMBOL_SETUP_RANGE_BREAK_INPUT_POPULATION_PARITY_FAIL_V1"
VERDICT_SUPPORT = "SYMBOL_SETUP_PULLBACK_RANGE_BREAK_MECHANISM_INSUFFICIENT_SUPPORT_V1"
VERDICT_FAIL = "SYMBOL_SETUP_PULLBACK_RANGE_BREAK_MECHANISM_NOT_SUPPORTED_V1"
VERDICT_PASS = "SYMBOL_SETUP_PULLBACK_RANGE_BREAK_MECHANISM_SUPPORTED_V1"
NEXT_PASS = "PRECOMMIT_SYMBOL_SETUP_REPAIRED_COMPLETE_STRATEGY_V1"
NEXT_STOP_REPAIR = "STOP_PULLBACK_RANGE_BREAK_REPAIR_V1"
NEXT_STOP = "STOP"
