"""C4_PORTFOLIO_CROWDING_PRECOMMIT_V2. Semantic seen-set correction + intervention prune. No economics."""
from __future__ import annotations

from research.c1_multi_timeframe_entry_exit_pair_precommit_v2 import EXPECTED_EXIT_FILE_SHA256
from research.c4_portfolio_crowding_precommit_v1 import (
    CONTROL_POLICY_ID as V1_CONTROL_POLICY_ID,
    KEPT_EXIT_IDS,
    TREATMENT_POLICY_ID as V1_TREATMENT_POLICY_ID,
)
from research.simple_full_strategy_discovery_v1 import (
    BURNED_HOLDOUT_DAYS,
    DEVELOPMENT_DAYS,
    FORBIDDEN_INPUT_DAYS,
    MAX_RESEARCH_DATE,
    POSITION_CAP,
    SHARES,
    STRESS_DAYS,
)
from research.systematic_state_transition_full_strategy_v1 import CANARY_EXPECTED, CANARY_ID, CANARY_SOURCE
from research.systematic_state_transition_library_precommit_v1 import FOLD_BLOCKS, PFQ_RECON_FORBIDDEN

ANALYSIS_ID = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V2"
PRIOR_V1_ANALYSIS_ID = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V1"
PRIOR_V1_VERDICT_REQUIRED = "C4_PORTFOLIO_CROWDING_MATCHED_LIBRARY_FROZEN"

CASE_A = "C4_PORTFOLIO_CROWDING_LIBRARY_V2_FROZEN"
CASE_INSUFFICIENT = "C4_PORTFOLIO_CROWDING_INSUFFICIENT_INTERVENTION_COVERAGE"
CASE_E = "C4_PORTFOLIO_CROWDING_PRECOMMIT_V2_INTEGRITY_FAILED"

NEXT_IF_A = "C4_PORTFOLIO_CROWDING_FULL_STRATEGY_V2"
NEXT_IF_INSUFFICIENT = "RESEARCH_OBJECTIVE_REBASE_V1"
NEXT_IF_E = "Fix integrity only. No alternative C4 rule. No economics."

DEV_CLASSIFICATION = "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
EXECUTION_ID = "X1_IMMEDIATE_ASK"
CONTROL_POLICY_ID = "C4_CONTROL_NONE"
TREATMENT_POLICY_ID = "C4_FIRST_ARRIVAL_PER_EXACT_T0_V2"
C4_SCOPE = "PER_ENTRY_ID_PER_TRADING_DAY"
CORRECTION_CLASS = "SEMANTIC_IMPLEMENTATION_CORRECTION"

ENTRY_N = 25
EXIT_N = 4
MIN_INFORMATIVE_BLOCK_N = 3

EXPECTED_V1_POLICY_SHA256 = "efec3404cee9f50d90d5dbb0e5c3d35ccb0d4453c706a526c614bb3cbd7621da"
EXPECTED_EVENT_N = 13790951
EXPECTED_SEQ_MISSING_N = 0
EXPECTED_SEQ_DUPLICATE_N = 0
EXPECTED_SEQ_NON_MONOTONE_N = 0
EXPECTED_EXIT_FILE_SHA256_PIN = EXPECTED_EXIT_FILE_SHA256

SESSION = "AM"
TRUE_OOS = False
CERTIFIED = False
SIZING = False
STRESS_OPENED_THIS_RUN = False
CANDIDATE_ECONOMICS_RUN = False
CONTROL_ECONOMICS_RUN = False
TREATMENT_ECONOMICS_RUN = False

assert ANALYSIS_ID == "C4_PORTFOLIO_CROWDING_PRECOMMIT_V2"
assert PRIOR_V1_VERDICT_REQUIRED == "C4_PORTFOLIO_CROWDING_MATCHED_LIBRARY_FROZEN"
assert CASE_A != CASE_INSUFFICIENT != CASE_E
assert NEXT_IF_A != NEXT_IF_INSUFFICIENT
assert NEXT_IF_A != PFQ_RECON_FORBIDDEN
assert TREATMENT_POLICY_ID == "C4_FIRST_ARRIVAL_PER_EXACT_T0_V2"
assert TREATMENT_POLICY_ID != V1_TREATMENT_POLICY_ID
assert CONTROL_POLICY_ID == V1_CONTROL_POLICY_ID
assert CORRECTION_CLASS == "SEMANTIC_IMPLEMENTATION_CORRECTION"
assert C4_SCOPE == "PER_ENTRY_ID_PER_TRADING_DAY"
assert len(KEPT_EXIT_IDS) == 4 == EXIT_N
assert "Z4_TRAILING_STRUCTURE" not in KEPT_EXIT_IDS
assert MIN_INFORMATIVE_BLOCK_N == 3
assert POSITION_CAP == 5
assert SHARES == 100
assert MAX_RESEARCH_DATE == "20260807"
assert len(DEVELOPMENT_DAYS) == 10
assert len(FOLD_BLOCKS) == 5
assert CANARY_ID == "RECOVERY_R2_X1_Z3"
assert CANARY_EXPECTED
assert CANARY_SOURCE
assert CANDIDATE_ECONOMICS_RUN is False
assert TRUE_OOS is False
assert CERTIFIED is False
assert SIZING is False
assert STRESS_OPENED_THIS_RUN is False
assert EXPECTED_EVENT_N == 13790951
assert EXPECTED_V1_POLICY_SHA256
assert ENTRY_N == 25
assert BURNED_HOLDOUT_DAYS
assert STRESS_DAYS
assert FORBIDDEN_INPUT_DAYS
assert SESSION == "AM"
assert DEV_CLASSIFICATION == "ADAPTIVE_REUSED_HISTORY_DEVELOPMENT"
assert EXECUTION_ID == "X1_IMMEDIATE_ASK"
assert EXPECTED_EXIT_FILE_SHA256_PIN
