"""E1_X7 PFQ EXIT Gate Reconciliation — pair-specific unique-episode gates; no EXIT change."""

ANALYSIS_ID = "E1_X7_PFQ_EXIT_GATE_RECONCILIATION"
SOURCE_BRIDGE_RUN = "e1x7_pfq_bridge_v2_20260804_232049_A"
SOURCE_VERDICT = "E1_X7_PFQ_ENTRY_SUPPORTED_EXIT_CAPTURE_LIMITATION"
CANDIDATE_ID = "PFQ_UPDATE_Q70"

PAIRS = (
    "PFQ_UPDATE_Q70|PFQ_X_PROGRESS_STRUCT",
    "PFQ_UPDATE_Q70|PFQ_X_PROTECT",
)

KNOWN = {
    "unique_episode_n": 92,
    "progress_trade_rows": 92,
    "protect_trade_rows": 92,
    "total_pair_trade_rows": 184,
}

MECH_SOFT = "SOFT_EXIT_PREMATURE"
MECH_GIVEBACK = "PLUS5_REACHED_BEFORE_EXIT_GIVEN_BACK_TO_NONPOSITIVE"

GATE_MIN_REPAIRABLE_N = 20
GATE_MIN_REPAIRABLE_DAYS = 5
GATE_MIN_REPAIRABLE_FRACTION = 0.50
GATE_MIN_TOP_MECH_FRACTION = 0.50
